### ISSUE TITLE
Single-touch display in SP4

### ISSUE THREAD

**Issue by legierski** [jakeday/linux-surface#1]
Hi Jake,

First of all, love the kernel, it saved me from running the SP4 with cheapo 2.4ghz-only wifi card occupying the only USB port - I can now use the built-in wifi without any issues. Thanks!

That being said, the issue I'm experiencing now (compared to a kernel I used before) is that the touch behaves as if I was using the mouse to click around, so to speak. SIngle-touch instead of expected 10 finger multi-touch. Two instances where I can notice it:

- In the past I was able to scroll websites in Chrome browser with my finger, whereas now it would select text, as if I tried to click-and-drag the cursor
- I was able to hold down ctrl and press a different key on the on-screen keyboard. Now I can't.
- (bonus point) I think I used to be able to pinch-to-zoom on google maps loaded in Chrome. Can't do that now.

Running Ubuntu 16.04 on SP4 m3. The previous kernel was fridgecow's 4.8 based version.

Thanks!

**Comment by jakeday** [comment]
I'm glad you're liking the kernel! I'm always working on getting better support for the Surface devices, so make sure you keep up to date!

As for your issue, it's actually not a problem with the driver in the kernel. Xorg gives you a few different options on how to treat the input device. You can take a look at my udev rule (99-ipts.rules) for how I'm using it. Just save it to /etc/udev/rules.d/ and reboot. I prefer touchscreen, which I believe is what you're going to want.

https://goo.gl/QSZCwq
