### ISSUE TITLE
SP4 Suspending doesn't work well

### ISSUE THREAD

**Issue by XiWinnie** [jakeday/linux-surface#10]
Thanks for your works very much! Following your instructions, most of things work fine.However,once my SP4 is suspended,I have to wake up it by a USB keyboard,neither the type cover nor power button can resume it.In addition,Wi-fi doesn't work frequently  after suspending or hibernation.

**Comment by bananflugan** [comment]
I have the same problem. After hibernation wifi has never worked for me, not with this kernel and not with any other kernel. Before, when i ran OpenSUSE i created this forum topic about it, https://forums.opensuse.org/showthread.php/525578-No-Wifi-networks-after-hibernation

**Comment by rosingle** [comment]
same problem here, well I think this batch has still a long way to go ...

**Comment by jakeday** [comment]
Did you guys run the commands in my README.md file?

**Comment by jakeday** [comment]
Assuming you run the commands in my README, you should be good on waking up. As for WiFi after that, it should be good with my 4.14 kernel.

**Comment by tmarkov** [comment]
Don't these commands disable suspend completely and change it with hibernate?
