### ISSUE TITLE
[SB2] Ethernet not working on SB2 15'

### ISSUE THREAD

**Issue by atharos1** [jakeday/linux-surface#100]
Hi! Sorry to bother you again.
Sorry to bother you again. I just noticed that, even though the Dock is working perfectly for all peripherals, Ethernet doesn't seem to be working, even though it is on Windows.

Thank you!

**Comment by jakeday** [comment]
@atharos1 That's kinda two part. My patch file enables it for the dock, but the core driver in the mainline kernel was changed in 4.14.5 and caused issues with all ethernet adapters over usb 3.0. I believe a bug has been filed upstream.

**Comment by npjohnson** [comment]
@jakeday Got a link to the pertinent upstream bug? Can't find it...
