### ISSUE TITLE
Surface Laptop / Surface Book 2: Speaker Popping/Hissing

### ISSUE THREAD

**Issue by maflin18** [jakeday/linux-surface#101]
When booting up, speakers emit a static noise and then upon completion of boot, make some loud pops. The sound is very disturbing. 

Also, sometimes after signing in the speakers will intermittently begin hissing again. 

(YES I am positive it is the speakers making all of the above noises and not the fan)

**Comment by remingtonlang** [comment]
This also happens on an SB2. I've noticed it consistently does this, post kernel load and stops right before loading X(lightdm in my case)

# uname -a
Linux surface-book 4.15.7-surface-linux-surface #12 SMP Tue Mar 6 22:15:47 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by timbk** [comment]
I own a SP2017. I heven't noticed the popping sound with either linux or windows. But i have noticed the static speaker noise on windows too, so that might not be solvable via software

**Comment by jakeday** [comment]
@maflin18 I updated the pulse daemon.conf settings. Can you pull them down (and install the latest kernel) and test again?

**Comment by maflin18** [comment]
@jakeday currently on family vacation, so limited in what I can do. But, I will be sure to do this as soon as I can next week if it is not solved by then.

**Comment by versipellis** [comment]
@jakeday I have this on my SB2 - still happening with pulse daemon.conf and latest kernel.

**Comment by xanf** [comment]
I have hissing issue on boot (for very short time - ~2-3 seconds) and constant hissing from speakers when I plug headphones. I'm running SB2

**Comment by remingtonlang** [comment]
I just noticed the same hissing noise on my SB2 when I have headphones plugged in. I managed to shut it off by disabling "Auto-Mute Mode" in ALSA:

`amixer -c 0 sset 'Auto-Mute Mode' Disabled && sudo alsactl store`

Storing it preserves it after reboot though I'm still hearing it for a few seconds on boot. Maybe someone can take it further?

**Comment by jakeday** [comment]
Fixed in 4.18.7 release, confirmed on my devices.

**Comment by SoleSensei** [comment]
#354
