### ISSUE TITLE
CUDA could not locate kernel source

### ISSUE THREAD

**Issue by buoyancy99** [jakeday/linux-surface#102]
I failed to install cuda through runfile after compiling and installing the kernel.
The installation always fails with message:
"unable to locate the kernel source"

I tried --kernel-source-path usr/src/linux-headers-4.14.25-surface-linux-surface but it did not work.

**Comment by jakeday** [comment]
@buoyancy99 That likely needs the linux-libc-dev package for the kernel. I'll upload it with the next batch of kernels I release, which will be here shortly.
