### ISSUE TITLE
Fedora Support

### ISSUE THREAD

**Issue by xlelephant** [jakeday/linux-surface#103]
I installed fedora on SurfacePro4. Fedora 27 has good support for surfacepro4 and seems to be very power-saving, i.e. drops 50% with screen lights up for 8 hours.

What's Working:
Keyboard, Touchpad
2D/3D Acceleration(kernel 4.15.6 above)
Bluetooth(only for kernel 4.13)
Speakers
Power Button
Volume Buttons
SD Card Reader
Sensors (accelerometer, ambient light sensor)
Battery Readings
Docking/Undocking Tablet and Keyboard
DisplayPort
microsoft docking station(ethernet is broken)

EXCEPT:
Touchscreen
Pen
WiFi
I have tried to install the latest marvell firmware, but it doesn't work for kernel 4.15
I really hope that you could help fix the WiFi problem in Fedora. 
^_^

**Comment by jakeday** [comment]
@xlelephant The marvell firmware does in fact work with 4.15 series kernels. Also, I cannot tell if you are actually running my kernel as I do not put out builds for Fedora. My kernel will add the support for things you are missing, and improve WiFi. There are plenty of guides for compiling kernels for Fedora, you will just need to apply my patches before compiling.

**Comment by npjohnson** [comment]
@xlelephant Assuming you aren't even running Jake's kernel as he insinuated, the place you're looking for to share use experience is https://reddit.com/r/SurfaceLinux.
