### ISSUE TITLE
Surface Dock GigE: PROBE FAILS: cdc_ether: probe of 2-4.2:2.0 failed with error -71

### ISSUE THREAD

**Issue by johnutz-self** [jakeday/linux-surface#105]
NOTE: This error is not specific to the  jakeday tree, it repro's on 4.13.0-37-generic and did not reliably repro on 4.10. I have submitted it here because it's Surface Dock specific and it is much more likely to get attended to here than it will out in the general linux developer population.

This dock is updated to the latest available dock fw and  attached to an original surfacebook.

Relevant dmesg snippet:

[    3.224222] usb 2-4.2: new SuperSpeed USB device number 5 using xhci_hcd
[    3.244874] usb 2-4.2: New USB device found, idVendor=045e, idProduct=07c6
[    3.244876] usb 2-4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[    3.244877] usb 2-4.2: Product: Surface Dock GigE
[    3.244878] usb 2-4.2: Manufacturer: Microsoft
[    3.244879] usb 2-4.2: SerialNumber: 000001000000
...
[   12.508344] usb 2-4.2: Disable of device-initiated U1 failed.
[   12.512350] usb 2-4.2: Disable of device-initiated U2 failed.
[   12.521088] usb 2-4.2: Set SEL for device-initiated U1 failed.
[   12.524609] usb 2-4.2: Set SEL for device-initiated U2 failed.
[   12.524629] cdc_ether: probe of 2-4.2:2.0 failed with error -71 (#define EPROTO  71 Protocol error?)
[   12.524667] usbcore: registered new interface driver cdc_ether

probe failure is the default case in really_probe() in drivers/base/dd.c:

	default:
		/* driver matched but the probe failed */
		printk(KERN_WARNING
		       "%s: probe of %s failed with error %d\n",
		       drv->name, dev_name(dev), ret);

the probe function specified in cdc_ether.c is usbnet_probe(), which is generic to usb ethernet methinks.

Any suggestion of next steps in debugging this? A frenzy of kprintf()? or does somebody already have a fix?

tnx!

johnu

**Comment by npjohnson** [comment]
https://github.com/jakeday/linux-surface/issues/70

Its a generic Linux USB-3 Ethernet dongle issue (in that all USB3 Ethernet devices are broken in some early revision of 4.15). Needs to be reported upstream.

Haven't had the chance to do so yet. Feel free to do it! I'd appreciate it.

**Comment by johnutz-self** [comment]
finally got around to it and filed this upstream

**Comment by npjohnson** [comment]
@johnutz-self link?

**Comment by johnutz-self** [comment]
thought you might ask....it was a test :-)....ok, not really....

https://bugzilla.kernel.org/show_bug.cgi?id=199153

**Comment by sedulam** [comment]
@johnutz-self I'm new to these things. Is there a way that we can increase attention for the kernel bug? I have been trying to use Ubuntu with dual boot on my Surface, and this bug has been a big thorn.

**Comment by qzed** [comment]
For the record: Still not working (at least for me), continued in #259.

**Comment by johnutz-self** [comment]
Repo'd for me last time I tried it as well.
