### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by ichbindannmalwegmann** [jakeday/linux-surface#106]
Hi,
Do you know why the wifi patches aren't integrated into the kernel?
Kind regards,
Roger

**Comment by peconi** [comment]
What do you mean by "not integrated into the kernel"?
https://github.com/jakeday/linux-surface/blob/master/patches/4.15/wifi.patch

**Comment by npjohnson** [comment]
He is asking why they aren't upstream yet @peconi

**Comment by ichbindannmalwegmann** [comment]
Yes, this is what I wanted ask, why isn't the patch upstream.

**Comment by jakeday** [comment]
@ichbindannmalwegmann Someone is working on upstreaming my patches for us, they just haven't made it yet.
