### ISSUE TITLE
Dock/undock at SB2

### ISSUE THREAD

**Issue by xanf** [jakeday/linux-surface#109]
Hi and thank you for your amazing work!

I've just built latest kernel from git (4.15) and it seems I can't dock-undock my SB2 - led remains red, and actually I do not see any actions in udevadm monitor.

Am I missing something? I'm running non-Ubuntu distribution (ArchLinux) so probably I'm wrong somewhere.

(other things working fine except battery stats, but I assume they still should not work for SB2)

**Comment by thmichel** [comment]
Hi,

you could try to  manually unload the driver for the Nvidia card (sudo rmmod nouveau). That might prevent the device from undocking.  I think it will not undock as long as the nvidia card is in use.

**Comment by buoyancy99** [comment]
Hi,
Undock worked fine on my ubuntu SB2. It might be a problem of Nvidia Card.
If you use you nvidia GPU for CUDA development, I would recommend install CUDA without nvidia driver.

**Comment by xanf** [comment]
Hmm.. Really weird - I'm not using nvidia driver and tried rmmod nouveau. Does not work for me. Any hints how I can debug reason for that?

**Comment by matthias-vogt** [comment]
Using the nvidia drivers but changing to the intel driver through the nvidia x server settings app did the job for me. Now I can dock and undock with the keyboard and trackpad (and touchscreen) working just fine - it just takes a few seconds longer than on windows to undock. (Using: 4.14.8, Running: SB2 13in, Ubuntu 17.10)

**Comment by jakeday** [comment]
Yeah, you'll need to disable nvidia if using it and unload nouveau and switch to the intel driver. Then you can undock.
