### ISSUE TITLE
Wifi occasionally drop in WPA2 Enterprise network

### ISSUE THREAD

**Issue by yodahuang** [jakeday/linux-surface#11]
I have both 4.12 and 4.13 series of kernels installed on my Surface Book. Wifi is good in the normal home environment. But it's not so good in my university, where the following configuration is used:

- Wireless security: WPA2 Enterprise
- Authentication: Protected EAP (PEAP)
- CA certificate: AddTrust External CA Root
- PEAP Version: Automatic or Version 0
- Inner/Phase 2 authentication: MSCHAPv2

After booting, the Wifi cannot be automatically connected, manually connect does work, but after like 10 minutes it would drop the connection and you're not able to reconnect again.

**Comment by afzalarsalan** [comment]
Yeah I suffer from this issue and have resigned to the fact that the roaming function required for enterprise networks is too perplexing for this network driver. Have pretty much tried everything but the only solution seems to be to go back to linux 4.9 with the old wifi patch which ends up being shockingly stable

**Comment by rosingle** [comment]
same problem here.

**Comment by jakeday** [comment]
I fixed as many of the WiFi issues as I could in my 4.14.x series kernel, and this is one of them. Should be working now and I have verified it does.

**Comment by yodahuang** [comment]
I tried your 4.14.RC5 in Ubuntu, however, the normal Wifi or LAN connection does not work now.

**Comment by jakeday** [comment]
Did you remember to apply the apparmor patch file mentioned in the instructions?

**Comment by yodahuang** [comment]
Oh sorry, After applying that works.
BTW, in the `README` there's a typo `chmow` which should be `chmod`, and when do dpkg install, header should be in the front of image.
Thanks for your work!
