### ISSUE TITLE
Question about note section in readme

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#111]
Hello,

 It is said in the readme one may have to update the intel microcode firmware if got stuck at boot.

Where can you get this intel microcode firmware ? and how can you upgrade it (without having properly booted) ?

Regards

**Comment by kanzwataru** [comment]
It's usually available under Additional Drivers on Ubuntu, but if it's not (or you're using a different distro) you can simply install the `intel-microcode` package.

**Comment by kanzwataru** [comment]
If you're having trouble booting the installer, you can try to make a persistent live USB, boot it on a different computer to install the microcode package and then boot your Surface. I have not tried it however.

**Comment by jakeday** [comment]
@kanzwataru is correct.
