### ISSUE TITLE
Touch stops working occasionally (Surface Book)

### ISSUE THREAD

**Issue by jasonmoofang** [jakeday/linux-surface#112]
So I'm using version 4.15.4 of your kernel, and as far as I know there are no further work on touch support in the newer releases. I'm still occasionally having touch randomly stop working on my Surface Book, and today I managed to catch the dmesg log: a huge number of repeats of messages like

[ 9541.749554] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.772363] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.780789] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.787743] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.796038] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.806043] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error
[ 9541.818127] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 2, source : 1, code : 48:248:255:255
               string Corrupted Full Frame Error

Thought I'd report it! Let me know if you need more info!

**Comment by jakeday** [comment]
@jasonmoofang This will be fixed in 4.15.12, which I have compiling now.
