### ISSUE TITLE
Surface Book 2 battery status

### ISSUE THREAD

**Issue by bovacu** [jakeday/linux-surface#113]
Hi, first of all thanks for your awesome work.

I found a page where it says that the battery status of the SB2 is fully working on Linux, but in your Readme it's says it's not working and I have not been able to make it work (here's the source https://www.reddit.com/r/SurfaceLinux/comments/7kazwp/current_state_of_surfaceseries_devices/)

Is it true that is already working? If it is, can you tell us how to do it?

Thank you so much.

**Comment by jakeday** [comment]
@bovacu That link needs to be updated, as I'm still working on it in #28.
