### ISSUE TITLE
Surface Pro 2017: Input stops working + high temperature

### ISSUE THREAD

**Issue by Ragora** [jakeday/linux-surface#115]
I recently experimented with Ubuntu 17.10 following the instructions on this repository and had excellent results (pretty much everything worked minus the physical buttons as is already known) and so I left Ubuntu running for a while with the device in lock. 

Eventually, though, I had noticed it was getting very hot to the touch so I had opened it up and went to try and figure out what was going on. Tapping some keys on the keyboard woke it up but it was no longer receiving input from the touch screen, touch pad or keyboard to allow me to do anything. I attached a USB keyboard and got the same result. I do know the device wasn't simply locked up because the clock on the lock screen was still updating as normal.

I would get more detailed information though it's kinda hard to inspect the state as it happens because it refuses to accept input anymore and I ultimately had to shut it down by holding the power button down, though I can try seeing what happens if I put an openSsh server on it and remote in.

This was on the 4.15.12-1 kernel.

**EDIT**
I had noticed [this issue](https://github.com/jakeday/linux-surface/issues/56) may be related to what I experienced as this was after closing the type cover on my surface and it sounds similar except my surface doesn't hang at any point.

It does, however, seem to lose wifi capabilities as well as touch capabilities when it comes back during my tests of suspend.

**Comment by jakeday** [comment]
@Ragora This has been confirmed as fixed with 4.15.15. Please update and look at the latest changes to the hibernate script.

**Comment by Ragora** [comment]
@jakeday Blue tooth seems to continue working after the resume but touch input + wifi still are no longer an option post-resume.
