### ISSUE TITLE
[Question] ipts_firmware for Surface Pro 3

### ISSUE THREAD

**Issue by rootasjey** [jakeday/linux-surface#117]
Hello,
Thank you for your work on this.

I see that there's no available _ipts_firmware_ for the Surface Pro 3 (altough there's one for _i915_firmware_).
So I skipped the 3rd step

I'd just like to check if I was supposed the skip the 3rd step or if I should use the 'v78 for the Surface Pro 4' instead.

**Comment by Zyfarok** [comment]
I asked myself the same question while installing, and I think there's no IPTS technology in the surface pro 3 (so you should be able skip). I might be wrong so let's wait for jakeday's answer.
In any case, I think jakeday should update the README.md to make sure that things are clear.
Also, to jakeday  :
intel_ipts is loaded and unload in hibernate(.sh), whether you use a SP3 or not, do you think that it could possibly cause a problem ?

**Comment by npjohnson** [comment]
SP3 doesn't use IPTS.

No need for touch firmware. Support is included in default Linux kernels.
