### ISSUE TITLE
Dose this  support PyTorch/TensorFlow GPU code run in native GPU and CUDA environment?

### ISSUE THREAD

**Issue by DIYer22** [jakeday/linux-surface#122]
Hi, Thank you for your awesome work! I want to use Surface book 2 to develop PyTorch/TensorFlow GPU code (just for write and debug code on GPU, not train) with native Linux GPU environment.

 So, I want to consult: Does the Ubuntu@Surface book 2 support PyTorch/TensorFlow GPU code run in native GPU and CUDA environment?

**Comment by buoyancy99** [comment]
I got cuda and TF work on my SB2. You can also run them without this kernel.

**Comment by DIYer22** [comment]
@buoyancy99 
Did your mean that your TensorFlow code run in native GPU and CUDA environment on vanilla Ubuntu?

**Comment by buoyancy99** [comment]
@DIYer22 What do you mean by "native"?

**Comment by buoyancy99** [comment]
BTW, you don't need a GPU to run a pre-trained NN. CPU would be fast enough.

**Comment by buoyancy99** [comment]
Yes. In addition, VM or Linux subsystem might not work as GPU is not virtualized.

**Comment by DIYer22** [comment]
@buoyancy99  Thank you a lot!
