### ISSUE TITLE
Linux install on SB2

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#125]
Hello,

I try to install linux on my new surface book 2.

I made my choice on the latest debian distribution (buster), which is still in testing stage but has already jumped to the 4.15.xx kernel versions.

After installation, I notice a kworker process which hog at least 80% of one cpu.

Did you already encounter this issue ? Can it be solved easily ?

Otherwise should I try another distribution ?

Thanks for your attention

regards

**Comment by deb75** [comment]
Regarding the kworker issue hogging most of one cpu, I found this page : 
[http://sudoremember.blogspot.fr/2013/05/high-cpu-usage-due-to-kworker.html
](http://sudoremember.blogspot.fr/2013/05/high-cpu-usage-due-to-kworker.html
)

which explains one possible reason for it, I will try if it solves it and let you know

Regards

**Comment by jakeday** [comment]
@deb75 Are you running my 4.15 kernel, or just the stock one that comes from debian?

**Comment by deb75** [comment]
the stock debian one, I am in the process of compiling yours with 4.15.15 from kernel.org

just one question : did you build the kernel config file from scratch ? or did you adapted an existing one ?
I am interested in the differences, if any.

**Comment by jakeday** [comment]
@deb75 You should see better performance when running my kernel. Also, next time you open an issue can you try it with my kernel prior to posting? As for the config, it comes from stock Ubuntu.
