### ISSUE TITLE
Broken display

### ISSUE THREAD

**Issue by buoyancy99** [jakeday/linux-surface#128]
There is a chance that the display was distorted when boot up. Restarting solves the problem but it is annoying.  Switching to command line using Ctrl+Alt+F1 shows a distorted command line. Attachment is a photo of a distorted login screen.
![2cec5d1df8f0cb02d37745c455fe2439](https://user-images.githubusercontent.com/16475227/38282989-391b8db2-3768-11e8-8b02-dc938a48ee40.jpg)

I had this issue on both my previous surface pro 4 (4.14 pre-compiled kernel around 2 month ago) and my current surface book 2 (latest 4.15.25 pre-compiled kernel Apr 18 2018).

**Comment by remingtonlang** [comment]
@buoyancy99 check out #114. The issue sounds like it has to do with th i915 firmware from Intel and not something Jake can do something about kernel side. I also documented some potential mitigation steps to reduce it from happening so often
