### ISSUE TITLE
Surface Book: Keyboard and Touchpad Unresponsive

### ISSUE THREAD

**Issue by cravend** [jakeday/linux-surface#129]
I randomly undocked my Surface Book, and when I rebooted, both the keyboard & the touchpad stopped responding. I've plugged in a USB keyboard/mouse which are both working. I also tried updating to the newest kernel, which didn't help.

**Comment by npjohnson** [comment]
This is a race condition I've run into a well.

It's random, only happens every now and then, and (at least in my case), the relevant dmesg details were not helpful to diagnosing the problem. I'd say it happens 1/10 times undocking for me.

**Comment by cravend** [comment]
I did some more digging... I'm not sure if it's from the kernel. I've tried rebooting multiple times, as well as booting to a generic kernel. The keyboard is also not working in Windows / in the BIOS. I'm not sure if it's a hardware problem, so I'm taking it to the Microsoft store today. Will update soon!

**Comment by xaviervilla** [comment]
I have not had this issue on my Surface book. I've been upgrading my kernel often, Im on the latest one right now.

**Comment by cravend** [comment]
Yep. It was something with my computer, not with the kernel.
