### ISSUE TITLE
dGPU not detected in SurfaceBook 

### ISSUE THREAD

**Issue by aeeladawy** [jakeday/linux-surface#130]
I have a dGPU SB but the GPU is not detected.

running:
`lspci | grep VGA`
yields:
`00:02.0 VGA compatible controller: Intel Corporation HD Graphics 520 (rev 07)`

`lspci | grep nvidia` yields nothing

Admittedly, I skipped the second step, but it's related to hibernating so I don't think that's why.

**Comment by deb75** [comment]
According to the README, it is a known issue.
