### ISSUE TITLE
Request: Diff / patch of config file

### ISSUE THREAD

**Issue by pierrebeaucamp** [jakeday/linux-surface#132]
Hi,

thanks again for all the amazing work. I'm very happy to use your kernel patches. However, could you outline in what way the config file differentiates from the mainline config file? A quick `diff` would already help a lot. 

Thank you

**Comment by deb75** [comment]
My guess :

Go there : [](http://kernel.ubuntu.com/~kernel-ppa/mainline/), retrieve the 4.14.23 deb package (as seen in the config file)

Unpack it : ar x your.package.deb then untar the data archive which should give you a boot directory in which you will find what you are looking for

Hopes this help

**Comment by jakeday** [comment]
@pierrebeaucamp Added config patch to repo.

**Comment by pierrebeaucamp** [comment]
Thank you so much!
