### ISSUE TITLE
IPTS patch not working for kernel version 4.16

### ISSUE THREAD

**Issue by ssmolkin1** [jakeday/linux-surface#133]
Thanks for this awesome resource! I've been using just the IPTS patch for patching my own kernels (I run Arch Linux and build kernels using the Arch Build System). On kernel versions 4.15.x, I just applied this one patch (the one for kernel version 4.15) and added the following to my `config` file: `CONFIG_INTEL_IPTS=m`. This worked great. However, I have now tried patching kernel 4.16.0-2 twice in this same way (using the IPTS patch for kernel version 4.16, but otherwise no changes to process), and touch doesn't work. Are there some extra configs that I need to add for this version? It didn't look like it, based on the config file in this repo... Maybe this is an issue with the patch? 

EDIT: My machine is a Surface Pro 2017

**Comment by BillKen** [comment]
I am seeing the same problem with 4.16.1.  The 4.16 patches for acpi are failing to apply and IPTS doesnt work.  Kernel is gentoo-sources (lightly patched) and openrc based instead of systemd.

The suspend works ok with 4.15.14, and less reliably with 4.15.15 & 4.15.16 for some reason but ipts works fine.

BillK

**Comment by jakeday** [comment]
I haven't updated the patches for 4.16.x since earlier in the RC series. Now that it's stable at 4.16.1, I'll update the patches for the next round of releases.

**Comment by jakeday** [comment]
@ssmolkin1 @BillKen I updated all of my patches to support 4.16 and pushed out my prebuilt kernels. Everything that worked on 4.14 and 4.15 is now working on 4.16!

**Comment by electrikjesus** [comment]
On v4.16.2 I had to add #include <linux/seq_file.h> to drivers/platform/x86/surface_acpi.c to get it to compile for Android.

**Comment by jakeday** [comment]
@electrikjesus As you can see in my patches, that is already there as of updating for 4.16 yesterday.

**Comment by electrikjesus** [comment]
LOL! I Just missed your push then :)

**Comment by ssmolkin1** [comment]
@jakeday Confirming that this works now on my SP2017 with kernel 4.16.3. Thank you!

**Comment by tinchou** [comment]
@electrikjesus are you running any Android flavor on your Surface? I would like to hear more about it but I don't want to spam this thread. Maybe you could write a quick note on https://www.reddit.com/r/SurfaceLinux/?

Thanks!
