### ISSUE TITLE
Bugs on surface pro 2017 i5 

### ISSUE THREAD

**Issue by roysorin** [jakeday/linux-surface#134]
- auto rotate screen dont work 
- volume & shutdown buttons dont work too

**Comment by jakeday** [comment]
@roysorin For auto rotate, you'll need to get the scripts for auto rotate. The buttons issue is covered in issue #34

**Comment by roysorin** [comment]
When it's fix? It's open 5 months ;/

בתאריך יום ד׳, 11 באפר׳ 2018, 05:13, מאת Jake Day ‏<notifications@github.com

**Comment by roysorin** [comment]
What scripts?

בתאריך יום ד׳, 11 באפר׳ 2018, 05:13, מאת Jake Day ‏<notifications@github.com
