### ISSUE TITLE
Surface Pro 4: No wifi or touch after close the typecover and reopen it.

### ISSUE THREAD

**Issue by MashPlant** [jakeday/linux-surface#136]
It works well right after booting up. However after I close the typecover and reopen it, wifi and touch won't work any more.

**Comment by jakeday** [comment]
@MashPlant What action are you associating with the lid close event? Suspend? Hibernate? Freeze?

**Comment by MashPlant** [comment]
@jakeday I'm not sure. I'm on default setting.

**Comment by jakeday** [comment]
@MashPlant Depending on if you had issues copying over my scripts and running the commands, the default might still be suspend. You'll need to switch to hibernate.

**Comment by MashPlant** [comment]
@jakeday I tried to switch to hibernate, but wifi and touch still don't work. (In fact, when I directly enter "sudo systemctl hibernate" in the terminal, they won't work after waking up) Then I switched to ignore. Fortunately they work this time. Thank you a lot anyway.

**Comment by jakeday** [comment]
Glad they work now!
