### ISSUE TITLE
SB2 : pci express hotplug floods  logs when docking

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#137]
When I dock the SB2 (13"), the pci express hotplug module floods logs with messages like : 

pciehp 0000:00:1c.4:pcie04: Card not present on Slot()
pciehp 0000:00:1c.4:pcie04: Card present on Slot()
pciehp 0000:00:1c.4:pcie04: Failed to check link status

For now, I was able to fix this with : 
`echo 0000:00:1c.4:pcie04 > /sys/bus/pci_express/drivers/pciehp/unbind`
at boot (/etc/rc.local)

Note that some boot kernel parameters like `pcie_aspm=off` also works.

**Comment by jakeday** [comment]
@deb75 This is fixed with my latest commits. Will push new prebuilt kernels shortly.

**Comment by deb75** [comment]
Hi,

Thanks for your reply.

I saw your latest changes in the kernel configuration, it seems that you disable entirely the pci express port bus (?)

I am surely not as skilled as you, but I wonder if it is necessary : will this choice affect the speed of devices which are connected to the pci express bus (like the nvidia card) ?

Furthermore, this is the pci express hotplug driver which was responsible for this issue. Recompiling the kernel without pcie hotplug, but letting pcie, solved it (at least no messages).

Also, disabling totally the pci express port can be achieved at boot with the kernel parameter : "pcie_ports=compat". I tried and dmesg confirms pcie is disabled. This saves you from recompiling the kernel.

Regards

**Comment by jakeday** [comment]
@deb75 While that's true to a degree, pcie decives can be used just fine with little performance loss without the pcie port bus enabled. Actually, using pcie_ports=compat or just letting it flood the errors will cause it to kick down to pci-to-pci so there is no impact on what you are seeing now. There are enhancements being working in linux-next to fix this so this a a temporary solution. Also, letting it be a kernel config is nice for those who are a little more experienced and requires no extra steps for those with a little less experience.
