### ISSUE TITLE
Surface Pro 3:  Touchscreen not working

### ISSUE THREAD

**Issue by karlberggren** [jakeday/linux-surface#139]
After updating the drivers (including marvell firmware and i915 bxt)) as instructed, touchscreen not working anymore.  

4.15.16-surface-linux-surface #37 SMP Tue Apr 10 09:01:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by jakeday** [comment]
@karlberggren I'm a little confused as the patches aren't required for the touchscreen on the SP3 nor do they impact it. Can you get me the output of dmesg and the xorg log?

**Comment by karlberggren** [comment]
I was able to  find the dmesg, but not the xorg log (/var/log didn't have any...could they be called something e3lse?)

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1908799/dmesg.txt)

**Comment by jakeday** [comment]
@karlberggren Looking at your dmesg output, the devices are correctly setup from the kernel. I would imagine it's a configuration issue. The xorg logs whould be in /var/log as well, unless you are using something else (which also may not support touch).

**Comment by jakeday** [comment]
@karlberggren I think that libinput is not picking up the touch device. I updated my 99-touchscreens.rules to support it.

**Comment by karlberggren** [comment]
I'm assuming this means I need to download and install the revised kernel.  Will do and confirm.

**Comment by karlberggren** [comment]
[dmesg.txt](https://github.com/jakeday/linux-surface/files/1913163/dmesg.txt)
[Xorg.0.log](https://github.com/jakeday/linux-surface/files/1913164/Xorg.0.log)
4.15.17-surface-linux-surface #38 SMP Sun Apr 15 09:53:45 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
I upgraded to the 4.15.17 version of the kernel (hope that was the right thing to do?) and touchscreen not working.

**Comment by jakeday** [comment]
@karlberggren Again, based on the logs it is loaded and working. It must be a configuration on your setup. Also, did you copy over the updated rules files?

**Comment by karlberggren** [comment]
I have, but I am going to close the issue for now.  I will try to figure out if I can adjust configuration, and try with pen, and a few other things, perhaps reinstall everything from scratch, then reopen if it is still giving me trouble.

Thanks!

**Comment by jakeday** [comment]
Sounds good, let me know!

**Comment by Orooz** [comment]
@jakeday 
I have the same problem!
Device:Surface Pro 3
Description: Ubuntu 18.04
The touchscreen works fine when it is working alone, but when the type cover(sp4 model) is connected, the touchscreen doesn't work anymore.
I think,it's a configurations problem,but I have no ideal,how to fix it.

**Comment by skydancer23** [comment]
Device: Surface Pro 3 + SP4 Keyboard
Description: Ubuntu 18.04.01
Kernel: Jakeday 4.17.3-3
Same problem. Touch was working fine with stock Ubuntu kernel. And stopped working after installation of Jakeday kernel
