### ISSUE TITLE
WPA2 still unstable

### ISSUE THREAD

**Issue by PrinceRAndrew** [jakeday/linux-surface#14]
Hi i installed your kernel and it's wonderful, only problem is that the wifi is still unstable in my schools enterprise network. I lose connection anywhere from 2 min to 20 min after boot. I haven't found any kernel past 4.9 that is stable in this wifi environment, is there any way to magically port all your edits to a 4.9 kernel?
Here's my dmesg report. Lotta red :(((
[    6.676868] audit: type=1400 audit(1508718894.063:9): apparmor="STATUS" operation="profile_load" name="/usr/lib/lightdm/lightdm-guest-session" pid=654 comm="apparmor_parser"
[    6.676995] audit: type=1400 audit(1508718894.063:10): apparmor="STATUS" operation="profile_load" name="/usr/lib/lightdm/lightdm-guest-session//chromium" pid=654 comm="apparmor_parser"
[    6.690739] audit: type=1400 audit(1508718894.079:11): apparmor="STATUS" operation="profile_load" name="/sbin/dhclient" pid=652 comm="apparmor_parser"
[    7.199167] mwifiex_pcie 0000:03:00.0: info: FW download over, size 820212 bytes
[    7.641070] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:63 / ret_size:0
[    7.643186] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:63 / ret_size:0
[    7.644030] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
[    7.644871] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:63
[    7.645712] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:7
[    7.647056] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:12
[    7.647905] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
[    7.648748] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
[    7.649592] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:4
[    7.651143] i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:15
[    7.827027] input: Microsoft Surface Keyboard Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:045E:07CD.0001/input/input8
[    7.886637] input: Microsoft Surface Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:045E:07CD.0001/input/input9
[    7.886776] input: Microsoft Surface Keyboard Touchpad as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:045E:07CD.0001/input/input10
[    7.886984] input: Microsoft Surface Keyboard Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:045E:07CD.0001/input/input11
[    7.887145] hid-multitouch 0003:045E:07CD.0001: input,hiddev0,hidraw0: USB HID v1.11 Keyboard [Microsoft Surface Keyboard] on usb-0000:00:14.0-1.4/input0
[    7.950382] usb 1-6: new high-speed USB device number 4 using xhci_hcd
[    8.091444] usb 1-6: New USB device found, idVendor=1286, idProduct=204c
[    8.091446] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    8.091448] usb 1-6: Product: Bluetooth and Wireless LAN Composite Device
[    8.091449] usb 1-6: Manufacturer: Marvell
[    8.091450] usb 1-6: SerialNumber: 0000000000000000
[    8.162541] mwifiex_pcie 0000:03:00.0: WLAN FW is active
[    8.257052] mwifiex_pcie 0000:03:00.0: CMD_RESP: cmd 0x242 error, result=0x2
[    8.257055] mwifiex_pcie 0000:03:00.0: mwifiex_process_cmdresp: cmd 0x242 failed during	initialization
[    8.280997] mwifiex_pcie 0000:03:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p77) 
[    8.280998] mwifiex_pcie 0000:03:00.0: driver_version = mwifiex 1.0 (15.68.7.p77) 
[    8.282164] mwifiex_pcie 0000:03:00.0 wlp3s0: renamed from mlan0
[    9.566231] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[    9.566295] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[    9.660662] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[   13.009793] snd_hda_intel 0000:00:1f.3: IRQ timing workaround is activated for card #0. Suggest a bigger bdl_pos_adj.
[   27.324034] Could not find key with description: [31247f41b8b43385]
[   27.324038] process_request_key_err: No key
[   27.324038] Could not find valid key in user session keyring for sig specified in mount option: [31247f41b8b43385]
[   27.324040] One or more global auth toks could not properly register; rc = [-2]
[   27.324042] Error parsing options; rc = [-2]
[   29.133573] mwifiex_pcie 0000:03:00.0: info: trying to associate to 'eduroam' bssid

**Comment by jakeday** [comment]
This doesn't look like the latest 4.14 version of my kernel. Can you please give that one a try?

**Comment by PrinceRAndrew** [comment]
Im sorry. Sometimes I do really stupid stuff and need someone to point it out to me. I installed the old kernel. I've been running the new one for a day now and it works like a dream. You're my hero sir! This makes linux for my classes actually enjoyable to use :))) thank you!!!
