### ISSUE TITLE
SB2 (13") : hibernation hangs after undocking/docking

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#141]
Hi,

On my SB2 13", debian 10 with linux-surface 4.15.16 (recompiled) kernel, hibernation and docking/undocking work fine.

Nevertheless, I noticed that after undocking/docking, hibernation (sudo pm-hibernate with uswsusp method)
hangs : it seems at first to work but instantly resumes, everything seems to work fine after.

In logs, I see that it is due to the i915 module which hangs : "[drm] GPU HANG ... in Xorg ... reason: Hang on rcs0, action: reset"

Did you experience such troubles ?

**Comment by jakeday** [comment]
@deb75 I have the nouveau driver blacklisted on my device as well and have not seen any issue. Unloading it worked fine with the reset prior to hibernation as well, though. As for the proprietary nvidia driver, I don't use it. Might be better to ask that on reddit.

**Comment by deb75** [comment]
Hi,

Thanks for your answeer, may I ask you what you meant by saying "Unloading it worked fine with the reset prior to hibernation as well". How do you perform a reset ?
