### ISSUE TITLE
SB2 : undocking udev rule not working

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#147]
For my SB2, with surface 4.15.16 kernel, the udev rule for undocking : 
`ACTION=="remove",SUBSYSTEMS=="usb",ATTR{idVendor}=="045e",ATTR{idProduct}=="0922", RUN+="/sbin/modprobe -r nouveau"`

is not working.

I just replaced the RUN command by "/usr/bin/touch /tmp/toto" and checked that nothing is created under /tmp when I undock. I blacklisted the nouveau driver, so I do not need them.

On the contrary, the udev rule for docking (ACTION=="add") do work with same test as above.

I checked with "udevadm monitor" that the undocking is detected with "remove" and "unbind" actions, so why the udev rule does not work ?

**Comment by jakeday** [comment]
@deb75 This is due to the matching for events with udev rules. I've updated the rule and will push it shortly.
