### ISSUE TITLE
Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by wildapt01** [jakeday/linux-surface#148]
First and foremost, many heartfelt thanks for your contributions. It really is a big help to get a Surface device running with Linux.

My main question applies to the soon public LTS version of Ubuntu, flavor 18.04. Do you expect problems with your custom Kernel? Can I upgrade from my actual 16.04 LTS without re-installing the whole stuff?

Thks in advance for any pointer!

**Comment by jakeday** [comment]
@wildapt01 I'm glad you're enjoying the kernel! As for Ubuntu 18.04, my kernels should work there as well with no problem!

**Comment by sergiusens** [comment]
I am on 18.04. Although I rebase the patches on top of an Ubuntu kernel to
get the latest and greatest apparmor bits for better lxd and snap support
(apparmor profile stacking for the most part)

**Comment by wildapt01** [comment]
@sergiusens  : Thanks Sergio to chime in. Much appreciated! 
Nevertheless, you got me lost a bit after the " rebase the patches...", I am very very green at the whole thing here. My apologies :-)
The plan so far is to update to 18.04. Should I upgrade the kernel to 4.16 first or after? Once done in the proper order (thanks in advance to let me know), should I reinstall the adequate 4.16 jakeday-headers/image/libdc?

**Comment by sergiusens** [comment]
If you follow the instructions to the letter as on the repo, you should be
fine on 18.04.

**Comment by wildapt01** [comment]
Thanks, will do.
