### ISSUE TITLE
Surface Book 2 : pen does not rotate with screen

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#150]
Hi,

When trying to rotate the screen like this :  `xrandr --output eDP1 --rotate left`

The screen indeed rotates but not the pen/touchpad (kernel 4.15.17).

I searched a little, does it depend on the wacom library ? As far as I know, the surface book 2 stylus is not made with wacom technology (?), the pen does work well while  `xsetwacom --list devices` returns
 nothing.

**Comment by 22dm** [comment]
I can rotate the pen/touch by using xinput on Surface Book.

**Comment by deb75** [comment]
RIght :smile:  

To turn portrait mode : 

```
#!/bin/sh

xrandr -o left
xinput set-prop "ipts 045E:0021 Touchscreen" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "ipts 045E:0021 Mouse"       --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "Microsoft Surface Keyboard Touchpad" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "ipts 045E:0021 Pen" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "ipts 045E:0021 Pen Pen (0)" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
```
and to turn landscape mode : 

```
#!/bin/sh

xrandr -o normal
xinput set-prop "ipts 045E:0021 Touchscreen" --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
xinput set-prop "ipts 045E:0021 Mouse"       --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
xinput set-prop "Microsoft Surface Keyboard Touchpad" --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
xinput set-prop "ipts 045E:0021 Pen" --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
xinput set-prop "ipts 045E:0021 Pen Pen (0)" --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1"
```

That is to note the device "ipts 045E:0021 Pen Pen (0)" is not listed in `xinput --list` at first. I try first to use "ipts 045E:0021 Pen" but it returns this error : 
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  57 ()
  Serial number of failed request:  19
  Current serial number in output stream:  20
```
then the device "ipts 045E:0021 Pen Pen (0)" appears in the xinput list.

**Comment by jakeday** [comment]
@deb75 Yes, you'll still need to updated wacom library.

**Comment by deb75** [comment]
I updated the libwacom library by recompiling the debian source with _geoffholden_ patch.
Then,   `libwacom-list-local-devices` does return something, but `xsetwacom --list devices` does not.

For xsetwacom to detect touchscreen and stylus, I guess I would have to configure the Xorg driver. But to what extent is it necessary ? If it is already recognized and works well (not with all applications though, e.g. xournal)
