### ISSUE TITLE
Surface Pro 2 Mainline - Volume, Windows button and Displayport

### ISSUE THREAD

**Issue by lope** [jakeday/linux-surface#151]
**Surface Pro 2**

**On Ubuntu 16.04 with Mainline (standard) kernel**
* Touchscreen, Wifi, Sound - **yes**
* Displayport - **no**
* Volume buttons - **yes**
* Windows logo capacitive button (under screen) - (not tested)

**On Ubuntu 18.04 with Mainline (standard) kernel**
* Touchscreen, Wifi, Sound - **yes**
* Displayport - (not tested yet)
* Volume buttons - **no**
* Windows logo capacitive button (under screen) - **vibrates only**
> Touching the windows button makes the tablet vibrate, but I can't bind anything to it as a shortcut key and xev doesn't detect it.

**Jakeday kernel patches**
Will the kernel patches help with Surface Pro 2?

**Comment by jakeday** [comment]
@lope Support for the Surface Pro 2 is upstreamed and available in the mainline kernel. I don't have additional patches for the Surface Pro 2. Displayport and Buttons are both supported, but you may have a configuration issue.
