### ISSUE TITLE
Missing i915_firmware_kbl file during 4.16.5-1 install

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#156]
Patching up to the latest firmware and kernels - the latest i915_firmware_kbl.zip doesn't seem to have the /i915/kbl_dmc_ver_1_04.bin file that 4.16.5-1 is looking for during the install. I had a blank, black screen upon trying to boot into 4.16.5-1, might be a related issue.

Attached screenshot below showing the contents of i915_firmware_kbl.zip and the error message thrown during the install of the kernels.
![screenshot from 2018-04-27 15-02-29](https://user-images.githubusercontent.com/6579034/39380757-ad98527e-4a2d-11e8-80d7-bf3cbf5e916e.png)

_as always, thank you so much for your incredible work in wrangling this awesome piece of hardware to work for the rest of the surface-linux community!_

**Comment by xaviervilla** [comment]
Since I have been using this repo, on all 3 of my fresh installs of Ubuntu, I have received the same output and have never experienced any instability. I think it is safe to ignore this.

**Comment by jakeday** [comment]
I updated the i915 firmware files.

**Comment by versipellis** [comment]
Can confirm that 4.16.5-1 loads fine now with the new firmware files.
