### ISSUE TITLE
Question : does suspend to ram work with 4.16.xx kernels ?

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#157]
Hello,

I read on reddit that 4.16.xx kernels brought support for suspend to ram for surface devices.

It seems Connected Standby is not supported yet by linux but that you can at least suspend to ram on surface devices.

I gave it a try (with 4.16.5) ... and had to reboot.

Just wanted to know if anyone tried and had more success, as it was reported on reddit.

Regards

**Comment by tmarkov** [comment]
Suspend to idle works well for me on 4.16.5 (the .deb from this repo) on SB.
Suspend to ram (which is different) doesn't work well, as the hardware doesn't support it.

**Comment by jakeday** [comment]
@deb75 I can give a longer answer, but I'll spare you the details. The short answer is no, the linux kernel still does not support connected standy - which is what they use instead of suspend-to-ram - even in the newer 4.16 kernels.

**Comment by deb75** [comment]
Thanks for your explanations.

I tried "suspend to idle" with `echo freeze > /sys/power/state`. The screen immediately shut off, but I had been unable to wake up the SB2. I had to hard reboot.

This sounds strange to me as there is no sign of the "suspend to idle" in logs and that the keyboard wakeup events seems enabled according to `/proc/acpi/wakeup` : 

```
XHC	  S4	*enabled   pci:0000:00:14.0
```

@tmarkov : may I ask you how you go into suspend to idle and how you wake up your SB ?

**Comment by tmarkov** [comment]
It worked for me out of the box with 4.16 fresh install. I used power button or "systemctl suspend" to invoke the suspend (this file already sets it to idle, https://github.com/jakeday/linux-surface/blob/master/root/etc/systemd/sleep.conf). I wake up by opening lid or pressing power button. I didn't need to modify /proc/acpi/wakeup or any /sys nodes for that, and I still don't have PWRB or LID in my /proc/acpi/wakeup.

I would say, if it didn't work for you out of the box, don't use suspend. I've tried many workarounds but nothing was useable. For example, you can set up the keyboard to wake it up, but if you do, it will also wake up on touchpad, which essentially means it will wake up on its own all the time.
If you really do want to try,
echo "enabled" > /sys/bus/usb/devices/1-1.4/power/wakeup
to enable wakeup on keyboard (this is in addition to /proc/acpi/wakeup).

**Comment by tmarkov** [comment]
@deb75 
I looked some more into what's different for me in 4.16, and here's an idea:

Can you try this:
cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/PNP0C09:00/MSHW0040:00/power/wakeup

cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/power/wakeup

These two are the parent /sys nodes to the power button and lid switch nodes respectively, and if the above print "disabled" that would disable wake up on power button and lid switch.

**Comment by deb75** [comment]
Hi

Thanks for the idea.

First path, the one for power button, does not exist on the SB2. But second path, for the lid, does exists and is enabled. So, resuming from suspend by opening the lid works. I would like to find the correct path for the power button though.
