### ISSUE TITLE
Surface Book 2 : setup.sh

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#161]
Hi,

In the `setup.sh` script, I noticed the line for the surface book 2 :
```
unzip -o firmware/ipts_firmware_v101.zip -d /lib/firmware/intel/ipts/
```

I did so manually and after reboot touchscreen was not working anymore.

I removed everything in the `intel/ipts` directory and reinstalled the v137 version (and only this one).

This fixed the issue. I just let you know.

Regards

**Comment by jakeday** [comment]
Fixed in the setup.sh script!
