### ISSUE TITLE
Surface Pro 4 Wi-Fi drops after a random amount of time on ubuntu 18.04 LTS 

### ISSUE THREAD

**Issue by dsmanneke** [jakeday/linux-surface#163]
I have an issue on SP4 running Ubuntu 18.04 LTS 4.16.6-surface-linux-surface

The Wi-Fi drops after a random amount of time. 
reload the Wi-Fi drivers every time when the Wi-Fi drops is not working

sudo modprobe -r mwifiex_pcie
sudo modprobe -r mwifiex
sudo modprobe mwifiex
sudo modprobe mwifiex_pcie

by rebooting the machine will temporary solve the issue

In `dmesg | grep "mwifiex_pcie 0000:02:00.0"`  i see the following
```
[    5.245244] mwifiex_pcie 0000:02:00.0: enabling device (0000 -> 0002)
[    6.831998] mwifiex_pcie 0000:02:00.0: info: FW download over, size 843828 bytes
[    7.812152] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[    7.924071] mwifiex_pcie 0000:02:00.0: Unknown api_id: 4
[    7.950832] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[    7.950835] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[    7.953023] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
[   10.879387] mwifiex_pcie 0000:02:00.0: info: trying to associate to ' Enterprice' bssid XX:XX:XX:XX:c6:e1
[   10.950397] mwifiex_pcie 0000:02:00.0: info: associated to bssid XX:XX:XX:XX:c6:e1 successfully
[   99.516806] mwifiex_pcie 0000:02:00.0: Firmware wakeup failed
[   99.517189] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[   99.517242] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517249] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.517256] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517261] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.517267] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517272] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.517277] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517282] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.517288] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517294] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.517300] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.517305] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[   99.518207] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.523884] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
[   99.536142] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[   99.536161] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[  100.638116] mwifiex_pcie 0000:02:00.0: WLAN FW already running! Skip FW dnld
[  100.638124] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[  100.690985] mwifiex_pcie 0000:02:00.0: Unknown api_id: 4
[  100.710991] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[  100.711000] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[  100.731062] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
[  103.480852] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'Enterprice' bssid XX:XX:XX:XX:c6:e1
[  103.512365] mwifiex_pcie 0000:02:00.0: info: associated to bssid be:XX:XX:XX:c6:e1 successfully
[  125.628313] mwifiex_pcie 0000:02:00.0: cmd_wait_q terminated: -110
[  135.661596] mwifiex_pcie 0000:02:00.0: info: successfully disconnected from be:XX:XX:XX:c6:e1: reason code 2
[  137.660261] mwifiex_pcie 0000:02:00.0: cmd_wait_q terminated: -110
[  137.660266] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[  149.692740] mwifiex_pcie 0000:02:00.0: cmd_wait_q terminated: -110
[  149.692751] mwifiex_pcie 0000:02:00.0: deleting the crypto keys

```
I tried after the issue occurs to set the power save mode off 
```
sudo iw dev wlp2s0 set power_save off
command failed: Connection timed out (-110)
```

**Comment by roundeye** [comment]
I was having an issue with Wi-Fi dropping on a Surface Book, and this is what resolved it for me.

Run `nmcli c show <YOUR SSID>` and see if it shows `802-11-wireless.powersave:              2 (disable)` on line 36. If it shows anything but `2 (disable)` run `nmcli c modify <YOUR SSID> wifi.powersave 2` and see if that keeps Wi-Fi from dropping.

Example: My SSID is :) so I used `nmcli c modify ':)' wifi.powersave 2`

**Comment by dsmanneke** [comment]
I did run the setup.sh script and the issue still exists.

**Comment by dsmanneke** [comment]
@roundeye I run your commands, it now takes longer for the error to occur

**Comment by jakeday** [comment]
@roundeye That is baked into both the kernel and the scripts installed from setup.sh. It's kinda odd if doing that helps, considering that it's already included which suggests it's more so the script either wasn't run or didn't run successfully.

**Comment by tmarkov** [comment]
Wi-fi used to drop for me, too. I actually resolved it by doing fresh install removing the mrvl firmware. Not that it's perfect now, but instead of dropping the ping jumps to 1000+.

**Comment by forlornidealist** [comment]
@jakeday I can confirm mine (SB2, Ubuntu 17.10) also shows wifi.powersave as enabled. The output of 'iw dev wlp1s0 get power_save' also shows enabled, which I believe you said in a different issue should be disabled by your scripts.

**Comment by rhartley-tech** [comment]
Surface Pro 4 with Ubuntu 18.04 here, using the latest linux-surface kernel release. Can confirm Power Save still shows as being enabled using iw and nmcli even after running scripts. Disabling using methods mentioned by others above works as an interim option.

Also noticed that under /etc/NetworkManager/conf.d there is a conf that sets wifi.powersave to **3**. Could that be interfering?

Happy to offer more debug info if needed.

**Comment by dsmanneke** [comment]
this is what I got from the lastest kernel version 4.16.7-surface-linux-surface
`[    3.802559] mwifiex_pcie 0000:02:00.0: enabling device (0000 -> 0002)
[    3.802696] mwifiex_pcie: try set_consistent_dma_mask(32)
[    3.802732] mwifiex_pcie: PCI memory map Virt0: 00000000d823b061 PCI memory map Virt2: 00000000be174b6e
[    5.459335] mwifiex_pcie 0000:02:00.0: info: FW download over, size 843828 bytes
[    6.432126] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[    6.544924] mwifiex_pcie 0000:02:00.0: Unknown api_id: 4
[    6.575608] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[    6.575610] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[    6.577712] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
[    9.474493] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'mstnetwork Enterprice' bssid 4e:5e:0c:f6:f4:4d
[    9.553380] mwifiex_pcie 0000:02:00.0: info: associated to bssid <bssid> successfully
[   78.541710] mwifiex_pcie 0000:02:00.0: info: successfully disconnected from 4e:5e:0c:f6:f4:4d: reason code 3
[   84.035751] mwifiex_pcie 0000:02:00.0: info: trying to associate to '<ssid>' bssid <bssid>
[   84.134082] mwifiex_pcie 0000:02:00.0: info: associated to bssid <bssid> successfully
[ 1303.387890] mwifiex_pcie 0000:02:00.0: info: successfully disconnected from <bssid>: reason code 3
[ 1303.781011] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
[ 1303.781578] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed <-----
` 
it seems like it shutdown the WiFi interface. it doesn't show up under gnome3 and in ifconfig
`nmcli c show <ssid> | grep powersave
802-11-wireless.powersave:              2 (disable)`

**Comment by lamarios** [comment]
Facing the same issue
```
$ iw dev wlp2s0 get power_save
> Power save: on

```

**Comment by oleid** [comment]
It would seem I've a similar issue, albeit power_save is off on my Surface Pro 4. I'm running pharra's built of `4.16.9-1-surface4 #5 SMP PREEMPT Thu May 17 08:51:32 CST 2018 x86_64 GNU/Linux` for ArchLinux. 

<pre>
dmesg  | grep -i wifi
[   16.966790] mwifiex_pcie 0000:02:00.0: enabling device (0000 -> 0002)
[   16.966939] mwifiex_pcie: try set_consistent_dma_mask(32)
[   16.966982] mwifiex_pcie: PCI memory map Virt0:         (ptrval) PCI memory map Virt2:         (ptrval)
[   18.490215] mwifiex_pcie 0000:02:00.0: info: FW download over, size 843828 bytes
[   19.450150] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[   19.577845] mwifiex_pcie 0000:02:00.0: Unknown api_id: 4
[   19.613364] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[   19.613366] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[   19.613880] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
</pre>

It would seem power save is off:

`$ sudo iw dev wlp2s0 get power_save
Power save: off`

After a random amount of time in the order of hours, I get:
<pre>[ 1241.000186] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1247.000700] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1247.000703] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1247.000723] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
</pre>

Of course, I'm using the firmware and the config from this repo.

**Comment by oleid** [comment]
It would seem, that power saving is responsible after all. I used powertop to "tune" all devices in my Surface Pro 4 but the Marvell Wifi chip. Nevertheless, this seems to trigger the issue for me. Anyone using powertop, too?

**Comment by remingtonlang** [comment]
I had this issue on my SP17. I haven't seen this mentioned here yet so to point out.. turning off power save isn't enough to stop the firmware from bombing out. In networkmanager:

```[connection]
wifi.powersave = 2
[device]
wifi.scan-rand-mac-address=false```

At least for the 2017 model wifi is 100% reliable

**Comment by m9115m** [comment]
@remingtonlang What file is wifi.powersave in?

Having the same issue on a SP4 with 4.16.7.  I'll try anything.  Have a $10 USB nub plugged now, which is working great.

**Comment by m9115m** [comment]
@GammaPi Thanks, Works!  I've been off the wifi nub for three days now, using SP4's internal wifi and it works great. Browsing the web, Hulu, YouTube, etc.  It's rock solid. No more wifi drops.  A simple change to the config file worked!  I'm on Xubuntu 18.04, 4.16.7 Kernel

**Comment by itsapenguinmachine** [comment]
I can confirm, that @remingtonlang's solution fixes the issue permanently.
At first I tried the prev. suggested solution to set powersave to 2, but that alone didn't the trick.
with 
[connection]
wifi.powersave = 2
[device]
wifi.scan-rand-mac-address=false
it has been stable for a week now. (on SP4 i7)

Thanks for posting the solution!

**Comment by FrankLiu007** [comment]
I can confirm, use " iw dev wlp2s0 get power_save" , I get "Power save: on". When I turn it off, everything goes fine. But when I connect to a new wifi, it show "Power save: on".

**Comment by jakeday** [comment]
This is fixed in the latest configs. Please update and run setup.sh again.

**Comment by CumpsD** [comment]
@jakeday sorry to bump this old issue, but I'm facing this on a new Surface Laptop 2. Marvell FW is in a bad state, card removed.

power save is off in the config

**Comment by lonkaut** [comment]
Same issue as @CumpsD.  I experience this on SurfacePro6 with 5.1.15-1 kernel.  Bunsen labs / debian fresh install. Although never tried the power save thing.  I'll update once I do.
