### ISSUE TITLE
Touch and pen stop working after a time on 4.16.5 (Debian Stretch)

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#164]
It would work normally, until at some point touch and pen would simply stop being recognized.
Here's some logs:
dmesg | grep ipts
[112599.886129] IPTS ipts_mei_cl_init() is called
[112730.737167] IPTS ipts_mei_cl_exit() is called
[112730.737220] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in reading m2h msg
[112730.822009] IPTS ipts_mei_cl_init() is called
[112742.836464] IPTS ipts_mei_cl_exit() is called
[112742.836492] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in reading m2h msg
[112747.408532] IPTS ipts_mei_cl_init() is called

**Comment by tmarkov** [comment]
It's Surface Book. I use firmware version 76.

In the case reported above, I needed a reboot to restore touch.

I have lost touch and pen on several other occasions as well, but in those cases unloading and reloading the ipts modules was enough to fix it, and no new lines containing ipts were added to dmesg.

**Comment by jakeday** [comment]
@tmarkov Can you get me a full dmesg output after it happens?

**Comment by tmarkov** [comment]
This would probably take some time. So far it hasn't happened very often.

**Comment by tmarkov** [comment]
I just lost touch input. This time, I was able to restore it by simply removing and reloading the touch modules. Attaching the dmesg.

PS> Should I open two different issues for the case where I can fix it by reloading the modules and for the case where I can't?

dmesg: https://pastebin.com/xLCqrxSD

**Comment by tmarkov** [comment]
I just lost touch input. This time, I was able to restore it by simply removing and reloading the touch modules. Attaching the dmesg.

PS> Should I open two different issues for the case where I can fix it by reloading the modules and for the case where I can't?

dmesg: https://pastebin.com/xLCqrxSD

I believe I lost touch input somewhere between these two lines:
[ 6247.706975] usb 2-1-port3: cannot disable (err = -110)
[ 6666.766135] usb 2-1: new SuperSpeed USB device number 4 using xhci_hcd

**Comment by tmarkov** [comment]
OK, it happened again. I was again able to restore touch with removing and reloading the modules, but this time the dmesg actually contains some IPTS-related errors, so I'll upload it too.

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1977543/dmesg.txt)

**Comment by jakeday** [comment]
@tmarkov This should be solved in my 4.16.7 kernel.
