### ISSUE TITLE
Surface Pro 2017 rotate to black

### ISSUE THREAD

**Issue by dl-sledding** [jakeday/linux-surface#165]
When I rotate from landscape (default) to portrait (using "xrandr -o left"), the screen turns to black.  The OS is still running, but even attempting to rotate back (using "xrandr -o normal") does not fix the problem.  A reboot is required to restore the screen.

**Comment by dl-sledding** [comment]
Also, the screen does not rotate automatically using the onboard sensors,  I had to create keyboard shortcuts to easily change from one orientation to the other.  This may need to be a separate issue...

**Comment by dl-sledding** [comment]
I created keyboard shortcuts to troubleshoot this a little more.

I rotated to portrait mode, and then created a screenshot, saved it, and rebooted.  The screenshot shows a portrait screen.

![screenshot from 2018-05-02 14-31-27](https://user-images.githubusercontent.com/14353013/39545398-b8cb16f8-4e16-11e8-859f-ee2ccefb5a2e.png)

Then, I again rotated to portrait, then back to landscape, then took a screenshot.  The new screenshot (which should have been in landscape mode) still shows portrait.  So, once it rotates to portrait, it's stuck there, and will not rotate back.

I can rotate back and forth from normal to inverted (both landscape) with no problem.

**Comment by remingtonlang** [comment]
I just tested this on my SP2017, running Ubuntu 18.04 w/ Jakes 4.16.3 kernel. Screen rotation works in Ubuntu without the need for xrandr or keyboard shortcuts, just flip the computer and it works. Implies to me your issue is related to Mint's configuration. I'd guess DE specific

**Comment by jakeday** [comment]
@remingtonlang I would try asking on reddit as I don't use Mint so can't really help.

**Comment by remingtonlang** [comment]
@dl-sledding install and configure https://github.com/hadess/iio-sensor-proxy

I tried Arch on my SP17 recently and that was the fix for screen rotation.
