### ISSUE TITLE
Surface Book: Hibernate Not Working

### ISSUE THREAD

**Issue by cravend** [jakeday/linux-surface#166]
When I click the hibernate button, my screen goes black but I can still hear the fans & my keyboard stays lit. It looks like clicking hibernate is equivalent to simply locking the screen. Is this how it's supposed to work? I'm using Ubuntu Budgie 17.10.

Thanks!

**Comment by jakeday** [comment]
@cravend That depends entirely on how you mapped the even to the button. This is likely a configuration issue. Can you provide additional detail?

**Comment by cravend** [comment]
My bad--when I said button, I meant the menu option on-screen (not a physical button).

I followed this tutorial, using "hibernate" instead of shutdown: http://tipsonubuntu.com/2016/10/24/ubuntu-16-10-auto-shutdown-hibernate-lid-closed/

**Comment by cravend** [comment]
I think I might not know the difference between hibernate & suspend to disk. Is there a way to test if hibernate is working?

**Comment by roundeye** [comment]
@cravend Looking over that tutorial, it has you editing the logind.conf file. Which setting in logind.conf did you change to hibernate? If it was HandlePowerKey, then that's for the physical power key on your device, not your Desktop Environment's power menu option.

You can test if hibernation works by using `systemctl hibernate` at the command line.

**Comment by forlornidealist** [comment]
I have the same behavior when using systemctl hibernate on Ubuntu 17.10 Desktop on a Surface Book 2. I was able to get hibernate working (Ubuntu doesn't seem to work with hibernate out of the box), but it only works once. On second hibernation, it will attempt to hibernate but keep running and turn off the screen as described by @cravend, with the WiFi not working. If i run the post commands found in /lib/systemd/system-sleep/hibernate, it fixes Wi-Fi, but I can't hibernate again unless I reboot.

**Comment by versipellis** [comment]
Can confirm same behavior with systemctl hibernate on Ubuntu 17.10, SB2 - it doesn't hibernate properly. Seems to shut down instead and boot back up after.

**Comment by forlornidealist** [comment]
@versipellis I'm not clear if that behavior isn't an Ubuntu thing vs. the kernel. I followed the instructions here (in short, ensure you're using a swap partition rather than a file and configure grub to use it for suspending):
https://ubuntuforums.org/showthread.php?t=2334278

Once I did that, I was able to hibernate properly, but as I mentioned above, it only does this properly once. Subsequent hibernations result in the screen turning off as if it goes into hibernation and immediately comes out of it without ever actually turning off. If I reboot I can hibernate once again. This obviously isn't ideal, but is a massive improvement for me as this is my work machine and I don't usually need to hibernate more than a couple of times per day; and that's only on days I have to commute.

**Comment by battaglia01** [comment]
I have more or less the same problem, intermittently, on an SP4 running KDE Neon (based on Ubuntu Trusty). Quite often, hibernate will leave the machine on with the screen shut off, with keyboard backlight still on. If I hold the power button for ~10s then the thing finally shuts off completely. I can then turn it back on, at which point it boots correctly and reloads the hibernated state without a problem. This has happened on the 4.15.12 and 4.16.0 kernels.

**Comment by battaglia01** [comment]
This seems to be the same problem as here (https://github.com/jakeday/linux-surface/issues/56). That thread is SP4-specific but closed, so if this is supposed to be only for SB2, I'll bring this there.

**Comment by jakeday** [comment]
I've made some kernel changes and updated the scripts and configs from setup.sh to address this. Can someone please verify?

**Comment by dfsbbl** [comment]
@jakeday After I followed the instructions given by @forlornidealist and updated to the latest kernel, hibernation works fine for not only the first time but also more than one time, and the WiFi problem does not exist anymore. However, same as the instructions suggest, after I run `sudo systemctl hibernate`, the computer hibernates successfully but reboot immediately afterwards, and I have to choose to boot into Windows, which is quite annoying. Is there any fix for the reboot problem, or is there a better way to configure hibernation than the given instructions?

My device is Surface Book (1st gen), dual boot with Ubuntu 18.04 LTS and Windows 10.

**Comment by vonAlenberg** [comment]
Sorry to bring this topic up again, maybe I'm too stupid...  

Ubuntu 18 and Win10 in dual boot. Refind as Bootmanager. Running kernel 4.17 and created swap partition according to https://help.ubuntu.com/community/SwapFaq#How_do_I_add_or_modify_a_swap_partition.3F

When I tell my SB2 to 
`sudo systemctl hibernate`  
it blacks out and the keyboard also gets shut down. When pressing the physical power button it reboots into refind (so far so good), but it has nothing saved - its like a fresh reboot. 

Can someone point me in the right direction pls?

**Comment by drannex42** [comment]
@vonAlenberg did you ever figure it out? Same issue.

**Comment by vonAlenberg** [comment]
Nope, not working at all.   
Maybe it has something to do with me using rEFInd as bootmanager, so that - when I select my Ubuntu install - it boots into the initramfs instead of the swap-partition? Just an idea...

**Comment by thekswenson** [comment]
Unfortunately hibernate doesn't work at all on my SP4. There was a kernel version at one point where the first hibernate would work, but successive hibernations wouldn't. With the more recent kernels this no longer seems to be the case: the machine will shutdown but the next boot does not appear to load anything from swap.

**Comment by edwarmic** [comment]
Actually I have this currently running on Manjaro on my SP4, all working well accept of the known issues with the camera and in Arch the battery indicator s aren't working, but hibernation is working well. I as well tested it in Ubuntu and Kubuntu (but then went on to Arch after jakedays kernel got forked). I can hibernate using the above instruction to setup a swap partiion https://help.ubuntu.com/community/SwapFaq#How_do_I_add_or_modify_a_swap_partition.3F and I as well use Refind since the switch to Manjaro with Jakeday's kernel or with the latest 4.18.5-1 kernel. I now installed Openbox into Manjaro and Jakeday's kernel as well works fine (accept of camera and battery and here as well the keyboard lights aren't working). Just to let you know it can work on a SP4, always in dual-boot with win10. cheers

**Comment by thekswenson** [comment]
@edwarmic That's surprising news! Does anyone else have hibernation working on SP4?

**Comment by thekswenson** [comment]
Thanks @edwarmic for the reminder about setting GRUB_CMDLINE_LINUX in my grub file!

This must have gotten changed when I upgraded to 18.04.  So my machine do hibernate now. The only problem is that wifi often no longer works (and I can't reload the kernel module) after hibernation (https://github.com/jakeday/linux-surface/issues/227#issuecomment-419483787). :/

**Comment by bhatiaabhinav** [comment]
Running elementary os 5 (based on ubuntu 18.04) on 1st gen surface book. with kernel 4.18.16. 8 GB ram and 11 GB swap partition.
But `sudo systemctl hibernate` makes the screen go blank and turns off the machine. On pressing the power button, the laptop boots as if a fresh reboot. It does not resume.

**Comment by Evoxus** [comment]
I have a similar issue to @bhatiaabhinav, though it is on ubuntu 18.04 on the SB1 with performance base. No matter what I try with the swap partition, or messing with the settings making sure that it hibernates, instead of sleep, it will power up as if it is a fresh reboot, without saving any thing I had open. Any advice would be greatly appreciated. For now I have gone back to ubuntu 16.04 as everything works there, but I have 18.04 on my desktop and like the way it runs. Would like to get it to work right on the SB.

**Comment by aleksfadini** [comment]
Same for me, ubuntu 18.10 on Surface Pro 6. Hibernating shuts down the computer, turning on results in regular fresh reboot.

**Comment by saturn-hh** [comment]
I had also a hard time getting it working. I had the following things to check /change:

- Does the system use a swap partition. This is standard in newer Ubuntu systems. If so, check the size of the swap file. For me hibernation only works with 10.5GB or more (RAM is 8 GB). With smaller swap file size the system couldn't wake up but start as without hibernation.
-Add commands to the kernel line in grub configuration. For resume from a swap file you need at least resume= and resume_offset= with the correct values. (Google for getting the right configuration) 
- check if uswsusp is installed. If so, remove it. On the newer Ubuntu systems systemd is in charge for suspend and hibernation. For testing you can start hibernating by systemctrl suspend (sic) If you used the installer script from jakeday, the suspend brings the system to hibernate. 

Good luck

P. S. My system is resuming but after 20 seconds it's freezing.

**Comment by ohthehugemanatee** [comment]
This is definitely Ubuntu's fault, not Jakeday's. In 18.04 there are a bunch of default configurations that break hibernation. It comes down to a handful of issues:

* Your swapfile has to be bigger than your RAM. By default Ubuntu 18.04 creates a 2GB file, which probably isn't big enough. :)
* The grub config and initramfs configs need to know where to find the swapfile, using the `resume` and `resume_offset` variables to specify the device and block where the file begins.
* polkit needs to allow suspend/hibernate with lockscreen

It's all laid out nicely in https://fitzcarraldoblog.wordpress.com/2018/07/14/configuring-lubuntu-18-04-to-enable-hibernation-using-a-swap-file/ for you.

**Comment by sheiun** [comment]
> This is definitely Ubuntu's fault, not Jakeday's. In 18.04 there are a bunch of default configurations that break hibernation. It comes down to a handful of issues:
> 
> * Your swapfile has to be bigger than your RAM. By default Ubuntu 18.04 creates a 2GB file, which probably isn't big enough. :)
> * The grub config and initramfs configs need to know where to find the swapfile, using the `resume` and `resume_offset` variables to specify the device and block where the file begins.
> * polkit needs to allow suspend/hibernate with lockscreen
> 
> It's all laid out nicely in https://fitzcarraldoblog.wordpress.com/2018/07/14/configuring-lubuntu-18-04-to-enable-hibernation-using-a-swap-file/ for you.

I have already done that before but I still ran into the same problem, after I suspend the Ubuntu 18.04 on my Surface Pro 4. I can't wake it up no matter I type on my keyboard or press the power button.

I'm pretty sure my `resume_offset` and `UUID` are corret.
