### ISSUE TITLE
Surface Pro 3: i915 error at boot

### ISSUE THREAD

**Issue by Pyloox** [jakeday/linux-surface#167]
My setup: 
- Surface Pro 3
- Ubuntu 18.04 (fresh install)
- Surface Linux 4.16.6 (followed instructions step by step, accepted all patches, correct firmware was chosen (bxt))

The screen freezes at boot after these outputs (full journal [here](https://github.com/jakeday/linux-surface/files/1970933/journal.txt)):
```
Mai 03 14:38:13 Surface-Pro-3-Ubuntu kernel: i915 0000:00:02.0: can't derive routing for PCI INT A
Mai 03 14:38:13 Surface-Pro-3-Ubuntu kernel: i915 0000:00:02.0: PCI INT A: not connected
Mai 03 14:38:13 Surface-Pro-3-Ubuntu kernel: [drm] Incompatible option detected: enable_guc=1, no GuC hardware!
Mai 03 14:38:13 Surface-Pro-3-Ubuntu kernel: checking generic (b0000000 1e0000) vs hw (b0000000 10000000)
Mai 03 14:38:13 Surface-Pro-3-Ubuntu kernel: fb: switching to inteldrmfb from EFI VGA
```

Anyway, thanks in advance for your effort!

**EDIT:**
I previously missed the note about the Intel microcode. However installing it didn't solve the problem either.

**Comment by jakeday** [comment]
@Pyloox  Update your grub config to pass in enable_guc=0.

**Comment by Pyloox** [comment]
@jakeday Thanks! That solved the boot issue. Now touch/pen are not working and wifi is still unstable.
I actually came here because of the unstable and slow wifi, the only thing that doesn't work with fresh install. I even patched the drivers myself with an older Version of the Marvel drivers (7.p66) and checked the Network.conf entries but nothing changes. Do you have any further tips for solving or debugging that Problem?

**Comment by Data643** [comment]
I have the same boot issue, but the grub line doesn't seem to change anything for me.

My setup:

- Surface Pro 3
- xubuntu 18.04 (also tested in normal ubuntu 18.04, no difference)
- Surface Linux 14.16.7

Tested with and without the new microcode.

**Comment by MichaelBaumgarn** [comment]
I have the same problem. Could you clarify what 'adding' means? Said line doesn't have a `:` but instead has an `=` and does adding mean putting inside the quotations? This is what I have `GRUB_CMDLINE_LINUX=""      `                                                                                                      
Im gonna try now what I assumed you meant.

**Comment by Data643** [comment]
Yeah, my bad. Add `i915.enable_guc=0` inside the quotations

**Comment by MichaelBaumgarn** [comment]
Thanks for the clarification. Doing it fixed the problem so I can start up ubuntu again. However I still have wifi problems (wifi works but stops working completely after 30~ minutes and this can only be fixed by a restart). That problem was the reason I installed this in the first place...
