### ISSUE TITLE
SP3, Ubuntu 18.04, 4.16.6-1: Multiple Issues

### ISSUE THREAD

**Issue by Pyloox** [jakeday/linux-surface#169]
I'm not enough into it to debug it correctly or solve these problems, so i'll list them up here. Correct me if some of these are my fault, but i followed the exact instructions after Ubuntu fresh install:
- Boot freeze (solved [here](https://github.com/jakeday/linux-surface/issues/167), by passing enable_guc=0 to grub)
- Wifi still unstable (slow donwload speed, bad ping)
- Touch not working
- Pen not working
- Screen rotation not working (doesn't recognize rotation)
- Wifi gone after wakeup from hibernate (edit: can get wifi back up as described [here](https://github.com/jakeday/linux-surface/issues/166) by @forlornidealist)

Current journal file [here](https://github.com/jakeday/linux-surface/files/1974202/journal.txt)

**Comment by jakeday** [comment]
@Pyloox Some of these are already solved or are configuration issues. Can you please break these into multiple issues if you are still experiencing them?
