### ISSUE TITLE
apparmor-fix-4.14.patch does not cleanly apply on Ubuntu 17.10 

### ISSUE THREAD

**Issue by OpenIT4u** [jakeday/linux-surface#17]
My WiFi was not connecting so I applied the apparmor-fix-4.14 patch.  It did not apply cleanly, but WiFi is now working.  Please see attached files.

[apparmor.zip](https://github.com/jakeday/linux-surface/files/1408698/apparmor.zip)

**Comment by jakeday** [comment]
The patch includes the change needed for dhclient and for cupsd. Your cleanly applied the change for dhclient, which fixed your WiFi. However, the cupsd patch failed as your distro has that one configure differently. I'm not going to support patches for every distro, but you can look in the patch and apply it manually if you like.

**Comment by samsungrocks10** [comment]
I am also on 17.10 and have actually tried patching it manually but now wifi(and Ethernet with a usb adapter) doesn't work on any of the kernels I have, what i would like to know is how to patch it manually. I dont really understand what's in the patch, I did try doing a "git diff <dir_here> <dir_here>" command but i think that's what bricked my wifi now. Oh and my kernel is on your 4.14.0-rc7. Thanks

**Comment by samsungrocks10** [comment]
@jakeday Well, just ended up reinstalling ubuntu to fix my internet, gonna try installing the kernel back onto it

**Comment by jakeday** [comment]
@samsungrocks10 In reality, you could just open up /etc/apparmor.d/abstractions/nameservice and /etc/apparmor.d/sbin.dhclient and add the missing lines that the patch would add. Each distro handles apparmor configs a little differently, so it's hard to have a one-size-fits-all patch. Also, based on some comments in the lkml, the patch won't be needed after rc8 drops.

**Comment by samsungrocks10** [comment]
Oh, After I reinstalled Ubuntu and the rc7 kernel, it actually was working so I didn't have to mess with the/a patch anyway, but thanks @jakeday
