### ISSUE TITLE
SP4 i7 8GB, Ubuntu 18.04, release 4.16.6-1: cover/pen right-click not working

### ISSUE THREAD

**Issue by itsapenguinmachine** [jakeday/linux-surface#170]
Right clicks of the surface cover 
and the pen are handled like left clicks. 
(works fine with an usb-mouse)

In other issues I repeatedly read about having the "correct"(most recent?) firmware version 
or configuration.
Is this still a probable issue if I used the setup script and went through the instructions for
pre-built kernel and headers?

**Comment by dsmanneke** [comment]
I use the setup.sh script and I don't have that problem on my surface pro 4 with the cover. The pen right-click is also not working for me but i don't use the pen on my surface pro in Ubuntu.

**Comment by itsapenguinmachine** [comment]
Ok, I am an idiot. The right click on the type-cover works just fine. 
I didn't know the right-click is default-set as two-finger-tap, I changed it now to right-corner click with gnome-tweak. (pen right click still doesnt work, but well, not that important, glad I am having right click at all)

I do have the same issue with the wifi though as dsmanneke mentioned in another recent issue.
It seemed to have worked fine though before applying the patched kernel. Maybe I will find a way to reinstall the default wifi-drivers whilst keeping the patched kernel. (I am not very experience with linux)
Worst case is that I reinstall the whole OS again and check if I was right about the default wifi driver.
(with 18.04 on the SP4 everything except the touchscreen and the pen seemed to have worked out-of-the-box already)

**Comment by thekswenson** [comment]
The pen button is probably doing middle click actually.
I remap middle click to right click when I'm using the pen.
