### ISSUE TITLE
Surface Pro 4: How to use VGA projection

### ISSUE THREAD

**Issue by 1397350942** [jakeday/linux-surface#174]
- My computer is surface pro 4
- The installed system is ubuntu18.04
- I am a teacher, can only expand the screen but not through VGA projection
- Can you help me? thank you

**Comment by 1397350942** [comment]
Ubuntu 16.04 LTS I also tried but cannot clone the screen properly

**Comment by 1397350942** [comment]
Without that option, and the resolution cannot be adjusted

**Comment by jakeday** [comment]
@1397350942 Can you please further explain your issue? I don't understand the problem.

**Comment by BillKen** [comment]
Hi, I use the sp4 (gentoo) occasionally for teaching as well with a cheap vga adaptor:

the process is (important for my adaptor) 
1. plug vga connector into adaptor THEN plug it into the displayport coonection
2. create an X mode that the data projector understands (typically 1024x768 - it isn't actually used for display, but allows each side to see the other)
3. add scaled mode for laptop and enable

Problem is that many external vga terminals wont turn on unless they see the connection, and the displayport wont enable without seeing the vga - catch 22!  :(

script (run as user in a terminal):
#!/bin/bash

xrandr --auto
xrandr --newmode "1024x768_60.00"   63.50  1024 1072 1176 1328  768 771 775 798 -hsync +vsync
xrandr --output DP-1 --mode "1024x768_60.00"
xrandr --output DP-1 --auto

set `xrandr`
RES=${45}
echo Requested: ${RES}
xrandr --output eDP-1 --mode 2736x1824 --output DP-1 --mode ${RES} --same-as eDP-1 --scale-from 2736x1824
sleep 1
xrandr

**Comment by jakeday** [comment]
I'm not seeing an issue here and believe it might be better to ask on the SurfaceLinux subreddit.
