### ISSUE TITLE
Slow WLAN

### ISSUE THREAD

**Issue by njust** [jakeday/linux-surface#175]
Hi,

I installed Ubuntu 18.04 LTS with your 4.16.7 kernel on my surface book first generation and applied the patches via your setup.sh. Unfortunately the WLan is very slow. I only get around 30kb/s - 200kb/s download speed. Any help is highly appreciated!

root@pluto:/home/nico/Downloads# uname -a
Linux pluto 4.16.7-surface-linux-surface #63 SMP Sat May 5 20:22:46 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

root@pluto:/home/nico/Downloads# dmesg | grep "mwifiex_pcie"
[    3.643579] mwifiex_pcie 0000:03:00.0: enabling device (0000 -> 0002)
[    3.643707] mwifiex_pcie: try set_consistent_dma_mask(32)
[    3.643742] mwifiex_pcie: PCI memory map Virt0: 00000000131f27b9 PCI memory map Virt2: 000000000d89c86b
[    5.285527] mwifiex_pcie 0000:03:00.0: info: FW download over, size 843828 bytes
[    6.260104] mwifiex_pcie 0000:03:00.0: WLAN FW is active
[    6.386306] mwifiex_pcie 0000:03:00.0: Unknown api_id: 4
[    6.415871] mwifiex_pcie 0000:03:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[    6.415874] mwifiex_pcie 0000:03:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[    6.417927] mwifiex_pcie 0000:03:00.0 wlp3s0: renamed from mlan0
[    9.356339] mwifiex_pcie 0000:03:00.0: info: trying to associate to 'FRITZ!Box 6340 Cable' bssid 24:65:11:21:7b:98
[    9.427460] mwifiex_pcie 0000:03:00.0: info: associated to bssid 24:65:11:21:7b:98 successfully

root@pluto:/home/nico/Downloads# iwconfig 
enxc49dede7c1e0  no wireless extensions.

lo        no wireless extensions.

wlp3s0    IEEE 802.11  ESSID:"FRITZ!Box 6340 Cable"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 24:65:11:21:7B:98   
          Bit Rate=108 Mb/s   Tx-Power=9 dBm   
          Retry short limit:9   RTS thr=2347 B   Fragment thr=2346 B   
          Encryption key:off
          Power Management:off
          Link Quality=53/70  Signal level=-57 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

root@pluto:/home/nico/Downloads# lshw -C network
  *-network                 
       description: Wireless interface
       product: 88W8897 [AVASTAR] 802.11ac Wireless
       vendor: Marvell Technology Group Ltd.
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: wlp3s0
       version: 00
       serial: 98:5f:d3:41:6d:c7
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=mwifiex_pcie ip=192.168.178.70 latency=0 multicast=yes wireless=IEEE 802.11
       resources: irq:131 memory:b9500000-b95fffff memory:b9400000-b94fffff
  *-network
       description: Ethernet interface
       physical id: 1
       logical name: enxc49dede7c1e0
       serial: c4:9d:ed:e7:c1:e0
       capabilities: ethernet physical
       configuration: broadcast=yes driver=cdc_ether driverversion=22-Aug-2005 firmware=CDC Ethernet Device link=yes multicast=yes

**Comment by njust** [comment]
I'm sorry. Setting the region via "sudo iw reg set DE" solved my issue. Thanks for all your great work!

**Comment by 8b8** [comment]
I have the exact same issue with the same setup. (SP4; fresh minimal 18.04 + surface linux 4.16.7)
The region is also DE. After setting the region with
`sudo iw reg set DE`
the output of `iw reg get` is:
```
global
country DE: DFS-ETSI
	(2400 - 2483 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 20), (N/A), NO-OUTDOOR, AUTO-BW
	(5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
	(5470 - 5725 @ 160), (N/A, 26), (0 ms), DFS
	(5725 - 5875 @ 80), (N/A, 13), (N/A)
	(57000 - 66000 @ 2160), (N/A, 40), (N/A)

phy#0
country FR: DFS-ETSI
	(2402 - 2482 @ 40), (N/A, 20), (N/A)
	(5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW
	(5490 - 5710 @ 160), (N/A, 27), (0 ms), DFS
	(57000 - 66000 @ 2160), (N/A, 40), (N/A)
```

```
iwconfig
lo        no wireless extensions.

wlp2s0    IEEE 802.11  ESSID:"APNAME"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 04:26:E7:E1:30:91   
          Bit Rate=144.4 Mb/s   Tx-Power=13 dBm   
          Retry short limit:9   RTS thr=2347 B   Fragment thr=2346 B   
          Power Management:off
          Link Quality=68/70  Signal level=-42 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

```
Speed is still around 100 kbit. After changing the AP channel from 2.462 Ghz to 2.422 Ghz the speed increased to about 3Mbit, but is still considerably slower than it should be.

**Comment by njust** [comment]
Unfortunately it was only a temporary fix for me. I had a follow up post on the askubuntu forums where I described similar observations than you, I also had slightly better throughput when I changed channels:

https://askubuntu.com/questions/1036292/slow-wlan-on-18-04

Unfortunately no one could help.

**Comment by remingtonlang** [comment]
@njust I'm not sure this is a specific problem related to Jakes kernel but to the wifi driver itself. This is probably not an appropriate forum to get help, Reddit may be best

**Comment by jakeday** [comment]
This is not an issue with the wifi driver but rather with the underlying marvell firmware. I would recommend staying up to date on the firmware until they get around to fixing it.
