### ISSUE TITLE
[SB2] 4.16.x not loading properly

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#176]
I'm having this issue 90% of the time with kernel versions 4.16.x. 4.15.16 was my last working version with 100% success rate. Upon selecting the kernel, I get the Ubuntu loading screen with the five progress dots below it, there's the audio hiss sound.. and the screen goes to black. Keyboard lights up, and I have to hard reset. Occasionally, I'll get to the login page, type in my credentials, and have it go to black. Other times, I'll boot in fine, and then it'll go to black the moment I open up something.

I tried removing all previous kernel versions, /lib/firmware/intel/ipts, /lib/firmware/i915, /lib/firmware/nvidia/gp108, and /lib/firmware/mrvl before running the ``sudo setup.sh`` and ``sudo dpkg -i`` commands. I'm guessing it's probably a display firmware issue somewhere, but can't figure out what. Been happening on Ubuntu 17.10 and now 18.04, both Wayland and xorg.

**Comment by calidor** [comment]
run dmesg, its intel_power_well_enable error, exact same symptoms as on my sb2:-)

**Comment by versipellis** [comment]
Thanks @calidor, I'll take a look later tonight. I don't seem to recall seeing intel_power_well_enable, but maybe now that I know what to look for I might spot it :)

**Comment by calidor** [comment]
oh and thanks for hint, ill try 4.15.16..

**Comment by versipellis** [comment]
So, I get the same output as in your dmesg in #173, even for 4.15.16. It loads fine, however. I get the same for 4.16.7 when it loads properly. and when it doesn't load properly.

**Comment by calidor** [comment]
yeah, i had to stop using it becouse after boot windows shows thermometer on boot. sb2 is not hot.. and well my guess error hes something to do with power management .. and for me its dangerous, i dont want to brick this expensive machine:)

**Comment by versipellis** [comment]
@npjohnson SB2. Sorry, forgot to mention.

**Comment by calidor** [comment]
mine is sb2 15inch version

**Comment by jakeday** [comment]
This is fixed in the 4.17.x series, which will upload here shortly.

**Comment by versipellis** [comment]
Ah, got it, my apologies!
