### ISSUE TITLE
Signed kernel module support

### ISSUE THREAD

**Issue by photodude** [jakeday/linux-surface#178]
I've been told that the Linux-surface kernel is not signed, Is that true?
If the Linux-surface kernel is not signed, would it be possible to have the kernel signed going forward?

- https://wiki.gentoo.org/wiki/Signed_kernel_module_support

**Comment by vonAlenberg** [comment]
Yes it's true. I used this guide https://blog.ubuntu.com/2017/08/11/how-to-sign-things-for-secure-boot and it works.
The only issue is that I cannot get the `bbswitch.ko` module to work with dkms, even though I sign it.
But kernel works well.

**Comment by photodude** [comment]
@vonAlenberg I'm not sure if self-signing is acceptable under secure boot requirements related to GDPR

**Comment by photodude** [comment]
@vonAlenberg it looks like self-signing is almost as bad as disabling Secure Boot. The signing of the custom kernel really needs to be at the developer/project level and not at a user level to be in proper compliance.

**Comment by jakeday** [comment]
The kernel will not be signed as this could lead to issues.

**Comment by photodude** [comment]
I'm sorry to hear that. What can of issues could signing the kernel lead to?
