### ISSUE TITLE
Cannot detach screen from keyboard (with dedicated NVIDIA graphics) on original Surface Book

### ISSUE THREAD

**Issue by Nicky1Finn** [jakeday/linux-surface#179]

**Comment by kitakar5525** [comment]
I have the same issue too (SB1).
I think the issue occurred after Windows 1803 update.

The workaround is detach the screen before powering off Windows
and reattach the screen when device is powered off.

**Comment by Nicky1Finn** [comment]
Thank you for the workaround; it works for me, too.

**Comment by SeanDonnellanWDI** [comment]
Hey folks, I've got this exact same issue but I do not want to rely on the Windows workaround every time I want to undock my screen because I do it often. Any solutions/patches yet?

**Comment by Nicky1Finn** [comment]
I agree. Also, this workaround seems to prevent undocking in Windows if it was hibernated instead of shut down. I trust a patch will surface in time, but I'm extremely grateful to have everything else working!

**Comment by kitakar5525** [comment]
This seems to be fixed by latest Windows Update. (fixed by KB4100403 or latest Feature Update)

**Comment by Nicky1Finn** [comment]
I'm on the latest feature update (after KB100403) and the issue is still present on my setup; when I boot into Ubuntu 18.04 and attempt to detach the screen, I get a solid red light on the detach button. Unless, of course, I detach the screen before suspending Windows.

**Comment by jakeday** [comment]
This is not an issue with the kernel. If you are using Windows and you are leveraging the automated switch from intel and nvidia GPUs, the current versions of Windows will put a lock on it. If you don't FULLY shut down Windows, the lock will persist into booting Linux. We can clear this in Linux, but it's a better idea to properly handle the issue on the Windows side.
