### ISSUE TITLE
Surface Book 2: Hard disk sometimes unresponsive

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#182]
Hi,

When my SB2 has been idle for a while, I ususally experience strange errors in the userspace : some files become unavailable, especially those on the system partition (btrfs).

As an example, when trying to launch a process with `popen`, it repeatdly answeers "no such file" during a few seconds. Then, it works.

I suspect some settings with the SB2 hard disk (nvme) or with the btrfs file system : it is as if the hard disk was set to hibernate after a certain time of inactivity and it takes a few seconds to resume

Did you experience such a behavior ?

Regards

**Comment by jakeday** [comment]
@deb75 Can you please confirm that you do not have tlp installed?

**Comment by deb75** [comment]
Hi,

`tlp` is not installed.

It currently only happens within my window manager (awesome). It sometimes fails to open files, but it succeeds after several attempts. It seems as if the wm was entering some kind of sleep state after being idle for a while.

Anyway, I do not think it is related specifically to the SB2 or the kernel. So let's close this issue.

Regards

**Comment by aleksfadini** [comment]
> Hi,
> 
> `tlp` is not installed.
> 
> It currently only happens within my window manager (awesome). It sometimes fails to open files, but it succeeds after several attempts. It seems as if the wm was entering some kind of sleep state after being idle for a while.
> 
> Anyway, I do not think it is related specifically to the SB2 or the kernel. So let's close this issue.
> 
> Regards

Again, having exactly same problems on a Surface Pro 6 i7 on arch linux, with i3wm. Was it your window manager? Did you solve this?
