### ISSUE TITLE
Surface Book: Automatic wake-up from hibernate

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#183]
Surface book, Debian Stretch, kernel 4.16.7.
Sometimes, when I hibernate the surface it wakes up on its own. journalctl attached.
[journal.txt](https://github.com/jakeday/linux-surface/files/2024004/journal.txt)

**Comment by tmarkov** [comment]
Some additional notes: It doesn't always happen immediately after hibernation. I started waiting a bit to make sure hibernation sticks, and even so I sometimes find the SB on next time I open it. Automatic wake up also happens if I try s2idle instead of hibernate.

**Comment by kitakar5525** [comment]
I use SB1 too. It will not wake up automatically anymore from s2idle with this command. Did you try this?

```bash
# echo XHC > /proc/acpi/wakeup
```
(but not tested on hibernate) 

This also disables resuming from keyboard input. Though, I can still wake it up with power button or lid open.

**Comment by tmarkov** [comment]
Yes, it looks like wakeup on USB was somehow the culprit. At least in these last two weeks I haven't had problems when I disabled XHC.

**Comment by endeavour** [comment]
I had this issue too with Suspend rather than Hibernate (Manjaro Linux with kernel 5.15.1).

To make the fix permanent (i.e. survive restarts) see here:
https://askubuntu.com/questions/152403/how-do-i-make-changes-to-proc-acpi-wakeup-permanent
