### ISSUE TITLE
Black Screen after Login

### ISSUE THREAD

**Issue by AndreasHecker** [jakeday/linux-surface#184]
After doing the recommended setup.sh on linux 17.10 kubuntu i can get the login screen to enter my password. After logging in there is only a black screen. What can  i do to get back into KDE after logging in?
Thanks fpr any help!
Andreas

**Comment by vonAlenberg** [comment]
Does it always happen for you?
For me it's just the first boot, a simple reboot fixes it for the rest of the day. I use GNOME though...

**Comment by AndreasHecker** [comment]
It happens every time i try to boot the modified kernel. When i boot an unmodified kubuntu kernel kde ist started and i can start using the notebook. After booting into the modified kernel the logon screen is visible an i can authenticate. After authentication, when kde plasma should launch, the screen keeps black. I have to reboot by pressing the surface power button for about 30 seconds.
Cheers,
Andreas

**Comment by jakeday** [comment]
@AndreasHecker This is fixed in the new 4.17.x series kernels that I'll be uploading here shortly.
