### ISSUE TITLE
Surface Pro 4: Small jumps of Pen input when starting line

### ISSUE THREAD

**Issue by fridgecow** [jakeday/linux-surface#185]
This happens across applications, and particularly happens when drawing quickly (as one might be when handwriting...)

The following lines were drawn in quick succession from right to left on Ubuntu 17.10 with Gnome 3 on X, linux-surface 4.15, and I just compiled the latest libinput and wacom input packages to try and sort this.

![image](https://user-images.githubusercontent.com/7999344/40443503-6f6531c0-5ebe-11e8-9e56-5b574ad87ec5.png)

**Comment by jakeday** [comment]
@fridgecow Which devices?

**Comment by fridgecow** [comment]
Ah, sorry - The Surface Pro 4 (with the same generation surface pen)

**Comment by jakeday** [comment]
This looks like one of the current issues with libwacom. We'll have to fill out a bug report there.
