### ISSUE TITLE
[SB2] Speakers hiss when headphones plugged in

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#187]
Kernels 4.15.x and 4.16.x both cause the speakers to start hissing when headphones are plugged into the jack. This notably was absent behavior in 4.14.x and when headphones are connected through the Surface Dock.

**Comment by remingtonlang** [comment]
Hey @versipellis. My SP2 did the same thing. Its not Jakea portion of the kernel, its either the sound module or newer software. At any rate it can be fixed via software by doing:

`amixer -c 0 sset 'Auto-Mute Mode' Disabled && sudo alsactl store`

**Comment by versipellis** [comment]
Well *that* was easy. Thank you @remingtonlang!
