### ISSUE TITLE
Getting perf working with custom kernel?

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#188]
The generic `perf` utility won't work on this kernel since it's patched.

~~You can still find the `perf` source code in the folder `/usr/src/linux-headers-4.15.12-surface-linux-surface/tools/perf`, or whatever version you have. But, typing `make` in that directory yields the following error:~~

```
  BUILD:   Doing 'make -j4' parallel build
Makefile.perf:6: ../scripts/utilities.mak: No such file or directory
make[1]: *** No rule to make target '../scripts/utilities.mak'.  Stop.
make: *** [all] Error 2
Makefile:69: recipe for target 'all' failed
```

Has anyone figured out how to get `perf` to work? In comparison, the tigerite kernel seems to have these tools working: https://launchpad.net/~tigerite/+archive/ubuntu/kernel

**Comment by battaglia01** [comment]
Note that the above was the wrong directory - to get perf working requires you to compile it yourself from linux-stable, not from the headers folder.

Doing this brings its own challenges re patching, but ultimately this should be doable.

**Comment by jakeday** [comment]
You'll need to compile from source yourself to get these tools.
