### ISSUE TITLE
[SB2 15"] Kernel install failure.

### ISSUE THREAD

**Issue by didibaba** [jakeday/linux-surface#190]
What is the problem below?

> (Reading database ... 325365 files and directories currently installed.)
> Preparing to unpack linux-headers-4.14.39-surface-linux-surface_4.14.39-surface-linux-surface-59_amd64.deb ...
> Unpacking linux-headers-4.14.39-surface-linux-surface (4.14.39-surface-linux-surface-59) over (4.14.39-surface-linux-surface-59) ...
> Preparing to unpack linux-image-4.14.39-surface-linux-surface_4.14.39-surface-linux-surface-59_amd64.deb ...
> Unpacking linux-image-4.14.39-surface-linux-surface (4.14.39-surface-linux-surface-59) ...
> dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
> dpkg-deb: error: subprocess <decompress> returned error exit status 2
> dpkg: error processing archive linux-image-4.14.39-surface-linux-surface_4.14.39-surface-linux-surface-59_amd64.deb (--install):
>  cannot copy extracted data for './lib/modules/4.14.39-surface-linux-surface/kernel/drivers/net/hamradio/baycom_ser_hdx.ko' to '/lib/modules/4.14.39-surface-linux-surface/kernel/drivers/net/hamradio/baycom_ser_hdx.ko.dpkg-new': unexpected end of file or stream
> Preparing to unpack linux-libc-dev_4.14.39-surface-linux-surface-59_amd64.deb ...
> Unpacking linux-libc-dev (4.14.39-surface-linux-surface-59) over (4.14.39-surface-linux-surface-59) ...
> Setting up linux-headers-4.14.39-surface-linux-surface (4.14.39-surface-linux-surface-59) ...
> Setting up linux-libc-dev (4.14.39-surface-linux-surface-59) ...
> Errors were encountered while processing:
>  linux-image-4.14.39-surface-linux-surface_4.14.39-surface-linux-surface-59_amd64.deb

**Comment by remingtonlang** [comment]
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess returned error exit status 2

Sounds like part of your problem is a corrupt/partial download

**Comment by didibaba** [comment]
@remingtonlang Thx! That's it!
