### ISSUE TITLE
[SP3 I7]SP3 with ubuntu 16.04 and 18.04 Linux has been wrong and it prompt i8042 

### ISSUE THREAD

**Issue by copyszj** [jakeday/linux-surface#192]
it raise that i8042: Can't read CTR while initializing i8042 and that the booting is stop.
Actually,It also prompts me to update the microcode,and It disappeared after updated
I am learning linux and I hope to get help

**Comment by jakeday** [comment]
I have no idea what you're trying to ask. Can you please clarify?

**Comment by copyszj** [comment]
sorry.
I8042 error message during Linux start up
 "i8042: Can't read CTR while initializing i8042"

**Comment by solomonik** [comment]
I ran into the same error after installing the kernel on SP3 and it seems to be the same as #167. Adding `enable_guc=0` to `GRUB_CMDLINE_LINUX` in `/etc/grub/default` (via safe boot, edit grub loader, root prompt) fixed it for me. Posting this here since the issue #167 was harder to find from the error message.

**Comment by Erudition** [comment]
> I ran into the same error after installing the kernel on SP3 and it seems to be the same as #167. Adding `enable_guc=0` to `GRUB_CMDLINE_LINUX` in `/etc/grub/default` then running 'update-grub' (via safe boot, edit grub loader, root prompt) fixed it for me. Posting this here since the issue #167 was harder to find from the error message.

Oops, that should be `/etc/default/grub`.

**Comment by Erudition** [comment]
> I ran into the same error after installing the kernel on SP3 and it seems to be the same as #167. Adding `enable_guc=0` to `GRUB_CMDLINE_LINUX` in `/etc/grub/default` then running 'update-grub' (via safe boot, edit grub loader, root prompt) fixed it for me. Posting this here since the issue #167 was harder to find from the error message.

Oops, that should be `/etc/default/grub`.
