### ISSUE TITLE
Battery status isn't showing

### ISSUE THREAD

**Issue by Catley94** [jakeday/linux-surface#193]
Hi Jake,

Really appreciate your work, if you need a hand (complete newbie here with linux but fluent in IT) let me know.

Just wondered if there's any update on the battery status, I'm happy with everything but cannot live without knowing how much battery is left. 

Thanks,

Sam

**Comment by Catley94** [comment]
Also, model: Surface book 2 13inch i5, intel GPU.  If there is a beta kernel that you wish for me to test for you, or anything that you wish me to test with regards to new kernels or battery status, let me know also.

Thanks.

**Comment by jakeday** [comment]
@Catley94 This is a duplice on #28. I'm back on working on it!
