### ISSUE TITLE
Pulseaudio change completely breaks audio due to double module-udev-detect load

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#196]
To @jakeday regarding latest commit: the new default.pa file is malformed and will result in module-udev-detect being loaded twice, which will cause Pulseaudio to fail to load. The problem is because of these two lines added in the default.pa file at the end:

```
# Use interrupt driven scheduling instead of timer based
load-module module-udev-detect tsched=0
```

Upon running pulseaudio, we get the following error:

```
E: [pulseaudio] module.c: Module "module-udev-detect" should be loaded once at most. Refusing to load.
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.
```

The problem is that you already try to load module-udev-detect earlier in the file in lines 50-56:

```
### Automatically load driver modules depending on the hardware available
.ifexists module-udev-detect.so
load-module module-udev-detect
.else
### Use the static hardware detection module (for systems that lack udev support)
load-module module-detect
.endif
```

To get the behavior you want, you should change the way module-udev-detect is loaded here, not add a second call to load it at the end of the file. Remove the two lines you added and add the tsched=0 call to line 52, producing this

```
### Automatically load driver modules depending on the hardware available
.ifexists module-udev-detect.so
load-module module-udev-detect tsched=0
.else
### Use the static hardware detection module (for systems that lack udev support)
load-module module-detect
.endif
```

and now things work as intended. This is the standard approach recommended by the Ubuntu wiki: https://wiki.ubuntu.com/PulseAudio/performance

**Comment by jakeday** [comment]
@battaglia01 Good catch, I commited part of my test file. Fixed.

**Comment by simonzanetti** [comment]
Excelent post!!!
