### ISSUE TITLE
config.patch too specific to work on (probably most) distributions - should bundle same .config used on binaries

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#197]
The config.patch file seems to have been generated using diff -u, as are most patch files. The problem is that the instructions say to do the following:

```
cat /boot/config-$(uname -r) > .config
patch -p1 < ~/linux-surface/patches/config.patch
```

The first command (a strange way to write cp) basically takes the current config file from the kernel you currently have running, and copies it to linux-stable/.config. But if this config file isn't the same as the one that @jakeday used when creating the patch, it's not guaranteed to work. I found that it didn't work when trying to copy the 4.13 config file that came stock with KDE Neon (based on Ubuntu Trusty) - the patch files didn't line up and certain hunks within the patch failed.

One problem is that by default it gives three lines of "context" before and after the patch. For example, look at the following code snippet:

```
--- a/.config	2018-04-30 19:19:53.667563564 -0400
+++ b/.config	2018-04-30 19:22:03.105721430 -0400
@@ -52,7 +52,7 @@
 CONFIG_INIT_ENV_ARG_LIMIT=32
 CONFIG_CROSS_COMPILE=""
 # CONFIG_COMPILE_TEST is not set
-CONFIG_LOCALVERSION=""
+CONFIG_LOCALVERSION="-surface"
 # CONFIG_LOCALVERSION_AUTO is not set
 CONFIG_HAVE_KERNEL_GZIP=y
 CONFIG_HAVE_KERNEL_BZIP2=y
```

This is counterproductive because a different distro might have CONFIG_LOCALVERSION somewhere in the file, without those specific three lines preceding or succeeding it, so this patch will fail for no reason. We could fix this by creating the patch with diff -u0, which would eliminate the context. But, you can still see the hunk here is specified from lines 52-58, so if, for instance, some distro has an extra line anywhere in the file, the rest of the hunks are screwed.

I'm not really sure what the solution is, as this is basically unusable. We don't really want to "patch" this file in the usual sense, we just want to make sure certain lines are either present or not present in the file. Perhaps a different patch tool would work? Of course, worst case scenario you could just write a script to go line by line.

**Comment by battaglia01** [comment]
Thinking about this more, the best solution here would be to just include the .config file that you're using for your build. Avoids all this mess, and has the bonus feature of making it way easier to match the .config file you're using for the binaries that most people probably use, which should help cut down on bad bug reports.

Would you be able to bundle the stock .config file?

**Comment by jakeday** [comment]
@battaglia01 That's the problem. The general consensus was to include a patch when I use to include the config file. But with the various versions and differences per distro, it's hard to have a patch that applies. I think the general idea is not to actually apply the config as a patch, but use it as a reference to edit your own config.

**Comment by hadrienk** [comment]
Isn't the patch here to make sure the options that are required are enabled?
I think a better way could be to use sed the same way it is used in arch or gentoo metapackages: 
```bash
  ### Optionally disable NUMA
  if [ -n "$_NUMAdisable" ]; then
    msg "Disabling NUMA from kernel config..."
    sed -i -e 's/CONFIG_NUMA=y/# CONFIG_NUMA is not set/' \
      -i -e '/CONFIG_AMD_NUMA=y/d' \
      -i -e '/CONFIG_X86_64_ACPI_NUMA=y/d' \
      -i -e '/CONFIG_NODES_SPAN_OTHER_NODES=y/d' \
      -i -e '/# CONFIG_NUMA_EMU is not set/d' \
      -i -e '/CONFIG_NODES_SHIFT=6/d' \
      -i -e '/CONFIG_NEED_MULTIPLE_NODES=y/d' \
      -i -e '/# CONFIG_MOVABLE_NODE is not set/d' \
      -i -e '/CONFIG_USE_PERCPU_NUMA_NODE_ID=y/d' \
      -i -e '/CONFIG_ACPI_NUMA=y/d' ./.config
  fi
```

**Comment by battaglia01** [comment]
@jakeday I see what you're saying. If that's the way to go, I think it'd still be better to use a patch tool more suited for all this, such as the one hadrienk mentions above. I'm not sure exactly how to use sed for this. There's also the makeconfig tool bundled in the kernel, which has defaults specified, but these files can be pretty long to go through manually...

Even if you include a patch, it would still be helpful to somewhere have the .config that you used to compile the binaries, for reference. This is because it's the de facto "standard" .config that everyone else is using when they file these bug reports, so if I'm compiling my own kernel, ideally I'd like only one or two things to be different from those (like adding debug symbols, for instance).

**Comment by battaglia01** [comment]
@jakeday to add, is there any reason that debug symbols are explicitly disabled in the patch? If I re-enable those will they cause problems?
