### ISSUE TITLE
Ubuntu 18.04 resume from hibernation breaks touchscreen, pen, wifi...

### ISSUE THREAD

**Issue by ohthehugemanatee** [jakeday/linux-surface#199]
Thank you for all your work, Jakeday! I'm amazed by how well the kernel works on my Surface Pro 2017.

Fresh install of 18.04 and this kernel using setup.sh . Accepted teh option there to use hibernate instead of connected suspend.  Everything seems great until I close the lid to hibernate, and open again. At that point the pen and touch screen are no longer detected, and the wifi card has disappeared, too. I don't see much in dmesg, though it seems to have some trouble with swap. I don't have a swap partition, so maybe it needs me to manually create a swap file... I'll look into that and report back. 

Any ideas what I can do in terms of helpful diagnostics?

**Comment by jakeday** [comment]
@ohthehugemanatee I would recommend using suspend instead of hibernate. Also, I'll be uploading the 4.17.x series kernels here shortly.

**Comment by ohthehugemanatee** [comment]
Thanks for the fast response @jakeday - the advice I see on reddit etc is to use hibernate instead of suspend, because of "connected suspend". So why is this different?

For the record: in order to use suspend instead of hibernate, I did
```
sudo ln -sf /lib/systemd/system/hibernate.target /etc/systemd/system/suspend.target
sudo ln -sf /lib/systemd/system/systemd-hibernate.service /etc/systemd/system/systemd-suspend.service
```

On the first try it seemed to get stuck in suspend mode (ie didn't detect the lid, power button, or keypress events to wake up). I didn't get a chance to test it properly, though.

**Comment by htrampe** [comment]
Hi,
i've got the same error on my pro 2017. After suspend wlan, touchscreen etc. breaks...

**Comment by thekswenson** [comment]
@jakeday :  you say "I would recommend using suspend instead of hibernate".  I thought suspend didn't work with surface devices?

https://github.com/jakeday/linux-surface/issues/157

Did something change?

**Comment by bhatiaabhinav** [comment]
Hi,
i am able to get my SB (ubuntu 18.04) to wake from suspend (by closing and opening the lid). But the touchscreen etc. does not work after that. It is as if whatever functionality this kernel added, is gone after wake.
