### ISSUE TITLE
Wifi drivers no longer working

### ISSUE THREAD

**Issue by danielfrankcom** [jakeday/linux-surface#20]
Hi, thanks so much for putting together this kernel! I installed it just now and everything was great, but after rebooting my wifi no longer works. It offers me a list of networks to connect to, but then it says "network is no longer connected" and gives up attempting to connect. In addition, when I click on a new network and it prompts me for a password, my type cover (surface pro 4) stops working (mouse and keyboard) until I reboot.

Any help would be greatly appreciated!
Thanks

**Comment by danielfrankcom** [comment]
Update: 

If I switch kernels back to the default, the wifi and the keyboard work flawlessly, but not the other features of the custom kernel such as the track-pad and the touchscreen.

**Comment by jakeday** [comment]
If you're using the 4.14 kernel, make sure you apply the apparmor patch otherwise networking won't work.
