### ISSUE TITLE
dmesg for 4.17

### ISSUE THREAD

**Issue by thmichel** [jakeday/linux-surface#200]
Hi Jske,

not an issue but you wanted to have a dmesg of a running 4.17 kernel. Find it attached.
Everything is working so far except the usual battery stuff. Model  is Surface Book 2017.

[dmesg.txt](https://github.com/jakeday/linux-surface/files/2092944/dmesg.txt)

**Comment by jakeday** [comment]
@thmichel Which device exactly are you using?

**Comment by thmichel** [comment]
Hi,

sorry, wasn't precise enough: It's a Surface Book 2 13".

**Comment by brendandburns** [comment]
Attaching my dmesg for a first-generation Surface Book 13"
[dmesg.txt](https://github.com/jakeday/linux-surface/files/2099158/dmesg.txt)

**Comment by PicoLegion** [comment]
Surface Pro 2017
[dmesg.txt](https://github.com/jakeday/linux-surface/files/2099409/dmesg.txt)

**Comment by AZdet** [comment]
Surface Book 2 15"
[dmesg.txt](https://github.com/jakeday/linux-surface/files/2108291/dmesg.txt)

**Comment by jakeday** [comment]
Can you get me the output of this? I want to ensure I understand what all is being used:

ls -1L /sys/bus/acpi/devices/* && ls -1L /sys/bus/i2c/devices/* && ls -1L /sys/bus/platform/devices/*

**Comment by thmichel** [comment]
[output.txt](https://github.com/jakeday/linux-surface/files/2131056/output.txt)

Hi Jake,

attached the output for as SB 2 13".

**Comment by brendandburns** [comment]
Here's mine for first generation SB 13"
[info.txt](https://github.com/jakeday/linux-surface/files/2143576/info.txt)

**Comment by jakeday** [comment]
I've gotten what I needed, thanks!
