### ISSUE TITLE
Surface Pro3  pm-suspend cannt be waken up

### ISSUE THREAD

**Issue by Gunkkk** [jakeday/linux-surface#201]
Touch my power button it goes into the suspend mode and will be automaticly waken up immediately.
I install the pm-utils and it can be in suspend while i can not call it back even start laptop_mode.
How can i solve it?
Thanks!

**Comment by jakeday** [comment]
@Gunkkk I'm really struggling to understand what your issue is. Can you please elaborate?

**Comment by Gunkkk** [comment]
@jakeday 
Sorry for  my poor English!
With the pm-utils, my surface can be suspended.However,i can't call it back(keep black).

**Comment by jakeday** [comment]
@Gunkkk Gotcha, then this is a duplicate of #166. Can you post a dmesg log there?
