### ISSUE TITLE
CUDA does not work on Surface Book 2 15"

### ISSUE THREAD

**Issue by AZdet** [jakeday/linux-surface#202]
Hi. Recently I have found that CUDA does not work on this kernel(4.17.1, 4.16.7, 4.14.39), while it works on the original Ubuntu 16.04. Although NVCC appears to work, when I try to run the device query sample code of CUDA, it tells me the driver version is not sufficient( although actually it is).  Nvidia-smi does not work by default, but after changing Nvidia X server setting to use GPU first, it works, but device query sample still fails.
Here is my dmesg result.
[dmesg.txt](https://github.com/jakeday/linux-surface/files/2108347/dmesg.txt)

**Comment by buoyancy99** [comment]
Nvidia cuda will have problems when you update the kernel. Try using the original kernel or reinstall it. If you use cuda a lot, customized kernel is not a good idea.

**Comment by AZdet** [comment]
Well it seems to be a driver problem.After reinstalling for many times, I finally settled for Nvidia 384 driver. For now, everything seems to work.
