### ISSUE TITLE
Touch input still crashing on 4.16.7 and 4.17.1-1 Debian Buster

### ISSUE THREAD

**Issue by ardynn** [jakeday/linux-surface#203]
I upgraded to the new kernel using the instructions on the main page. It seems to be stable a bit longer, but after about twenty minutes or so touch crashes.

I'm on Debian Buster. Surface Book with performance base.

**Comment by Wesley-VanNeck** [comment]
same on surface pro 4 on ubuntu 16.04.4

**Comment by Wesley-VanNeck** [comment]
it seems more stabble but it crases if there is a work around for it  plz let me hear it

**Comment by ardynn** [comment]
Since I made this, I've realized it seems to happen a lot more in landscape mode. In fact, in some cases after a minute or two.

**Comment by Wesley-VanNeck** [comment]
I noticed it to

**Comment by electrikjesus** [comment]
This behavior is also still present on Android as well with Kernel-4.16.8 & 4.16.14 (Surface Book)

**Comment by Wesley-VanNeck** [comment]
It seems to be working fine on ubuntu 17.10.1

**Comment by jakeday** [comment]
This is due to kernels 4.16+ and how they handle different contexts for guc clients. I'll have to re-work that part of the driver. You'll run into it when having too high of activity.

**Comment by jakeday** [comment]
Closing this as it's a duplicate of #171
