### ISSUE TITLE
Suggestion: Make the SB detach button unmount USB storage or SD card

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#204]
Since the SD card reader and USB port of the Surface Book are on the keyboard, it makes perfect sense to automatically unmount them when pressing the detach key.

I haven't been able to detect it to bind an unmount event to it, but can that be done in some way?

**Comment by jakeday** [comment]
@tmarkov Look at the udev rules I have defined in the root folder. You can add your logic in a similar fashion.

**Comment by tmarkov** [comment]
I don't think that will work. Sure, I can make a udev rule to unmount things when the keyboard is removed. The problem is, they need to be unmounted before the keyboard is removed. After all, when the keyboard is removed, any USB drives / SD cards are already disconnected.

The best thing I can think of, is to have them unmounted when the detach button is pressed. However, no event happens when it's pressed, so I can't set up anything to trigger then.

**Comment by tmarkov** [comment]
@jakeday I don't think that will work. Sure, I can make a udev rule to unmount things when the keyboard is removed. The problem is, they need to be unmounted before the keyboard is removed. After all, when the keyboard is removed, any USB drives / SD cards are already disconnected.

The best thing I can think of, is to have them unmounted when the detach button is pressed. However, no event happens when it's pressed, so I can't set up anything to trigger then.

**Comment by qzed** [comment]
While this won't work for the original SB, for the SB2 I've now implemented support for this via the surface-acpi module and a user-space daemon. For now this requires the module version, but the patches will be updated soon.

**Comment by qzed** [comment]
Let's track this in #286, as this also seems to rely on the `SAM` chip.
