### ISSUE TITLE
Does This Work With Linux Mint On A Surface Book 2?

### ISSUE THREAD

**Issue by hemlokc** [jakeday/linux-surface#205]
Hoping this fixes some of the quirks I'm dealing with...power button doesn't shut the screen off, weird audio crackles when I boot up initially.

**Comment by hemlokc** [comment]
All went well! But my power button still isn't working to shut off my screen. Is it because I chose to defer the option to replace 'suspend' with 'hibernate'? Since 'suspend' is still not working?

**Comment by ptimatth** [comment]
No the power button still not working same with "tablet" volume button and lid openning: closing captor. @jakeday work!

**Comment by jakeday** [comment]
This seems more like a topic for /r/SurfaceLinux.
