### ISSUE TITLE
Surface Laptop 1769+Linux Mint 18.3, not booting after installing latest kernel/restarting

### ISSUE THREAD

**Issue by thefoodleagues** [jakeday/linux-surface#206]
Following the 'pre-build kernel and headers' instructions, my surface laptop just refuses to boot back up again after the kernel is installed and the machine is restarted.

I get the bios screen, then some text at the top-left corner (which is too small and quick to read), followed by a blank screen. I do NOT get the Linux boot animation (which I did get prior to installing this).

I've tried with and without installing the Intel Microcode drivers. Same behavior for both.

Any ideas?

**Comment by Scontoni** [comment]
I'm having the same issue on Ubuntu 18.04 on Surface 3

**Comment by jakeday** [comment]
@thefoodleagues How long are you letting it wait? Sometimes it will seemingly hang for a few minutes and will boot.

@Scontoni You're sounds more like an issue on the newer kernels for older SP2 and SP3. You can use my updated kernel, 4.17.3-1, and add the boot param i915.enable_ipts=false and you should be good.

**Comment by thefoodleagues** [comment]
@jakeday I left it for a good 10 minutes on one of the tests. I see LM-19 has just been released. I'll try with that and see if the behaviour is any different.

**Comment by jakeday** [comment]
@thefoodleagues I would also try it with Ubuntu. I don't test with Linux Mint or use it, so there may be something weird going on there. Feel free to re-open this once you've done those two things!
