### ISSUE TITLE
Surface Pro 4: Audio fallbacks to dummy on reboot after hibernation

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [jakeday/linux-surface#207]
I guess the title explains the thing, since it's quite simple.
If I let my Surface Pro 4 (running on your 17.1 kernel) suspend after a period and hibernate the session, on reboot I'll find that the audio reproduction stopped working, and the device actually in use is barely a Dummy Output, which doesn't reproduce sound obviously.

**Comment by jakeday** [comment]
@MuAlphaOmegaEpsilon Can you get me a dmesg log?

**Comment by jakeday** [comment]
Should be working in 4.18.7 now.
