### ISSUE TITLE
Error in apparmor

### ISSUE THREAD

**Issue by PrinceRAndrew** [jakeday/linux-surface#21]
Hey jakeday! Thank you for what you do! you are our hero.

You missed an "l" on line 36 of the apparmor patch in the word "dhclinet."

Also could you be so kind as to give a few instructions on how to change a surfacebook to multitouch mode. People on reddit seem to be confused too and trying to echo 1 into the ipts mode kinda crashes everything.

**Comment by jakeday** [comment]
Fixed. Thank you!
