### ISSUE TITLE
SP4 18.04 LTS Problems

### ISSUE THREAD

**Issue by Sartharon** [jakeday/linux-surface#210]
Today I've installed ubuntu 18.04 LTS, after fiddling around somewhat I can't seem to resolve these:

-Touchscreen not working at all
-Pen not working at all
-Closing the lid and opening it turns off the typecover with no way of reviving it again (removing and reconnecting it doesn't help). Still the screen stayed on (I used your replace sleep with hibernate)

I used Kernel 14.16.7

**Comment by oleid** [comment]
Strange, I'm using ArchLinux on SP4 and Touchscreen and Pen are definitively working. The software should be similarly recent. 

Do you see events for Touchscreen and Pen using `sudo libinput debug-events`?

**Comment by Sartharon** [comment]
No events when touching the screen or using the pen

**Comment by oleid** [comment]
That would suggest, that something went wrong during the execution of `setup.sh` in this repo. I didn't use the script, as it doesn't work on Arch. Instead, I did the stuff manually. I guess the script might need a tweak or two to work on 18.04.

Do you get any error messages when running the script? My first guess would be, that the ipts firmware didn't get installed or that some udev rule isn't working.

**Comment by Sartharon** [comment]
Well i didn't get any errors that's why i assumed everyrhing installed properly

**Comment by oleid** [comment]
Fair enough. Would you dump the output of `journalctl -b` right after a fresh boot to a file and upload here? Then I can check, if I see something suspicious.

**Comment by Sartharon** [comment]
Well i think i might found the culprit .... my bootloader. rEFInd needed some reconfiguration as he failed to boot the surfacelinux kernel and switched back to 4.16.7 without the patches.
Didn't thought of journalctl thanks for the help.

**Comment by oleid** [comment]
Ah, that explains! I'm glad you found the prob!
