### ISSUE TITLE
Volume Buttons mixed up on Surface Book 2 / driver must be loaded manually

### ISSUE THREAD

**Issue by thmichel** [jakeday/linux-surface#212]
Hi,
ues
I have tested the latest kernel and found 2 small issues:

1. I have to manually unload the surfacepro3_button module and load the surfacebooke2_button module
2. The volume buttons are mixed up - the Volume Up button acts like Volume Down and vice versa.

Dev ice is a Surface Book 2 13.

But a big thank you for making it work at all!

**Comment by qzed** [comment]
The mixed up buttons are weird. I'm on the same device and for me they are correct. Although they are, in my opinion, placed inverted to what you'd expect (up on the left, down on the right, maybe check the little indicators on them, makes sense if you use it as tablet in portrait mode with the pen facing up).

I already mentioned that there might be issues with the module loading [here](https://github.com/jakeday/linux-surface/issues/34#issuecomment-401086714), and why this is the case. I'm currently using a blacklist to block the `surfacepro3_button` module and, to be honest, I have not tried the new kernel without the blacklist.

To add `surfacepro3_button` to a blacklist, just create/add the following line to `/etc/modprobe.d/blacklist.conf` (actually the filename isn't important, just the folder)
```
blacklist surfacepro3_button
```
Surface Pro 4 users might want to do the same, just with the `surfacebook2_button` module. And yes, I think this should be handled automatically when loading the drivers, but I currently have no idea how.

**Comment by thmichel** [comment]
Stupid me!

Just booted into Windows and yes, the behave the same there. Rarely use Windows so didn't notice.  So it's a weired hardware design (Javing Volume Up on the left and down on the right),

Thanks for the tip to blacklist the module.

PS: The perfect solution would be to change button behaviour based on screen rotation like some Android devices do - but that's probably asking too much :-)

**Comment by jakeday** [comment]
@qzed The DMI matching was flaky and not at all reliable. I ended up checking for the DSM method, which will never be on devices using the MSHW0040 the way the SP4 does.

**Comment by qzed** [comment]
Nice, thanks!

**Comment by qzed** [comment]
So it would probably be a good idea to add the opposite check to the opposite check to the SB2 driver to make sure it doesn't interfere with the SP4 one? I can have a go at that later.

**Comment by jakeday** [comment]
@qzed I'm pushing that change now.

**Comment by qzed** [comment]
@thmichel 

> PS: The perfect solution would be to change button behaviour based on screen rotation like some Android devices do - but that's probably asking too much :-)

I've finally come around to write a script for that (https://github.com/qzed/surfacebook2-linux-button-autoremap). It's pretty basic though.
