### ISSUE TITLE
Surface Book 2 Discrete GPU Thermal Issue While Using Integrated Graphics

### ISSUE THREAD

**Issue by Vehrlich22** [jakeday/linux-surface#213]
Device: Surface Book 2
Ubuntu: 18.04
Kernel: 4.17.3-surface-linux-surface
Video Drivers:
- i915
- nouveau

Issue:
- nouveau-pci-0200 idles at 51.0°C = 123.8°F while inactive (Will linearly increase with time, 51.0°C is just a sample)

**Comment by jakeday** [comment]
@Vehrlich22 This is covered with #194
