### ISSUE TITLE
Nvidia dGPU thermal throttle

### ISSUE THREAD

**Issue by dotvezz** [jakeday/linux-surface#216]
From the [ArchWiki page for the Surface Book 2](https://wiki.archlinux.org/index.php/Microsoft_Surface_Book_2):

> The Nvidia 1050 and 1060 cards in the Surface Book 2 Performance Base are recognized by the kernel and supported by `nvidia` and `nvidia-dkms` drivers. However, when a load is put on the Nvidia graphics hardware, it immediately and severely throttles down to around 139MHz. The reason, as reported by `nvidia-smi`, is software thermal throttling. The cause is that, apparently, the fan cannot be controlled automatically, nor through `nvidia-smi` or `nvidia-settings`, even when the nvidia xorg `Coolbits` option is set to 8.

Speculation from a [Reddit thread](https://www.reddit.com/r/SurfaceLinux/comments/8dij5v/dgpu_fan_problem_on_surface_book_2/dxnkdbj/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=SurfaceLinux), praphrased: The fan seems like it's being controlled by firmware, and perhaps the driver shouldn't *need* to worry about controlling the fan.

To lump my own speculation on top: Indeed, even when the software thermal-throttles, it's done regardless of the actual package temperature reported to the driver. It seems like it might just be due to the fan's speed being reported as zero, and that value being presented as read-only. To add to that, the base fan (which cools the dGPU) does spin up, even without the driver, when the base gets warm (like when I close the lid having forgotten to install bbswitch for turning off the dGPU).

Maybe there's some way to trick the driver into thinking the fan's always at 100% (or better just find some flag that lets it not care about the fan) and let the actual management of the fan's speed just be done by whatever firmware is already controlling it.

**Comment by jakeday** [comment]
@dotvezz This should be posted under #194 as that's the issue being tracked.
