### ISSUE TITLE
Surface Pro 2017 / Ubuntu 18.04: Wired touch action on the dock menu

### ISSUE THREAD

**Issue by zetadigital** [jakeday/linux-surface#217]
Hi,

Thank you very much for your work.

The issue I have is that touchscreen is working fine on the all the areas except the dock menu in Ubuntu 18.04. When I touch any button from the dock menu such as "Files" or "Firefox" it will click twice so that it will open two windows for clicked applications. 

Btw, I've used the setup script and installed the latest kernel.

**Comment by remingtonlang** [comment]
@zetadigital I've noticed the same behavior on my SP2017 with 18.04. I'm fairly sure it has nothing to do with the driver or the kernel but GNOME itself I just haven't had a chance to dig into it further. The Surfacelinux or Ubuntu subreddits would probably be a better and more appropriate forum in figuring this out.

**Comment by thekswenson** [comment]
I also have this problem with Ubuntu Gnome on SP4.
If anyone figures it out, please post a solution!

**Comment by zetadigital** [comment]
@thekswenson It seems the gnome default dock is not working on SP.
I've removed the gnome default dock and installed Plank.

**Comment by buoyancy99** [comment]
@remingtonlang @zetadigital 
Wired behavior shows up for mouse click as well after i installed the kernel. i.e. When i single click an app in the dock, it behaves as if i am dragging the icon.
This problem started only after i installed the patch.

Therefore I think this issue should be reconsidered.
