### ISSUE TITLE
Question : power and volume buttons working with 4.17.3

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#218]
Hello,

I have recompiled the 4.17.3 original kernel with latest patches.

Buttons are still not working for me. The `surfacebook2_button` module is loaded, but nothing happens when I press either power or volume buttons.

But it is most probably my fault as I removed many modules from the original kernel config.

Which modules need to be loaded for `surfacebook2_button` to work ?

Regards

**Comment by qzed** [comment]
In the latest release this should work automatically (I assume you are experiencing this on a Surface Book 2). You could check if the `surfacepro3_button` module has been loaded, this could cause some troubles (if it is, unload it and reload the SB2 module).

**Comment by deb75** [comment]
Hi,

Thanks for your answeer.

Yes I forgot to say this concerns the surface book 2.

I have just unloaded the `surfacepro3_button` module and reloaded the `surfacebook2_button` one.

But still nothing happens, I checked with `acpi_listen` or `xev`.

I removed some gpio modules from the kernel configuration, maybe the `surfacebook2_button` module need one of them to work properly ?

**Comment by qzed** [comment]
Yes, gpio is required. The buttons use gpio interrupts, which is why this driver is required in the first place.

**Comment by deb75** [comment]
Do you know which gpio chip MS uses ?

Otherwise, I will compile them all and see

**Comment by qzed** [comment]
I only know that HID identifier is MSHW0040, but that won't help you much. Basically the driver requires the `gpio_keys` module, not sure what else is required to make gpio work in general.

**Comment by deb75** [comment]
Got it !

I was lacking the `gpio_keys` driver.
