### ISSUE TITLE
Surface book 2 : fan loud when on power adapter

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#219]
Hi,

With latest kernel 4.17.3, compiled with latest patches (buttons working), the surface book 2 fan becomes loud when I plug the surface book 2 to its power adapter, not immediately but gradualy. Conversely, when I unplug (on battery), the fan returns to a quiet mode.

It is most probably the nvidia card fan, as when I undock the fan noise stops suddenly.

I do not remember having this trouble with 4.16.xx kernels.

I blacklisted the `nouveau` driver, nothing is currently using the nvidia card.

Is there something wrong ?

Regards

**Comment by deb75** [comment]
Hi,

It is still noticeable that the nvidia card fan begins to roar when I plug the power cable. However, it tends to slow down after a while, so it is not a too annoying issue for the moment. I wish there were a way to shutdown the nvidia card, but all my attempts (bbswitch, vgaswitcheroo, acpi_call) did not come to anything successful.

**Comment by jaythespacehound** [comment]
It's indeed because the nvidia card is running. 
I had some luck disabling it.
I'm fairly sure the ACPI call needed is: '\_SB.PCI0.RP05.PRP5._OFF'

There's a post here with more info:
https://www.reddit.com/r/SurfaceLinux/comments/8yth5p/surface_book_2_disable_discreet_nvidia_card/?st=jjod9sj3&sh=f5a10622

**Comment by deb75** [comment]
Hi,

Thanks for sharing your finding. I tried and it works as said in your reddit post. However, I could not check with full confidence that the nvidia card was indeed shut down. Using `powertop` just showed the nvidia card did no more consume power (0%).

In the logs, at boot I can see several ACPI messages :
```
[    0.107054] ACPI: Power Resource [PX01] (on)
[    0.107139] ACPI: Power Resource [PX02] (on)
[    0.107226] ACPI: Power Resource [PX03] (on)
[    0.107310] ACPI: Power Resource [PX04] (on)
[    0.107390] ACPI: Power Resource [PX05] (on)
[    0.107471] ACPI: Power Resource [PX06] (on)
[    0.107550] ACPI: Power Resource [PX07] (on)
[    0.108839] ACPI: Power Resource [USBC] (on)
[    0.109446] ACPI: Power Resource [PXP] (off)
[    0.109699] ACPI: Power Resource [PRWF] (on)
[    0.111381] ACPI: Power Resource [PRP5] (off)
[    0.113320] ACPI: Power Resource [PXP] (off)
[    0.123189] ACPI: Power Resource [CAMP] (on)
```

As you can see, `PRP5` is already said `off`. It would be interesting to find out which device corresponds to each `Power Resource`. This could help improve battery management when we will have the battery statistics.

I will make a few other tests. My guess is that, when booting on battery, the nvidia card is shut off automatically by the bios, that is why I do not hear the nvidia fan when running on the battery. But when I plug the power cable, the bios turns it on and its fan begins to run. That is where your acpi call could be helpful : keep it off when on ac adapter.

Thanks again for your help.

Regards

**Comment by jakeday** [comment]
This will be handled with #213
