### ISSUE TITLE
Surface 3: Black screen after grub menu/won't boot

### ISSUE THREAD

**Issue by Scontoni** [jakeday/linux-surface#221]
Using 14.7.3-3 I get a black screen after the grub menu. I have tried your fix mentioned in #206 "i915.enable_ipts=false" which returned an error about 'false' not being usable so I tried =0 and =1 which did nothing. After a bit of searching I tried "i915.enable_psr=0" and =1 which also did nothing. What do you reckon the problem is?

Regards,
Scontoni

**Comment by jakeday** [comment]
Can you try setting i915.enable_guc=0 as well?

**Comment by Scontoni** [comment]
@jakeday That worked perfectly, thanks

**Comment by noisemakeloud** [comment]
Did you set all parameters mentioned above to 0? Did you make any other adjustments to the boot params?

**Comment by Scontoni** [comment]
@noisemakeloud I just reinstalled Ubuntu 18.04 and Linux-Surface on my S3 yesterday and set i915.enable_guc=0 and it worked perfectly for me. That is the only thing I changed.
How are you setting the parameter?

**Comment by noisemakeloud** [comment]
I added it to end of the boot line in grub.  I used grub customizer first then checked when I rebooted to the 4.17.3 kernal.

**Comment by Scontoni** [comment]
@noisemakeloud I am using the newly released kernel 4.17.7, try that and see if it fixes it
I am running just i915.enable_guc=0 and kernel 4.17.7 it is working for me

**Comment by noisemakeloud** [comment]
4.18.7 with i915.enable_guc=0 parameter added worked for me.  Thanks!
