### ISSUE TITLE
add -b to ln to create backup in suspend->hibernate script

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#222]
As it stands, the command in setup.sh to change suspend to hibernation is

ln -sf /lib/systemd/system/hibernate.target /etc/systemd/system/suspend.target && sudo ln -sf /lib/systemd/system/systemd-hibernate.service /etc/systemd/system/systemd-suspend.service
It would be very helpful if these were both changed to -sfb. The -f flag deletes if suspend.target and systemd-suspend.service that are already there, and there is no way to get them back. Making it -sfb means the existing files get backed up to suspend.target~ and systemd-suspend.service~, respectively, and the new links still overwrite the old ones.

**Comment by jakeday** [comment]
Can you perhaps do a pull request to change this?

**Comment by battaglia01** [comment]
I did. It's here:

https://github.com/jakeday/linux-surface/pull/235

I also added -b to the cp for the root directory too. I wish this was there before, because the default pulseaudio was overwritten and I don't know what the original was. Do you know what changes you made to the two pulseaudio files?

**Comment by jakeday** [comment]
Merged. Thanks!
