### ISSUE TITLE
how to enable camera

### ISSUE THREAD

**Issue by melnaquib-optiva** [jakeday/linux-surface#225]
Hello,
You mentioned camera is partially working, but disabled for now,
how to enable this partial support?
what's the limitations?
what's the main blocker?
Thanks,

**Comment by jakeday** [comment]
@melnaquib-optiva You can't it's hard disabled now for your protection. I'd hate to mess up your Surface unless you know what you're doing!

**Comment by melnaquib-optiva** [comment]
Thanks for all the time you spent on this.
are we talking about permanent hw damage/bricking my surface/ system instability/data loss?
I consider myself a power user + learnt a little kernel programming, I have also some hw interface experience.
where should I go to read about the problem?

**Comment by sciencedude100** [comment]
> are we talking about permanent hw damage/bricking my surface/ system instability/data loss
No, I've used this kernel and everything is just peachy in Windows

> where should I go to read about the problem?
I too would be interested in this.
