### ISSUE TITLE
Surface Pro 2017: Suspension Causes Wifi + Touch functionality to Stop

### ISSUE THREAD

**Issue by Ragora** [jakeday/linux-surface#227]
Fresh Ubuntu 18.04 install on kernel version 4.17.3-3 with all answers set to yes on the setup script.

When the machine is opened after having closed the cover on it (or otherwise suspended), I can no longer use the touch capabilities (neither the pen or touching the screen directly) and the WiFi appears to quit working entirely.

Bluetooth appears to remain active in this state.

**Comment by Ragora** [comment]
On a second reproduction of this issue to get debug information, it would appear input from both the surface keyboard and a USB keyboard quit working as well while I was still able to use the surface keyboard on my first occurrence mentioned above.

**Comment by Ragora** [comment]
Did I misread something somewhere about needing this script? Simply placing an exit 0 at the top appears to allow everything to function as normal. Though I'll continue operating the device like this to see if I get any obvious incorrect behavior.

**Comment by wildapt01** [comment]
Fresh install also here, with the Ubuntu 18.04 and Jake's kernel 4.17.3-3. SB2 15" i7
Bluetooth pairing fails after sleep or closing the lid. Touch functions seem to restart fine though.

**Comment by Ragora** [comment]
@wildapt01 Loss of input doesn't happen every time. I've had to try multiple times until I lost USB support and touch randomly stopped sometime later.

**Comment by bareya** [comment]
I came here because I have random WIFI issues, not necessary after suspension. Sometimes after some time WIFI stops to work, then I have to reboot.

**Comment by battaglia01** [comment]
Same problem on SP4.

**Comment by jakeday** [comment]
Should be working right now in 4.18.7. Please re-open if you see it again, but I'm not seeing it on my devices.

**Comment by yuzvir** [comment]
pci rescan doesn't work for me. I had to add one more line to the script to remove the wifi device
```
    echo "1" > /sys/bus/pci/devices/0000\:02\:00.0/remove;
    echo "1" > /sys/bus/pci/rescan;
```
