### ISSUE TITLE
Does Pressure Sensitivity work on the screen?

### ISSUE THREAD

**Issue by thedonquixotic** [jakeday/linux-surface#228]
Hi. I'm a designer learning development. I bought a Surface Book 2 recently because it is VR capable and has a really great graphics monitor. I'm learning development and... well I'm just kind of sick and tired of jumping through so many hoops with using Windows WSL Ubuntu 18.04 Subsystem layer and stuff. A part of me kind of wants to convert to using Linux full time. 

I just downloaded and installed Kubuntu on my home desktop because I figured I'd use it as a cloud server. I'd have to keep Windows around for the occasional game and stuff but... I'm kind of tempted to try switching over and just going duel boot with my Surface Book. BUT I would HAVE to have working drivers etc for the touch screen. No lag or anything added in either. 

Is that possible? Does the touch screen sensing etc work well? I know Adobe isn't super well suited for Linux but there have been some people who have done it, so I'm pretty tempted to give it a try. (I don't have a lot of time to tinker though as I'm taking a bunch of classes right now so I don't want to start a project I can't reasonable finish). 

How doable is this?

**Comment by jakeday** [comment]
Everything you asked for is already built into my kernel. For app support, please post to the SurfaceLinux subreddit on reddit.com.

**Comment by thedonquixotic** [comment]
Thanks! I looked around and I asked someone on reddit with sb2 after posting this question and they said the gpu still gets throttled so looks like I won't be able to do the switch for now. Thanks though!

**Comment by thedonquixotic** [comment]
And keep up the good work! It's inspiring seeing all the people in open source working on cool projects like this :)
