### ISSUE TITLE
High Xorg CPU when on dock and secondary screen

### ISSUE THREAD

**Issue by atasoglou** [jakeday/linux-surface#229]
Hello,

when using the dock and a secondary screen, cpu load goes quite high. Cpu load on `Xorg`.
Doing `killall unity-control-center` restores CPU load back to normal. Dunno if this is kernel related.

- NVIDIA handles the graphics (396.24.10).
- Kernel: 4.17.3-surface-linux-surface
- Ubuntu 16.04

**Comment by jakeday** [comment]
I'm not seeing this. Can you get me some logs?
