### ISSUE TITLE
Surface Book, Performance base with Surface Dock, no Monitor detected

### ISSUE THREAD

**Issue by valeryan** [jakeday/linux-surface#23]
I installed your kernel and it is functioning well but I am still not able to get Linux to see the monitor I have connected to my surface dock. All the other things connected to the dock works just fine.  I see that in your know issues that the dedicated GPU in the performance base is not functioning. Do you know if this is why the system does not see monitors connected to the dock? Do you happen to know if there is any work around to get the monitor to work through the Intel GPU?

**Comment by jakeday** [comment]
It's not related to the dedicated GPU. The monitor only works if everything is plugged in and connected prior to powering on the Surface Book.

**Comment by valeryan** [comment]
Hmm, I connect the dock before powering on but it still doesn't detect the monitor. Should it automatically detect the monitor or would I have to do some config stuff? Thanks for your help with this.

**Comment by jakeday** [comment]
It will automatically add the monitor as a display device, but you would need to configure your system to use it as an output.

**Comment by valeryan** [comment]
Thanks, I will look into that. Its Linux so I expected I am missing some crucial configuration step in getting this to work.
