### ISSUE TITLE
Any tips on cloning the kernel repo with a wifi that drops out every 5 minutes and crashes the kernel ?

### ISSUE THREAD

**Issue by jukefr** [jakeday/linux-surface#231]
Git clone is made in such a way that it is not resumable.
My SP4 kernel panics every 5 minutes, even less when the wifi is under load. (probably because of mwifiex)
Does anyone have any tips on a way to clone the kernel ? 

I thought about maybe downloading it zipped through github but the stable branch is not on github, only linux main and it doesn't even have any branches only master so no checkouts...
Maybe I could try only cloning the .git from stable and downloading a zip of linux then moving the stable .git to be able to checkout the right commits...

edit: to be more precise, I mean that I only have access to the surface, with no extra hardware available (usb ethernet or other devices)

**Comment by jukefr** [comment]
I think I might be on to something.
Noticed that I would crash whenever my wifi was under load so I tried limiting my bandwith (with https://github.com/magnific0/wondershaper) by using `wondershaper -a wlp1s0 -u 512 -d 8192` and that seems to prevent it from crashing as fast as it usually does... For some reason.
Try and tune these upload and download values for your needs.
I will report back when (and if) I manage to clone the entirety of the kernel.

**Comment by mattjlee** [comment]
@jukefr I know it's been a while, but what was your conclusion?
