### ISSUE TITLE
cannot run virtual PC in virtualbox

### ISSUE THREAD

**Issue by luyang93** [jakeday/linux-surface#232]
Virutualbox    5.2.10_Ubuntu r121806
==========================================
Kernel driver not installed (rc=-1908)

The VirtualBox Linux kernel driver (vboxdrv) is either not loaded or there is a permission problem with /dev/vboxdrv. Please reinstall virtualbox-dkms package and load the kernel module by executing

'modprobe vboxdrv'

as root.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT. 

===========================================

sudo apt install virtualbox-dkms
==========================================
正准备解包 .../virtualbox-dkms_5.2.10-dfsg-6ubuntu18.04.1_all.deb  ...
正在解包 virtualbox-dkms (5.2.10-dfsg-6ubuntu18.04.1) ...
正在设置 virtualbox-dkms (5.2.10-dfsg-6ubuntu18.04.1) ...
Loading new virtualbox-5.2.10 DKMS files...
Building for 4.17.3-surface-linux-surface
Building initial module for 4.17.3-surface-linux-surface
ERROR (dkms apport): kernel package linux-headers-4.17.3-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 4.17.3-surface-linux-surface (x86_64)
Consult /var/lib/dkms/virtualbox/5.2.10/build/make.log for more information.

==============================================

cat   /var/lib/dkms/virtualbox/5.2.10/build/make.log
================================================
...
...
cc1: some warnings being treated as errors
scripts/Makefile.build:312: recipe for target '/var/lib/dkms/virtualbox/5.2.10/build/vboxpci/linux/VBoxPci-linux.o' failed
make[2]: *** [/var/lib/dkms/virtualbox/5.2.10/build/vboxpci/linux/VBoxPci-linux.o] Error 1
scripts/Makefile.build:559: recipe for target '/var/lib/dkms/virtualbox/5.2.10/build/vboxpci' failed
make[1]: *** [/var/lib/dkms/virtualbox/5.2.10/build/vboxpci] Error 2
Makefile:1571: recipe for target '_module_/var/lib/dkms/virtualbox/5.2.10/build' failed
make: *** [_module_/var/lib/dkms/virtualbox/5.2.10/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.17.3-surface-linux-surface'

========================================================

**Comment by martinnyborg** [comment]
I've had this bug before. 

The issue is due to changes to the kernel API which virtualbox uses (See: https://www.virtualbox.org/pipermail/vbox-dev/2018-April/015001.html) 

The issue was fixed in 5.2.12 of virtualbox (See: https://www.virtualbox.org/wiki/Changelog - 5.2.12 -  Linux hosts: support Linux 4.17 changes.)

So get yourself the latest version of virtualbox and it should work.

**Comment by novo-redeunt** [comment]
Yes, same here. Ran into issues with the Virtual Box version provided by Ubuntu 18.04. Installing the latest version resolved the problem.

**Comment by luyang93** [comment]
Thanks a lot.
