### ISSUE TITLE
4.17 regressions?

### ISSUE THREAD

**Issue by mattzuba** [jakeday/linux-surface#236]
I'm having some issues with 4.17 that I don't have with 4.16 on an OG Surface Book under Kubuntu 18.04.  

- The physical power button no longer works to do anything.  I previously had this mapped to suspend, however on 4.17 it does nothing.  Rebooting under 4.16 allows it to work again.
- If I manually suspend (systemctl suspend), it suspends, and then comes back a few minutes later and the volume up key (on the keyboard) seems stuck (but it's not).  Rebooting under 4.16 solves this as well.

**Comment by fpoussin** [comment]
I'm currently testing on my SP 2017 but it seems like there are other issues with 4.17.3:

- Wi-Fi crash - device disappears (needs reboot)
- USB ethernet adapter crash - device disappears (in my case using the r8152 module, needs reboot)
- Various screen freezes while playing videos (might be software)

This cause the system to hang at various places, there's no kernel error messages.
I'm back on 4.15.16 for now.

Power button still works.

**Comment by mattzuba** [comment]
I tried patching and building the latest 4.17 Kernel from upstream as well and had issues as well.  I ended up building the latest 4.16 kernel manually and installing and everything is pretty stable.

**Comment by jakeday** [comment]
Give this a shot on my latest 4.18.7 kernel.
