### ISSUE TITLE
patching 4.18.5 kernel issue

### ISSUE THREAD

**Issue by yuzvir** [jakeday/linux-surface#239]
I've tried to patch and build kernel for fedora (4.18.5) using **dutc's** fork and [branch](https://github.com/dutc/linux-surface/tree/v4.18-patches) **v4.18-patches** but it doesn't work. Since you or dutc probably thinking about new kernel versions support, I'll leave the journalctl log with errors. Maybe you know how to fix it?

[crash.txt](https://github.com/jakeday/linux-surface/files/2363326/crash.txt)

**Comment by qzed** [comment]
I haven't tested that fork yet, however when I tried to apply the patches to 4.18.5. (with slight corrections and removing the camera patch, basically just enough to make it compile) it also crashed (Surface Book 2). Removing the IPTS patchset fixed that issue (at the expense of no touchscreen-/pen-support however). I haven't had the time to look into that any further, it seems like there may be a bit of work involved in getting IPTS to work properly again.

**Comment by jakeday** [comment]
I added patches for 4.18.x.
