### ISSUE TITLE
systemd files changed locations

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#24]
This is to report that in Ubuntu 17.10 there are different locations for the systemd files.
So in the documentation where it says "Fix issue with Suspend to Disk:"
we need 
`sudo ln -s  /lib/systemd/system/hibernate.target /etc/systemd/system/suspend.target`
ans
`sudo ln -s  /lib/systemd/system/systemd-hibernate.service /etc/systemd/system/systemd-suspend.service`

**Comment by jakeday** [comment]
Added a note to the README.md file. Thanks for pointing this out!
