### ISSUE TITLE
Surface Book 2 - Ubuntu 18.04

### ISSUE THREAD

**Issue by crazyfrog-github** [jakeday/linux-surface#240]
Hi,

I have followed the instructions on the site listed below to install Ubuntu 18.04, however after I install the patched kernel part and reboot into kernel 4.17.3 it goes in a login loop, enter my password then it loops back to password entry. When I boot into 4.17.3 recovery it ; looks like it hangs at ''User Manager for UID 121''?

When I choose kernel 4.15.x it loads but Nvidia driver not installed shows Intel HD driver?

Any idea how I can get this working? does this only work with Ubuntu 16.04?

http://turlucode.com/how-to-install-ubuntu-16-04-on-surface-book-2/

Thanks

**Comment by jakeday** [comment]
This is a config issue. Please ask over on the surfacelinux subreddit.
