### ISSUE TITLE
Surface Pro 4 touch does not work

### ISSUE THREAD

**Issue by oazabir** [jakeday/linux-surface#246]
Firstly, this is an awesome work! My hats off to you.

Just installed Linux Mint 19 and installed the latest linux-surface on Surface Pro 4. Current loaded kernel is 4.18.7-surface-linux-surface. Cinnamon Version 3.8.9. 

Good news is keyboard, lights, volume key, brightness, wifi, bluetooth, suspend works. But touch on screen does not work. 

Could you help solve this problem please?

**Comment by WesleyVanNeck** [comment]
@oazabir works fine for me on my sp4

**Comment by battaglia01** [comment]
It works for me on my SP4, but then as soon as you suspend it no longer does until restart.

**Comment by oazabir** [comment]
No luck for me. Tried installing both Linux Mint and Elementary OS and then the latest linux surface kernel. I can see linux kernel is loaded. But still no touch. Not even after a fresh boot.

In fact, I don't see any visible change in the functions of wifi, lights, keyboard, bluetooth, wifi etc with or without the linux kernel. They work the same whether I boot in original kernel or boot using linux kernel. The only benefit I get with linux-kernel is suspend works. 

But I see wifi stops working after resume from suspend. Try this:
Suspend
Resume
Suspend again
Resume
Keep browsing for a while. Soon wifi will die for good.

**Comment by battaglia01** [comment]
You can reset wifi after it drops by resetting the `mwifiex_pcie` and `mwifiex` modules, and then reinserting them. Try 

```
sudo modprobe -r mwifiex_pcie
sudo modprobe -r mwifiex
sudo modprobe mwifiex_pcie
sudo modprobe mwifiex
```

This usually does the trick. But, touch has been slightly more different for me.

**Comment by oazabir** [comment]
Thanks for the commands, but when I run them, it hangs on the first line. If I try to run it again, says device busy. The commands never complete. When I try to restart, restart hangs. Have to force power down.

**Comment by jakeday** [comment]
Please ensure you are running the latest kernel and have re-run the setup.sh script. This has been addressed.
