### ISSUE TITLE
mmcblk on Surface Go does not work under latest 4.18.7

### ISSUE THREAD

**Issue by taichichuan** [jakeday/linux-surface#248]
mmcblk drive worked under 4.15.0-20 Ubuntu stock kernel but stops working after booting 4.18.7 linux-surface kernel.  This is on a new Surface Go tablet with 8 GBs RAM and 128 GBs nvme and dual boot with Windows.

**Comment by remingtonlang** [comment]
Sorry for my lack of understanding but I was under the impression the stock kernel provided all functionality out of the box. What was the inspiration for installing Jakes?

**Comment by taichichuan** [comment]
I had some issues with the Wifi.  It doesn't work with the stock kernel -- even with the new Atheros firmware.  The missing driver for the mmc card appears to be the rtsx_pci_sdmmc driver for the Realtek 
RTS522A.  I'll grab the sources for 4.18 and see if I can turn this on to get it working.

**Comment by taichichuan** [comment]
Have now verified that it was just a case of a missing driver in the 4.18-7 configuration file.  The RealTek PCI SD card interface was not selected by default for the config.  Enabling that interface and rebuilding the kernel resulted in joy at being able to see the SD card interface again.  Additionally, I add the network filter code back because these things should always have the ability to run a firewall.

[diff-config.txt](https://github.com/jakeday/linux-surface/files/2386232/diff-config.txt)

**Comment by small1** [comment]
This fix would be good to get a fix for. Noted today when i was about to restore a backup from an SD card that it didn't work.

**Comment by jakeday** [comment]
Fixed in 4.18.11.
