### ISSUE TITLE
enable multi-touch mode

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#25]
Thanks for compiling this kernel for us!

I'm wondering how to enable multi-touch so that the pen works.
Thanks again.

**Comment by Yanim** [comment]
sudo echo 1 > /sys/kernel/debug/ipts/mode.

It enables the pen for me and works fine with pressure, and so forth. However, for me at least, the command also makes the touchscreen (with fingers) completely non-functional.

**Comment by thekswenson** [comment]
Thanks @Yanim.  I get the same behaviour!

**Comment by Yanim** [comment]
If the issue is still the same on rc8 it would probably be best to make a new issue/rename this one.

**Comment by jakeday** [comment]
I applied the changes i had WIP from the 4.13 kernel (unreleased) into the 4.14 rc builds. Since there were a ton of changes to the i915 modules in 4.13 and 4.14, I had to re-do a lot of the IPTS modules. Single touch and pen both work now as you pointed out, but I hadn't finished multi-touch when changing modes. If you boot directly into multi-touch, it works, but that requires a kernel change. Since 4.14 rc8 is the last rc and the modules have settled down, I'm going to finish the changes and will release another build with fully functional single touch, pen, and multi touch. It will either be this week with an update to rc8 or Sunday with the official 4.14.0 release. Probably early this week though.

**Comment by jakeday** [comment]
@limond That commit was just finishing the port of my changes from 4.13, there was a lot of earlier changes that were required as well.

As for the errors you see, that's the difference from the firmware versions. I package the 76 build, but 78 and 79 work as well (and are technically included in my firmware file). I would use which ever one works best for you.

**Comment by thekswenson** [comment]
Thanks Jake!

**Comment by jakeday** [comment]
Sure thing! I'm trying to get everything working, but writing these drivers and rewriting other drivers can be a pain and time consuming. We'll get there! :)

**Comment by jakeday** [comment]
Multi-touch and pen both work on boot with my current test kernel, which I'll release later today.

**Comment by jakeday** [comment]
Compiling build now. Will upload in a few minutes.

**Comment by jakeday** [comment]
Pushed changes and uploaded kernel. Enjoy!

**Comment by oleid** [comment]
Thanks for uploading the new build.  It seems, however, that the touchscreen isn't working in multi-touch-mode, or something.

<pre>
Device:           ipts 1B96:006A UNKNOWN
Kernel:           /dev/input/event28
Group:            5
Seat:             seat0, default
Size:             293x165mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
</pre>

I get 
<pre>
root@m5:/sys/kernel/debug/ipts# cat status 
sensor mode : 1
ipts state : 4
</pre>

[2017-11-08-rc8_kernel-bootlog-sp4.txt](https://github.com/jakeday/linux-surface/files/1454024/2017-11-08-rc8_kernel-bootlog-sp4.txt)

Pen input seems to work fine, though.

Tapping the screen, I get the following kernel messages:

<pre>
# dmesg -c
[  725.166931] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.176343] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.196023] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.203579] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.213632] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.223643] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.235835] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.245839] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.255836] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.263409] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.273504] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.283198] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.295510] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.305434] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
[  725.316043] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255
               string Fatal Error
</pre>

This is on a surface pro 4.

Screen rotation for input doesn't work on gnome-shell, but I guess that needs to be solved within mutter:
<pre>Nov 08 14:29:10 m5 gnome-shell[914]: Could not get tablet information for 'ipts 1B96:006A Pen': Unsupported bus 'mei'</pre>

**Comment by jakeday** [comment]
@oleid It looks like it's loading and is detected fine, and those errors can be ignored. Are you sure you have your udev rule setup correct and touchscreen configured?

**Comment by oleid** [comment]
It would seem I missed your change of _99-ipts.rules_ on Nov 4th, since I installed that rule before Nov 4th. Trying that now.

**Comment by oleid** [comment]
No change for me; I think I'm seeing the same as in #27, so let's continue there.
