### ISSUE TITLE
Surface Go cannot detect or pair with Surface Mobile Mouse

### ISSUE THREAD

**Issue by ecc1** [jakeday/linux-surface#254]
I'm unable to pair with or even detect my Surface Mobile Mouse.

I'm running 4.18.7-surface-linux-surface on a Surface Go, with QCA6174/hw3.0/4.4.1/firmware-6.bin_WLAN.RM.4.4.1-00119-QCARMSWP-1 from https://github.com/kvalo/ath10k-firmware

In bluetoothctl, with "scan on", I see other BT devices, and when I make the Surface Go discoverable, I can see it on other devices like my phone. But the Mobile Mouse never appears (although it shows up on other Linux machines and I can pair and use it fine with my Linux desktop).

I see these messages in the Surface Go's log:

> Sep 22 17:16:15 debian kernel: [  658.149855] Bluetooth: hci0: last event is not cmd complete (0x0f)
> Sep 22 17:16:31 debian kernel: [  674.277835] Bluetooth: hci0: last event is not cmd complete (0x0f)
> Sep 22 17:16:47 debian kernel: [  690.149807] Bluetooth: hci0: last event is not cmd complete (0x0f)
> Sep 22 17:17:03 debian kernel: [  706.277830] Bluetooth: hci0: last event is not cmd complete (0x0f)

(but I also see those messages when succesfully discovering other BT devices, so they may be irrelevant)

**Comment by jakeday** [comment]
You can use the same workaround as the designer mouse.

https://www.ianthurston.com/fixes/ubuntu-designer-mouse-inspiron/

**Comment by ecc1** [comment]
This workaround doesn't have anything to do with the problem, as far as I can tell. The hci0 device is up on my Surface Go, and I can pair with other kinds of Bluetooth mice, just not the Surface Mobile mouse (it doesn't show up on the scan at all). Those workarounds are for a mouse that pairs but doesn't seem to work -- I can't get that far.

**Comment by sboehler** [comment]
@jakeday I have the same problem and am wondering what the workaround is. Unfortunately the link you provided is behind a paywall and the site looks not very trustworthy, can you give a hint?
