### ISSUE TITLE
Static coming from SB2 Speakers

### ISSUE THREAD

**Issue by Eclmist** [jakeday/linux-surface#255]
There are random popping sounds coming from the speakers, often when transitioning between the splash screen on boot to the desktop manager, and when logging out of the desktop environments. There are also continuous static noises when in recovery mode.

I'm on a SB2 15" and running Ubuntu 18.04 with the prebuilt kernels.

**Comment by remingtonlang** [comment]
@Eclmist there's a fix for this in #187

**Comment by Eclmist** [comment]
@remingtonlang It's not the same issue, I've not tested with plugging any headphones. I've also tried your fix, but the speaker still produces poping noise. You can test it simply by restarting the machine, you'll hear it as soon as you click restart.

Note that this does not happen with the original kernels.

**Comment by JackMorganNZ** [comment]
Can confirm this occurs with the latest kernals on SB2 Ubuntu 18.04. Occurs when booting, if I remember I'll record a video of boot up. I think it's playback from the microphone as I tapped my mics one time when booting and could hear it during the playback (only lasts for 1 to 2 seconds). Sorry, I'm new to Linux so don't know how to diagnose further but happy to follow any instructions.

**Comment by remingtonlang** [comment]
@JackMorganNZ yes the one or two second static is coming from the MIC. If you use headphones the same static will be constant. There is something weird in the way ALSA detects/sets the MIC Boost.

However the 1-2 seconds on boot I think happens before ALSA is fully loaded and disables the boosting. It's slightly concerning but entirely safe hardware wise and may be more appropriate to raise upstream or the Surface subreddit.

@Eclmist are you seeing anything in dmesg/syslog related to the sound driver or pulse/alsa?

Working on something else I stumbled on this though I don't get any static coming out of my SB2 w/ 4.18.7-Jakes:
```
p 28 12:58:01 sb2 pulseaudio[1628]: [alsa-sink-ALC298 Analog] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Sep 28 12:58:01 sb2 pulseaudio[1628]: [alsa-sink-ALC298 Analog] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
Sep 28 12:58:01 sb2 pulseaudio[1628]: [alsa-sink-ALC298 Analog] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```

**Comment by vonAlenberg** [comment]
I have this popping when GDM launches. However I have some slight static sound permanently. Muting the speakers doesn't help. Anyone else has this experience?
Running 4.18.11 on Ubuntu 18.04

**Comment by remingtonlang** [comment]
@vonAlenberg I just discovered a few more cases of hissing or popping sounds on my SB2. Are you by any chance running tlp?

I came into an issue where switching from AC to battery I'd get some weird loud clicks.
https://linrunner.de/en/tlp/docs/tlp-faq.html#audio

I simply disabled tlp for the sound card( SOUND_POWER_SAVE_ON_BAT=0 ) it and it resolved that issue

There is one more case of hissing that I suspect is related to the ACPI module but I've yet to be able to reliably reproduce

```Dec 25 22:33:44 sb2 kernel: [   67.142150] surfacegen5_acpi_notify_san MSHW0091:00: unsupported request: RQSG(0x13, 0x02, 0x00)
Dec 25 22:33:44 sb2 kernel: [   67.146082] surfacegen5_acpi_notify_san MSHW0091:00: ETWL(0x01, 0x02): RQST(19, 2, 0) error: 6
Dec 25 22:33:44 sb2 kernel: [   67.193897] surfacegen5_acpi_notify_ssh serial0-0: sending message
```
The few times I caught this immediately after resulted in a loud hiss that was only resolved by rebooting. If I can isolate/reproduce it I'll update

**Comment by jakeday** [comment]
This is resolved with the latest release.

**Comment by SoleSensei** [comment]
@jakeday same issue
laptop surface. lastest kernel release.
Hissing speakers 2 seconds sound while booting.
Laptop switched off if cover is closed with the same sound.

**Comment by phillpeters** [comment]
Surface Book 2 Linux Mint 19.1 4.18.2
I'm hearing a static hiss from my speakers a few seconds after grub2 screen (dual booting with windows 10).  Persists until I log in.

**Comment by SoleSensei** [comment]
@phillpeters it seems we'll need to open new issue fo SL/SL2 with this problem
