### ISSUE TITLE
[SB2 15] Installing nvidia-driver-396 from PPA breaks xorg

### ISSUE THREAD

**Issue by Eclmist** [jakeday/linux-surface#256]
Is the current version of the kernel not compatible with Nvidia's drivers from the PPA? It seems like these following packages break xorg (wayland still works): 

- nvidia-dkms-396
- nvidia-kernel-common-396
- nvidia-kernel-source-396

I have yet to explicitly test 390 yet, but I believe the same issue is present when 390 is installed from the software/update center.

The only fix so far for anyone who installed the proprietary drivers is to reinstall Jake's kernels and delete /etc/X11/xorg.conf if it exists. 

If this is a known bug (or known incompatibility), I didn't see it anywhere.

I'm running Ubuntu 18.04.
> `Linux SB2 4.18.7-surface-linux-surface #13 SMP Mon Sep 10 18:14:46 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jakeday** [comment]
This is a known issue with the nvidia drivers.
