### ISSUE TITLE
[Surface 3 (non pro)] Battery status not working

### ISSUE THREAD

**Issue by thecherry94** [jakeday/linux-surface#258]
Hello,

I can't get the battery monitor to work. 
I've installed the modified kernel and tried several proposed attempts for a solution on forums that I've found while searching on google.

​Unfortunately, none of these have been solving my problem.

**Comment by kitakar5525** [comment]
I have encountered the same issue.
You need to apply these two patches:

- [fedora-surface3-kernel/0001-power-MSHW0011-rev-eng-implementation.patch at master · hadess/fedora-surface3-kernel](https://github.com/hadess/fedora-surface3-kernel/blob/master/0001-power-MSHW0011-rev-eng-implementation.patch)
- [fedora-surface3-kernel/0002-ACPICA-adapt-buffer-length-for-Field-Attrib-Raw-Proc.patch at master · hadess/fedora-surface3-kernel](https://github.com/hadess/fedora-surface3-kernel/blob/master/0002-ACPICA-adapt-buffer-length-for-Field-Attrib-Raw-Proc.patch)

**Comment by random25252** [comment]
I've gotten the kernel working on fedora 28 & 29, I think this guide might be able to help you: https://denzilferreira.github.io/microsoft-surface-pro-4-and-fedora-28/

Note, I am not the guy that made that, his guide just worked for me on fedora.

**Comment by jakeday** [comment]
Resolved.

**Comment by bitfactory-justin-kouwenhoven** [comment]
@jakeday 
How is this resolved? Has the patch been added?
