### ISSUE TITLE
Screen keyboard popping up

### ISSUE THREAD

**Issue by XiaodongAAA** [jakeday/linux-surface#26]
Hi jakeday,
Really thanks for your work!!
I installed the kernel according to your instruction. Solved my wifi problem which was quite annoying before. The touch screen also works, but anytime I touch the screen, the keyboard pops up. Do you have any idea have to stop the touch screen from popping up or better idea to solve it?

**Comment by navneet92** [comment]
@XiaodongAAA ..is multitouch working for you, with the new kernel?

**Comment by XiaodongAAA** [comment]
@navneet92 Yes, mine (surface pro 4) is working. Seems everything is quite fine. Didn't check the pen though. But the screen keyboard is really annoying. This is a already-known bug of ubuntu 17.10. Hope someone could give a solution and make it work like in windows.

**Comment by thekswenson** [comment]
Check out this thread:
https://askubuntu.com/questions/965250/on-screen-keyboard-popping-up-whenever-i-touch-screen

**Comment by jakeday** [comment]
@XiaodongAAA This is not related to the kernel, but to your distro. Follow the link that @thekswenson provided and you should be good.
