### ISSUE TITLE
Possible typo in "Instructions to sign kernel"

### ISSUE THREAD

**Issue by sphh** [jakeday/linux-surface#260]
@ArcticXWolf thank you for adding the instructions to sign a kernel. Very helpful indeed!

IMHO the last command in #238 might be wrong:
```
sudo mv /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface{.signed,}
```
I get an error saying that this file does not exist (and yes, I substituted `[KERNEL-VERSION]` with my actual kernel version. I believe the command should read:
```
sudo rm /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface
```
(At least it worked for me.)

**Comment by ArcticXWolf** [comment]
No, it should not be a typo. I want both to rename the signed kernel and at the same time remove the unsigned one. However you can do it your way, it should not make a difference (the unsigned kernel gets deleted).

As for the command did not work on your side, maybe you did not save the signed kernel as `/boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface.signed` during the following line in step 7?

```
sudo sbsign --key MOK.priv --cert MOK.pem /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface --output /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface.signed
```

You could check the /boot directory for the file. My command is just a short version of:

```
sudo mv /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface.signed /boot/vmlinuz-[KERNEL-VERSION]-surface-linux-surface
```

**Comment by sphh** [comment]
Thanks for your comments. Here is my mileage:
```
$ sudo su -
# ls /boot/*signed
/boot/vmlinuz-4.18.11-surface-linux-surface.signed
# mv /boot/vmlinuz-4.18.11-surface-linux-surface{.signed}
mv: missing destination file operand after '/boot/vmlinuz-4.18.11-surface-linux-surface{.signed}'
Try 'mv --help' for more information.
```
This is my shell:
```
# echo $SHELL
/bin/bash
# $SHELL --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
```
running in `GNOME Terminal v3.28.1` and
```
# mv --version
mv (GNU coreutils) 8.28
```

**Comment by ArcticXWolf** [comment]
Ah, you are missing a comma. The {,} is a bash substitution. You can use it like this:
```
$ echo test{foo,bar}
testfoo testbar
```
It generates all possible combinations of the parts inside the brackets and the prefix/suffix.
Therefore you can use it to quickly remove or add a file extension without needing to type the whole path twice.

```
$ mv test{.conf,}
-> mv test.conf test
```
It does not work when you put there just `{.signed}`, you need to use `{.signed,}`.

For more on that: https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html

**Comment by sphh** [comment]
Oops, bad copy'n'past on my side I guess! Sorry!!
