### ISSUE TITLE
"Instructions to sign kernel"

### ISSUE THREAD

**Issue by sphh** [jakeday/linux-surface#261]
@ArcticXWolf , I followed your excellent "Instructions to sign kernel" #238 just to find, that a couple of packages were missing.

Could you please add the information, that on Ubuntu based distributions, which do not use the SHIM approach per default (such as Linux Mint), you have to install some additional packages. I succeeded by installing `shim-signed` which installed `shim`, `mokutil` and `sbsigntool` as dependent packages. It also set the system up to use SHIM.

**Comment by jrevillard** [comment]
A bit related: I'm using gentoo and use an initram created by Dracut.
When I activate secured boot, I can see my grub menu but then it fails saying the the system is corrupted. I think that it's due to the Dracut initram.
Anybody able to give me some instructions please (and then I could complete the documentation ;-) )
Best.

**Comment by ArcticXWolf** [comment]
Okay, I can do that. But I am curious, what Preloader/shim do they use? Linux Foundation Preloader? A complete different one? Or do they simply do not support Secure Boot?

**Comment by sphh** [comment]
Thanks, yes I guess this should put most people onto the right path. Maybe worth adding that `shim-signed` installs all other other packages necessary and modifies the boot process to use shim (if you are lucky).

**Comment by sphh** [comment]
Regarding Linux Mint and secure boot: Secure boot worked at least up to 17.x. It does not work in 19.x. (And I can't remember, if it worked in 18.x.)

**Comment by bitfactory-justin-kouwenhoven** [comment]
> Is there a step missing? I couldn't get the resulting `.signed` 4.18.7 or .11 kernels to boot. Got the `VFS: Unable to mount root fs on unknown block (0,0)` message, which seemed to indicate a missing initramfs output (which rightly isn't part of the process).
> 
> However when I tried simply renamed the `.signed` output to the standard `vmlinuz` filename, it worked without issue.
> 
> Is there an `initrd.img` supposed to be generated by of the signing steps or something?

Im having the same issue, didn't test it yet with renaming.

**Comment by Chugajstyr** [comment]
> Is there a step missing? I couldn't get the resulting `.signed` 4.18.7 or .11 kernels to boot. Got the `VFS: Unable to mount root fs on unknown block (0,0)` message, which seemed to indicate a missing initramfs output (which rightly isn't part of the process).
> 
> However when I tried simply renamed the `.signed` output to the standard `vmlinuz` filename, it worked without issue.
> 
> Is there an `initrd.img` supposed to be generated by of the signing steps or something?

I got the same issue with the signed Jayday kernel 4.18.16 on SB2 (OS - Linux Mint 19 "Tara", Ubuntu 18.04 LTS derivative), and you right - the problem in that initrd not generated for it. I solved it by creating copy of original initrd:
`sudo cp -p /boot/initrd.img-4.18.16-surface-linux-{surface,surface.signed}`
then running
`sudo update-grub`.

**Comment by bitfactory-justin-kouwenhoven** [comment]
The get back on my comment.
Im using a surface 3 (non pro). 
When i used the signed kernel (and renamed it like @combivanCoder said.

Image: [https://i.postimg.cc/tg3WWQ4q/IMG-9172.jpg](url)

**Comment by ArcticXWolf** [comment]
Strange, I did not have to do that, but you are right, we need an initrd for booting. I will publish a pull request for including the copy command later.

I'm curious: what harddrives do the Surface Nonpro devices have? My SP4 has NVME disks and they are directly specified in my grub.cfg, this might be why I did not need a initram disk. But I'm no expert on that either.

**Comment by ArcticXWolf** [comment]
As for @bitfactory-justin-kouwenhoven: Sadly I have no idea, what the problem can be.. I suspect this has nothing to do with not having an initram. Maybe the kernel got corrupted during the signing process? You could try to repeat the process. (You shouldn't need to do the key creation again, just the sbsign step)

Otherwise I have no idea, maybe someone else here knows more. The /r/SurfaceLinux community might know more, too, at least more people would see your issue there.

**Comment by bitfactory-justin-kouwenhoven** [comment]
> As for @bitfactory-justin-kouwenhoven: Sadly I have no idea, what the problem can be.. I suspect this has nothing to do with not having an initram. Maybe the kernel got corrupted during the signing process? You could try to repeat the process. (You shouldn't need to do the key creation again, just the sbsign step)
> 
> Otherwise I have no idea, maybe someone else here knows more. The /r/SurfaceLinux community might know more, too, at least more people would see your issue there.

Going to try again this week but with a different config values for openssl.cnf.

**Comment by ArcticXWolf** [comment]
I have published a pull request (#288) for adjusting the instructions.
