### ISSUE TITLE
Surface Pro 4 headphone jack muted

### ISSUE THREAD

**Issue by m9115m** [jakeday/linux-surface#263]
On Xubuntu 18.04.1. Kernel 17.3

I think the headphone jack worked on prior kernels...

STR
1.)  On SP4, Kernel 17.3, plug in headphones.

The SP4 speakers are muted along with the headphones. No sound from the headphones.

Hope this is an easy fix.

Thanks, as always, for a great kernel.
Mike

**Comment by remingtonlang** [comment]
@m9115m you're making us shoot in the dark a bit. Can you give a little more information? 

Have you messed with the audio settings yet? (Opening up alsamixer in a terminal. Is the volume muted? volume up? Does it see the sound card?)

**Comment by m9115m** [comment]
@remingtonlang Sorry bud, I thought it was simple enough.  Headphone audio is (was) not working.  Figured all SP4's would be seeing this issue with Kernel 17.3 

I poked around the mixer and didn't see anything obvious.  Here are a few screen shots

However, now it's working.  But I didn't follow my original STR.

Since you mentioned the mixer, I opened it before I tried plugging in the headphones, toggled the settings a bit, then plugged in the headphones and all was well.

![screenshot_2018-10-05_17-08-16](https://user-images.githubusercontent.com/16707058/46565209-018c9080-c8c2-11e8-89b6-e61a579bbd53.png)
![screenshot_2018-10-05_17-09-26](https://user-images.githubusercontent.com/16707058/46565210-018c9080-c8c2-11e8-9e40-b1b521fe81c4.png)

Let me reboot, and try to reproduce what I did yesterday (not opening the mixer first), to see if the headphones have magically returned to life...

Uno momento por favor

**Comment by remingtonlang** [comment]
Do you have multiple audio devices like a DAC plugged in? I have noticed device selection gets a little confused sometimes when multiple devices are present?

**Comment by m9115m** [comment]
@remingtonlang ....yeah, gremlins.  No other audio devices plugged in.

Must've been a combination of watching the new HBO series "The Deuce" and then listening to Dio on Spotify that did it. :)

Hard to believe, but I really plugged in the headphones and got nada.

Anyway, we can close this one.
