### ISSUE TITLE
[SB2 15] nouveau gets reloaded although blacklisted

### ISSUE THREAD

**Issue by vonAlenberg** [jakeday/linux-surface#264]
When booting the tablet only `nouveau` is not loaded. But when I reattach the tablet to its base the module gets loaded again, although I have blacklisted it in `/etc/modprobe.d/blacklist-nouveau.conf`.
That's quite annoying as the dGPU does nothing useful but drains my battery.

4.18.11, Ubuntu 18.04, xorg-session

**Comment by remingtonlang** [comment]
Thats strange, I detach/reattach the screen all the time and nouveau doesn't interfere or get loaded. What are the content blacklist-nouveau?

I have
```
blacklist nouveau
blacklist lbm-nouveau
alias nouveau off
alias lbm-nouveau off
options nouveau modeset=0

```

**Comment by vonAlenberg** [comment]
Originally I just had
`blacklist nouveau`
in it, but even with the contentc from @remingtonlang  it still gets loaded on boot.

**Comment by qzed** [comment]
@remingtonlang detaching/reattaching works fine on my system too, event hough I can't unload nouveau.

**Comment by vonAlenberg** [comment]
> @vonAlenberg after the file update did you run 'sudo update-initramfs -u' and reboot?

Things can be so easy... if you're not dumb like me. Thanks and closed ;)

**Comment by ezyang** [comment]
I spent a long time editing blacklists and running `update-initramfs` and wondering why it didn't work. Turns out, `update-initramfs` was updating my *unsigned* initramfs (but I'm using signed kernels because I'm on Surface Book 2 and didn't turn off trusted boot). A quick copy fixed the problem.
