### ISSUE TITLE
SB2: hibernate shuts down instead

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#266]
Ubuntu 18.04, latest kernel. Running audio systemctl hibernate shuts down my SB2 instead. I configured everything as per here: https://help.ubuntu.com/community/SwapFaq#How_do_I_add_or_modify_a_swap_partition.3F

**Comment by lucasvanlierop** [comment]
I experience the same issue.

**Comment by nkkollaw** [comment]
Same here (I think).

Any solution..?

**Comment by SoleSensei** [comment]
same

**Comment by nkkollaw** [comment]
In the README it says that suspend isn't working, can this have something to do with that? I experience the same problem.

**Comment by phillpeters** [comment]
I'm having this same issue.  I said yes to the option of having suspend be replaced with hibernate when installing the kernel (4.18.20).  When I choose suspend from the Quit options, the computer just performs a complete shutdown.

**Comment by nkkollaw** [comment]
I mean, it's fine as @jakeday does whatever with his repo, but I see the majority of issues get closed without even a note, even though they're not resolved.

**Comment by jakeday** [comment]
@nkkollaw I usually try to close with a note, and in most cases they are being tracked in another issue. For example, this one currently has 4 open issues on here for it. Currently this is being tracked on #378 as those issues are all related. Sorry for not being more clear!
