### ISSUE TITLE
Surface Studio 1st gen / 2nd gen with Ubuntu dual boot

### ISSUE THREAD

**Issue by wildapt01** [jakeday/linux-surface#268]
Was wondering if anybody has done it? I am looking at adding a Studio 2 to the stable.
Would Jake's kernel and patches work alright ?

I have Ubuntu 18.04 on dual boot on a SB2, working like a charm (Thanks a mil' Jake!)

**Comment by qzed** [comment]
I'm closing this as there hasn't been any response for a while now. If you're still deciding, I think you'll probably have better luck elsewhere.

**Comment by crispincorky** [comment]
Hello,

**Comment by crispincorky** [comment]
Did you manage to get this to work? I've got the Ubuntu live USB but it goes to a blank screen. Did you manage to get it running?

**Comment by wildapt01** [comment]
Unfortunately no. The reason is the Studio 2 is still on the "projects-to-do-later-after-I-get-a-job" shelf...

On the other hand, the SB2 works like a champ'

**Comment by sebastiaanfranken** [comment]
> Did you manage to get this to work? I've got the Ubuntu live USB but it goes to a blank screen. Did you manage to get it running?

Add "nouveau.modeset=0" to the kernel boot options. And be prepared to wait ~2 minutes for it to boot, since something is causing timeouts (for me at least, with my Studio 2 and Fedora 32 and 33 and Rawhide)
