### ISSUE TITLE
kernel uploaded on Nov. 8 2017 doesn't have multi-touch support

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#27]
Thanks again for all your work.  It's making my surface pro 4 actually FUN TO USE with Linux!

You uploaded ubuntu .deb packages last night to https://goo.gl/QSZCwq.
They were supposed to include multi touch fixes from Nov. 8.

They don't appear to work on my machine after uninstalling your previous .debs and replacing them with the new ones.  The new kernel acts exactly as the previous one did;  with `echo 0 > /sys/kernel/debug/ipts/mode` I have a kernel with nice single touch and no pen, while with `echo 1 > /sys/kernel/debug/ipts/mode` I have no touch but the pen works.

One unexpected thing I noticed:  the new .deb have exactly the same name as the others, despite being uploaded last night.  Is this expected?

Please let me know if I can give you any debug information.

**Comment by jakeday** [comment]
@thekswenson The file names are the same with the new upload. One thing to keep in mind is that the device name is different for touchscreen in multi-touch mode. You'll need to setup your rule and configuration appropriately. Maybe I'll build that in to the next release.

**Comment by thekswenson** [comment]
@jakeday Any chance you could give me a hint or some links to rule setup?

**Comment by jakeday** [comment]
@thekswenson The udev rules are in my repo. Can you give me the output of dmesg in multi-touch mode?

**Comment by jakeday** [comment]
@thekswenson The udev rules are in my repo. Can you give me the output of dmesg in multi-touch mode?

**Comment by oleid** [comment]
I'm using the latest udev rules from the repo now. Just to make sure setup is correct: multi-touch is supposed to be mode 1, correct? And I should see:
<pre>
# cat status 
sensor mode : 1
ipts state : 4
</pre>

What puzzles me is, that I don't get any output from `libinput debug-events`  when touching the screen in "sensor mode 1". For "sensor mode 0" I get lots of output, though. But then the touchscreen behaves strangely in gnome-shell.

**Comment by jakeday** [comment]
This should be working now with the build and changes I just pushed. You'll need to install the latest kernel and headers, use the new udev rule, and use the appropriate updated ipts_firmware package.

**Comment by oleid** [comment]
The build + udev rules alone didn't do a thing, However updating the firmware to v78 (I believe you only had v76 in the repo before) yields the missing _debug-events_. And on top, the `string Fatal Error` spam I  mentioned in #25 is gone. Hooray! :)

**Comment by navneet92** [comment]
@oleid .so multitouch is working for you now?

**Comment by oleid** [comment]
It is, yes.

**Comment by thekswenson** [comment]
Multitouch and pen work on SP4 when using the v78 firmware.

**Comment by thekswenson** [comment]
Multitouch and pen working on SP4 with the v78 firmware.

**Comment by navneet92** [comment]
@oleid can you try pinch to zoom on google maps?

**Comment by oleid** [comment]
@navneet92 : works on gnome-maps, however not in firefox @ maps.google.com. I guess that might be related to firefox being an X application and I'm running wayland- not sure.

**Comment by navneet92** [comment]
Thanks. I will check on ubuntu tomorrow. Let's see if that works.

**Comment by oleid** [comment]
Good luck!
In case you're using gnome-shell: I found a way to get automatic input transformation for the pen device working:

https://bugzilla.gnome.org/show_bug.cgi?id=790136

**Comment by oleid** [comment]
Multi-touch in firefox works when run

<pre>
MOZ_USE_XINPUT2=1 firefox
</pre>

**Comment by navneet92** [comment]
@oleid are you using surface 2017?
