### ISSUE TITLE
Surface Book2: Cannot Install NVIDIA Driver and Cannot Connect Hidden Wifi

### ISSUE THREAD

**Issue by MHijikata** [jakeday/linux-surface#271]
I installed latest linux-surface to Surface Book2. It almost work correctly.
But I cannot install nvidia driver. When I do it, login loop is occurred.
I think nvidia driver is not installed completely.
Because secure boot disable process is failed when I tried to install nvidia dirver.
Of Course, I made secure boot disable. So I cannot understand that secure boot disable process run.

Add to this problem, I cannot connect hidden wifi network.
When I use normal kernel 4.15.0-36-generic, I can connect it.

**Comment by remingtonlang** [comment]
Please see #253 

And the nvidia card has nothing to do with a hidden network. that's definetly software related. A general help forum would probably get you resolved quicker than here

**Comment by MHijikata** [comment]
Thank you for your quick response.
I could install nvidia driver by removing /etc/X11/xorg.conf.d/20-intel.conf.

**Comment by jakeday** [comment]
Resolved in latest setup.sh script changes.
