### ISSUE TITLE
Linux-surface Kernel with Po_os

### ISSUE THREAD

**Issue by divtodiv** [jakeday/linux-surface#275]
1st Thanks for the great work you did up to now.
2nd I installed Po_os and I'm trying to run your Kernel, it makes me install but after rebooting nothing appends...
I run $ uname -r and it still on the original kernel     4.15.0-36-generic
any suggestions ?

**Comment by adi-ida** [comment]
Have you changed the default boot kernel ? You can use grub customizer (GUI) or edit the grub.cfg file

**Comment by divtodiv** [comment]
I tried with grub customizer i even set it as default deleting the 4.15.0.36 but nothing. when i reboot everything goes back to normal. Can be because i have refind boot manager installed?

**Comment by divtodiv** [comment]
Yeeeeeeeee!!!!! works great!!!
its my fault i was logging in in the wrong img 
i will test it out and i will give an update of how it works on POP os.
for now after 10 min usage everything seems to work perfect

**Comment by divtodiv** [comment]
I love this hahaha.
works great I find works better than on Ubuntu, give it a try because the way the design is made feels like using an iPad.
The touchscreen froze sometimes but if you turn the screen will work again

**Comment by divtodiv** [comment]
Conclusion, 
Really laggy and not really worth it. the distro is nice but the kernel works better on Ubuntu, i find.
