### ISSUE TITLE
Surface Go: on-board keyboard

### ISSUE THREAD

**Issue by tuurleyck** [jakeday/linux-surface#277]
Any idea how to fix on-screen keyboard?
It doesn't show up when activated under Universal Access.

**Comment by remingtonlang** [comment]
Simply enabling it in Universal access simply means use it the onscreen keyboard when over an input field, its not a toggle for the keyboard like in Windows. 

This question is probably more suitable for a GNOME forum (/r/linuxquestions or r/GNOME on Reddit maybe) There's a GNOME extension that does what I think you're looking for. https://extensions.gnome.org/extension/1061/on-screen-keyboard-button/

Try that though your mileage my vary. On screen keyboards and Linux I found are way behind what Windows has to offer currently.

**Comment by qzed** [comment]
This is an issue with Gnome rather than the kernel. I doubt we can do much about that here.
