### ISSUE TITLE
Morrolinux

### ISSUE THREAD

**Issue by divtodiv** [jakeday/linux-surface#278]
https://github.com/morrolinux/SurfaceLinuxGoodies
Guys check this guy what he did.

**Comment by MuAlphaOmegaEpsilon** [comment]
He's an italian guy with a YouTube channel. I remember I saw a video where he was talking about his repository but forgot to check that out.

I wonder if an integration could be possible.

**Comment by divtodiv** [comment]
I`m currently tryng some stuff to see if i can fix the problem of the touch that keeps stopping randomly.
ill keep update

**Comment by MuAlphaOmegaEpsilon** [comment]
Nice.
