### ISSUE TITLE
[Surface Pro 2017] Poweroff on Power button

### ISSUE THREAD

**Issue by LandKingdom** [jakeday/linux-surface#283]
Hi, I compiled and installed the kernel provided in this repo on my surface pro 2017, and I wanted the power button to match the behaviour that it has on Windows: locking the screen. Unfortunetely I wasn't able to set that up since each time I try to check that button the power button is on the ACPI the kernel starts shutting the system off, making me unable to hook custom behaviour with acpid. How can I disable this behaviour so that it doesn't shut down automatically?

**Comment by qzed** [comment]
This seems like a configuration issue. What distro and desktop environment are you using? If your distro is using systemd, you can specify what happens with the power button there. Using acpid on top of systemd could probably cause some issues, as there are then multiple different handlers doing things.

**Comment by LandKingdom** [comment]
I'm on arch linux, using systemd by default. I tried checking what button is bound to the power button via journalctl -f or acpi_listen. I'll try to check if systemd is using it.

**Comment by qzed** [comment]
Nice to see that it wasn't a more serious problem! Thanks for the extensive write-up, I'm sure this will help others in the future!

**Comment by LandKingdom** [comment]
Edited title so it's easier for others to find... Have a nice weekend.
