### ISSUE TITLE
unknown command: hwmatch

### ISSUE THREAD

**Issue by nshanny** [jakeday/linux-surface#284]
Hi there, 

I used setup which ended up installing 4.18.16 from 4.18.0-10.  Upon booting I receive an error indicating that hwmatch could not be found. 

Surface Book 1
Ubuntu 18.10

Any quick ideas?

Nick

**Comment by qzed** [comment]
Seems like a bootloader/grub installation issue, see [here](https://askubuntu.com/questions/766355/error-unknown-command-hwmatch).
