### ISSUE TITLE
Anyone tried this on surface pro 6?

### ISSUE THREAD

**Issue by TTTPOB** [jakeday/linux-surface#285]
I just got a surface pro 6 and I want to get Linux run. Is there anyone can tell me will this work? I ask this because I didn't see descriptions about what will work and what will not.

**Comment by KatsuoRyuu** [comment]
What's your hardware specifications, specifically on the 6?

**Comment by TTTPOB** [comment]
nothing special, this is a minor upgrade. But as sp4 to new sp is also a minor upgrade and caused some problems, I am still worried.
Perhaps I should try it on my own.
