### ISSUE TITLE
[SB w Performance Base] Closing and opening the lid causes black screen or reboot

### ISSUE THREAD

**Issue by Menci** [jakeday/linux-surface#287]
Sometimes it reboots.

Sometimes when I open it, its screen keeps black and keyboard light can be turned on when pressing a key.

**Comment by sorsok** [comment]
I am having this same issue.

**Comment by Y05H10** [comment]
Me too

**Comment by Menci** [comment]
Select `yes` when the driver installer prompt you `Do you want to replace suspend with hibernate?` seems fixed it for me.

**Comment by jakeday** [comment]
@Menci yes, that is the accepted work around that fixes this.
