### ISSUE TITLE
linux-tools-linux-* package?

### ISSUE THREAD

**Issue by Menci** [jakeday/linux-surface#290]
Could someone make a linux-tools-linux-* package for us? I don't know about compling kernels but I believe it won't be that hard.

**Comment by Vonor** [comment]
What is that package supposed to contain?
In Debian there is no such package, in Ubuntu there are quite a few linux-tools-* packages but on the first glance I only see two files from /usr/share/doc in these packages....
https://packages.ubuntu.com/de/trusty/kernel/

**Comment by qzed** [comment]
@Menci could you elaborate on what such a package would contain or what it would be used for?

**Comment by Menci** [comment]
@qzed perf, a performance analyzing tool, requires the matching version of linux-tools to be installed.

**Comment by jakeday** [comment]
As mentioned before, this package is Ubuntu specific and will not be pre-compiled for release. You are free to compile the kernel from source using my guide and build this package as well if you need it on Ubuntu.
