### ISSUE TITLE
Surface 3 - Ubuntu 18.10 can't boot (signed kernel)

### ISSUE THREAD

**Issue by bitfactory-justin-kouwenhoven** [jakeday/linux-surface#291]
I think the kernel is broken for surface 3.
After following the readme (and signing) im getting the following error message while booting to the kernel:
https://i.postimg.cc/tg3WWQ4q/IMG-9172.jpg

**Comment by jakeday** [comment]
@bitfactory-justin-kouwenhoven Those errors are not related. Try booting with either the i915.enable_guc=0or i915.enable_ipts=0 param. Should work.
