### ISSUE TITLE
problem getting started with Surface go

### ISSUE THREAD

**Issue by opensas** [jakeday/linux-surface#293]
Sorry for the newbie question, but I'm having troubles just getting started with the Surface Go

I entered the bios to disable secure boot and set the boot order to start from the usb pen drive

I downloaded ubuntu-18.10-desktop-amd64.iso, saved it to a usb drive using etcher from windows, and then used a usb c to usb adapter to boot from it.

The boot process just ignores it and goes to windows 10. Same thing happened with linuxmint-19-cinnamon-64bit-v2.iso

I could make linux work from antergos-18.11-x86_64.iso though. It seems to work fine except for the wifi. Then I tried to replace /usr/lib/firmware/ath10k/QCA6174/board.bin with http://www.killernetworking.com/support/K1535_Debian/board.bin (following this tutorial: https://www.reddit.com/r/SurfaceLinux/comments/94hjxv/surface_go_first_impressions/) but I don't know how to get to the file. Wifi is not working and I can't mount the windows partition.

Anyway, could anybody provide me a detailed step by step just to get started? Or shall I need a usb wifi compatible with linux to download and install everything (and in that case I would also need a usb c adapter that allows me to have at the same time a usb pen drive and the usb lan card, am I right?)

**Comment by KatsuoRyuu** [comment]
If I'm not mistaking the bios is the same as on the other surfaces (sorry haven't worked with Surface Go) but in the bios there are a boot configuration you will have to drag the USB (USB Storage) to the top of the list.
I found on my Surface 2017 that even if i disable all except the USB it tends to boot to windows if USB is not at the top.
also make sure the ubuntu image you are using has UEFI support ;) If i remember correctly i could choose between a normal image and a UEFI supported image ;)

**Comment by tuurleyck** [comment]
@opensas , easiest way to get started for me was by connecting my phone over usb to tether my network connection. From there get this 'linux-surface' repo and run the script. It will patch the ath10k libraries and you're good to go. 

Alternative is to download the repo and run it offline from a usb stick.
