### ISSUE TITLE
Surface Laptop 2

### ISSUE THREAD

**Issue by looterz** [jakeday/linux-surface#294]
Has anyone had a chance to test this kernel out with the new Surface Laptop 2? I have one in the mail I can test with if needed.

**Comment by qzed** [comment]
I'm not aware of any testing so far, would definitely be appreciated!

**Comment by jcklpe** [comment]
My understanding is that it works, but also that there are throttling issues with the GPU. I could be wrong and would like to hear an update on this if possible too.

**Comment by looterz** [comment]
I ran into issues trying to install from a bootable USB since the keyboard isn't recognized, and the USB port on the power block isn't recognized, I'm unable to keep the live-usb + a keyboard device inserted at the same time.

**Comment by ejarmand** [comment]
> My understanding is that it works, but also that there are throttling issues with the GPU. I could be wrong and would like to hear an update on this if possible too.

I think that jcklpe is referencing the surfacebook 2 rather than the surface laptop 2 as the surface laptop 2 doesn't have a dgpu and someone posted on the main thread that the keyboard doesn't work for the surface laptop 2.

**Comment by jcklpe** [comment]
Ah yeah sorry. I forgot about the laptop. I just think of my book as a laptop haha

**Comment by tdan** [comment]
Bummer! I was really expecting you being right, @jcklpe . Having to use Windows full-time is really annoying. 😄

**Comment by hxoht** [comment]
I bought some hardware to try to fix this. I've applied the patch and as expected I'm having the keyboard problem reported in issue #5.

![img_1981](https://user-images.githubusercontent.com/136109/49267723-aafa8900-f410-11e8-8dab-462cd82ea089.JPG)

I'm going to take a stab at updating the patch and rebuilding the kernel from source. If I'm successful I'll merge my changes into my fork.

**Comment by hxoht** [comment]
@tdan thanks!

so far so good, im able to get the kernel building on the machine. I'm able to get verify changes by, piping the output from `dmesg` to `grep`. I can see we are getting to this point in the code (`Surface VHF: No keyboard resource defined`, https://github.com/jakeday/linux-surface/blob/master/patches/4.18/keyboards_and_covers.patch#L334).

I just noticed something suspicious of the driver member, `.acpi_match_table` (https://github.com/jakeday/linux-surface/blob/master/patches/4.18/keyboards_and_covers.patch#L438) not using the `ACPI_PTR` macro, as it does in other places (https://github.com/jakeday/linux-surface/search?q=acpi_match_table&unscoped_q=acpi_match_table).

**Comment by qzed** [comment]
I think we've got everything we need to know, if there's any specific issue feel free to open a new one.
