### ISSUE TITLE
Surface Pro 6:  Touchscreen Freezes when interacting with it consecutively. 

### ISSUE THREAD

**Issue by gliitch** [jakeday/linux-surface#296]
The touch screen works as intended, provided you don't interact with it too often. After a certain amount of touches, the screen appears to not respond. However, while running while true; do dmesg | tail -10; sleep 1; clear; done & tailf -10 /var/log/syslog

I have noticed that, the touch screen does indeed respond, as the number of interactions goes up. But it does not appear to do anything. 

If you try to do anything, for example, grab anything, you are unable to. So you'll need to Ctrl+Alt F4 then reboot the system from there.

![touch screen bug](https://user-images.githubusercontent.com/16258762/48305004-5f447600-e51b-11e8-851e-69daef5f8e58.jpg)

Hopefully this helps.

**Comment by jakeday** [comment]
This is being tracked in other issues for touchscreen stops responding.
