### ISSUE TITLE
Surface Book 2 - NVidia downclocking to 139MHz while gaming.

### ISSUE THREAD

**Issue by phunyguy** [jakeday/linux-surface#299]
Nvidia mostly works it seems, but the fan is not being controlled well enough to keep the internals cool.  I can provide logs/stats/etc upon request.  Been doing extensive testing, including with latest nvidia-drivers available in Gentoo. 
        Graphics                    : 1632 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:20 EST 2018
        Graphics                    : 1657 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:21 EST 2018
        Graphics                    : 1657 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:22 EST 2018
        Graphics                    : 1657 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:23 EST 2018
        Graphics                    : 1645 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:24 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:26 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:27 EST 2018
        Graphics                    : 1645 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:28 EST 2018
        Graphics                    : 1645 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:29 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:30 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:31 EST 2018
        Graphics                    : 1645 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:32 EST 2018
        Graphics                    : 1670 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:34 EST 2018
        Graphics                    : 1657 MHz
        GPU Current Temp            : 84 C
Mon Nov 12 22:50:35 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:36 EST 2018
        Graphics                    : 1670 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:37 EST 2018
        Graphics                    : 1632 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:38 EST 2018
        Graphics                    : 1620 MHz
        GPU Current Temp            : 85 C
Mon Nov 12 22:50:39 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 80 C
Mon Nov 12 22:50:40 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 76 C
Mon Nov 12 22:50:41 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 74 C
Mon Nov 12 22:50:43 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 73 C
Mon Nov 12 22:50:44 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 71 C
Mon Nov 12 22:50:45 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 70 C
Mon Nov 12 22:50:46 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 69 C
Mon Nov 12 22:50:47 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 68 C
Mon Nov 12 22:50:48 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 67 C
Mon Nov 12 22:50:49 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 66 C
Mon Nov 12 22:50:51 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 65 C
Mon Nov 12 22:50:52 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 64 C
Mon Nov 12 22:50:53 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 63 C
Mon Nov 12 22:50:54 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 63 C
Mon Nov 12 22:50:55 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 62 C
Mon Nov 12 22:50:56 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 61 C
Mon Nov 12 22:50:58 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 61 C
Mon Nov 12 22:50:59 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 60 C
Mon Nov 12 22:51:00 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 60 C
Mon Nov 12 22:51:01 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 59 C
Mon Nov 12 22:51:02 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 59 C
Mon Nov 12 22:51:03 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 59 C
Mon Nov 12 22:51:05 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 58 C
Mon Nov 12 22:51:06 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 58 C
Mon Nov 12 22:51:07 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 57 C
Mon Nov 12 22:51:08 EST 2018
        Graphics                    : 139 MHz
        GPU Current Temp            : 57 C
Mon Nov 12 22:53:10 EST 2018
        Graphics                    : 1404 MHz
        GPU Current Temp            : 51 C
Mon Nov 12 22:53:11 EST 2018
        Graphics                    : 1404 MHz
        GPU Current Temp            : 51 C

**Comment by qzed** [comment]
See #213, #216, #219. Will be addressed in #194, I can't give you any estimation as to when though. With the `acpi_notify` module I'm working on right now some of the required stuff will get implemented but I think we're still missing a few pieces after that.

**Comment by phunyguy** [comment]
OK, thanks.  I anxiously await it.   I should've mentioned, I am on kernel 4.18.18, if that matters.
