### ISSUE TITLE
Pen not working on Surface Pro 2017

### ISSUE THREAD

**Issue by andreweskild** [jakeday/linux-surface#30]
I tried your newest changes from last night, still no working pen here.
As requested, here is my dmesg output.
[dmesg-output.txt](https://github.com/jakeday/linux-surface/files/1459224/dmesg-output.txt)

**Comment by andreweskild** [comment]
Also, I just tried using the different versions of ipts firmware files. Using v78 allows both single and multi touch, but pen movement is completely undetected. While using v76 or v79, single touch still works. Multi touch mode no longer works, but both touch events and pen events show up in dmesg. Hope that helps.

**Comment by jakeday** [comment]
@andreweskild Are you saying that the pen does not work with any of the firmware packages?

Would it be possible to get a dmesg from each firmware?

**Comment by andreweskild** [comment]
That is correct, the pen doesn't work in any of the firmware packages. The one difference being that in the v76 and v79 firmware packages, pen movement events do show up in the dmesg output so it is at least receiving something from the pen. I will try to get dmesg from each firmware uploaded later today.
Thanks.

**Comment by andreweskild** [comment]
Here are the dmesg outputs for each firmware. I also included the journalctl outputs, as I noticed the dmesg outputs seem to be spammed by evbug events. On the outputs for the v76 and v79 firmwares you can see a bunch of lines that look like this:

`ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error : severity : 1, source : 1, code : 250:255:255:255 string Fatal Error`

That is what I get when I when moving the pen around the screen, however I do not get any events in evtest or libinput. Also, there is a section starting on line 2351 in the v79 journalctl output (the same output can also be found in the other journalctl outputs, though on different line numbers) that might be useful. It mentions that the pen is unknown to libwacom.

[dmesg-output-v76.txt](https://github.com/jakeday/linux-surface/files/1462438/dmesg-output-v76.txt)
[dmesg-output-v78.txt](https://github.com/jakeday/linux-surface/files/1462439/dmesg-output-v78.txt)
[dmesg-output-v79.txt](https://github.com/jakeday/linux-surface/files/1462440/dmesg-output-v79.txt)
[journalctl-output-v76.txt](https://github.com/jakeday/linux-surface/files/1462441/journalctl-output-v76.txt)
[journalctl-output-v78.txt](https://github.com/jakeday/linux-surface/files/1462442/journalctl-output-v78.txt)
[journalctl-output-v79.txt](https://github.com/jakeday/linux-surface/files/1462443/journalctl-output-v79.txt)

**Comment by jakeday** [comment]
This is due to incorrect ipts firmware files. As it turns out, the Surface Pro 2017 uses a slightly different device (MSHW0102) and needs the v102 ipts firmware files. These are now available in my repo.

**Comment by andreweskild** [comment]
You're amazing. Multi touch and pen working great here. One issue, though. The v102 firmware archive was missing the ipts_fw_config.bin file. I used the one provided in the v78 archive and it works great now.
Thanks!

**Comment by jakeday** [comment]
@andreweskild Yeah, that's the same file. I'll get it re-uploaded with the missing file. Thanks for pointing it out and I'm glad it's working for you!
