### ISSUE TITLE
Kernel patch for 4.19

### ISSUE THREAD

**Issue by hadrienk** [jakeday/linux-surface#303]
Hi, I tried to adjust the patches to the version 4.19 of the kernel but got more rej than I can handle: 

`acpi.patch` ignored in favor of the @qzed patches.
`buttons.patch` ok
`cameras.patch`
```
checking file drivers/media/usb/uvc/uvc_driver.c
Hunk #1 succeeded at 2352 (offset 5 lines).
checking file drivers/staging/Makefile
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED
checking file drivers/staging/ov5693/Kconfig
checking file drivers/staging/ov5693/Makefile
checking file drivers/staging/ov5693/ad5823.c
checking file drivers/staging/ov5693/ad5823.h
checking file drivers/staging/ov5693/ov5693.c
checking file drivers/staging/ov5693/ov5693.h
```
`ipts.patch`
```
checking file drivers/gpu/drm/i915/Makefile
Hunk #1 succeeded at 155 with fuzz 2 (offset 1 line).
checking file drivers/gpu/drm/i915/i915_drv.c
Hunk #2 succeeded at 697 (offset -21 lines).
Hunk #3 succeeded at 1436 (offset -9 lines).
checking file drivers/gpu/drm/i915/i915_drv.h
Hunk #1 succeeded at 3213 (offset -17 lines).
checking file drivers/gpu/drm/i915/i915_gem_context.c
Hunk #1 succeeded at 467 (offset 10 lines).
checking file drivers/gpu/drm/i915/i915_irq.c
Hunk #2 succeeded at 1504 with fuzz 2 (offset 27 lines).
Hunk #3 succeeded at 4126 (offset 213 lines).
checking file drivers/gpu/drm/i915/i915_params.c
Hunk #1 succeeded at 145 (offset -7 lines).
checking file drivers/gpu/drm/i915/i915_params.h
Hunk #1 succeeded at 46 (offset -1 lines).
Hunk #2 succeeded at 68 (offset -2 lines).
checking file drivers/gpu/drm/i915/intel_dp.c
Hunk #1 succeeded at 2604 (offset 3 lines).
checking file drivers/gpu/drm/i915/intel_guc.h
checking file drivers/gpu/drm/i915/intel_guc_submission.c
Hunk #4 succeeded at 1216 (offset 44 lines).
Hunk #5 succeeded at 1362 with fuzz 1 (offset 60 lines).
checking file drivers/gpu/drm/i915/intel_guc_submission.h
checking file drivers/gpu/drm/i915/intel_ipts.c
checking file drivers/gpu/drm/i915/intel_ipts.h
checking file drivers/gpu/drm/i915/intel_lrc.c
Hunk #1 FAILED at 163.
Hunk #2 FAILED at 1345.
Hunk #3 FAILED at 1399.
Hunk #4 succeeded at 2453 (offset 89 lines).
Hunk #5 FAILED at 2631.
4 out of 5 hunks FAILED
checking file drivers/gpu/drm/i915/intel_lrc.h
Hunk #1 succeeded at 106 with fuzz 2 (offset -5 lines).
checking file drivers/gpu/drm/i915/intel_panel.c
Hunk #2 succeeded at 660 (offset -20 lines).
Hunk #3 succeeded at 850 (offset -20 lines).
checking file drivers/hid/hid-multitouch.c
Hunk #1 FAILED at 151.
Hunk #2 FAILED at 614.
Hunk #3 FAILED at 666.
Hunk #4 succeeded at 1283 with fuzz 2 (offset 221 lines).
Hunk #5 FAILED at 1129.
Hunk #6 succeeded at 1541 (offset 224 lines).
Hunk #7 succeeded at 1558 (offset 225 lines).
Hunk #8 FAILED at 1456.
5 out of 8 hunks FAILED
checking file drivers/misc/Kconfig
checking file drivers/misc/Makefile
checking file drivers/misc/ipts/Kconfig
checking file drivers/misc/ipts/Makefile
checking file drivers/misc/ipts/ipts-binary-spec.h
checking file drivers/misc/ipts/ipts-dbgfs.c
checking file drivers/misc/ipts/ipts-gfx.c
checking file drivers/misc/ipts/ipts-gfx.h
checking file drivers/misc/ipts/ipts-hid.c
checking file drivers/misc/ipts/ipts-hid.h
checking file drivers/misc/ipts/ipts-kernel.c
checking file drivers/misc/ipts/ipts-kernel.h
checking file drivers/misc/ipts/ipts-mei-msgs.h
checking file drivers/misc/ipts/ipts-mei.c
checking file drivers/misc/ipts/ipts-msg-handler.c
checking file drivers/misc/ipts/ipts-msg-handler.h
checking file drivers/misc/ipts/ipts-resource.c
checking file drivers/misc/ipts/ipts-resource.h
checking file drivers/misc/ipts/ipts-sensor-regs.h
checking file drivers/misc/ipts/ipts-state.h
checking file drivers/misc/ipts/ipts.h
checking file drivers/misc/mei/hw-me-regs.h
checking file drivers/misc/mei/pci-me.c
checking file include/linux/intel_ipts_if.h
```
`keyboards_and_covers.patch`
```
checking file drivers/hid/hid-ids.h
Hunk #1 succeeded at 794 (offset 1 line).
checking file drivers/hid/hid-microsoft.c
Hunk #1 succeeded at 313 with fuzz 1 (offset 35 lines).
checking file drivers/hid/hid-multitouch.c
Hunk #1 succeeded at 1956 (offset 202 lines).
checking file drivers/hid/hid-quirks.c
checking file drivers/platform/x86/Makefile
Hunk #1 FAILED at 85.
1 out of 1 hunk FAILED
checking file drivers/platform/x86/surface_vhf.c
checking file drivers/platform/x86/surface_vhf_keyboard.c
```
`sdcard_reader.patch` ok
`wifi.patch` ok

**Comment by hadrienk** [comment]
Are some of the patch upstreamed? I noticed some of the rejections from the `ipts.patch` seemed to have very similar code.

**Comment by tgm4883** [comment]
I've been able to update all the patches to apply cleanly except ipts.patch. That one is massive and out of my depth

**Comment by tgm4883** [comment]
Attached are my changes. I used quilt to update these patches as I find it easier to work with.

[patches.zip](https://github.com/jakeday/linux-surface/files/2602512/patches.zip)

**Comment by hadrienk** [comment]
Thanks @tgm4883. I didn't know about quilt. I'll take a look at the ipts.patch see if I can lay some ground work.

**Comment by tgm4883** [comment]
@hadrienk If you can figure that out that would be great. I had started getting the patch to work but I don't know enough about kernels to know if I was just getting the patch to work and not removing/breaking/changing what the code was meant to do. The other patches were failing because surrounding things changed (more lines added, the code moved in the file, etc). IPTS has actual code changes that I just don't know about.

**Comment by qzed** [comment]
Has anyone been able to to make some progress on this? Otherwise I'll have a look at this next, so we don't get stuck too far behind.

**Comment by leonm1** [comment]
I've worked on it; however, I got stuck with a kernel that panics on boot. I'm blind on exactly how to proceed. I reverted back to 4.18 for finals, and now I'm ready to take another look -- perhaps this time with guidance from a more seasoned kernel developer?

**Comment by qzed** [comment]
Nice, I'm sure we can figure this out together! My plan is currently to look at what the IPTS patch does to understand why the changes it makes to existing files are required. So far I only have a bit of an overview:

- There is (at least) an IPTS _core_ part (`intel_ipts.c`), a _kernel_ part (`ipts-kernel.c`) for OpenCL based acceleration (probably of stroke smoothing, I don't know yet), an _HID_ part (`ipts-hid.c`) and an _MEI_ (Intel Management Engine, `ipts-mei.c`) part.

- The core seems to be (somewhat) integrated into the Intel graphics driver (i915). The IPTS device itself is an MEI device with a driver that in turn makes use of the IPTS core.

- The IPTS device supports at least two modes: _raw data_ and _HID_ mode. The HID mode seems to require some changes to `hid-multitouch.c`, but I don't know yet why and what those should accomplish.

- The HID descriptor (describing the inputs of the device, i.e. 10 finger touch input, stylus with one button and eraser, ...) is extracted from a firmware package (which needs to have a fixed name; since this is device dependent we may also want to look into a better way to do this, e.g. via DMI switching). The OpenCL kernel(s) are also stored in the firmware, as well as some configuration for those (?).

If we only look at the parts we have to adapt for 4.19/4.20 (I think we should probably focus on 4.20 since it's already out now), the biggest issues are within the integration of the IPTS core into the graphics driver. I haven't really looked at that though.

**Comment by jakeday** [comment]
@qzed I would't worry about it. I have a working 4.20 kernel with all of my patches. I'll merge your work in and release a 4.20 kernel in the next couple of days (likely tomorrow).

**Comment by krifisk** [comment]
> @qzed I would't worry about it. I have a working 4.20 kernel with all of my patches. I'll merge your work in and release a 4.20 kernel in the next couple of days (likely tomorrow).

Any ideas about the differences to 4.19? Since that is a Longterm stable release ( https://www.kernel.org/category/releases.html ) I'd really appreciate a working 4.19 patchset

**Comment by jakeday** [comment]
I have a working 4.20 kernel with IPTS, I just need to finish up the issue with power management. I usually like to wait until a x.y.1 release is out prior to pushing patches, so expect it around that time.

**Comment by jakeday** [comment]
Also to note, the patch for 4.20 should apply almost cleanly to 4.19 as well if we want to support that going forward too.

**Comment by krifisk** [comment]
> Also to note, the patch for 4.20 should apply almost cleanly to 4.19 as well if we want to support that going forward too.

Sounds good, thanks for quick response to both of you :)

**Comment by KatsuoRyuu** [comment]
Sorry for bumping.
I might be mistaking, or is this 4.20 merged into the patches already?
My distro (Gentoo) no longer had 4.18, at all. Which means I should either use custom kernel, be very careful not cleaning up my system ;-) 
So would just like to see/hear what status it ;-)

**Comment by jakeday** [comment]
@KatsuoRyuu No worries! I finished (hopefully) the changes and left it compiling when I went to work today. I'll test it out tonight, and hopefully release soon!

**Comment by jakeday** [comment]
Quick update, the 4.19 patches are done and working great! I'm building now for the changes to 4.19.18 (I was testing with 4.19.17) and will upload once it's complete this morning!

**Comment by KatsuoRyuu** [comment]
That's awesome! Will try it on my Gentoo system, I'll update my compile server with the new patches. I'll probably be able to test it all out this weekend

**Comment by krifisk** [comment]
> That's awesome! Will try it on my Gentoo system, I'll update my compile server with the new patches. I'll probably be able to test it all out this weekend

I upgraded yesterday using the updated patches on sys-kernel/gentoo-sources-4.19.18 and everything is working nicely :)
