### ISSUE TITLE
CONFIG_ACPI_SURFACE requires CONFIG_INPUT_SPARSEKMAP

### ISSUE THREAD

**Issue by krifisk** [jakeday/linux-surface#304]
Thanks for your work on these kernels!

When enabling CONFIG_ACPI_SURFACE: the build error below presents unless CONFIG_INPUT_SPARSEKMAP is also enabled. I recommend adding it as explicit dep for others that encounters the same :)

drivers/platform/x86/surface_vhf.o: In function `surface_vhf_probe':
surface_vhf.c:(.text+0x1c8): undefined reference to `sparse_keymap_setup'
make: *** [Makefile:1011: vmlinux] Error 1

**Comment by qzed** [comment]
This particular configuration issue should become irrelevant with #321.

**Comment by jakeday** [comment]
This is now irrelevant.
