### ISSUE TITLE
Icons not displaying properly after install (Surface Book 1, Ubuntu 18.10, Dual Boot)

### ISSUE THREAD

**Issue by jillianpenfield** [jakeday/linux-surface#307]
I just installed and set up the secure boot but ran into an issue with my Slack app icon. When I open a window of Slack this is what the icon of that window looks like:
![slackscreenshot](https://user-images.githubusercontent.com/44952536/49052696-fd426c80-f1ba-11e8-828a-70fe06d0cb8d.png)

Any ideas?

**Comment by brendandburns** [comment]
I don't think this is related to the Surface Kernel. This repo is just about the kernel. This looks like a general  issue with your distribution that is independent of the kernel/hardware you are using.

**Comment by jakeday** [comment]
That would not be a kernel issue. Can you please post your question on the SurfaceLinux subreddit?
