### ISSUE TITLE
Installation error of AUR package on Surface Book 1

### ISSUE THREAD

**Issue by RononDex** [jakeday/linux-surface#308]
I have been trying to install the linux-surface4 AUR package on my Arch install on my surface book.

I keep getting getting the following error: 
![image](https://user-images.githubusercontent.com/2249071/49075970-3cfb6980-f238-11e8-8a0f-2644c5ead717.png)

Steps to reproduce:
```
git clone https://aur.archlinux.org/linux-surface4.git
cd linux-surface4
makepkg -sic
```

**Comment by brendandburns** [comment]
This doesn't seem like it's related to this kernel, but rather something about that Arch package...

**Comment by brendandburns** [comment]
@jakeday looks like this is fixed. If you want to add me as a contributor, I can help cull/triage issues...
