### ISSUE TITLE
[Solved] No Signal detected ... external display connected on Microsoft dock detected 

### ISSUE THREAD

**Issue by arupbg** [jakeday/linux-surface#309]
Hello jakeday,

Similar to issue #79 and #300 . I face similar external monitor *no signal* issue on DP-2-2. Even though  `xrandr` shows connected ... but no signal. 

#### [dmesg.txt](https://github.com/jakeday/linux-surface/files/2626408/dmesg.txt)

Screen 0: minimum 320 x 200, current 2736 x 1824, maximum 8192 x 8192
`eDP-1 connected primary 2736x1824+0+0 (normal left inverted right x axis y axis) 260mm x 173mm
   2736x1824     60.01*+`
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 disconnected (normal left inverted right x axis y axis)
`DP-2-2 connected (normal left inverted right x axis y axis)`
   3840x2160     60.00 +  30.00    29.97  
   1920x2160     60.00  
   2560x1440     59.95  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    50.00    59.94    24.00    23.98  
   1600x1200     60.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  

### Monitor is detected but not signal
![image](https://user-images.githubusercontent.com/36227321/49178008-8f2ab080-f346-11e8-9198-85586e989934.png)

### If you select the grayed monitor .. you also see no selectable resolution
![image](https://user-images.githubusercontent.com/36227321/49178091-bf724f00-f346-11e8-960c-f51a5dc4fb4b.png)

**Comment by arupbg** [comment]
I just resolved. 
- Bought a £10 (4k) HDMI 1.2 to DV adapter from amazon
- Connected the (4k) HDMI port to the back of the monitor and DV port back of the Microsoft dock (brick)
## Signals picked up as if plug-n-play
![image](https://user-images.githubusercontent.com/36227321/49187537-b772d900-f35f-11e8-9c6d-d6305e0c8377.png)

**Comment by versipellis** [comment]
@arupbg How were you connecting it previously?

**Comment by arupbg** [comment]
- previously connected the default (provided) DP wire from the monitor to DP of the dock. *Does not work*
- provided DP wire from monitor direct to Surface Pro DP *works*
- Instead now using HDMI-2 (4k) monitor port to HDMI 1.2 adapter to DP of the Dock *works*

**Comment by versipellis** [comment]
@arupbg Thanks a ton. Just, wow. I tried it with EVERY possible connector combination _except_ HDMI->miniDP, and HDMI->miniDP works perfectly fine upon testing!
