### ISSUE TITLE
[SP 5 (2017), kernel 4.18.20]: System freeze after resuming from hibernate 

### ISSUE THREAD

**Issue by saturn-hh** [jakeday/linux-surface#310]
Dear all, 
I want to say thank you to all developer and supporter for their great work. I have the kernel running on the following system:

Surface Pro 5 (2017)
Ubuntu 18.10 (Gnome)

My Problem is, that I can't get hibernation to work. During the installation of the kernel with the setup.sh script I've enabled hibernation. But in Ubuntu 18.10 there is no swap partition but a swap file. I increased the size of the swap file and added the kernel parameters in the /etc/default/grub file. Furthermore I had to install uswsuswp and configured it to with the UUID of the partition where the swap file is and the swap offset. I also added the UUID in /etc/initramfs-tools/conf.d/resume. 

Now I can enter hibernation by submitting "sudo systemctrl hibernation" but the system isn't starting form the hibernation file, in fact it does a normal boot.
I'cant find any helpful information in dmesg or syslog.
 
What can I do? Any help is appreciated.

Alexander

**Comment by jonas2515** [comment]
You need to add kernel parameters so the kernel knows at which point in the filesystem to look for the hibernation data: https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation

Also, you should remove uswsuswp again, since hibernation is handled by systemd nowadays.

**Comment by jonas2515** [comment]
I'm pretty sure your home partition should already be decrypted when resuming. You can get logs of the last boot by setting `Persistent=1` in /etc/systemd/journald.conf and using journalctl --boot=-1.

**Comment by saturn-hh** [comment]
Thank's again for your help. I added the "Persistent" option to journald.conf and drm.debug=0xe to the kernel command line.
After the resume from hibernation everything seems fine for half a minute and then the system freeze. I think it has to do with i915 driver. After reboot (with magic sysrequest) I get this with journalctrl from the boot with the freeze:

`Dez 11 11:22:55 saturn-tablet kernel: [drm:gen9_dc_off_power_well_disable [i915]] Enabling DC6
Dez 11 11:22:55 saturn-tablet kernel: [drm:gen9_set_dc_state [i915]] Setting DC state from 00 to 02
Dez 11 11:22:56 saturn-tablet kernel: [drm:intel_power_well_enable [i915]] enabling DC off
Dez 11 11:22:56 saturn-tablet kernel: [drm:gen9_set_dc_state [i915]] Setting DC state from 02 to 00
Dez 11 11:22:56 saturn-tablet kernel: [drm:drm_mode_addfb2 [drm]] [FB:97]
Dez 11 11:22:57 saturn-tablet kernel: [drm:drm_mode_addfb2 [drm]] [FB:96]
Dez 11 11:22:57 saturn-tablet kernel: [drm:drm_mode_addfb2 [drm]] [FB:97]
Dez 11 11:22:57 saturn-tablet kernel: [drm:drm_mode_addfb2 [drm]] [FB:96]
Dez 11 11:22:58 saturn-tablet gnome-shell[1203]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Dez 11 11:23:07 saturn-tablet kernel: asynchronous wait on fence i915:gnome-shell[1203]/1:10c8 timed out
`
A google search brought up nothing  helpful.

**Comment by jonas2515** [comment]
Ouch, I found the ipts driver to cause those i915 hangs quite often, but just to be sure it doesn't have anything to do with the powersaving state the card enters before, disable the power saving for the graphics with the kernel parameter `i915.enable_dc=0`.

**Comment by jonas2515** [comment]
Those error messages you posted are caused by some gnome-shell extensions you have installed.

So it works fine with guc (or huc) firmware loading disabled, so maybe you should check if the right firmware is installed (the files from this repo are working for me), also you can try checking if its caused by the IPTS driver by setting `i915.enable_ipts` to 0.

**Comment by saturn-hh** [comment]
This are the firmware files witch are loaded during boot:

`Dec 13 18:32:50 saturn-tablet kernel: [    1.241561] [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_04.bin (v1.4)
Dec 13 18:32:50 saturn-tablet kernel: [    1.260748] [drm] HuC: Loaded firmware i915/kbl_huc_ver02_00_1810.bin (version 2.0)
Dec 13 18:32:50 saturn-tablet kernel: [    1.272098] [drm] GuC: Loaded firmware i915/kbl_guc_ver9_39.bin (version 9.39)
Dec 13 18:32:50 saturn-tablet kernel: [    1.283051] i915 0000:00:02.0: GuC firmware version 9.39
`
As far as I can tell, these are the correct/last versions of the files.

**Comment by etnguyen03** [comment]
Sorry to hijack this but I have a SP4 that also experiences this problem - after suspend the Fn key is working but all other keys (including Caps lock) aren't, mouse isn't working, touchscreen isn't working, and [KDE's login box is weird](https://i.imgur.com/jVcRSi6.jpg).

Not sure what logs and other diagnostic info is helpful but I'd be willing to provide them.

**Comment by jakeday** [comment]
This should be working now, and progress is tracked in #270

**Comment by 33Fraise33** [comment]
I don't know if anyone managed to fix this? I'm still seeing this issue to date on the latest version.
