### ISSUE TITLE
Surface Pro 2 black screen after install of kernel 4.18.16

### ISSUE THREAD

**Issue by zottelmann** [jakeday/linux-surface#311]
Hello!
I've got a used Surface Pro2 with no installed Windows, so i just installed a fresh Ubuntu 18.10. Everything worked ok, just some issues with keyboard sometimes not working. So i installed linux-surface as described in the readme. right after the reboot the surface stuck on a black screen. sometimes i can get into grub by first boot into "bios" and changeing secure boot to enabled/disabled and reboot. from there i can boot into my old kernel.
Is this a known problem? If it cant be fixed right now, how can i remove the kernel in a clean way?

Regards,
Zottel

**Comment by jakeday** [comment]
You can boot into your old kernel and then uninstall this package. It may be worth trying one of the newer kernels.
