### ISSUE TITLE
Linux Surface on NixOS

### ISSUE THREAD

**Issue by anthe** [jakeday/linux-surface#312]
I'm planning to setup nixos on my SB2. I think I can adapt the patches, firmware and setup.sh fairly easily to nixos, but I can't do much with the custom libwacom package. Can you share the patches you're applying to libwacom?

**Comment by qzed** [comment]
See [here](https://github.com/qzed/libwacom-surface), where I've extracted the patches from [this](https://github.com/geoffholden/libwacom) libwacom fork (this is the original source, all credits to @geoffholden). I haven't checked them in a while, so If you have any problems feel free to open an issue over there.

**Comment by anthe** [comment]
Perfect. Thanks!

**Comment by razvan-flavius-panda** [comment]
@anthe Did you manage to get it working on NixOS? If yes, could you share with us how to do it? Thank you

**Comment by anthe** [comment]
I did! I've been using it happily for a number of months. s2idle works, though I have occasionally freezes during suspend that I may not bother to debug. You can see what I've done in my fork of linux-surface. I'm not sure it's really ready for anyone else to use, but you're welcome to give it a try.

**Comment by razvan-flavius-panda** [comment]
@anthe Thank you very much. You're a hero. I might give it a try since Ubuntu is causing me issues with dual boot.

**Comment by razvan-flavius-panda** [comment]
@anthe One way to install it is to `git clone` your fork inside `/etc/nixos` and then reference that `SB2.nix` in the `configuration.nix`?

**Comment by anthe** [comment]
Yes, that’s how I have it setup on my machine.

**Comment by razvan-flavius-panda** [comment]
@anthe I did that and when I do `nixos-rebuild switch` it gives:

```shell
building Nix...
building the system configuration...
error: getting attributes of path `/etc/nixos/libwacom-surface/mei-bus.patch`: No such file or directory (use `--show-trace` to show detailed location information)
```

**Comment by razvan-flavius-panda** [comment]
@anthe I removed the `libwacom` installation from the nix file and now I am getting a different error:

```shell
QUESTION: ATOM Punit debug driver, NAME: PUNIT_ATOM_DEBUG, ALTS: M/n/y/?, ANSWER: m
GOT: m
GOT: Choose kernel unwinder
GOT:   1. ORC unwinder (UNWINDER_ORC)
GOT: > 2. Frame pointer unwinder (UNWINDER_FRAME_POINTER)
GOT:   3. Guess unwinder (UNWINDER_GUESS)
CHOICE: 1-3?, ANSWER: 2
GOT: 2
GOT: #
GOT: # configuration written to .config
GOT: #
GOT: make[1]: Leaving directory '/build/linux-5.1.21/build'
GOT: make: Leaving directory '/build/linux-5.1.21'
warning: unused option: EXT4_ENCRYPTION
warning: unused option: F2FS_FS_ENCRYPTION
warning: unused option: SECURITY_SELINUX_BOOTPARAM_VALUE
error: option not set correctly: SQUASHFS_DECOMP_SINGLE (wanted 'y', got 'n')
builder for '/nix/store/50k93frkycliqas7hx92726vkr2xckdr-linux-config-5.1.21.drv' failed with exit code 255
cannot build derivation '/nix/store/wihjgvrwy9cciqsh220dkprv3v3av7h2-linux-5.1.21.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/15yr252d0iri1nwknpwx6256b8hgj7pf-nixos-system-nixos-19.03.173575.0e0ee084d6d.drv': 1 dependencies couldn't be built
error: build of '/nix/store/15yr252d0iri1nwknpwx6256b8hgj7pf-nixos-system-nixos-19.03.173575.0e0ee084d6d.drv' failed
```

**Comment by razvan-flavius-panda** [comment]
I see that CONFIG_SQUASHFS_DECOMP_SINGLE is set to yes in three places. So I do not understand why it says it got no.

**Comment by anthe** [comment]
Oh yeah, that’s from qzed/libwacom-surface. At some point I’ll include that repo.

**Comment by razvan-flavius-panda** [comment]
@anthe `libwacom-surface` is required for the touch screen? touch screen is currently not working, and it was working when I installed the original kernel on Ubuntu

**Comment by anthe** [comment]
As far as I know it is, it’s been a while so I don’t remember the behavior I saw before I added the modified libwacom.

**Comment by razvan-flavius-panda** [comment]
@anthe The automatic screen rotation is not working either. Was that supposed to work? Or how can I achieve that?

**Comment by razvan-flavius-panda** [comment]
Oh, I can change screen rotation under settings -> Displays. But if I do that since I do not have touch support it is not really that useful.

What would I need to do to get that libwacom working so that touch screen works?

**Comment by anthe** [comment]
I had some time to update my work. I've at least made it easier to get all the required packages. It's in a new repo [nixos-suface](https://github.com/anthe/nixos-surface) The only issue I've found so far is that the eraser on the stylus doesn't work. I probably have an error in the way I setup libwacom. We'll just have to see when I have time to get around to fixing that.

I didn't know automatic screen rotation was possible, what program do you use to access the accelerometer?
