### ISSUE TITLE
Ubuntu not booting the linux-surface kernel (currently using ubuntu 18.10) (new to linux)

### ISSUE THREAD

**Issue by saltedfishsandals** [jakeday/linux-surface#313]
I have Ubuntu working on my surface book 2 but it doesn't support touch or any of the feature that come with the Linux-surface kernel when i try to boot Linux-surface all it shows is

loading Linux 4.18.16-surface-linux-surface ...
error: /boot/vmlinuz-4.18.16-surface-linux-surface has invalid signatures.
loading initial ramdisk ...
error: you need to load the kernel first

im currently using the default kernel to use linux on my surface but it get pretty hot while using it like that. I don't know what to do to fix this. Any help would be appreciated

**Comment by brendandburns** [comment]
See here:

https://github.com/jakeday/linux-surface#notes

Where it says:

"If you are getting stuck at boot when loading the ramdisk, you need to install the Processor Microcode Firmware for Intel CPUs (usually found under Additional Drivers in Software and Updates)."

Hope that helps!

**Comment by Erudition** [comment]
Just started getting this problem too. Microcode is installed.

**Comment by remingtonlang** [comment]
'error: /boot/vmlinuz-4.18.16-surface-linux-surface has invalid signatures.' 

I believe that's referring to an unsigned kernel. Ubuntu made the decision to stop signing kernels magically some time ago. If you have secure boot enabled I believe you need to do that on your own now. See: https://github.com/jakeday/linux-surface/pull/288

**Comment by jakeday** [comment]
You need to sign your kernel. Please refer to the SIGNING.md file in this repo.

**Comment by Erudition** [comment]
Or turn off secure boot.
