### ISSUE TITLE
Turning off LCD backlight fails on Kubuntu 18.10 cosmic - turns right back on

### ISSUE THREAD

**Issue by battaglia01** [jakeday/linux-surface#314]
In Kubuntu 18.10, it is impossible to turn off the LCD backlight. Whether I have power management attempt to turn off the backlight after 10 minutes, or upon closing the touch cover, or any way at all, the result is the same: the backlight turns off for a few seconds, then turns right back on.

I get the same behavior if I type `xset dpms force off` or `xset dpms force standby`. In both cases, the backlight turns off -- sometimes for longer, maybe 5 seconds or so -- but then turns right back on again anyway.

The following command does turn off the backlight: `sudo echo 1 > /sys/class/backlight/intel_backlight/bl_power` -- however, it does not turn back on when the mouse is moved. Rather, it just stays off unless you send another command to the screen.

I have now tried this with kernel 4.17.0 and 4.17.19 and am in the process of trying with 4.18.y and 4.16.y. Does anyone know why this happens?

**Comment by BenWestcott** [comment]
I've had no issues with this, also using Kubuntu 18.10. I can turn on and off the screen with `xset`, `/sys/class/backlight`, and setting the brightness to 0% also works.
Which Surface are you using? I'm on an SP4.

**Comment by battaglia01** [comment]
SP4 as well. Which kernel are you using? Is it compiled or are you using one of the binaries?

**Comment by BenWestcott** [comment]
Using the provided 4.18.16 package from the releases page.

**Comment by battaglia01** [comment]
I get the issue with that. Are you using the Kubuntu plasma backports PPA?

**Comment by BenWestcott** [comment]
I'm using the general Ubuntu bionic-backports PPA, but not Plasma backports.

**Comment by jakeday** [comment]
@battaglia01 based on your comments, the kernel itself is working as you can properly disable the backlight by interacting with the intel_backlight sys class. That would point to this being a configuration issue with your distro. I would recommend looking into what packages you're running with the backports you've used.
