### ISSUE TITLE
WPA2 wifi slowdown on most recent multitouch version

### ISSUE THREAD

**Issue by PrinceRAndrew** [jakeday/linux-surface#32]
Hi jakeday thank you for adding multitouch. It's basically perfect now! Only problem is that now ive been experiencing wifi slowdowns after about half an hour of use. I go from 160-200 mbps to 0.04 mbps :( 
I sometimes goes back to normal after re-clicking on the wifi network or by restarting Network Manger. Sometimes though a restart is the only way to fix it..
This is my dmesg report which just prints this for ever and ever. I don't know what to make of it... I'm running ubuntu 17.10.
[ 7745.155040] >> == DB s:1, c:a ==
[ 7745.155043] >> == WQ h:160, t:160 ==
[ 7748.227224] >> tdt : fw status : 8180505D 000A0000 000B000B 00000000 00000000 00000000

Also when it gets really bad ubuntu starts to get slow too. Memory leak???

**Comment by jakeday** [comment]
This is fixed in my latest build.
