### ISSUE TITLE
[Surface Book 1] Touchscreen randomly stops working

### ISSUE THREAD

**Issue by legoman420** [jakeday/linux-surface#322]
The touchscreen randomly stops working and the only way i can get it to work again without a reboot is to rotate the screen. 
Also when i try to remove the tablet from the dock it either freezes or turns itself off and then on a reboot i get a blackscreen when trying to boot in to linux again. I then have to use recovery mode to boot back in to linux.

**Comment by qzed** [comment]
>  or turns itself off

If by dock you mean detach the screen/clipboard from the base, then this is a known issue (#224). If you can provide me a DSDT/acpidump I'll have a look at it (just run `sudo acpidump > acpidata.dat` and upload the created file in the issue I referenced).

Also a dmesg log could be useful to see what could cause the other issues.

**Comment by alexanderi96** [comment]
Same touchscreen problem with my surface pro 2017, on 4.18.20, I'll provide the log as soon as I get home

**Comment by jakeday** [comment]
This issue is related to the changes to the priority contexts, specifically with the breakout of the guc clients, after ekrnel series 4.15. I'm fixing this in 4.20.

Let's continue this in issue #242
