### ISSUE TITLE
[Surface Book 2] Battery not detected despite new kernel

### ISSUE THREAD

**Issue by nkkollaw** [jakeday/linux-surface#323]
Hello,

I've compiled and installed the kernel using `master` (so, with the `surface-acpi` component). However, my battery is still not detected.

When I run `acpi` I get nothing, and `acpi -V` prints:

```bash
Adapter 0: off-line
Cooling 0: Processor 0 of 10
Cooling 1: GEN6 no state information available
Cooling 2: GEN8 no state information available
Cooling 3: pch_skylake no state information available
Cooling 4: Processor 0 of 10
Cooling 5: B0D4 no state information available
Cooling 6: Processor 0 of 10
Cooling 7: GEN5 no state information available
Cooling 8: intel_powerclamp no state information available
Cooling 9: GEN7 no state information available
Cooling 10: GEN9 no state information available
Cooling 11: x86_pkg_temp no state information available
Cooling 12: INT3400 Thermal no state information available
Cooling 13: Processor 0 of 10
Cooling 14: GEN1 no state information available
```

Is there anything one must do to activate this feature after installing the kernel?

I'm not sure if this is an issue of mine, or an issue.

**Comment by qzed** [comment]
Have you enabled the module in the kernel config? The relevant settings are
```
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_ACPI_SSH=y
CONFIG_SURFACE_ACPI_SAN=y
CONFIG_SURFACE_ACPI_VHF=y
```

**Comment by nkkollaw** [comment]
I have followed the instructions in the README and pached the config.

The only instruction I have (in `.config`) out of the ones you mentioned is:

```bash
CONFIG_SURFACE_ACPI=y
```

Wouldn't they be enabled by default? I am also not sure how to pass options before compiling.

Maybe I could wait for an official release, it's just that it's a pain to keep my laptop plugged in the whole time :-)

**Comment by qzed** [comment]
Yes, if you've enabled the first one, the rest should default to 'y'. I'd recommend you check (e.g. with `make xmenuconfig`) that the config variable and its dependencies are set correctly, manually setting them might not enable all dependencies. You can also check your current kernel if you have those options set (for debian-based systems the config should be at `/boot/config-VERSION` or something similar).

**Comment by nkkollaw** [comment]
in `/boot/config-VERSION` I have `CONFIG_SURFACE_ACPI=y`, but not the rest of the values (also, note that the value is set to `y`, not `m` like in your original comment.

Can I enable those modules via `modprobe`? Do you have precompiled kernel files in your repo? I had tried installing your .deb files, too, but they didn't work for me, either.

**Comment by nkkollaw** [comment]
Maybe I could close this and move this conversation to #28 ..?

**Comment by qzed** [comment]
> I had tried installing your .deb files, too, but they didn't work for me, either.

[Those](https://github.com/qzed/linux-surface/releases/tag/v4.18.20-pre2) should work (the ones prior to them don't include the module inside of the kernel). You may want to make sure that that's actually the kernel you're booting into if it still doesn't work (grub by default boots into the newest kernel).

**Comment by nkkollaw** [comment]
Yup. Yours works perfectly.

I guess the problem is me not being able to compile correctly, despite following the instructions in the README..?

**Comment by qzed** [comment]
Yeah, the config patch hasn't been updated yet since the addition. I guess Jake will do that with the next release. Also I think we should add a note in the README that it's best to use one of the configuration tools to set these values, as the config patch won't apply in cases with a modified/different config anyways. Maybe a script would be the better way, but I'm not sure if this will handle the dependencies correctly.

I'll close this for now.
