### ISSUE TITLE
Wifi disconnects after 2nd suspension - Ubuntu 18.10

### ISSUE THREAD

**Issue by alexmigf** [jakeday/linux-surface#326]
Hi,

I have installed Ubuntu 18.10, but when i close the lid and resume for the first time the Wifi works, but when i do that a second time the Wifi no more works.

My log: https://pastebin.com/L4NbXQKN

Edit: It's a Surface Laptop 1

**Comment by qzed** [comment]
Relevant excerpts in case pastebin deletes it:

Unloading before suspend:
```
[ 1013.515509] mwifiex_pcie 0000:02:00.0: info: successfully disconnected from c4:b8:b4:4b:6c:3c: reason code 3
[ 1013.516877] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.516879] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1013.516880] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.516880] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1013.516881] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.516882] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1013.516883] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.516883] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1013.516884] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.516885] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1013.516981] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.517111] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW in reset state
[ 1013.522822] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
[ 1013.523468] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1013.523474] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed

```

Reloading after suspend:
```
[ 1061.701890] mwifiex_pcie: try set_consistent_dma_mask(32)
[ 1061.701966] mwifiex_pcie: PCI memory map Virt0: 00000000b352f60e PCI memory map Virt2: 000000008bd7cf85
[ 1061.702543] mwifiex_pcie 0000:02:00.0: WLAN read winner status failed!
[ 1061.702545] mwifiex_pcie 0000:02:00.0: info: _mwifiex_fw_dpc: unregister device
```

**Comment by jonas-schievink** [comment]
I have the exact same problem (identical error) on a Surface Pro 3 and stock Linux 4.19.12. This never happened with the patches in https://github.com/matthewwardrop/linux-surfacepro3/ so now I'm trying to forward-port the `wifi.patch` from there.

**Comment by jakeday** [comment]
@jonas-schievink can you try with my latest patchset and prebuilt kernel? Should work great now!

**Comment by jonas-schievink** [comment]
@jakeday Wow, thanks! I'll try it out tomorrow (builds take a while)

**Comment by jonas-schievink** [comment]
@jakeday That patch worked perfectly

**Comment by alexmigf** [comment]
Great! I will test on mine in the next couple of days.

**Comment by victhebeast** [comment]
@jakeday patch broke WiFi on the surface pro 2017

**Comment by alexmigf** [comment]
Ok, i can confirm that it's fixed with last patch.

To get the lid close working with suspension i had to do:

`sudo nano /etc/systemd/logind.conf`

And replace HandleLidSwitch=**hibernate** with **suspend**

I want to thank everyone involved on this amazing repo that turn this possible.

**Comment by jakeday** [comment]
Awesome! And thanks for pointing out the default lid switch, I've been meaning to update that too!
