### ISSUE TITLE
[SP4]  Pen not working

### ISSUE THREAD

**Issue by icamps** [jakeday/linux-surface#327]
Hello @jakeday 

Thank you for your work!

Maybe I am arriving later to this, but...

I installed the latest Ubuntu (18.04) in my SP4, then I followed the steps and now I am able to boot from  `4.18.20-surface-linux-surface` kernel.

My issue is that the Pen is not working. I read other messages here but anything help me.
The output from `sudo cat /sys/kernel/debug/ipts/status` is:
```
sensor mode : 1
ipts state : 4
```
Do you have any idea?

Regards,

Camps

How to test if MultiTouch is working? Trying to zoom using two finger is not working either.

**Comment by qzed** [comment]
I have no idea about the pen issue, but you could check multitouch with [evemu](https://wiki.ubuntu.com/Multitouch/Testing/Evemu), specifically `evemu-record`. This should show one slot per finger when you touch the screen. Unfortunately touch integration in most Linux DEs is not quite there yet, so it heavily depends on the application if gestures, e.g. zooming with two fingers works. (See also [this](https://askubuntu.com/questions/536663/how-can-i-get-firefox-to-recognize-multitouch-gestures-on-a-touch-screen) askubuntu post for firefox in particular).

**Comment by jakeday** [comment]
@icamps Did you run the setup.sh script? Is touch working for you? Can you check the xorg log to verify the pen has been detected? And I have to throw this out as it's happened to me, but is the battery dead in your pen?
