### ISSUE TITLE
WiFi connected with no internet (UFW/iptables)

### ISSUE THREAD

**Issue by victhebeast** [jakeday/linux-surface#328]
Updated to the new patch 4.18.20 and wifi connects to network but no internet on surface pro 2017. It was working with the 4.18.16 just fine. I'm running Ubuntu 18.10 latest updates.

**Comment by jakeday** [comment]
Can you get me a log, please?

**Comment by victhebeast** [comment]
So after playing around I found out it is ufw that's the culprit. It was working before the patch but the only rule I had was block incoming/allow outgoing with the exception of allowing port 22 on my home networking. I disabled it, reset the rules, and tried to re-enable but i'm getting ufw-init problems.

**Comment by sir-vancelot** [comment]
I am having this issue on the SB2 as well. UFW is having the same troubles though I couldn't say if it's the culprit.

**Comment by victhebeast** [comment]
@sir-vancelot I disabled ufw for time time being and I had full internet connectivity on both wired (surface dock) and built in wifi. While ufw was on, it was connected to wifi and I could do non internet tasks (ssh to local computer on the network). I did a full complete reset (wiped partition, reinstalled Ubuntu all over) but I didn't have time to fully set it up because new years. I'll see more tomorrow.

**Comment by victhebeast** [comment]
woops wrong button

**Comment by sphh** [comment]
I can confirm @victhebeast finding: Enabling `ufw` on my Surface 2017 with Linux Mint 19.1 keeps me from connecting to the internet. Disabling `ufw`, WiFi works fine.

**Comment by qzed** [comment]
@victhebeast, @sphh are there any details as to why those lines are failing?

**Comment by victhebeast** [comment]
@qzed dmesg log:
```[  203.632705] xt_conntrack: cannot load conntrack support for proto=2
[  203.650347] xt_conntrack: cannot load conntrack support for proto=2
[  203.696770] xt_conntrack: cannot load conntrack support for proto=10
[  203.714526] xt_conntrack: cannot load conntrack support for proto=10```

**Comment by qzed** [comment]
@jakeday Could this be due to [`CONFIG_NF_CONNTRACK_IPV4`](https://github.com/jakeday/linux-surface/blob/9b218f92455842e5185812e213044c5770bdda47/configs/4.18/config#L1322) being disabled in the kernel config?

**Comment by jakeday** [comment]
@qzed Yep, and a few other config options. I'm adjusting and re-compiling now.

**Comment by jakeday** [comment]
Pushed changes and uploading release now.

**Comment by jakeday** [comment]
Release has been published!

**Comment by jakeday** [comment]
@victhebeast just pushed the support for ipv6 as well. Compiling now and will upload shortly.
