### ISSUE TITLE
Build kernel module?

### ISSUE THREAD

**Issue by rosinx** [jakeday/linux-surface#329]
Hi jakeday,
Thanks for creating this awesome kernel! I had a question,is it possible to build a kernel module for this particular kernel? And if so, do you think you could show me how to do it?
Thanks alot!

**Comment by qzed** [comment]
That works just like on any other kernel. Do you have any specific issues, e.g. does some existing kernel module fail to build or do you want to create a new one?

**Comment by rosinx** [comment]
I tried to run this command, sudo apt-get build-dep linux-image$(uname -r) but received an error "Unable to locate source package". Was trying to create a new kernel module which ended up working using the linux 4.2.0 kernel.

**Comment by qzed** [comment]
`apt-get build-dep linux-image$(uname -r)` should install the build-dependencies, the latter (`linux-image$(uname -r)`) shlouldn't be required as you've already installed that (or rather the version you need) when you installed this kernel.

**Comment by rosinx** [comment]
Ok that makes sense. Thanks!

**Comment by jakeday** [comment]
Closing this as the question has been answered.
