### ISSUE TITLE
Touchpad tap to click and two finger scroll

### ISSUE THREAD

**Issue by arprince** [jakeday/linux-surface#337]
Hi. I have a surfacebook 1 and just updated to the most recent kernel and settings today. Ton of improvements btw, I love it. Only problem is the touchpad no longer recognizes tap to touch and i cant invert my two fingered scrolling. These used to be settings in org gnome desktop peripherals touchpad, But when i change them nothing happens.

**Comment by jakeday** [comment]
@arprince Thanks for pointing this out! However, I'm going to close this as it's a config issue and not a kernel issue.

**Comment by xjcl** [comment]
This works for me about 1-2 minutes after boot using the config file dit but then it suddenly stops working. 

I even uninstalled libinput-gestures (```libinput-gestures-setup uninstall```) to prevent any possible negative interaction.

I **THINK** I got tap-to-click working permanently with this trick (two-finger scroll always worked) but some other software broke it. But I really didn't install anything besides libinput-gestures =/

**Comment by xjcl** [comment]
Okay, update.

Sometimes the touchpad tap-to-click is even broken directly after boot, so let's say 0-3 minutes. Also, when I uncomment the line you recommended adding I also get my 0-3 minutes so I think it didn't even do anything. This ever makes me doubt I got it completely working.

**Comment by xjcl** [comment]
The solution I found was to install synaptics for input:

`sudo apt install xserver-xorg-input-synaptics`

This has an inexplicable short delay when i tap-to-click somehow that libinput didn't have but tap-to-click is a killer feature for me so it's better than nothing.
