### ISSUE TITLE
Modules required by Docker missing

### ISSUE THREAD

**Issue by nkkollaw** [jakeday/linux-surface#338]
For all devs that use `linux-surface` and Docker, unless I'm missing something the latest kernel is missing a few modules that Docker requires to function, specifically:

- CONFIG_NF_NAT_IPV4: missing
- CONFIG_IP_NF_TARGET_MASQUERADE: missing
- CONFIG_IP_NF_NAT: missing

This stops Docker from starting. I'm using https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh to check for missing modules.

I'm sure this issue is not common, but I'm wondering if these modules can be enabled by default for all devs out there (unless it's a problem on my end).

I'm now trying to compile the kernel manually to enable those modules myself.

**Comment by jakeday** [comment]
@nkkollaw These are enabled in the latest kernels and in the example config file.

**Comment by nkkollaw** [comment]
I'm running the latest kernel, and they don't seem enabled, though. I'll try installing again!
