### ISSUE TITLE
Can I run apt sugested kernel update ?

### ISSUE THREAD

**Issue by doomdevelop** [jakeday/linux-surface#340]
Hi , I have SP 2017 and I am running your kernel on ubuntu 18.10
I did install as the description setup.sh
Will update of kernel via apt overriding the current surface kernel ? 
Thank you 
andrzej

**Comment by qzed** [comment]
The way this (normally) works is that the surface kernel is installed in parallel to the default distribution kernel. Updating the distribution kernel will only do that: update the distribution kernel. It won't override the surface kernel.

The only thing that can happen though is: It may change the kernel which boots by default. Assuming you are using grub, you can then manually load the kernel from the "advanced options" menu at boot, and then later change this default by editing `/etc/default/grub` after you've installed the update. Just change the `GRUB_DEFAULT` to e.g. `GRUB_DEFAULT="1>2"`, where in this case `1` is the index of the menu-entry you want to boot by default (this can also be a submenu, e.g. the "advanced options" menu), and `2` is the index of the submenu-entry (if the entry you want to boot is not in a submenu, then just omit the `>2` part). To figure out what the indices are, you need to, after the update, have a look at the grub boot-menu.

**Comment by doomdevelop** [comment]
Ok thank you for the explanation .
Just to more questions please to make it clear 
I am going to use only surface kernel any way ,  if I like to get latest kernel (or latest security update) I will need to build again surface kernel  with the script setup.sh for that, right  ? 
Is the power status integrated in to the surface kernel already (I saw some comments but not sure if it was about that)? Or I will need to again install [module](https://github.com/qzed/linux-surfacegen5-acpi) for the new kernel?

**Comment by qzed** [comment]
> if I like to get latest kernel (or latest security update) I will need to build again surface kernel with the script setup.sh for that, right ?

Either that or (potentially wait and) grab a prebuilt from the releases.

> Is the power status integrated in to the surface kernel already?

Yes, fully integrated, no need to build the module.

**Comment by doomdevelop** [comment]
Great ! Thanks again !

**Comment by qzed** [comment]
You're welcome! Feel free to ask if you have any more questions.
