### ISSUE TITLE
[SB2] `kworker` process with latest kernel

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#343]
Hello,

I installed the latest kernel (4.18.20) on `debian/buster` and I get somme `kworker` processes which are running constinuously at a high rate :
```
   61 root      20   0       0      0      0 R  89,7   0,0   0:39.72 kworker/0:2+kacpi_notify           
    7 root      20   0       0      0      0 D  15,7   0,0   0:06.19 kworker/u16:0+kacpi_hotplug        
```
Everything was running smooth before with kernel 4.18.16. Does someone face the same issue ?

Regards

**Comment by qzed** [comment]
Are you sure you've booted into the right kernel? The `kacpi_notify` thread running constantly usually indicates that an unpatched kernel is in use.

**Comment by qzed** [comment]
Alright, had to make sure.

I assume you have the config from this repo applied and there are no indications as to what's going wrong in the dmesg log?

Can you also make sure the required drivers have probed correctly, i.e. run
```
ls -l /sys/bus/acpi/devices/MSHW0084:00/physical_node/driver
ls -l /sys/bus/acpi/devices/MSHW0091:00/physical_node/driver
```
and make sure this is `surfacegen5_acpi_ssh` for the first and `surfacegen5_acpi_san` for the second one?

**Comment by deb75** [comment]
Hi,

I have no such file `/sys/bus/acpi/devices/MSHW0084:00/physical_node/driver`.

Here is the content of `/sys/bus/acpi/devices/MSHW0084:00` : 
```
drwxr-xr-x 2 root root    0 janv. 13 22:41 power
-r--r--r-- 1 root root 4096 janv. 13 22:41 hid
-r--r--r-- 1 root root 4096 janv. 13 22:41 modalias
-r--r--r-- 1 root root 4096 janv. 13 22:41 path
-r--r--r-- 1 root root 4096 janv. 13 22:41 status
lrwxrwxrwx 1 root root    0 janv. 13 22:41 subsystem -> ../../../../bus/acpi
-rw-r--r-- 1 root root 4096 janv. 13 22:41 uevent
```

Also : `ls -l /sys/bus/acpi/devices/MSHW0091:00/physical_node/` gives : 

```
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:00
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:04
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:05
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:06
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:07
drwxr-xr-x 3 root root    0 janv. 13 22:42 INT3403:08
drwxr-xr-x 2 root root    0 janv. 13 22:42 power
-rw-r--r-- 1 root root 4096 janv. 13 22:42 driver_override
lrwxrwxrwx 1 root root    0 janv. 13 22:42 firmware_node -> ../../LNXSYSTM:00/LNXSYBUS:00/MSHW0091:00
-r--r--r-- 1 root root 4096 janv. 13 22:42 modalias
lrwxrwxrwx 1 root root    0 janv. 13 22:42 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root 4096 janv. 13 22:42 uevent
```
The file `driver_override` constains `(null)`

I recompiled the kernel 4.18.20 with latest patches, I still have the issue.
I noticed that the `surface_acpi` module was not loaded at boot. But this changes nothing to manually load it, I do not have any battery statistics.

I do not use the same kernel configuration as that of the repo, but this should not make any changes, I only removed modules that were not necessary.

**Comment by deb75** [comment]
My bad, there was something missing  in my kernel configuration.

**Comment by qzed** [comment]
Nice that you got it working! Just out of curiosity: what was missing?

**Comment by deb75** [comment]
I used to cleaning the kernel configuration from all not necessary device drivers and also from all what does not concern the SB2.

It appears that I removed one of the `surface-acpi` module dependency.
I was lacking the serial device bus.

**Comment by qzed** [comment]
Ah, I see, thanks!
