### ISSUE TITLE
[SB2] Additional monitors through Surface Dock not working

### ISSUE THREAD

**Issue by GMory** [jakeday/linux-surface#345]
I've gone through the other issues related to this, including [#155](https://github.com/jakeday/linux-surface/issues/155), [#123](https://github.com/jakeday/linux-surface/issues/23), and [#309](https://github.com/jakeday/linux-surface/issues/309), but haven't found a solution.

Curiously, my multi-monitor setup through the dock worked just fine with the default kernel prior to loading this kernel. I restarted several times after a fresh install and the monitor's worked well. But after installing the kernel then restarting my monitors won't work. Anyone else experiencing this?

**Comment by versipellis** [comment]
I know you said you've looked at the other issues already, but what are you
using for hardware connections to your dock?

**Comment by GMory** [comment]
Yeah both monitors have HDMI to MiniDP, which I think was what fixed things for you. I tried disconnecting them for a minute and replugging them back in as suggested in another thread too.

**Comment by GMory** [comment]
OK so I restarted and loaded into windows, then restarted and back into ubuntu and it works now :| Hah, solutions like this are some of my favorite.

**Comment by qzed** [comment]
If that's reproducible (getting it fixed by booting into Windows and then directly to Linux) it looks a lot like the ethernet issue. Is the display output of the Dock USB based? If so, it might be worth a try adding the power-management quirk for that too.
