### ISSUE TITLE
Touchscreen on Surface Laptop 2 not working

### ISSUE THREAD

**Issue by aakroytor** [jakeday/linux-surface#346]
Hello! After following the setup instructions, the keyboard on my Surface Laptop 2 works--but the touchscreen doesn't! There doesn't even seem to be a touchscreen input listed in xinput:
ak@ak-Surface-Laptop-2:~$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ MSHW0092:00 045E:0933 Mouse             	id=7	[slave  pointer  (2)]
⎜   ↳ MSHW0092:00 045E:0933 Touchpad          	id=8	[slave  pointer  (2)]
⎜   ↳ Microsoft Virtual HID Framework Device Consumer Control	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Microsoft Virtual HID Framework Device Keyboard	id=9	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=11	[slave  keyboard (3)]
    ↳ Microsoft Virtual HID Framework Device Consumer Control	id=12	[slave  keyboard (3)]

**Comment by rosinx** [comment]
I'm having a similar issue on Surface Book 1

**Comment by jakeday** [comment]
@aakroytor Can you run "uname -r" and tell me which kernel you are using? Same for you please, @rosinx

**Comment by aakroytor** [comment]
Sure:
4.18.20-surface-linux-surface

**Comment by jakeday** [comment]
Can you get me the output of "lsmod | grep -i ipts"? Also can I see your xorg log output?

**Comment by dbranham20** [comment]
I have the same output for `uname -r`. Here is my lsmod output. Not sure how to get the xorg log output!

[lsmod.txt](https://github.com/jakeday/linux-surface/files/2793296/lsmod.txt)

**Comment by jtsen** [comment]
I'm having a similar issue with SP5. Any help would be appreciated. 
uname -r returns: 4.15.0-43-generic.
and "lsmod | grep -i ipts" returned nothing.

**Comment by jakeday** [comment]
@jtsen You're not running the linux-surface kernel. Please install the kernel, run the setup.sh script, and ensure you're booting to the correct kernel.

**Comment by jtsen** [comment]
@jakeday I successfully installed the newest version of the kernel and everything is working now. Thank you so much! This is awesome.

**Comment by dbranham20** [comment]
Any luck with this? Need anything else as far as logs or testing goes?

**Comment by jakeday** [comment]
@dbranham20 Can you get me the output of these two commands?

sudo dmidecode

ls sys/bus/acpi/devices

**Comment by dbranham20** [comment]
Here you go! 

[devices.txt](https://github.com/jakeday/linux-surface/files/2845508/ls.txt)
[dmi.txt](https://github.com/jakeday/linux-surface/files/2845509/dmi.txt)

**Comment by jakeday** [comment]
Perfect, I'll have this fixed over lunch today!

**Comment by jakeday** [comment]
Make sure you are on the latest kernel, and run the updated setup.sh script and you should be good to go!

**Comment by MaxBanister** [comment]
Do I have the same problem? Here are the output of those two commands:

[devices.txt](https://github.com/jakeday/linux-surface/files/2846781/devices.txt)
[dmidecode.txt](https://github.com/jakeday/linux-surface/files/2846783/dmidecode.txt)

**Comment by jakeday** [comment]
@MaxBanister Yep!

**Comment by dbranham20** [comment]
Installed the latest kernel and ran the setup script (said no to all of the options) and everything works great! Thanks

**Comment by jakeday** [comment]
Awesome, thanks for confirming!

**Comment by mannmann2** [comment]
Hi - I'm facing an issue on my SL2. Just installed the latest version of the kernel and the following is showing up on my dmesg:

[    1.958252] systemd[1]: /etc/systemd/system/surfacego-touchscreen.service:6: Unknown lvalue 'ConditionPathExists' in section 'Service', ignoring
[    1.959669] systemd[1]: /etc/systemd/system/surfacego-touchscreen.service:7: Unknown lvalue 'Exec' in section 'Service', ignoring

_uname -a_ returns -

Linux ubuntu 5.4.6-surface #1 SMP Fri Dec 27 22:27:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mtdoughty** [comment]
I believe this is a known issue on the 5.4 kernel.  (I know this as I made the same mistake myself).

If you read the release notes you will see that kernel 5.3 is recommended for everything but the very latest devices.

https://github.com/linux-surface/linux-surface/releases

I would note though that for me Kernel 5.4 seems to fix WIFI and graphics issues I was having on my Surface Pro 6, so I am living without touchscreen for now.

**Comment by zuhaib1214** [comment]
@jtsen Hello Sir!
I'm using ubuntu on my Microsft Surface laptop 2 and I install the linux-surface as well by following the instruction but when i reboot my laptop it is not loading the surface kernel it is saying "load the kernel first". 
I really need help regarding this issue.
I'll be very thankful to you if you guide me.
![1](https://github.com/jakeday/linux-surface/assets/125727928/7a880e0f-3f58-43cf-90df-c1341e82ec4c)
![2](https://github.com/jakeday/linux-surface/assets/125727928/5bf4fcc9-d896-4351-960d-22fa57bff54d)
![3](https://github.com/jakeday/linux-surface/assets/125727928/d0c3ce58-7204-4672-b866-146c40a4d36d)
