### ISSUE TITLE
Loading Initial Ramdisk

### ISSUE THREAD

**Issue by NickSica** [jakeday/linux-surface#35]
I've done this before so I believe I'm doing it correctly. The installation goes well but when I go to boot the kernel for the first time I get stuck at Loading initial Ramdisk... Usually I would try to figure it out on my own but Google yields very little that helped and my Linux skills are low. I tried various tags like verbose and removing quiet with no fixes, I reinstalled, and attempted to rebuild the initrd among other things. If you need files from me, please let me know I just want to get this fixed so it can also help others who have this problem.

**Comment by oleid** [comment]
What Distribution are you using and is there any output during boot (i.e. edit boot options from within the bootmanager, look for the line passing flags to the kernel and remove "quiet" and anything that looks like "splash" -- that will yield a more verbose boot).

**Comment by oleid** [comment]
Oh, and what kind of Surface are you using?

**Comment by jakeday** [comment]
Try reinstalling the kernel image and headers and send me the output. My guess is dkms is failing during installation and you need the latest patch files.

**Comment by Sevimuelli** [comment]
I experienced the same issue. Ubuntu 17.04 worked well but when i upgraded to 17.10 I had the same problem. I had to use the Processor microcode firmware for Intel CPUs, found in Software and Updates under Additional Drivers. I don't have much experience on this topic but it seams to be the solution. 
Slight lead: When you get stuck at Loading initial Ramdisk, just select a different kernel in grub. For me 4.13 worded. When you're able to boot just make the changes. Hope this helps you.

**Comment by NickSica** [comment]
Thank you everyone for the quick responses! I'm on Ubuntu GNOME 16.04 on the 2016 i7 surface book with dGPU. Last time I tried verbose nothing was produced but I'll try again.

**Comment by NickSica** [comment]
I reinstalled once already but I'll do it again, do you just mean the terminal output?

**Comment by NickSica** [comment]
I'm also able to boot completely into Ubuntu 16.04's generic kernel.

**Comment by NickSica** [comment]
Well Sevi's recommendation fixed it immediately! Thank you so much! Maybe add in a bit about it to warn others?

**Comment by jakeday** [comment]
Done.
