### ISSUE TITLE
Lots of evbug messages in Journal

### ISSUE THREAD

**Issue by thmichel** [jakeday/linux-surface#350]
On my Surface Book 2 I get lots of the following errors in the journal:

Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 0, Code: 0, Value: 0
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 2, Code: 0, Value: -7
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 0, Code: 0, Value: 0
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 2, Code: 0, Value: -4
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 0, Code: 0, Value: 0
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 2, Code: 0, Value: -1
Jan 13 21:07:27 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input51, Type: 0, Code: 0, Value: 0
Jan 13 21:07:28 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input12, Type: 4, Code: 4, Value: 458976
Jan 13 21:07:28 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input12, Type: 1, Code: 29, Value: 1
Jan 13 21:07:28 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input12, Type: 0, Code: 0, Value: 0
Jan 13 21:07:28 tomlinux.vbmichel.local kernel: evbug: Event. Dev: input12, Type: 1, Code: 29, Value: 2

I am using the lates pre-compiled kernal and used setup.sh to install the firmwares. Extracted the kernel manually, however, as I am using Fedora.

**Comment by qzed** [comment]
As far as I know, this is a config/distro issue, I had the same problem on Debian a while back, but not on Arch. Since the `evbug` module is just used for input event debugging, you can simply blacklist it, i.e. edit/add `/etc/modprobe.d/blacklist` and add the line
```
blacklist evbug 
```
without any implications.

**Comment by jakeday** [comment]
I agree with @qzed
