### ISSUE TITLE
Surface Pro 2017: Pen goes wrong after rotation

### ISSUE THREAD

**Issue by WangZhihua1998** [jakeday/linux-surface#351]
I'm testing on Ubuntu 18.10. After rotating the screen, the cursor of the pen goes to the wrong place. If the pen moves horizontally, the cursor will move vertically.It seems as if the pen won't "rotate" with the screen. And If I rotate it back, the pen will work fine as usual.

**Comment by qzed** [comment]
Installing the [patched libwacom package](https://github.com/jakeday/linux-surface/tree/master/packages/libwacom) should fix that.

**Comment by jonas2515** [comment]
This is actually a bug in Mutter that should be fixed in the next release (3.32).

**Comment by qzed** [comment]
@jonas2515 Ah, thanks for the info!
