### ISSUE TITLE
Surface Pro 2017 - The application of this method did not work

### ISSUE THREAD

**Issue by Guillaume-CHR** [jakeday/linux-surface#355]
Dear Jakeday,

First of all thank you for your GitHub :)

I run the steps described in your [README](https://github.com/jakeday/linux-surface#instructions) and get the "All done, please reboot" message.
I rebooted but none of the features (battery, touch-screen, volume buttons) are working...
Is there any specific steps I've missed??

For info, I have the Ubuntu (full Ubuntu) version 18.04.1 on a Surface Pro 2017 (i7).

Have a nice day,
Guillaume C.

**Comment by jakeday** [comment]
@Guillaume-CHR Can you confirm the kernel is running with "uname -r"? Also, did you get any output from the script detecting your device and installing firmware?

**Comment by Guillaume-CHR** [comment]
@jakeday Yes it is running and its output is "4.19.0-041900-generic". Dunno if it's the correct one.
My device has been detected as a surface (not sure if the model was retrieved but I don't remember so). Some things where install (packages) but can't recall which ones. I can relaunch it if you wish so I can get the out

**Comment by jakeday** [comment]
@Guillaume-CHR That means you are not running the linux-surface kernel. The generic 4.19 kernel is         getting selected by default as it's a higher version. You can set the 4.18.20 kernel as default, or in the grub boot menu select advanced options and pick the kernel.
