### ISSUE TITLE
Surface Pro 4. Faults found

### ISSUE THREAD

**Issue by Predatux** [jakeday/linux-surface#356]
I have installed Kubuntu version 10.10 with kernel 4.18.20.
The bugs I find are the following:
The touch screen is disconnected from time to time (there is already open incident). I would like to comment that many touch screen disconnections are said to occur when chrome is opened. I had problems in Linux with the composer, which also fell constantly when opening opengl applications. Is it possible that it could be related?
Apart from the problem of the touch screen failure, from time to time the battery indicator also fails. This fault is independent of the touch screen, which is still working. 
The screen rotation is supposed to work just like in Android? It doesn't work for me.
If you tell me which log files you need, I'll attach them.
Thank you and greetings.

**Comment by chylee** [comment]
I have the similar problems with touch under kubuntu 18.10 stop working while I'm interfacing using touch I have to use 'xset dpms force suspend' for to touch returns with out restarting though sometimes touch returned after I left it alone for a while. Looking on the internet and found that In KDE has not implemented screen rotation.

**Comment by jakeday** [comment]
The auto rotation works for the iio-sensors, but you likely need to configure them. The touchscreen issues are tracked under #242
