### ISSUE TITLE
Surface 3 (non-pro) sound not working with latest kernel (4.18.20-4)

### ISSUE THREAD

**Issue by Badorio** [jakeday/linux-surface#357]
Sound worked fine before installing the kernel. I installed Ubuntu Budgie 18.04, sound worked. Stopped working after installing the 4.18.20-4 patched kernel. 
Everything else seems to work fine.

**Comment by jakeday** [comment]
@Badorio can you get us some log files and the device list (aplay --list-devices) so we can debug?

**Comment by kitakar5525** [comment]
I had this issue on kernel 4.18. But now my Surface 3 has sound on 4.20. Not tested on LTS 4.19.

**Comment by Norswear** [comment]
how to install the jakeday's kernel? I have tried several times but after the installing steps and reboot，it cannot enter the OS, it shows the error like this: [cherryview-pinctrl INT33FF:00: Failed to request GPIO]
plz help me, thx @jakeday

**Comment by Norswear** [comment]
surface 3 non pro, elementary OS 5.0

**Comment by Norswear** [comment]
> surface 3 non pro, elementary OS 5.0

oh i found the way to fix it！add `GRUB_CMDLINE_LINUX_DEFAULT:"i915.enable_guc=0"`

**Comment by Norswear** [comment]
Here is the result:
```
**** List of PLAYBACK Hardware Devices ****
Home directory not accessible: Permission denied
card 0: Audio [Intel HDMI/DP LPE Audio], device 0: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [Intel HDMI/DP LPE Audio], device 1: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [Intel HDMI/DP LPE Audio], device 2: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```
It seems like we lost the surface 3 's sound card, the rt5645? @jakeday

**Comment by jakeday** [comment]
I'll fix it for the next release.

**Comment by Badorio** [comment]
I'm not sure if it is still necessary, but here is what I have:

`
**** List of PLAYBACK Hardware Devices ****
card 0: Audio [Intel HDMI/DP LPE Audio], device 0: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: Audio [Intel HDMI/DP LPE Audio], device 1: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [Intel HDMI/DP LPE Audio], device 2: HdmiLpeAudio [Intel HDMI/DP LPE Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

**Comment by Norswear** [comment]
EVERYTHING works well in newest 4.19 patched kernel！！！thx very much！（ without running the setup.sh，otherwise the sound will turn to very strange and crackling.）

**Comment by Norswear** [comment]
EVERYTHING works well in newest 4.19 patched kernel！！！thx very much！（ without running the setup.sh，otherwise the sound will turn to very strange and crackling.） @jakeday

**Comment by jakeday** [comment]
@Norswear Awesome, thanks! The crackling is due to the config files for pulse audio in the repo. I've switched them to be example files and they can be removed in the setup script now too.
