### ISSUE TITLE
Surface 3 Pro can't boot with latest

### ISSUE THREAD

**Issue by rednag** [jakeday/linux-surface#358]
First of all, thanks to your work. Without you many Surface users would not try either to run dual boot or productive linux systems.

Device: Surface 3 Pro
OS: Ubuntu 18.04
Kernel: 4.15.0-39

Tested 4.18.20-4, installed with your setup-script. After installation I was not able to boot anymore, it stopped while initializing CTR i8042.

**Comment by RussH** [comment]
Hi @rednag this may be issue as #167 can you try the fix?

**Comment by jakeday** [comment]
You need to add the grub boot command as mentioned in #167. Also, wifi should be fixed in the current release.
