### ISSUE TITLE
Surface Book 2: Lag when not charging

### ISSUE THREAD

**Issue by btearle** [jakeday/linux-surface#360]
After updating to 4.18.20 on my SB2 running 16.04, there's a noticeable system lag as soon as I unplug the power. Scrolling through a webpage / resizing windows / mouse movement all stutter much more when the computer is running on just battery. Doubled checked 4.18.16 and there's no similar issue there.

**Comment by qzed** [comment]
I don't experience this, but you could try and play around with the cpu governor.

**Comment by justinthomas** [comment]
@btearle are you using the Nvidia GPU? I've noticed that the GPU clock is throttled significantly when power is disconnected. You can monitor using `nvidia-smi dmon`.

**Comment by btearle** [comment]
Yep was using the Nvidia GPU. You're right, disconnecting the power immediately pulls the clock down to 139 MHz. Know of any way around this to force it back up to a normal speed?

Everything behaves normally when i switch over to the intel GPU (or if I plug the power back in).

**Comment by justinthomas** [comment]
I found a workaround, but I certainly cannot endorse it as I do not know the ramifications. I compiled the kernel from scratch and disabled the ACPI_AC module so that the NVIDIA driver no longer knows when the AC is (dis)connected. It works quite well; the battery indicator still shows whether or not the battery is charging, but it doesn't show that the AC adaptor is connected once the battery is at 100%. It's not an ideal fix, but it will work until a better option comes by.

**Comment by jcklpe** [comment]
Hey guys. Sorry to butt in. I was just wondering what ya'll's experience running Linux on your surface books has been like? I checked in a couple of months ago thinking about switching and I read that everything worked except the Nvidia gpu. Is that still true? I intend to use the machine to do graphic intensive stuff like 3d modeling and vr and I wanted to see if that was possible yet.

**Comment by omnicons** [comment]
> 
> 
> Hey guys. Sorry to butt in. I was just wondering what ya'll's experience running Linux on your surface books has been like? I checked in a couple of months ago thinking about switching and I read that everything worked except the Nvidia gpu. Is that still true? I intend to use the machine to do graphic intensive stuff like 3d modeling and vr and I wanted to see if that was possible yet.

They added proper support for the GPU recently, yes.

**Comment by jcklpe** [comment]
> > Hey guys. Sorry to butt in. I was just wondering what ya'll's experience running Linux on your surface books has been like? I checked in a couple of months ago thinking about switching and I read that everything worked except the Nvidia gpu. Is that still true? I intend to use the machine to do graphic intensive stuff like 3d modeling and vr and I wanted to see if that was possible yet.
> 
> They added proper support for the GPU recently, yes.

Full full support with no throttling? That's great news!

**Comment by ZHG2017** [comment]
Hi, may I inquire if this issue has been fixed or not ?

**Comment by qzed** [comment]
I think the best solution to the lag is: Use the Intel IGPU for normal desktop usage, and the Nvidia dGPU only for applications that really need it via optirun (or similar). This won't fix down-clocking on the Nvidia dGPU but should fix lags in casual desktop use. Fixing the down-clocking for disconnected AC probably requires a power-management driver, there are some hints on power-management of the dGPU in SSDT7 (`\_SB.DGFX.SPL0`, `"SPL0: Set DGPU Power limit to %0 mW"`). I'll probably have a look at this in the future.

**Comment by btearle** [comment]
Yep this is the solution I've been using. The vast majority of the time I don't need to be using the NVIDIA dGPU, so I just keep the Intel IGPU active which causes no issues.

**Comment by qzed** [comment]
I've made some progress on the throttling issue: It's possible to set performance-states via the EC. It looks like this will solve this issue, see https://github.com/qzed/linux-surfacegen5-acpi/issues/18 if you want to test this.

Also for anyone interested in dynamically turning on/off the dGPU, https://github.com/qzed/linux-surfacebook2-mshw0153 is now in a usable state, you just need to load/unload the gpu drivers after/before doing that.

**Comment by qzed** [comment]
This is now available in the latest release. For details on how to change the performance mode see https://github.com/qzed/linux-surfacegen5-acpi#setting-the-performance-mode.

**Comment by Resonious** [comment]
Using `surface performance set 4` works beautifully when charging, but I still experience poor GPU performance when unplugged. Openbox through nvidia-xrun can barely handle mouse movement (screen freezes for several seconds at a time), but as soon as I plug in the charger, everything's silky smooth, including games.

Forgive me if I'm missing something, but it seems like the "lag when not charging" problem hasn't quite been solved. Is there something else that needs to be looked into?

**Comment by qzed** [comment]
@Resonious This has been observed before (see [this comment](https://github.com/qzed/linux-surfacegen5-acpi/issues/18#issuecomment-490334470)), so I don't think you're missing something. It seems to be a bit better, but it's still limited somehow. Unfortunately I can't say what's causing this yet (I guess this could also be the nvidia driver). If I remember correctly, there isn't any difference in the SMC/EC communication that sets the power state if it's charging or not, so it might not be something that we can change via surface-acpi. I'll do some more testing in the future to see if we can't find a way to change this. I haven't done much research on this yet, though.

A good start would probably to observe the behavior on Windows when not charging, i.e. is there the same power limit or not? I suspect that there is _some_ limit on the dGPU, but probably/hopefully not as much.

**Comment by Resonious** [comment]
Ah, thanks for the link! I'll do some benchmarking to see how Windows behaves when plugged/unplugged.
