### ISSUE TITLE
Cant awake after sleep

### ISSUE THREAD

**Issue by dfghj44444** [jakeday/linux-surface#362]
As the title,I have a Surface Pro 6 ,when sleeped, the ketboeard or the key never worked.I tried install tlp or laptop_mode ,just not work,so every time it sleep ,I press(shortly) power on and then it boot with run a disk check, I think my harddisk will reduce its life time.

**Comment by jakeday** [comment]
@dfghj44444 Don't install tlp, it will cause several issues. Can you clean it up and see if you still get issues? If you do, please provide us some logs.
