### ISSUE TITLE
Pen side button recognized as middle mouse click instead of right mouse click.

### ISSUE THREAD

**Issue by ZZZXXX0110** [jakeday/linux-surface#363]
On Surface Pro 6 running Kubuntu 18.10, each click of the pen side button (with or without the tip touching the screen, but is close to the screen) is registered as a middle mouse button click.

It would have been incredibly more convenient and useful, however, to have the side button click registered as right mouse click, particularly for tablet usage, since in most DE there's no native way to issue right mouse click input through the touch screen alone.

**Comment by jakeday** [comment]
@ZZZXXX0110 That's a configuration change for Kubuntu. You can map the button to whichever action you like.

**Comment by ZZZXXX0110** [comment]
You're right. It seems unique to KDE that the right mouse button is number 3 and middle button is number 2.
As a reference for anyone else need help on this, I solved this problem by manually remapping the key for the button of "ipts 045E:001F Pen Pen (0)" device following the instructions here: https://wiki.archlinux.org/index.php/Libinput#Manual_button_re-mapping
This setting does not seem to persist through reboot, so I put a command into an automated script, which is executed on startup.
The eraser button on the other hand, is registered as a separate device.
