### ISSUE TITLE
Right mouse click emulation on touch screen.

### ISSUE THREAD

**Issue by ZZZXXX0110** [jakeday/linux-surface#366]
Anyway we can have touch screen register long press and emulate right mouse click? That would be greatly helpful since most DE don't provide native right mouse click for touch screen.

One way this could be implemented is through some kind of configuration file in /usr/share/X11/xorg.conf.d/, I think. But what exactly is the name of the driver used for the touchscreen on Surface devices? Is it "ipts"?

**Comment by jakeday** [comment]
This is a config change and not a kernel issue. Can you please post this over at https://gitter.im/linux-surface/support?
