### ISSUE TITLE
Linux kernel update in Update Manager - SL2

### ISSUE THREAD

**Issue by dbranham20** [jakeday/linux-surface#367]
I am currently running the latest releases of this repository. There is an update in the Update Manager in Linux Mint 19 for "Firmware for linux kernel drivers." Is it safe to update? How can we decide if future kernel updates are safe to install? Attached is a screenshot of some of the changelog for the update. I wasn't sure how to copy the entire changelog because it is quite long.

![linux-firmware](https://user-images.githubusercontent.com/29207819/51707311-dc499c80-1fee-11e9-8c5d-9014d98b63be.png)

**Comment by jakeday** [comment]
It's safe to update and won't cause any conflicts with the kernel.
