### ISSUE TITLE
Surface Pro 4: flaky wireless with the 4.14.0 kernel

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#37]
I've applied the apparmor patches, yet experience unpredictable wireless performance.
Half the time when I boot I'm incapable of connecting a network.  Sometimes only insecure connections work.  Other times, a secure connection works yet I cannot change to another one.

None of these problems happen running the Ubuntu 14.13.0-16-generic kernel. 

The following is a sample dmesg output from the last time I booted the computer.
PART A: The machine connected to eduroam and works (as it is now) despite error messages. 
PART B: Then I try to connect to the other encrypted network.  Now no connection can be made.
PART C: NetworkManager struggles, maybe trying to reconnect to eduroam and fails.
PART D: I reload the mwifiex_pcie module and then kill and restart NetworkManager.  This doesn't help and no network can be connect to hereafter.

PART A:

> 
> [    7.280718] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p77)
> [    7.280719] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p77)
> [    7.282873] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
> [    7.383720] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [    7.383810] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [    7.383814] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [    7.387384] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [    7.387390] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [    7.433140] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [   10.320946] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [   10.320984] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [   10.603668] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [   10.644678] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'eduroam' bssid 6c:aa:b3:5f:1a:fc
> [   10.728482] mwifiex_pcie 0000:02:00.0: info: associated to bssid 6c:aa:b3:5f:1a:fc successfully
> [   10.728509] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
> [   21.771258] rfkill: input handler disabled
> [   21.976029] Bluetooth: RFCOMM TTY layer initialized
> [   21.976036] Bluetooth: RFCOMM socket layer initialized
> [   21.976041] Bluetooth: RFCOMM ver 1.11

PART B:
> [  115.258906] mwifiex_pcie 0000:02:00.0: info: successfully disconnected from 6c:aa:b3:5f:1a:fc: reason code 3
> [  115.272390] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  115.272395] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  115.305328] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  115.305333] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false

PART C:

> [  141.005818] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  141.006734] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  141.006739] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  141.035994] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  141.036002] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  166.007495] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  166.008904] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  166.008912] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  166.038354] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  166.038359] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  174.742577] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  174.743668] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  174.743673] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  174.751718] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  174.751728] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false

PART D:

> [  196.481750] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
> [  196.482250] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
> [  196.482257] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
> [  197.663293] mwifiex_pcie: try set_consistent_dma_mask(32)
> [  197.663396] mwifiex_pcie: PCI memory map Virt0: ffffb3d381b00000 PCI memory map Virt2: ffffb3d384200000
> [  197.664640] mwifiex_pcie 0000:02:00.0: WLAN FW already running! Skip FW dnld
> [  197.664641] mwifiex_pcie 0000:02:00.0: WLAN FW is active
> [  197.772363] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p77)
> [  197.772372] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.7.p77)
> [  197.782586] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
> [  197.830119] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  197.830256] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  197.830262] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  197.835033] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  197.835039] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  197.903675] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  200.198525] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  200.198769] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  200.198774] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  200.204267] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> [  200.204270] mwifiex_pcie 0000:02:00.0: overriding ps_mode to false
> [  200.375430] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
> 

 

These may be related issues:
https://github.com/jakeday/linux-surface/issues/20
https://github.com/jakeday/linux-surface/issues/11

**Comment by arprince** [comment]
^Upvote. Also getting random dropouts and slowdowns :( I updated to the most recent kernel and am on wpa2 enterprise.

**Comment by jakeday** [comment]
Are you guys using the updated firmware files from marvell? Should I add those to my repo as well? I had this issue until I updated.

**Comment by thekswenson** [comment]
No I'm not.  I'm not sure how to do that.  I'll look into it.

**Comment by thekswenson** [comment]
There are many options for getting firmware and I'm not sure how to know which is the most recent or which is the one that works for you.  I did install the latest linux-firmware .deb from (https://packages.ubuntu.com/bionic/linux-firmware).  This did not solve the problem.

Other information I found was:

- https://www.reddit.com/r/SurfaceLinux/comments/6pmvpi/gitmarvellcom_alternative/
- https://bugzilla.redhat.com/show_bug.cgi?id=1185804
- https://github.com/wkennington/linux-firmware/tree/master/mrvl
- https://www.marvell.com/support/downloads/driverSearchResults.do;jsessionid=13DdhTcbWWBvxYB1txGVktcCCvv52Vkyc3D7Llh19HBt9JtL0fyL!347846052#

Do you have advice on which to follow?

**Comment by andreweskild** [comment]
If you go here: 
- https://www.reddit.com/r/SurfaceLinux/comments/6eau79/current_state_of_surfaces/
There should be a wifi section listed under your device on that thread. It links to a pastebin url with instructions on how to install the marvell firmware. I haven't had any issues with it so far.

**Comment by oleid** [comment]
I'm experiencing occasional WiFi loss on artful, too. Only reboot helps in that case.

For the record : Assuming the git repo [1] has the latest firmware, then artful doesn't have the most recent blobs:
<pre>
$ LC_ALL=C diff -Nur  /lib/firmware/mrvl/ mrvl/
Binary files /lib/firmware/mrvl/pcie8897_uapsta.bin and mrvl/pcie8897_uapsta.bin differ
Binary files /lib/firmware/mrvl/pcieusb8997_combo_v4.bin and mrvl/pcieusb8997_combo_v4.bin differ
</pre>

@jakeday : I still have to test if my occasional probs are gone, however, adding a link to the readme or even the files would most certainly reduce the support amount on that matter.

**Comment by PrinceRAndrew** [comment]
Update: I updated the drivers as Andrew mentioned and now the wifi is rock solid. No dropouts whatsoever after a few hours of use. I totally recommend adding instructions to update the marvel drivers into the readme because I bet the issue is bound to happen to someone else using enterprise wifi. https://pastebin.com/aBLHBFak Thank you jakeday and andrewskild!!!!

**Comment by jakeday** [comment]
Awesome, I'll make note of this in my next push.

**Comment by thekswenson** [comment]
This bug persists for me.  That being said, the wireless is much more usable than it used to be:  when reloading the kernel module and NetworkManager I manage to reconnect most of the time!
Thanks @jakeday!

Here is the script that I run to reconnect:

```
#!/bin/bash
sudo modprobe -r mwifiex_pcie
sleep 1
sudo modprobe mwifiex_pcie
sleep 1
sudo lsmod | grep mwifiex
sudo service network-manager restart
```

**Comment by thekswenson** [comment]
I vote to reopen this issue, since I would still classify my connection as "flaky".  There are times that I boot my SP4 and the wireless will never work, despite running the script I posted.  When the script does result in a connection, the next time I change network I can no longer connect to anything.

My experience with the default 17.10 kernel is much better, although nothing I would classify as "rock solid" (@PrinceRAndrew).  There are very rare losses of connection.  Unfortunately this kernel is not as good yet.  Maybe @PrinceRAndrew always uses his machine on the same network?

This is my work machine, and I need a solid network connection :(.

**Comment by jakeday** [comment]
@thekswenson That's odd, with the stock kernel I lose connection when walking around the office a I work in. With my kernel, it stays completely solid. This applies to both my Surface Book and Surface Book 2. Did you also disable random mac address assignments?

**Comment by thekswenson** [comment]
haha.  odd.
I haven't enabled or disable anything that was not in the instructions.   How would I disable random mac address assignments?

**Comment by thekswenson** [comment]
As you had guessed @jakeday , I missed the update from a couple of days ago to /etc/NetworkManager/NetworkManager.conf.  Wireless is working much better now.  Thanks for the help!
