### ISSUE TITLE
Question regarding the kernel config file

### ISSUE THREAD

**Issue by hadrienk** [jakeday/linux-surface#370]
I am wondering why is a config file present in the repo? Is it so the the modules added by the patches are enabled?

Regardless, I am wondering if anyone would be interested I making config files tailored for SB that remove useless config options? I am thinking of this mainly to speed up compilation time.

**Comment by jakeday** [comment]
I added a config file so you can see how the prebuilt kernel is compiled, as well as compare it for the required modules for your distro. Maintaining a patch was not feasible due to constant changes per minor release.

Also, please ask questions like this on the gitter community.
