### ISSUE TITLE
 surface 3  non pro video patches are not working

### ISSUE THREAD

**Issue by dmitryam** [jakeday/linux-surface#371]
I tried installing the packages. unfortunately they are not working due to uncompatible video. the system boots only via recovery mode and seems to go to framebuffer mode rather than to i915. the resolution is only 800x600. The stock ubuntu video drivers seem to work. 
Other features like battery seem to work

**Comment by jakeday** [comment]
You need to add either i915.enable_ipts=0 or i915.enable_guc=0 to your boot command for your device. I added a note to the readme for this.
