### ISSUE TITLE
{Feature Request] Battery management

### ISSUE THREAD

**Issue by vonAlenberg** [jakeday/linux-surface#372]
@jakeday Looking at all those issues I assume you have a lot to do. However I'd like to ask the following:

_Would it be possible to implement a switch for choosing, which battery gets drained first?_ 

I always thought both batteries would be used equally, which is already quite uncool. Now I saw this:
![battery-usage](https://user-images.githubusercontent.com/26161253/51846829-ab34d900-231a-11e9-911d-fd6abc3c8f30.png)
(I guess "extra" is the tablet part)
Both ways I don't like, because the tablets battery wear out is much worse than the base's one.

**Comment by Scarzer** [comment]
This is a bit weird of a topic but it can be talked about [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/powermeter/software-defined-batteries). I'm not sure how transferrable this would be though :X 

Microsoft did some really cool stuff regarding defining multiple batteries in an operating system

**Comment by qzed** [comment]
I'm not sure if this is even possible, I haven't found anything in the ACPI related to this. Anyone know if this is possible on windows?

Also if it's possible, then most likely via the surface-acpi module, not sure if we want to move the issue there.

**Comment by qzed** [comment]
@vonAlenberg AFAIK the extra is the battery in the base. The behavior I've observed is it de-charges both batteries until ~80%, after which the clipboard battery stays at ~80% and the base battery de-charges until some threshold. This can also be observed on Windows.

**Comment by jakeday** [comment]
From what I've noticed, this behaves the same way as Windows and it's as designed. I don't think we should change this even if we could.
