### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by oliverwood93** [jakeday/linux-surface#375]
Hi Jake, I installed one of your previous kernels/builds maybe like 2 months ago, how can I go about updating to your new release/update? 

Thanks in advance.

**Comment by dbranham20** [comment]
The easiest way to do this, and the way I did it, is by simply going to the [releases](https://github.com/jakeday/linux-surface/releases) page and downloading/installing each of the .deb files on the latest release! They should just open and install within your software manager
