### ISSUE TITLE
SP2017 IPTS patches breaks wifi randomly 

### ISSUE THREAD

**Issue by tkimmm** [jakeday/linux-surface#379]
Hi jakeday.

Firstly, thank you for the work that you have been doing on this project.

I'm exhibiting very similar issues as andew-ws described https://github.com/jakeday/linux-surface/issues/68

SP2017 running i3 manjaro on 4.18 and tried 4.19 too

I've done several fresh installs trying to troubleshoot. And I suspect the IPTS drivers/patch causing the WLAN to crash and no longer be detected as an available connection, what makes the bug particular nasty is, any attempt to reboot or shutdown results in a hang and requires a subsequent hard reset.

heres a grep output - its fairly long so I've tried to truncate

[ 173.005000] audit: type=1131 audit(1548910224.975:60): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 174.153557] mwifiex_pcie 0000:01:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xfa, act = 0x0
[ 174.153582] mwifiex_pcie 0000:01:00.0: num_data_h2c_failure = 0
[ 174.153584] mwifiex_pcie 0000:01:00.0: num_cmd_h2c_failure = 0
[ 174.153585] mwifiex_pcie 0000:01:00.0: is_cmd_timedout = 1
[ 174.153587] mwifiex_pcie 0000:01:00.0: num_tx_timeout = 0
[ 174.153588] mwifiex_pcie 0000:01:00.0: last_cmd_index = 0
[ 174.153590] mwifiex_pcie 0000:01:00.0: last_cmd_id: fa 00 a4 00 7f 00 16 00 3f 02
[ 174.153592] mwifiex_pcie 0000:01:00.0: last_cmd_act: 00 00 00 00 00 00 00 00 00 00
[ 174.153593] mwifiex_pcie 0000:01:00.0: last_cmd_resp_index = 3
[ 174.153595] mwifiex_pcie 0000:01:00.0: last_cmd_resp_id: 16 80 a4 80 7f 80 16 80 7f 80
[ 174.153596] mwifiex_pcie 0000:01:00.0: last_event_index = 4
[ 174.153598] mwifiex_pcie 0000:01:00.0: last_event: 17 00 2b 00 1c 00 33 00 33 00
[ 174.153599] mwifiex_pcie 0000:01:00.0: data_sent=0 cmd_sent=1
[ 174.153601] mwifiex_pcie 0000:01:00.0: ps_mode=0 ps_state=0
[ 174.153660] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device

at this point I'm considering just giving up on the IPTS

**Comment by tkimmm** [comment]
I've noticed an update to 4.19.18-2 stating "fix touch screen lag and crashing in ipts module".

I think the arch installation instructions are slightly out date https://github.com/dmhacker/arch-linux-surface so I will have an attempt at recreating the configuration sh manually and report back on my results.

**Comment by jakeday** [comment]
@tkimmm I'm not seeing any correlation between ipts and mwifiex, and your log doesn't suggest it either. It's more likely to be how mwifiex handles deep sleep vs ps_mode in the kernel. I'll push another change to adjust this.

**Comment by tkimmm** [comment]
Thanks for the feedback @jakeday, I ended up doing anoter fresh install with 4.18.

And (knock on wood) have yet to see the Wifi die, not entirely sure why and frustrating that I can't reproduce, the only discerning difference from before to now were the recent patch updates before installing the build files. 

I suppose the only lesson learnt was that the compilation instructions for Arch based dist's (the link you provided in your readme.md) no longer works but that's up to dmhacker to update.

Thank you again for your assistance

**Comment by tkimmm** [comment]
Ok, it broke again.

I was doing all my work in a vm so it wasn’t due to changing a system setting. The only feedback I can give is that when working on the Ethernet connection then dropping to wifi seemed to be fine. However working without a previously recognised Ethernet causes the network manager to fail and doesn’t recognise network connections.

Resetting network manager and nm-applet doesn’t fix the issue and as earlier described reboot or shutdown hangs.

**Comment by tkimmm** [comment]
So after googling around and testing I'm coming up to the fourth hour without a wifi drop/crash. All credits to  PJ_Julius in this comment https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1730924/comments/101

I tried a few other solutions (adjusting NetworkManager.conf, soft unblocking/blocking etc)  without result. It seems ASPM doesn't seem to play nice with the wifi card, causing dropping and freezing, coincidentally these issues were reported on SP2017 devices.

Included the shell script posted by Julius as a service and haven't had any issues since, thanks again for the offer of assistance @jakeday and apologies if I sent you down the wrong path.

**Comment by jakeday** [comment]
@tkimmm Can you test the latest 4.19.20-1 kernel without that workaround?

**Comment by tkimmm** [comment]
Sure, have disabled on 4.19.20 and will let you know how it goes
