### ISSUE TITLE
New release 4.19.19-1 breaks wifi after resume on Surface Pro 3

### ISSUE THREAD

**Issue by RussH** [jakeday/linux-surface#380]
The latest release https://github.com/jakeday/linux-surface/releases/tag/4.19.19-1 breaks wi-fi after resume. Wi-fi doesn't come back up. Errors below; 
` 46.557966] PM: hibernation exit
[   47.309447]  sdb: sdb1
[   56.634574] mwifiex_pcie 0000:01:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0x1e, act = 0x0
[   56.634580] mwifiex_pcie 0000:01:00.0: num_data_h2c_failure = 0
[   56.634583] mwifiex_pcie 0000:01:00.0: num_cmd_h2c_failure = 0
[   56.634585] mwifiex_pcie 0000:01:00.0: is_cmd_timedout = 1
[   56.634588] mwifiex_pcie 0000:01:00.0: num_tx_timeout = 0
[   56.634590] mwifiex_pcie 0000:01:00.0: last_cmd_index = 0
[   56.634595] mwifiex_pcie 0000:01:00.0: last_cmd_id: 1e 00 07 01 20 00 07 01 e5 00
[   56.634597] mwifiex_pcie 0000:01:00.0: last_cmd_act: 00 00 00 00 08 00 00 00 01 00
[   56.634600] mwifiex_pcie 0000:01:00.0: last_cmd_resp_index = 4
[   56.634603] mwifiex_pcie 0000:01:00.0: last_cmd_resp_id: 75 80 07 81 20 80 07 81 e5 80
[   56.634606] mwifiex_pcie 0000:01:00.0: last_event_index = 2
[   56.634609] mwifiex_pcie 0000:01:00.0: last_event: 0b 00 0a 00 0a 00 0a 00 0a 00
[   56.634612] mwifiex_pcie 0000:01:00.0: data_sent=0 cmd_sent=1
[   56.634615] mwifiex_pcie 0000:01:00.0: ps_mode=0 ps_state=0
[   56.635392] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.635627] mwifiex_pcie 0000:01:00.0: ===mwifiex driverinfo dump start===
[   56.635635] mwifiex_pcie 0000:01:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[   56.635648] mwifiex_pcie 0000:01:00.0: PCIE register dump start
[   56.635741] mwifiex_pcie 0000:01:00.0: pcie scratch register:
[   56.635752] mwifiex_pcie 0000:01:00.0: reg:0xcf0, value=0x0
               reg:0xcf8, value=0x0
               reg:0xcfc, value=0x0
               
[   56.635755] mwifiex_pcie 0000:01:00.0: PCIE register dump end
[   56.635808] mwifiex_pcie 0000:01:00.0: ===mwifiex driverinfo dump end===
[   56.635812] mwifiex_pcie 0000:01:00.0: == mwifiex firmware dump start ==
[   56.638017] IPv6: ADDRCONF(NETDEV_UP): mlan0: link is not ready
[   56.638078] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.638080] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.638113] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.638114] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.638118] IPv6: ADDRCONF(NETDEV_UP): mlan0: link is not ready
[   56.638121] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.638271] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
[   56.666049] mwifiex_pcie 0000:01:00.0: Fail to pull ctrl_data
[   56.666056] mwifiex_pcie 0000:01:00.0: == mwifiex dump information to /sys/class/devcoredump start
[   56.666131] mwifiex_pcie 0000:01:00.0: == mwifiex dump information to /sys/class/devcoredump end
[   56.666177] mwifiex_pcie 0000:01:00.0: info: shutdown mwifiex...
[   56.667400] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
[   57.862510] mwifiex_pcie 0000:01:00.0: FW CRC error indicated by the helper: len = 0x0011, txlen = 17
[   57.862517] mwifiex_pcie 0000:01:00.0: Invalid parameter in mwifiex_pcie_send_boot_cmd <00000000c9c3a854. len 0>
[   57.862520] mwifiex_pcie 0000:01:00.0: Failed to send firmware download command
[   57.862527] mwifiex_pcie 0000:01:00.0: prog_fw failed ret=0xffffffff
[   57.862530] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device`

**Comment by jakeday** [comment]
@RussH To be clear, this was happening before the 4.19.19-1 release as well right?

**Comment by RussH** [comment]
No just the latest kernel.. I can boot to your previous one and it's fine.

**Comment by jakeday** [comment]
@RussH I meant to mark it as pre-release, which I just did. This is due to the suspend/resume functionality I'm working on for intel_ipts and mwifiex modules. I'm hoping to finish them soon, but you should be able to just restore the old copy of the /lib/systemd/system-sleep/sleep script to get it working again.

**Comment by RussH** [comment]
Sorry! Entirely down to my mistake then!
