### ISSUE TITLE
Can't wake up from suspend using lid or power button

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#381]
I just installed the latest kernel and I notice that lid and power button don't wake mu SB1 from suspend.
Edit: The system can't wake up at all. Even this fails:
```
$ sudo rtcwake -m freeze -s 10
```

I do have the appropriate wakeup files in sysfs and they are enabled.
```
$cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/power/wakeup # lid switch
enabled
$ cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/PNP0C09:00/MSHW0040:00/power/wakeup # buttons
enabled
```

I had working suspend and wakeup in 4.16. I'll do some testing to check which release breaks it.
Edit: suspend seems to be working in 4.18.20-6, so it's a 4.19 issue.

**Comment by jakeday** [comment]
@tmarkov I'm curious, what happens if you use the same latest kernel but go back to the older /lib/systemd/system-sleep/sleep script?

**Comment by tmarkov** [comment]
@jakeday  Indeed, if I remove the ipts modules before suspend, SB wakes up normally. If I don't, it doesn't wake up.

**Comment by jakeday** [comment]
@tmarkov That's perfect, actually. I was pretty sure that's what it was. I'm still working on finishing up the suspend/resume of the ipts module so we can handle this properly. Thanks for testing!

**Comment by jakeday** [comment]
@tmarkov This is fixed with the latest kernel and latest setup.sh script.
