### ISSUE TITLE
Touchscreen not working at all on SB2 (arch)

### ISSUE THREAD

**Issue by AnMaillard** [jakeday/linux-surface#386]
Hi, 
  I have a new SB2 on wich I recently installed arch on dual boot with windows. I installed the kernel but I still can't manage to get the touchscreen detected. I am using Gnome (with wayland), and intel_ipts is listed by lsmod, however xinput --list does not recognize the touchscreen :

```
xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:15                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:15            	id=7	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:15                    	id=8	[slave  keyboard (3)]
```

Am I missing something ? Thanks a lot for your help !

**Comment by jakeday** [comment]
I don't maintain or test the arch packages, so I can't say whether or not they are causing an issue. However, can you let me know what uname -r says, as well as the output of running setup.sh?

**Comment by AnMaillard** [comment]
I actually installed an ubuntu in the end, and here the touchscreen works out of the box with the script ! I juste have one question : when I detach the screen and rotate it, the touchscreen doesn't rotate, basically if I rotate it by 180 degrees, drawing on the bottom of the screen will draw on the top of the screen : is it a known issue ? In any case, thank you so much for having made this !

**Comment by jakeday** [comment]
@AnMaillard You need to install the patched libwacom package (included in this repo) for that to work.

**Comment by chambln** [comment]
I have this problem too on Arch. Surface Pro 2017 model.

    $ uname -r
    4.19.19-1-surface

I compiled the kernel following [dmhacker's repo](https://github.com/dmhacker/arch-linux-surface) and installed with `sudo pacman -U linux-surface-*.tar.xz`. I then tried his pre-compiled version but still it doesn't work.
