### ISSUE TITLE
Surface Book 2: Multi-touch does not work

### ISSUE THREAD

**Issue by navneet92** [jakeday/linux-surface#39]
Hi,

I am using latest kernel 4.14, and the ipts firmware version 102 on "surface book 2, model 1703". But, i couldn't get multitouch to work on it. Even for single touch, i need to enable it manually using the "sudo echo 0 > /sys/kernel/...". when i switched echo to 1 single touch also stopped working.
I have also added udev rules as /etc/udev/rules.d/99-ipts.rules. Also, in the starting, kernel 4.14 was not booting in surface book 2. Then i used the solution from previous thread then it started booting.

Dmesg output: 
[dmes.txt](https://github.com/jakeday/linux-surface/files/1482682/dmes.txt)

**Comment by jakeday** [comment]
The Surface Book 2 uses the v101 ipts firmware. Are you using my updated udev rules?

**Comment by navneet92** [comment]
Sorry..it ws v101 not v102 and i used the latest updated rules today.

**Comment by jakeday** [comment]
@navneet92 Oh ok. So do you have the 13" or 15" model? Can you also get me the output of the below command?

ls /sys/bus/acpi/devices

**Comment by jakeday** [comment]
@navneet92 Once you get me that output I can probably fix it. While you're at it, when single touch mode can you give me the output of this:

sudo dmesg | grep -i ipts

**Comment by navneet92** [comment]
I am using 13'' model. I left my device in the office. I will send you the output next week.

**Comment by jakeday** [comment]
Fixed in latest push. Pay attention to the updated ipts firmware versions.
