### ISSUE TITLE
very slow shutdown

### ISSUE THREAD

**Issue by karthikeyaparunandi** [jakeday/linux-surface#391]
Hi,
Whenever I shutdown Ubuntu 16.04 on my surface book-2, it takes a long time to shut down. Apart from that, the light dims away in about 30 seconds giving an impression that it is actually shut down. However, when I place it in my bag with lid closed, I feel the heat on my back and upon opening the lid, I find that it is not shut down yet. Is there something I can do to fix this problem? Or in other words, is there a way for quick shut down? I am guessing that it is he kernel issue. If so, how can I use the latest kernel with this module? I went through the instructions in readme page, but could not quite understand if it is possible to use our own latest stable kernel with this package. 

Thank you!

**Comment by tmarkov** [comment]
You can press escape during shutdown. This will drop you to terminal that will show what's going on with the shutdown and if something is blocking it. Alternatively, after the reboot you can look at the last messages of the previous boot syslog:
`journalctl --boot=-1`
Or you can post the log here.

**Comment by jakeday** [comment]
This should be fixed in the latest release.
