### ISSUE TITLE
[Surface 3] ACPI Errors after signing 4.19.20-surface-linux-surface Kernel

### ISSUE THREAD

**Issue by Soundwubz** [jakeday/linux-surface#392]
After following all of the instructions in the readme to install the 4.19.20 surface kernel on my Surface 3 (non-pro), I moved onto following the instructions for signing the kernel. Everything worked up until rebooting after updating grub for the new signed kernels. Now I cannot get to grub at all and a ton of ACPI errors are thrown. Please advise. See image below:
![img_1933](https://user-images.githubusercontent.com/18151297/52740880-0c5ade80-2fa2-11e9-9ada-46abe82976ec.JPG)

**Comment by ighorn1** [comment]
Hi I have the same problem I tried to add acpi=off and now I have blank screen, the Ubuntu is not starting

**Comment by kalenpw** [comment]
Having the same issue on my Surface 3. You should still be able to access grub by tapping esc during boot until grub appears then go to advanced options and select a different kernel

**Comment by ighorn1** [comment]
Thank you gor you answer, the jakeday surface kernel is not working on surface 3 non pro

**Comment by RevMadamsPlus** [comment]
This really needs reopening. This is still the case with the latest kernel. There is a workaround posted to enable boot with the latest kernel but still leaves non-pro Suface 3 users with a huge boot delay. Can this be addressed? Everything else except some sound issues seems to be working (ok so cameras like everyone else) .......?

**Comment by Soundwubz** [comment]
> This really needs reopening. This is still the case with the latest kernel. There is a workaround posted to enable boot with the latest kernel but still leaves non-pro Suface 3 users with a huge boot delay. Can this be addressed? Everything else except some sound issues seems to be working (ok so cameras like everyone else) .......?

I had closed the issue thinking that there would not be much support for the non pro Surface 3, but apparently I was wrong lol. By default, installing Ubuntu 18.04, leaves me without a sound output device and no battery indicator. I really want to see the Surface 3 get some decent support for once.

**Comment by RevMadamsPlus** [comment]
There is a solution to the sound issue. Sound is there. This worked for me - install pavucontrol. Open it in terminal. It will say at first that it can't connect to Pulseaudio. Wait a bit..... it will. Maybe reboot a couple of times and try again. After it connects..... go to Settings/Sound and what was blank before should now be populated. What seems to be happening is that Sound defaults to Intel HDMI and not the local Speakers/Headphones. I fiddled with so many files that I can't remember exactly what got it to be the Default.... if you search Issues above for 'Sound' (duh!) you'll find lots of bits of advice re config files. Beleive it or not after much fiddling what 'fixed' the Default for me was logging in and out again of Ubuntu and back into Ubuntu Wayland.... after a few reboots the Speaker icon appeared top right, left of the slider bar (missing before) the Settings/Sound remained populated and I had sound all round.... yay! YMMV but keep trying.

**Comment by RevMadamsPlus** [comment]
Now we just need the ACPI errors fixing...... anyone?

**Comment by Soundwubz** [comment]
I've gotten the sound to work after running pavucontrol, however after reboots and logging out and back in, the sound always breaks again. I haven't been able to find any issues that reference re configuring files. Could I get a link to an issue

**Comment by Soundwubz** [comment]
It seems that the only way to solve the little issues with the Ubuntu, like the audio and battery indicator. There needs to be a workaround for the ACPI errors so that the Surface 3 can boot this kernel.

**Comment by RevMadamsPlus** [comment]
Yes, well, just happen to be here playing about. It does keep breaking..... but hey the sound works! OK so when you reboot and it doesn't work, are you logging into Ubuntu or 'Ubuntu Wayland'? I just booted up - autologin - and no sound. I logged out (just Ubuntu) and logged immediately back in, but to 'Ubuntu Wayland' and hey presto - sound. How are you testing sound? The Speaker Test in Settings/Sound never works. Get an MP3 on your desktop, open it in VLC. In VLC set Tools/Sound to Pulseaudio, then in the File menu (out of Tools now) set Audio Device to Built-In Headphones and Speaker and hey presto - noise! It may crackle for a couple of seconds but then audio will play fine for the rest of your session. Youtube also fine. Try it. I often found the fix 'sticks' after reboot but several programs like SystemBack don't run in Wayland..... so i stick to Ubuntu only.

**Comment by RevMadamsPlus** [comment]
PS my battery indicator works fine...... but I'm booting the latest kernel despite ACPI errors.

**Comment by RevMadamsPlus** [comment]
This is one edit that helped keep sound alive
**sudo gedit /etc/pulse/default.pa**  and put this (or edit existing entry) ate the end of the file, and save;
**set-default-sink output 1** 
I think it help because the HDMI output is entry 0 and so the default.

**Comment by RevMadamsPlus** [comment]
To boot the latest kernel and not be stopped by the ACPI errors do this;
**sudo gedit /etc/default/grub**
and add this or edit existing entry;
**GRUB_CMDLINE_LINUX="i915.enable_guc=0"**
I knew I'd find it somewhere - this may get your battery indicator running!

**Comment by Soundwubz** [comment]
I'll have to test this out later tonight. Been working on this over my lunch break lol. Will report my results tonight.

**Comment by RevMadamsPlus** [comment]
I'm in Spain eating chocolate coated peanuts and drinking whisky in front of a log fire! Going offline now - catch up tomorrow. Good luck!

**Comment by RevMadamsPlus** [comment]
Aaargh - couldn't resist trying one more thing - 
**sudo gedit /etc/pulse/client.conf**
Set the bottom of the file to read like this - NOT THE WHOLE FILE - just from default-sink;

default-sink = 1
; default-source =
; default-server =
; default-dbus-server =
; autospawn = yes
; daemon-binary = /usr/bin/pulseaudio
;extra-arguments = --log-target=syslog
; cookie-file =
; enable-shm = yes
; shm-size-bytes = 0 # setting this 0 will use the system-default, usually 64 MiB
auto-connect-localhost = yes
auto-connect-display = yes

Now I don't need to run pavucontrol frequently..... sound control bar up every time..... yay!
YMMV!

**Comment by ighorn1** [comment]
Hi thanks

> To boot the latest kernel and not be stopped by the ACPI errors do this;
> **sudo gedit /etc/default/grub**
> and add this or edit existing entry;
> **GRUB_CMDLINE_LINUX="i915.enable_guc=0"**
> I knew I'd find it somewhere - this may get your battery indicator running!

This worked fine for me thank you

**Comment by kalenpw** [comment]
Adding i915.enable_guc=0 I can now boot on 4.19.20, but I still don't have a working battery indicator. Any other ideas that might do it?

**Comment by RevMadamsPlus** [comment]
Mmm .... Look guys I'm no Linux programmer - I feed off the skill of the good guys here and am grateful for there amazing input..... but while I'm here......
I assume you have Surface 3 non pro....
Are you running Ubuntu (not Xubuntu, Lubuntu, etc?)
Did you use the setup.sh to download and run the latest kernel?
I said 'no' to each option as it ran......
I did the above fixes to boot it and immediately had battery indicator
Did you try logging into straight Ubuntu or Ubuntu Wayland?
There seem to be some differences in how the new kernel plays with each. Try both.
Beyond that for now we need soemone with more experience than me to chime in...... And to help eliminating the original problem - the boot delaying ACPI errors!

**Comment by kitakar5525** [comment]
- Distribution: Arch Linux

#### sound issue
I'm curious. I have my Surface 3 sound working out-of-the-box on Arch Linux kernel 4.19.23. Maybe PulseAudio config issue or kernel config issue?

- [Arch Linux PulseAudio configs](https://github.com/kitakar5525/note-linux-on-surface-3/tree/master/etc/pulse)
- [Arch Linux kernel config](https://github.com/kitakar5525/arch-kernel-linux-lts419-surface/blob/master/config)

I can use both the internal speaker/headphone output and HDMI sound output.

#### cannot boot issue (i915.enable_guc)

I think `i915.enable_guc=-1` (auto) works for all Surface devices. My SB1 works with IPTS correctly and at the same time my Surface 3 boots correctly with this value.

```diff
diff --git a/drivers/gpu/drm/i915/i915_params.c b/drivers/gpu/drm/i915/i915_params.c
index 80cd47fd8..84415814c 100644
--- a/drivers/gpu/drm/i915/i915_params.c
+++ b/drivers/gpu/drm/i915/i915_params.c
@@ -145,7 +145,7 @@ i915_param_named_unsafe(edp_vswing, int, 0400,
 i915_param_named_unsafe(enable_guc, int, 0400,
     "Enable GuC load for GuC submission and/or HuC load. "
     "Required functionality can be selected using bitmask values. "
-    "(-1=auto, 0=disable, 1=GuC submission [default], 2=HuC load)");
+    "(-1=auto [default], 0=disable, 1=GuC submission, 2=HuC load)");
 
 i915_param_named_unsafe(enable_ipts, int, 0400,
     "Enable IPTS Touchscreen and Pen support (default: 1)");
diff --git a/drivers/gpu/drm/i915/i915_params.h b/drivers/gpu/drm/i915/i915_params.h
index b15f81d55..4ab800c3d 100644
--- a/drivers/gpu/drm/i915/i915_params.h
+++ b/drivers/gpu/drm/i915/i915_params.h
@@ -46,7 +46,7 @@ struct drm_printer;
     param(int, disable_power_well, -1) \
     param(int, enable_ips, 1) \
     param(int, invert_brightness, 0) \
-    param(int, enable_guc, 1) \
+    param(int, enable_guc, -1) \
     param(int, guc_log_level, -1) \
     param(char *, guc_firmware_path, NULL) \
     param(char *, huc_firmware_path, NULL) \
```

#### ACPI related errors

I also see a lot of ACPI related errors, but I don't know how harmful this is. I don't have the boot delay issue.

```
$ dmesg -xHTP -l err
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Needed [Integer/String/Buffer], found [Device] 00000000feac25b6 (20181003/exresop-391)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Needed [Integer/String/Buffer], found [Device] 00000000feac25b6 (20181003/exresop-391)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: AE_AML_OPERAND_TYPE, Could not execute arguments for [KEYS] (Region) (20181003/nsinit-433)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Needed [Integer/String/Buffer], found [Device] 00000000feac25b6 (20181003/exresop-391)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: AE_AML_OPERAND_TYPE, Could not execute arguments for [KEYS] (Region) (20181003/nsinit-433)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: No handler for Region [GPOR] (00000000183b1849) [GeneralPurposeIo] (20181003/evregion-132)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Region GeneralPurposeIo (ID=8) has no handler (20181003/exfldio-265)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Method parse/execution failed \_SB.PCI0.SPI1.NTRG._STA, AE_NOT_EXIST (20181003/psparse-516)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Cannot assign type [Device] to [BufferField] (must be type Int/Str/Buf) (20181003/exstoren-93)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Method parse/execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/psparse-516)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Method execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/uteval-69)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: No handler for Region [GPOR] (00000000183b1849) [GeneralPurposeIo] (20181003/evregion-132)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Region GeneralPurposeIo (ID=8) has no handler (20181003/exfldio-265)
kern  :err   : [Wed Feb 20 21:14:22 2019] ACPI Error: Method parse/execution failed \_SB.PCI0.SPI1.NTRG._STA, AE_NOT_EXIST (20181003/psparse-516)
kern  :err   : [Wed Feb 20 21:14:22 2019] dw_dmac INTL9C60:00: Missing DT data
kern  :err   : [Wed Feb 20 21:14:22 2019] dw_dmac INTL9C60:01: Missing DT data
kern  :err   : [Wed Feb 20 21:14:23 2019] ACPI Error: Cannot assign type [Device] to [BufferField] (must be type Int/Str/Buf) (20181003/exstoren-93)
kern  :err   : [Wed Feb 20 21:14:23 2019] ACPI Error: Method parse/execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/psparse-516)
kern  :err   : [Wed Feb 20 21:14:23 2019] ACPI Error: Method execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/uteval-69)
kern  :err   : [Wed Feb 20 21:14:26 2019] ACPI Error: Cannot assign type [Device] to [BufferField] (must be type Int/Str/Buf) (20181003/exstoren-93)
kern  :err   : [Wed Feb 20 21:14:26 2019] ACPI Error: Method parse/execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/psparse-516)
kern  :err   : [Wed Feb 20 21:14:26 2019] ACPI Error: Method execution failed \_SB.PCI0.UOTG._CRS, AE_AML_OPERAND_TYPE (20181003/uteval-69)
kern  :err   : [Wed Feb 20 21:14:26 2019] rt5640 i2c-10EC5640:00: Device with ID register 0x6308 is not rt5640/39
kern  :err   : [Wed Feb 20 21:14:28 2019] [drm:vlv_dsi_init [i915]] *ERROR* Failed to own gpio for panel control
kern  :err   : [Wed Feb 20 21:14:30 2019] usb 1-6: device descriptor read/64, error -110
kern  :err   : [Wed Feb 20 21:14:45 2019] usb 1-6: device descriptor read/64, error -110
```

#### Touchpanel input crashes after suspend

Touchpanel input crashes after suspend. I'm not sure this is related to ACPI errors. Does someone have this issue, too?

dmesg says:

```
$ dmesg -xHTw
kern  :err   : [Wed Feb 20 21:33:15 2019] Surface3-spi spi-MSHW0037:00: SPI transfer timed out
```

**Comment by Soundwubz** [comment]
> To boot the latest kernel and not be stopped by the ACPI errors do this;
> **sudo gedit /etc/default/grub**
> and add this or edit existing entry;
> **GRUB_CMDLINE_LINUX="i915.enable_guc=0"**
> I knew I'd find it somewhere - this may get your battery indicator running!

After trying this out and installing the surface-linux kernel, I was able to boot to the kernel with no hitches. Sound and the battery indicator work out of the box with the surface-linux kernel. So, although there is no "official support" from this kernel, I've encountered no issues so far. Since this seems to solve the booting issue, I'm going to close this issue. Thanks very much for the help!
