### ISSUE TITLE
Surface Pro 6 Touch not working MINT 19.1 and UBUNTU 18.04 USB Boot

### ISSUE THREAD

**Issue by RDRichardson** [jakeday/linux-surface#393]
I have tried to boot from USB for both UBUNTU 18.04 and MINT 19.1.  The tablet boots, but none of the touch functions work.

**Comment by jakeday** [comment]
@RDRichardson You are installing this kernel and running the setup.sh script after installing your distro, right? What does "uname -r" return?

**Comment by RDRichardson** [comment]
Jake,

I am entirely new to loading Linux unto a dual-boot device, such as Surface Pro 6.  My application software currently runs on MINT 17 a PC.  I want to port it to a tablet running one of the latest versions:  either MINT 19.1 or UBUNTU 18.04.  I targeted the Surface Pro 6 based on my studies of what people say have successfully run Linux.  Initially I want to test with a USB boot to verify everything works and select the exact OS.  If everything works I would want to migrate to a dual-boot platform without the USB device.  In both cases the OS booted successfully and the touch, which is my only I/O right now, did not work.  I installed the ”*.iso” images from a website download and converted it to a USB bootable image with recommended applications (Rufus/Etcher).

I did not install the kernel.  I am not sure how to do that on the Surface Pro 6 Windows 10 platform.  I am also not familiar with the setup.sh script.  I will go out to the internet and try to figure out how to do that, but any guidance you can give will be much appreciated.

Thanks,

Randy

**Comment by tmarkov** [comment]
The official USB doesn't have touch, and if you installed it, you won't have touch out of the box, and the wifi will fail frequently, necessitating restart to use it again. To fix those you'll need to install the custom kernel and firmware from this repo. But right now you can't just test, you'll need to take a leap of faith, install everything, and then find out if the system is good enough for you.

**Comment by jakeday** [comment]
@RDRichardson As mentioned, the live linux distros do not ship with this custom kernel. You'll need to install the distro then install this kernel for it to work.
