### ISSUE TITLE
surface3-power: Newer version available

### ISSUE THREAD

**Issue by kitakar5525** [jakeday/linux-surface#397]
Hi! Firstly, thank you for supporting even Surface 3.

There is an updated version of battery status reading module for Surface 3 available. I tested this module with all the other patches in your repository and it is working with no problem on 4.19.

- [[v3] platform/x86: surface3_power: MSHW0011 rev-eng implementation - Patchwork](https://patchwork.kernel.org/patch/10584079/)

**Comment by jakeday** [comment]
Updated, thank you!
