### ISSUE TITLE
Suspend suddenly stopped working (it now wakes up imemdiately)

### ISSUE THREAD

**Issue by tmarkov** [jakeday/linux-surface#399]
I had suspend working on my SB(1) perfectly until yesterday. Suddenly, after a reboot today it stopped working. I have done no changes in configuration, and installed no new software. However, now if I try to suspend my SB, it wakes up immediately after suspend and the network is down (before, there was no problem with the network after wakeup). This prompted me to update with the latest patches, but that didn't change anything.

[journal.txt](https://github.com/jakeday/linux-surface/files/2886655/journal.txt)

EDIT: At roughly the same time, my Wi-Fi performance degraded, see https://github.com/jakeday/linux-surface/issues/352#issuecomment-465685974. It may be related, or it may be just a coincidence (Wi-Fi performance wasn't very stable before, but it became noticeably less so).

**Comment by tmarkov** [comment]
Some more debug details:

Here's an error I get when I try to suspend attempt via /sys/power/state directly
```
root@todor-surface:/home/todor# echo freeze > /sys/power/state
bash: echo: write error: Device or resource busy
```

After this the journal had these lines:

```
Feb 21 18:52:10 todor-surface kernel: PM: Device usb2 failed to suspend async: error -16
Feb 21 18:52:10 todor-surface kernel: PM: Some devices failed to suspend, or early wake event detected
```

I notice they were not present in the journal I uploaded above. I somehow doubt I have suddenly encountered two separate issues that cause the exact same behavior, but I sometimes see these lines, and sometimes - not.

[journal.txt](https://github.com/jakeday/linux-surface/files/2890294/journal.txt)

**Comment by kitakar5525** [comment]
What is the result of `sudo tail $(sudo find /sys -name wakeup) | grep -n1 enabled` ?
I disabled all the wakeup sources except Power Button.

```bash
$ sudo tail $(sudo find /sys -name wakeup) | grep -n1 enabled
tail: error reading '/sys/kernel/debug/tracing/events/ftrace/wakeup': Is a directory
216-==> /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/PNP0C09:00/MSHW0040:00/power/wakeup <==
217:enabled
```

**Comment by tmarkov** [comment]
@kitakar5525 Disabling wakeup sources seems fix this for now. I'm still concerned about the fact that I did NOT change any configuration when this started up. I know I my wakeup sources were enabled before and didn't cause me problems. So somehow, the SB started behaving differently on its own.
