### ISSUE TITLE
Sleep doesnt wake up

### ISSUE THREAD

**Issue by cydia2020** [jakeday/linux-surface#4]
G'day there

Sleep doesn't seems to work on a Surface Book with 16.04LTS

Others seems fantastic except the camera are not supported yet

Good job getting the kernel work for Surface devices, it's always been a pain to install Linux on surface until this point.

**Comment by jakeday** [comment]
Did you make sure to run the additional steps in the README?

**Comment by cydia2020** [comment]
Yes, I did run them, but closing the lead and open it after a few minutes only opens a black screen

**Comment by cydia2020** [comment]
Suspend and hibernate does not wake up from black display
