### ISSUE TITLE
Surface Pro 2017: Volume buttons not working on boot

### ISSUE THREAD

**Issue by Frans-Willem** [jakeday/linux-surface#401]
Hi,

I'm running ArchLinux with Jake's 4.19.23 kernel, and the volume buttons are not working on boot.
If I do a modprobe -r soc_button_array; modprobe soc_button_array they start working fine.
Weirdly on boot, lsmod does show soc_button_array, but the /sys/devices/platform/MSHW0040:00 does not have this driver attached. After doing the unload/reload, it gets taken up by soc_button_array properly.
I've also ensured my initramfs contains the same modules as Jake defined for Ubuntu.

Is there anything else I can check? I suspect it might be a module loading order issue, but am unsure on how to get the kernel to output load order...

**Comment by Frans-Willem** [comment]
I suspect the soc_button_array module may be loading before the driver for the GPIO pins. After some digging, I believe the GPIO driver is pinctrl_sunrisepoint. Adding pinctrl_sunrisepoint to my initramfs solved my problem, for now.

Is there a nicer way to instruct my kernel that pinctrl_sunrisepoint is a dependency for soc_button_array ? (or maybe soc_button_array depends on gpio_keys, and gpio_keys should depend on a GPIO driver to be loaded?)

**Comment by Frans-Willem** [comment]
An alternative to forcing pinctrl in the initramfs, is to create a file name ```/etc/modprobe.d/button-array.conf``` with the following line:
```
softdep soc_button_array pre: pinctrl_sunrisepoint
```

Can also confirm that to be working for me :)

**Comment by pijulius** [comment]
Hi Guys,

I would just like to add that indeed can confirm this on Surface Pro 2017 with Fedora 29 and for now my fix was to just simply reload the soc_button_array on a fresh start with an init script but would be good to have a fix for it instead.

Regards,
Julius

**Comment by Programming4life** [comment]
@pijulius How did you get the patches and everything to work under F29? I've tried but keep getting all kinds of errors.

**Comment by pijulius** [comment]
Hi Programming4life,

These would be the basic steps I do to get everything up and running on Fedora 29
IMPORTANT: steps only for Surface Pro 2017!

# Firmware and System changes
wget https://github.com/jakeday/linux-surface/archive/master.zip
unzip master.zip
mkdir -p /lib/firmware/intel/ipts
unzip -o linux-surface-master/firmware/ipts_firmware_v102.zip -d /lib/firmware/intel/ipts/
unzip -o linux-surface-master/firmware/i915_firmware_kbl.zip -d /lib/firmware/i915/
unzip -o linux-surface-master/firmware/mrvl_firmware.zip -d /lib/firmware/mrvl/
unzip -o linux-surface-master/firmware/mwlwifi_firmware.zip -d /lib/firmware/mwlwifi/
cp -Rb linux-surface-master/root/etc/* /etc/
cp -Rb linux-surface-master/root/lib/* /lib/
chmod a+x /lib/systemd/system-sleep/sleep
ln -sfb /usr/lib/systemd/system/hibernate.target /etc/systemd/system/suspend.target
ln -sfb /usr/lib/systemd/system/systemd-hibernate.service /etc/systemd/system/systemd-suspend.service

# Kernel
wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.21.tar.xz
tar -zxf linux-4.19.21.tar.xz
cd linux-4.19.21
for i in ../linux-surface-master/patches/4.19/*.patch; do patch -p1 < $i; done
cp ../linux-surface-master/configs/4.19/config .config
make oldconfig
make -j 4 bzImage
make -j 4 modules
make -j 4 modules_install
make -j 4 install

That would be all.
Regards,
Julius

**Comment by qzed** [comment]
I'm not sure there's a better solution that adding the dependency in `/etc/modprobe.d`. As far as I know, there is no possibility to set dependencies via `Kconfig` on "any of x modules" or something like this.

Maybe it's possible to defer the driver probe somehow. It could fail [here](https://github.com/torvalds/linux/blob/master/drivers/input/misc/soc_button_array.c#L331-L335), if so I guess we could defer the probe there. Is there anything in the logs when you enable debug output?

**Comment by aleksfadini** [comment]
> softdep soc_button_array pre: pinctrl_sunrisepoint

I can confirm same situation and on arch, Surface Pro 6

**Comment by qzed** [comment]
#478 should fix this. It'd be awesome if you guys could validate this once it lands, as this is currently the last issue regarding the button patch (that I'm aware of). If it works I'll try to get it upstream next.

**Comment by pijulius** [comment]
Hi @qzed,

Can confirm this works now just perfectly fine, set up Fedora 30 with Kernel 5.0.13 and everything build and running just perfectly right from the start.

Thanks guys for all the hard work and for keeping this updated!

Regards,
Julius

**Comment by qzed** [comment]
Awesome, thanks! Will try to get this upstream in the near future (can't promise any timeline at the moment though).
