### ISSUE TITLE
Surface Go; on screen rotation, no stylus rotation

### ISSUE THREAD

**Issue by losbaeros** [jakeday/linux-surface#407]
Hi,

first of all I have to really appreciate your work; I really enjoy running ubuntu on the surface go.
Running it on the latest jakeday kernel.

What I can not get to work - even though there is a similar issue posted for the surface book here - that when I rotate the screen from landscape to portrait, the stylus orientation is not rotated. It stays the same. I read this could be fixed through installing libwacom_0.29-1-surface_amd64.deb but this was not doing it, on the surface go at least.

Any ideas?

Thanks
Chris

**Comment by qzed** [comment]
Probably the same issue as in #415, let's try and figure this out there.
