### ISSUE TITLE
Undo replace suspend with hibernate without rebuilding kernel

### ISSUE THREAD

**Issue by tejasvi** [jakeday/linux-surface#419]
Hibernate is not working in my installation. It shuts down instead. On looking up, I guess there is some issue with swap or Ubuntu 18. Since there is no fix in sight I would be content with sleep instead of loosing all my work when I accidentally close the type cover.

**Comment by tmarkov** [comment]
The replacement isn't done on kernel level, it's just a configuration. It's these two commands:

`ln -sfb /lib/systemd/system/hibernate.target /etc/systemd/system/suspend.target && sudo ln -sfb /lib/systemd/system/systemd-hibernate.service /etc/systemd/system/systemd-suspend.service`

It backs up the files /lib/systemd/system/hibernate.target and /lib/systemd/system/systemd-hibernate.service and replaces them with symlinks to the files handling suspend. You just need to restore the original files.
