### ISSUE TITLE
Specify status of DisplayPort

### ISSUE THREAD

**Issue by saveriomiroddi** [jakeday/linux-surface#42]
I don't have this kernel installed, so I can't test it, but I'm very interested, in case it was supported.

Note: I can't unassign myself from the assignees list.

**Comment by jakeday** [comment]
It's untested as far as I know. I don't have a dsiplayport adapter to test with either, unfortunately. I'll make a note of it though.

**Comment by andreweskild** [comment]
Can confirm that displayport works perfectly here

**Comment by saveriomiroddi** [comment]
> Can confirm that displayport works perfectly here

@andreweskild wow, this is great. which machine do you have exactly?

**Comment by andreweskild** [comment]
I have the Surface Pro 2017 i5

**Comment by casainho** [comment]
My displayport works well but sometimes, if I disconnect, I just get a black screen but I can see the mouse pointer... maybe this can be an issue of Ubuntu 17.10.
Running on SP4.
