### ISSUE TITLE
Sound doesn't work with model=generic in Surface Book 2 with Linux 4.19.27 (Arch Linux)

### ISSUE THREAD

**Issue by hjr265** [jakeday/linux-surface#426]
While waiting for dmhacker to release the kernel packages for Arch Linux, I thought I would give this a shot and do build this myself using dmhacker's script.

Once the kernel was built I moved it to my Surface Book 2, installed them, added the two new files to `/etc/modprobe.d/`.

However, stuff related to sound was super weird until I changed the contents of `/etc/modprobe.d/snd-hda-intel.conf` to:

```
options snd-hda-intel single_cmd=1
options snd-hda-intel probe_mask=1
options snd-hda-intel model=basic
```

So where is what I experienced before making the change:

- On first boot after upgrade, sound devices appeared under Gnome's sound settings.
- But there was no sound coming through the speakers at all.
- I checked `dmesg | grep 'snd'` and saw some errors along the lines of `azx_get_response timeout, switching to polling mode: last cmd=...` and `azx_get_response timeout, switching to single_cmd mode: last cmd=...`.
- After a reboot, Gnome kept showing this "Dummy Output" device only under sound settings.
- `dmesg` had this error about "no codecs found"
- I restarted to Windows and saw that sound was broken there as well.

After making the changes above and turning off/on the "On-board Audio" device from the firmware interface, and it seems to be working now on Linux. And, then on Windows, I had to remove and rescan devices to get sound working.

I am sorry I couldn't keep the logs and actual outputs of dmesg, but while Gnome showed "Dummy Output", lspci and hwinfo still detected the audio device:

```
lspci -v

00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21) (prog-if 80)
	Subsystem: Intel Corporation Sunrise Point-LP HD Audio
	Flags: bus master, fast devsel, latency 64, IRQ 137
	Memory at d4738000 (64-bit, non-prefetchable) [size=16K]
	Memory at d4720000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [50] Power Management version 3
	Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel, snd_soc_skl
```

```
hwinfo --sound

19: PCI 1f.3: 0403 Audio device                                 
  [Created at pci.382]
  Unique ID: nS1_.W1Z4e5RiN9D
  SysFS ID: /devices/pci0000:00/0000:00:1f.3
  SysFS BusID: 0000:00:1f.3
  Hardware Class: sound
  Model: "Intel Audio device"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x9d71 
  SubVendor: pci 0x8086 "Intel Corporation"
  SubDevice: pci 0x7270 
  Revision: 0x21
  Driver: "snd_hda_intel"
  Driver Modules: "snd_hda_intel"
  Memory Range: 0xd4738000-0xd473bfff (rw,non-prefetchable)
  Memory Range: 0xd4720000-0xd472ffff (rw,non-prefetchable)
  IRQ: 137 (no events)
  Module Alias: "pci:v00008086d00009D71sv00008086sd00007270bc04sc03i80"
  Driver Info #0:
    Driver Status: snd_hda_intel is active
    Driver Activation Cmd: "modprobe snd_hda_intel"
  Driver Info #1:
    Driver Status: snd_soc_skl is active
    Driver Activation Cmd: "modprobe snd_soc_skl"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
```

**Comment by zatay** [comment]
I meet this problem too,in surface 6,with dmhacker's pre-built kernel.

**Comment by Aargonian** [comment]
I have encountered a sound issue with the current kernel as well, though again from dmhacker. The sound for me shows up in Gnome as a "headphone" device, for some reason, but no actual sound is played. If I attempt to use pavucontrol to manually switch to the onboard audio, it says the speakers are "unavailable".

Switching the on-board audio off in the boot settings, booting into Arch, then rebooting and switching them back on allows the sound to work, but only after the initial boot. If I reboot again, the sound goes back to being represented as headphones, and I get no available speakers again. It's also notable that, when the sound did work, the volume did not. Changing the volume level (aside from muting) had no effect on how loud the sound was, and everything was fairly quiet (like normally 20%ish?), unless I enabled overamplification, which almost allowed me to reach normal sound levels.

After trying the fix above, I can confirm that the issue appears resolved for me.

**Comment by boke0** [comment]
I have same issue in Surface Pro 6, with dmhacker's pre-build kernel, and I tried hjr265's solution, but it still doesn't work and pavucontrol doesn't show sound devices.

**Comment by hjr265** [comment]
@boke0 What do you see when you run `dmesg | grep 'snd'`?

**Comment by boke0** [comment]
When I rebooted several times, sound device was loaded correctly. Maybe rescanning wasn't executed when I rebooted. Thanks!

**Comment by minrui-hust** [comment]
I got the same situation with @hjr265 with model surface pro6， after modifying “etc/modprobe.d/snd-hda-intel.conf” to the suggested one and a series rebooting between windows and ubuntu， the sound went to work。Thanks to @hjr265 。
However， I still wondering， what happened to my audio devices？

**Comment by deb75** [comment]
Hi,

I face the same issue with my surface book 2 (13").

I tried the above changes, switched from linux to windows and back (dual boot), disabled and reenabled it in the bios. I still get no sound and these log messages at boot : 
```
[   10.141452] snd_hda_intel 0000:00:1f.3: CORB reset timeout#1, CORBRP = 0
[   10.142664] snd_hda_intel 0000:00:1f.3: no codecs found!
```
and there are no sound cards, however lspci still shows an audio device : 
```
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
```

More disturbing is that does not work also on windows, it says no audio peripherical !

I wonder how an upgrade in linux could apparently damage windows (?)

**Comment by fxmy** [comment]
```bash
fxmy@Surface2  ~  cat /etc/modprobe.d/snd-hda-intel.conf
#options snd-hda-intel model=generic
options snd-hda-intel single_cmd=1
options snd-hda-intel probe_mask=1
options snd-hda-intel model=basic
```
This really helps on my surface book 2. Before applying this fix there are 3 problems:
1. only left speaker works.
2. volume adjust has no effect.
3. sound still comes out through speaker when headphone is plugged-in.

And now it's all gone, bravo!

**Comment by zatay** [comment]
I did as what @hjr265 said and my sound came back! I just change the code and power off my surface 6 and boot again(Windows will scan your hardware and fix the problem,it also work in my Linux)

**Comment by hjr265** [comment]
@deb75 It's very odd, but you might need to reboot a few times between Linux and Windows to eventually get it fixed.

I have a feeling the probing logic messes up the state of the hardware somehow and a few restarts and toggling it on/off from the firmware interface gets it working again.

The change to the `snd-hda-intel.conf` I shared above just stops this from happening again (and of course gets audio working). 

So steps that you can follow:

- Update the `snd-hda-intel.conf` file
- Restart to firmware interface
- Turn off on-board audio
- Restart to Windows
- Restart back to firmware interface
- Turn on on-board audio
- Restart to Linux

I know this doesn't sound like science, but this was roughly what I did - in a state of panic of course - and then saw that it worked.

But, the repeated restarts definitely helped. Because once I got it fixed for the first time, I tried to break it again to see if this fix worked consistently, and saw that I had to restart a few times before this worked.

I hope it helps.

**Comment by deb75** [comment]
@hjr265 following your steps made it work again in both windows and linux. Thanks a lot ! This is also the kind of bugs that throws me into a panic : a bug that occurs on both linux and windows is usually the sign of a hardware defect.

**Comment by jakeday** [comment]
Fixed.
