### ISSUE TITLE
Surface Go: Stylus acts as eraser if tilted (X11)

### ISSUE THREAD

**Issue by ShapeShifter499** [jakeday/linux-surface#429]
I just got my Surface Go (4GB RAM - 64GB storage) in the mail a couple of days ago and promptly installed Antergos (Arch Linux based).

On the drivers and kernel provided by Arch Linux with the proper xorg configuration file there is a issue with stylus tilt. If you tilt the stylus too far over it triggers the eraser function and I don't know why. 

Currently compiling your kernel patches with the helper script from https://github.com/dmhacker/arch-linux-surface  So I'll report back if I see the same issue after installing your kernel patches. 

My current xorg configuration I'm using for the Surface Go.
```
Section "InputClass"   
        Identifier "SurfaceGo Touch"   
        MatchProduct "ELAN9038:00 04F3:261A"   
        MatchDevicePath "/dev/input/event*"   
        Driver "wacom"   
        Option "Gesture" "off"   
EndSection  
```

**Comment by ShapeShifter499** [comment]
Same issue occurs with your kernel installed.

**Comment by losbaeros** [comment]
Same here running Ubuntu 18.10 on the Surface Go. At first I thought it kind of changes randomly between writing/drawing and eraser tip. But I think it might be the same here that it just changes too early when tilted.

I wonder if there is an option in the xorg configuration/xsetwacom to apply settings on how tilting of the pen is detected and when it switches to eraser. Anybody?

**Comment by ShapeShifter499** [comment]
I tried making use of the libwacom changes as mentioned here https://github.com/qzed/libwacom-surface.  Didn't change anything.

**Comment by ShapeShifter499** [comment]
I'm convinced that this is related to my other tablet. I have a cheaper tablet called a Nuvision Solo 10 Duo that supports the same pen as the Microsoft Surface line. 

Related to https://github.com/linuxwacom/libwacom/issues/70

**Comment by qzed** [comment]
Can you run `sudo evtest` (select the non-touchscreen/non-keyboard IPTS device, if you've got the right one you should see a flood of events when you get near the screen with the stylus) and check if there is any `BTN_TOOL_RUBBER` in the output when you tilt the stylus?

**Comment by ShapeShifter499** [comment]
@qzed I dumped a bunch of logs from my Surface Go to https://github.com/linuxwacom/libwacom/issues/75

#### Mainline Kernel + Mainline libwacom drivers

```sudo evtest``` log
[pen_writing.log](https://github.com/jakeday/linux-surface/files/2974543/pen_writing.log)

#### Mainline kernel + libwacom patches from @qzed 

```sudo evtest``` log
[pen_writing.log](https://github.com/jakeday/linux-surface/files/2974544/pen_writing.log)

#### @jakeday kernel patches + mainline libwacom drivers

```sudo evtest``` log
[pen_writing.log](https://github.com/jakeday/linux-surface/files/2974547/pen_writing.log)

#### @jakeday kernel patches + libwacom patches from @qzed 

```sudo evtest``` log
[pen_writing.log](https://github.com/jakeday/linux-surface/files/2974549/pen_writing.log)

**Comment by qzed** [comment]
Okay, I can't see anything odd in the logs, so the driver itself should be working correctly (I assume the problem occurs in the logs you posted?). No idea what could cause this... In what programs do you get this problem?

**Comment by ShapeShifter499** [comment]
@qzed I'm not seeing BTN_TOOL_RUBBER 

BUT I'm seeing a lot of BTN_TOUCH, I wonder if this is causing issues.

**Comment by ShapeShifter499** [comment]
@qzed I see this issue in Xournal, Xournal++, and Stylus Labs Write (http://www.styluslabs.com/)

**Comment by qzed** [comment]
@ShapeShifter499 `BTN_TOUCH` means that the tip is touching, `BTN_TOOL_...` indicates which tip (normal or eraser) is in use.

Hmm okay, Xournal and Xournal++ are GTK based apps. Stylus Labs Write, as far as I know, uses QT. Based on that I doubt that this is some weird quirk of a UI framework, so it has to be somewhere in-between.

**Comment by ShapeShifter499** [comment]
@qzed if I remove the xorg configuration (as posted in the log dump) the eraser side doesn't work at all. The pen and pen sensitivity does work though.

**Comment by jakeday** [comment]
@ShapeShifter499 Did you try with the updated patches to libwacom in addition to the xorg config? The older scripts (and I believe @qzed 's) are missing the references/ids for the Surface Go. They are included in my package. It looks like everything is setup right and the config is there, it's just missing the references (I believe, not really an expert on llibwacom!)

**Comment by qzed** [comment]
@jakeday Fixed that in my last update a few days ago :-)

**Comment by qzed** [comment]
@ShapeShifter499 So the original problem does not appear if you don't use the xorg config? Have you tried to identify which option specifically causes this?

**Comment by ShapeShifter499** [comment]
@qzed if I don't use any xorg configuration, the pen works but I can't erase anything by flipping the pen to the eraser side, and the side button doesn't appear to work. 

I could care less if the side button works though. It's much to hard for me to click in a normal fashion while holding the pen to write. I rather flip the pen to erase than use the side button for anything. 

Should I try some other driver setting? Or should I try omitting the driver line altogether?  

Changing the "gesture" line with the driver line set didn't seem to affect anything.

**Comment by qzed** [comment]
@ShapeShifter499 Can you try without the `Driver` and `Gesture` lines? I'm just wondering where the issue comes from. Based on your logs I'd say the events are reaching the kernel correctly (so the subsystem drivers are fine). If it were an application or UI-framework problem it'd work in other applications, which it doesn't. So it has to be something in-between the UI-framework and kernel, maybe the x-server... problem is, I'm not sure what else goes on between there. I'm hoping the libwacom guys know more about this.

**Comment by qzed** [comment]
Also weird is that it has to be something specific to the Surface Go, yet the problem seems to originate from a somewhat higher abstraction layer that shouldn't even care about specific devices. Anything above the input-driver layer should be fairly device-independent and only detect the eraser via the `BTN_TOOL_RUBBER` flag.

**Comment by ShapeShifter499** [comment]
@qzed If I remove the two lines "Gesture" and "Driver", the eraser stops working as an eraser. It just creates lines. Just like if I removed the xorg configuration altogether.

I don't think it's Surface Go specific. I have another tablet that supports the Surface Pens, a Nuvision Solo 10 Draw. I mentioned it earlier up this thread. It has the same eraser issue.

**Comment by qzed** [comment]
> I remove the two lines "Gesture" and "Driver", the eraser stops working as an eraser.

That's actually what I expected, just wanted to make sure. The tilt issue should then be a problem in the x-input wacom driver, but I'd kind of like to know why the eraser doesn't work without a config. On the SB2 I don't need any (just activate the eraser-tip setting in Xournal) and I haven't spotted any difference in the input logs.

**Comment by ShapeShifter499** [comment]
@qzed you're saying your logs look similar to mine?    Can you check what hid-tools record gives? Tool from here: https://gitlab.freedesktop.org/libevdev/hid-tools

**Comment by qzed** [comment]
Only had a look at evtest until now, hid-recorder shows something I've missed before: Sometimes, your tilt value gets negative, while mine is always positive. This could explain the tilt-issue. Still doesn't explain why the eraser isn't working without a config file, though.

Here are the logs:
[pen.log](https://github.com/jakeday/linux-surface/files/2982754/pen.log)
[eraser.log](https://github.com/jakeday/linux-surface/files/2982757/eraser.log)

**Comment by ShapeShifter499** [comment]
I uploaded a video I made demonstrating the issue I'm experiencing. https://www.youtube.com/watch?v=eiEjowBf12c

Posted some more logs to the libwacom issue page.

**Comment by ShapeShifter499** [comment]
@qzed So with the help of the Linux Wacom team, it's been narrowed down to a X11/Xorg issue.   The problem no longer occurs when running Wayland.

**Comment by qzed** [comment]
Okay, makes sense given your logs.

**Comment by ShapeShifter499** [comment]
@qzed @jakeday Any more ideas as to where the fault might be in X11?

**Comment by qzed** [comment]
@ShapeShifter499 Nope, sorry. My knowledge about that is pretty limited.

**Comment by ShapeShifter499** [comment]
Update: Thanks to @Baldurius and @jigpu the issue has been narrowed down to a specific issue with the way the code handles "ABS_MISC" data. https://github.com/linuxwacom/xf86-input-wacom/issues/52#issuecomment-483368933

Still far from a proper fix. If anyone following this knows how to help, it would be appreciated.

**Comment by ShapeShifter499** [comment]
Anyone following this, please test the following patch @jigpu posted at https://github.com/linuxwacom/xf86-input-wacom/issues/52#issuecomment-497164924    Appears to fix the issue. Then please post your results there so the developers know to add it to mainline.

**Comment by anuyts** [comment]
That patch is no longer available from the link.

**Comment by ShapeShifter499** [comment]
> That patch is no longer available from the link. I think I'm having this issue with Wacom intuos and Styluslabs' Write.

@anuyts have you submitted a issue ticket to the linuxwacom team? https://github.com/linuxwacom    Since the Wacom intuos is not a Surface Go the code involved could be entirely different.  

I'm going to close this issue as the original issue is now been fixed.  I no longer experience this issue at the time of writing on a fully up to date Arch Linux install with Gnome and Wayland
