### ISSUE TITLE
Specify apt behavior on `linux-firmware` package upgrade

### ISSUE THREAD

**Issue by saveriomiroddi** [jakeday/linux-surface#43]
The guide suggests to overwrite the Marvell chip firmware files.

While correct, I suspect there is a problem with this when apt will find an update of the `linux-firmware` package (that includes those files (`dpkg -S /lib/firmware/mrvl/*.bin`)); likely, apt will find that there is a conflict, prompting the user with the choice of what to do.

I think it's worth confirming if this is the case, and documenting it, since it could be puzzling (and also, possibly inadvertly cause files overwriting).

**Comment by saveriomiroddi** [comment]
Tested this, and confirmed that while there is no prompt, there is actually an overwriting problem.

**Comment by jakeday** [comment]
Either way, the user would have to notice the issue. As such, Id rather they pull the latest from the git repo and install. Hopefully the latest firmwares get added to linux-firmware soon and this becomes a non-issue.
