### ISSUE TITLE
No Multitouch on Surface Book 2 (13'') with newest Version 5.0.1

### ISSUE THREAD

**Issue by sokolowistan96** [jakeday/linux-surface#432]
Hello, first thank you very much for the great work you've put in here, its very much appreciated :-)
So, I have installed your kernel on my Surface book 2 (13'', but the high-end one). I had to sign the kernel, which was easy thanks to your tutorial and everything is working fine now, except for one issue:
I don't seem to have multitouch. 
When I try to scroll a page in the browser with my finger, it will just select stuff instead of scrolling. It seems to me, that this is because of multitouch not working, right?
Is there some known solution to this problem? Because judging from what i have read here, it should be working without further settings.

**Comment by qzed** [comment]
This may be a software issue. If you're using firefox, you may want to have a look at [this](https://askubuntu.com/questions/978226/how-to-make-touch-screen-scrolling-work-in-firefox-quantum?rq=1).

Also, to check that multitouch works, you can run `sudo evtest` and select the touchscreen device. Multiple `ABS_MT_SLOT` entries should appear if you touch the screen with one corresponding `value` for each finger.

**Comment by sokolowistan96** [comment]
Thank you for your answer, it works in Google Chrome indeed!
