### ISSUE TITLE
SB2 - NVIDIA driver not being loaded after installing jakeday kernel on Ubuntu

### ISSUE THREAD

**Issue by jtcotton63** [jakeday/linux-surface#435]
Hello jakeday and crew,

First of all, thanks a ton for all the awesome work you all have put into this repo! It really has made a spectacular impact for linux gurus all around the world :)

I recently discovered an issue where the nvidia driver wasn't being loaded on the latest editions of Ubuntu _when the driver wasn't loaded before the jakeday kernel was installed_. The jakeday kernel doesn't seem to install those drivers correctly.

**Setup**
I have a Surface Book 2 with the following configuration:

* i7 processor
* 16GB RAM
* 1TB NVME SSD
* Two graphics cards:
** Intel (idk the model)
** NVIDIA GeForce GTX 1060 (Mobile)
* Secure boot is disabled

**First attempt - Linux Mint 19.1 - driver failed to load**
I attempted to dual boot LM19.1, which is based on Ubuntu 18.04. These are the setups steps I went through:

* I booted into the LM19.1 live environment from a USB
* I used the graphical installer to install LM19.1 with the following configuration:
** I created a 1GB ext4 partition as the mount point for /boot
** I created a 200GB encrypted volume as the mount point for /
* I rebooted the machine into LM19.1
* I cloned the jakeday/linux-surface repo
* I ran the setup script to download and install the latest kernel (which happens to be 5.0)
* The script exited successfully, so I rebooted.
* Upon reboot, the functionality provided by the jakeday kernel appeared to be working (touch interaction, battery icon, fans were a lot lower, tablet could be removed from base, etc).
* I opened up the Driver Manager app. The nouveau driver was selected.
* I selected the NVIDIA driver that was available (v390)
* I hit Apply. This began the process of downloading and installing the driver
* Once that was done, I restarted my machine again
* When LM came back up, I opened the Driver Manager again. This time the NVIDIA 390 driver was selected.
* I opened up the NVIDIA settings app. However, all I got was a blank grey screen that didn't have any buttons or text.
* Curious, I closed the app and reopened it from the command line:
`$ nvidia-settings
ERROR: NVIDIA driver is not loaded
ERROR: Unable to load info from any available system
(nvidia-settings:11931): GLib-GObject-CRITICAL **: 16:31:08.785: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** Message: 16:31:08.789: PRIME: No offloading required. Abort
** Message: 16:31:08.789: PRIME: is it supported? no`

I tried to purge and reinstall the NVIDIA driver multiple times, and every time I got the same errors.

**Second attempt - Ubuntu 18.10 - driver failed to load**
Finally I gave up and decided to try it on LM's predecessor Ubuntu. I downloaded and installed Ubuntu 18.10.

* I booted into the U18.10 live environment
* I used the disk utility to delete the partitions I had created when installing LM19.1

The rest of the steps I took to install U18.10 on my computer were essentially the same as those I took to install LM19.1, except that U18.10 doesn't have a Driver Manager app. Instead, I had to open up the Software & Updates app and click on the Additional Drivers tab. Other than that, all the steps were the same. More importantly, the result was the same - the driver would install but not load.

**Third attempt - Ubuntu 18.10, but install driver first - driver loads**
Being frustrated that installing the driving didn't work on U18.10 either, I decided to try installing the NVIDIA driver before loading the jakeday kernel onto my installation.

* I booted into the U18.10 live environment
* I used the disk utility to delete the partitions I had created when installing U18.10 previously
* I used the graphical installer to install U18.10 with the following configuration:
** I created a 1GB ext4 partition as the mount point for /boot
** I created a 200GB encrypted volume as the mount point for /
* I rebooted the machine
* I opened up the Software & Updates app
* I clicked on Additional Drivers. The nouveau driver was selected.
* I selected the NVIDIA driver that was available (v390)
* I hit Apply. This began the process of downloading and installing the driver
* Once that was done, I restarted my machine again
* When U18.10 came back up, I opened the Software & Updates app again. This time the NVIDIA 390 driver was selected.
* I opened up the NVIDIA settings app. This time, the app opened correctly and I was able to see all the settings and profiles.
* I cloned the jakeday/linux-surface repo
* I ran the setup script to download and install the latest kernel
* The script exited successfully, so I rebooted
* Upon reboot, the functionality provided by the jakeday kernel appeared to be working (touch interaction, battery icon, fans were a lot lower, tablet could be removed from base, etc).
* I opened up the NVIDIA settings app again, and it was still working fine.

Ever since I did this last method, I haven't had any problems with the NVIDIA driver.

**Summary**
I post this for two reasons:

* To highlight the fact that the jakeday kernel isn't installing the NVIDIA driver correctly for these distros, but is able to utilize it if it has been installed correctly previously. It would be wonderful to have this fixed.
* To provide a work-around for others who experience the same issue in the future but weren't able to find a solution.

Thanks,

jtcotton63

**Comment by qzed** [comment]
I'm not sure how this is handled on Ubuntu/Mint (and what version of the nvidia driver they install automatically), but you might need to install the DKMS version (nvidia-dkms) of the driver since you're loading a custom kernel. At least that's what I have to do on Arch.

**Comment by ZHG2017** [comment]
Hi,  may I inquire if it is possible to use only Intel video card to display meanwhile using nvidia video card to compute on the surface book 2 once you succeed in installing the driver ?
Your's sincerely

**Comment by qzed** [comment]
@ZHG2017 Yes that is possible, although enabling/disabling the dGPU on the fly is currently a bit tedious (see https://github.com/jakeday/linux-surface/issues/180).

**Comment by ZHG2017** [comment]
@qzed Hi, thank you for the information. But I think I did not clearly ask my question, I wonder if it is possible to use the Intel video card and nvidia video card at the same time but with different tasks.

**Comment by qzed** [comment]
Yeah that's possible, you could run e.g. cuda on the nvidia gpu while you run your desktop on the intel gpu, or use optirun etc.

What I meant by my answer was that you may reduce your time-on-battery even if you're not actively using the nvidia gpu, i.e. if you've got the driver installed the device gets claimed by gnome which keeps it on, even if it is not rendering on the nvidia gpu. Normally for these kinds of devices it's possible to activate the nvidia gpu only when you want to use it and put it in standby otherwise, but that's currently still on the todo-list.

**Comment by ZHG2017** [comment]
@qzed Hi, thank you again for your reply. I did not know this would be so complicated especially for someone like me who are not expert of linux. And glad to know this is possible.

**Comment by qzed** [comment]
I hope that we can make this a bit easier in the future, it's pretty much the next thing on my todo-list.

**Comment by qzed** [comment]
@ZHG2017 It's now possible to turn on/off the dGPU with [this module](https://github.com/qzed/linux-surfacebook2-mshw0153). It's not as user-friendly yet as I'd like it to be though. For now you still need to manually load the driver (`nvidia-modprobe`) after turning the dGPU on and unload the driver (e.g. `modprobe -r nvidia`) before deactivating it. I'd recommend to install the module (e.g. via dkms) so that the dGPU is automatically turned off at boot and thus preventing gnome from "claiming" the dGPU, making unloading of the driver impossible (as mentioned in one of my previous posts).

Also if you're using the dGPU, there's some thermal/power management stuff that you might want to look at to avoid throtteling: https://github.com/qzed/linux-surfacegen5-acpi/issues/18.

**Comment by qzed** [comment]
@jtcotton63 Thank you for your comment, I've now added a link to it in the FAQ section of the wiki.
