### ISSUE TITLE
[SB2] 5.0 Kernel - No audio, speakers or headphones + very laggy when unplugged

### ISSUE THREAD

**Issue by lynscott** [jakeday/linux-surface#437]
First off thank you to all of the contributors working on this in your spare time. Complaining about free, optional software feels dirty and "millennial" but here's to improvement.

Installed the latest kernel and have no audio output via speakers or headphone jack.
Also the mouse and screen become very laggy and unresponsive when unplugged, not sure if anyone else had ventured into the latest kernel yet and experienced anything similar.

SB2 15'

**Comment by ezyang** [comment]
Re the laggy issue, do you know which GPU is doing rendering? Can you run `nvidia-smi` and see if Xorg is living on the NVIDIA GPU?

FYI, audio is working on 5.0 for me (in fact, it was not working before.)

**Comment by lynscott** [comment]
@ezyang Yes Xorg shows up running on the GPU. Could it be a driver issue? I'm using one from the nvidia ppa and not the nouveau one. 410.104.

Audio worked for me on on 4.19.27 (sort of), it ignored my headphone input and always used the speakers.

**Comment by ezyang** [comment]
Yeah, that's bad. You want the integrated Intel graphics to render your display. Try adding

```
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
EndSection
```

to your xorg conf. Described in more detail at http://blog.ezyang.com/2019/03/microsoft-surface-book-2/

**Comment by lynscott** [comment]
@ezyang Ahh I see, I think that file was deleted when I ran the setup.sh script to install the kernel. I'll try recreating it with those lines. Nice blog by the way.

**Comment by lynscott** [comment]
@ezyang Funny enough that seemed to have fixed both of my issues.

I had to recreate the Xorg config file and set it up appropriately but I now have the GPU available for use and the Intel graphics rendering my display. 
I followed this guys comments on setting up the Xorg config file. 
https://gist.github.com/alexlee-gk/76a409f62a53883971a18a11af93241b

**Comment by ezyang** [comment]
@lynscott Do you know why that guy has you setup a second screen for the NVIDIA GPU? I thought it was pretty strange, and it wasn't necessary to let nvidia-smi see it.

**Comment by lynscott** [comment]
@ezyang I assumed it was for exactly that, to load to the driver and give access to nvidia-smi but default to the Intel graphics for rendering. Is it enough to simply add the NVIDIA GPU as a device but setting the Intel GPU to Screen 0?

**Comment by ezyang** [comment]
I have working nvidia-smi without it. And that makes sense: why would Xorg have anything to do with whether or not the CUDA driver sees the NVIDIA GPU.
