### ISSUE TITLE
Surface Go needs additional WLAN drivers

### ISSUE THREAD

**Issue by omnibaer** [jakeday/linux-surface#441]
Running 5.0.1/Ubuntu 18-04 LTS on Surface Go.  WL is ath10k QCA6174 hw 3.0, full id 168c:003e:168c:3370.  firmware and board don't match any standard Ubuntu firmware.

Fix is:
sudo cp /lib/firmware/ath10k/QCA6174/hw3.0/board.bin /lib/firmware/ath10k/QCA6174/hw3.0/backup_board.bin
sudo cp /lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin /lib/firmware/ath10k/QCA6174/hw3.0/backup_board-2.bin
sudo wget http://www.killernetworking.com/support/K1535_Debian/board.bin -O /lib/firmware/ath10k/QCA6174/hw3.0/board.bin
sudo cp /lib/firmware/ath10k/QCA6174/hw3.0/4.4.1/firmware-6.bin_WLAN.RM.4.4.1-00132-QCARMSWP-1 /lib/firmware/ath10k/QCA6174/hw3.0/firmware-6.bin

(Not sure why the killernetworking board.bin works when the linux-firmware and kvalo bins don't, might diff them just for s&gs)

Dmesg results after restart:
dmesg | grep ath10k
[    5.486304] ath10k_pci 0000:01:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[    5.761878] ath10k_pci 0000:01:00.0: qca6174 hw3.2 target 0x05030000 chip_id 0x00340aff sub 168c:3370
[    5.761883] ath10k_pci 0000:01:00.0: kconfig debug 0 debugfs 1 tracing 1 dfs 0 testmode 0
[    5.762814] ath10k_pci 0000:01:00.0: firmware ver WLAN.RM.4.4.1-00132-QCARMSWP-1 api 6 features wowlan,ignore-otp,mfp crc32 79f4db86
[    5.832068] ath10k_pci 0000:01:00.0: board_file api 1 bmi_id N/A crc32 70c38a29
[    5.909646] ath10k_pci 0000:01:00.0: unsupported HTC service id: 1536
[    5.929418] ath10k_pci 0000:01:00.0: htt-ver 3.60 wmi-op 4 htt-op 3 cal otp max-sta 32 raw 0 hwcrypto 1
[    6.720970] ath10k_pci 0000:01:00.0 wlp1s0: renamed from wlan0
[    7.187733] ath10k_pci 0000:01:00.0: unsupported HTC service id: 1536

**Comment by iandonnelly** [comment]
Thanks, this worked for me on Debian on the 4.19.0-4 debian kernel and was a huge help. 2 points:
1. The wget step also requires sudo
2. /lib/firmware/ath10k/QCA6174/hw3.0/4.4.1/firmware-6.bin_WLAN.RM.4.4.1-00132-QCARMSWP-1 didn't exist on my system, instead I had to download it from the following github: https://github.com/kvalo/ath10k-firmware/tree/master/QCA6174/hw3.0/4.4.1

**Comment by omnibaer** [comment]
Thanks, I edited to add the sudo there (I had downloaded separately since no wifi ;)) Glad it helped

**Comment by jakeday** [comment]
I updated the ath10k firmware in this repo to account for the change. Thanks!

**Comment by fungl164** [comment]
Thanxs for this.  However, the latest patches with these firmware files seem to be working ok on the Surface Go for 2.4Ghz. 

I cannot connect to 5Ghz.  I'm on Lubuntu 19.04.  Any ideas?? Thnxs!

**Comment by fungl164** [comment]
After trying a bunch of firmware combinations, I ended up removing board-2.bin and left firmware-4.bin and firmware-6.bin in place.  I can now connect to 5ghz without issues. Thnxs!
