### ISSUE TITLE
FYI: Unlock and login with camera / face recognition (SP3, Ubuntu)

### ISSUE THREAD

**Issue by jcward** [jakeday/linux-surface#442]
I was curious about unlocking my surface pro 3 with ubuntu 18.04 via the camera and facial recognition, and I figured some might search here for that info, so I thought I'd share my experience.

Searching, I found the **howdy** package (https://github.com/Boltgolt/howdy), and it works like a charm!

While it is generally acknowledged that facial recognition isn't the most secure login mechanism, this is an **incredibly handy way to log into your Surface Pro without the keyboard attached**.

Installation is easy (it does take quite some time, be patient!) - e.g. on Ubuntu:

```
sudo add-apt-repository ppa:boltgolt/howdy
sudo apt update
sudo apt install howdy
```

During installation it'll activate and test your cameras. When it tests the rear camera, enter `n` for no, and when it activates the front camera (little light comes on), enter `y`. 

After installation is complete, you need to train it on your face. You can enter the following command multiple times (and they recommend in multiple lightings / settings / etc.)

```
sudo howdy add
```

Then, as you can see, when the lock screen appears, 1) the light near the camera lights up, 2) the dialog says "identified face as jward", and 3) it logs me in very quickly!

![ezgif com-crop](https://user-images.githubusercontent.com/2192439/55192382-f0825500-5169-11e9-971c-7d34d1bb3771.gif)

It's a generic auth module (PAM), so it works in various places where the system asks for a password, like `sudo`.

**Comment by GarvTambi** [comment]
Sir Unknown error:1 is shown while testing

![WhatsApp Image 2020-07-09 at 12 00 06 AM](https://user-images.githubusercontent.com/42083679/86957703-ba0ef480-c178-11ea-8beb-0a120bc7b118.jpeg)

**Comment by GarvTambi** [comment]
In (f,b,s ) which one I choose
