### ISSUE TITLE
Usernamespace

### ISSUE THREAD

**Issue by NitroBAY** [jakeday/linux-surface#443]
Brave requires unprivileged_userns_clone to be set to 1 to run sandboxed.
In arch I could do it, in debian U also do sysctl -w kernel.unprivileged_userns_clone=1 but this kernel doesn't have sysctl -w kernel.unprivileged_userns_clone=1.
How to enable it (I'm using arch and using the arch repository). Do I have to recompile everything on my own, why don't u ship this feature by default, what am I missing ?
Sorry for my possible poor understanding of linux.

**Comment by kitakar5525** [comment]
I assume you are using [aur/brave-bin](https://aur.archlinux.org/packages/brave-bin/) on Arch Linux.

I installed [aur/brave-bin](https://aur.archlinux.org/packages/brave-bin/) on Arch Linux and I noticed [brave-bin.sh](https://aur.archlinux.org/cgit/aur.git/tree/brave-bin.sh?h=brave-bin) is the cause of the problem when you don't apply the patch `add sysctl to disallow unprivileged CLONE_NEWUSER by default` to the kernel. It assumes that the kernel has this patch applied.

Maybe jakeday's prebuilt kernels also don't have this patch, then user namespaces feature is enabled by default.

Comment out the relevant lines of `/usr/bin/brave` like this:
```bash
#!/usr/bin/env bash

# if [[ ! (-r /proc/sys/kernel/unprivileged_userns_clone && $(< /proc/sys/kernel/unprivileged_userns_clone) == 1 && -n $(zcat /proc/config.gz | grep CONFIG_USER_NS=y) ) ]]; then
#     >&2 echo "User namespaces are not detected as enabled on your system, brave will run with the sandbox disabled"
#     FLAG="--no-sandbox"
# fi

exec "/usr/lib/brave-bin/brave" $@ $FLAG
```

**Comment by kitakar5525** [comment]
Below is a more detailed memo on Chromium also for myself.
Thank you for the interesting discussion😎

We can check the sandbox status.

If your system doesn't have `kernel.unprivileged_userns_clone` but user namespaces feature is enabled by kernel config `CONFIG_USER_NS=y`, then you will see `Layer 1 Sandbox    Namespace` with a green background on `chrome://sandbox/`. (right in the picture)

If your system doesn't have user namespace enabled, maybe you will see `Layer 1 Sandbox    SUID` with a yellow background. (left in the picture)

![【left:user-namespace-disabled,right:user-namespace-enabled】](https://user-images.githubusercontent.com/34676735/55311509-15dece00-549e-11e9-9289-faa150cad736.png)

#### `CONFIG_USER_NS`

User namespaces feature is enabled if `CONFIG_USER_NS` is set to `y`

```
$ zcat /proc/config.gz | grep -i CONFIG_USER_NS
CONFIG_USER_NS=y
```

#### `kernel.unprivileged_userns_clone`

However, Arch Linux and Debian kernels have a patch to disallow unprivileged user namespaces usage by default. I didn't know this😲

- [#Sandboxing_applications - Security - ArchWiki](https://wiki.archlinux.org/index.php/security#Sandboxing_applications)
- [#Setup - Linux Containers - ArchWiki](https://wiki.archlinux.org/index.php/Linux_Containers#Setup)
- [debian - unprivileged_userns_clone no such - Server Fault](https://serverfault.com/questions/939455/unprivileged-userns-clone-no-such/939457#939457)

The patch
- [0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch\trunk - svntogit/packages.git - Git clone of the 'packages' repository](https://git.archlinux.org/svntogit/packages.git/tree/trunk/0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch?h=packages/linux-lts)
- [debian/patches/debian/add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-default.patch · master · Debian kernel team / linux · GitLab](https://salsa.debian.org/kernel-team/linux/blob/master/debian/patches/debian/add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-default.patch)

If this patch is applied, as you mentioned, you can re-enable user namespaces feature by this:
```
sudo sysctl kernel.unprivileged_userns_clone=1
```

**Comment by NitroBAY** [comment]
Thank you for the very extensive/comprehensive details.
The problem is definitely with brave-bin from aur only chromium works (I checked also previously in chrome://samdbox).
Yeah the thing is that Arch and Debian version of linux kernel allow you to toggle the setting for namespaces dynamically.
I don't if @jakeday will feel wheter it's appropriate to have this mechanism too in his kernel.
However I first thought this was required by chromium but brave's original requirment for sandbox (actually being discused so they may find a new mechanism) is faulty and as brave's marketshare aren't as important as pure chromium's one (or chrome) it may not be very important to add a layer of complexity I guess.
Up to jakeday to judge now.

**Comment by kitakar5525** [comment]
> The problem is definitely with brave-bin from aur only chromium works (I checked also previously in chrome://samdbox).

Isn't your brave working with modified `/usr/bin/brave` as I mentioned in https://github.com/jakeday/linux-surface/issues/443#issuecomment-478520888?
Or this one is more appropriate:

```bash
#!/usr/bin/env bash

if [[ -r /proc/sys/kernel/unprivileged_userns_clone ]]; then
    # Your kernel has the patch add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-default.patch
    if [[ ! ($(< /proc/sys/kernel/unprivileged_userns_clone) == 1 && -n $(zcat /proc/config.gz | grep CONFIG_USER_NS=y)) ]]; then
        >&2 echo "User namespaces are not detected as enabled on your system, brave will run with the sandbox disabled"
        FLAG="--no-sandbox"
    fi
else
    # Your kernel doesn't have that patch
    if [[ ! -n $(zcat /proc/config.gz | grep CONFIG_USER_NS=y) ]]; then
        >&2 echo "User namespaces are not detected as enabled on your kernel, brave will run with the sandbox disabled"
        FLAG="--no-sandbox"
    fi
fi

exec "/usr/lib/brave-bin/brave" $@ $FLAG
```

This script is not to be meant for providing additional security, but to be meant for falling back to `--no-sandbox` automatically if user namespaces feature is not available.

>Yeah the thing is that Arch and Debian version of linux kernel allow you to toggle the setting for namespaces dynamically.

That patch `add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-default.patch` is rather intended to disable user namespaces feature by default, which is needed to run brave.

Or maybe I'm misinterpreting your need. What you want to do is not to run the brave, but to toggle namespaces dynamically? then, sorry.

**Comment by NitroBAY** [comment]
Thank you for your help and time.
It is already falling back to --no-sandbox automatically, no need to modify anything. The message that pops up everytime is not my actual problem as you said the problem is how to run sandboxed brave. If I got to recompile the kernel I'll just run unsandboxed RN hoping for a quick brave patch.
If the same mechanism as debian and arch's one won't be implemented I close the issue, thanks.

**Comment by kitakar5525** [comment]
1. On terminal, run `/usr/lib/brave-bin/brave`
2. yay

![Screenshot from 2019-04-03 04-20-23](https://user-images.githubusercontent.com/34676735/55430103-2d19da80-55c8-11e9-89de-b92df001a917.png)

**Comment by NitroBAY** [comment]
I stopped using brave, sandbox problems + no VAAPI kills it for me (well actually now I installed chromium-vaapi I noticed vaapi is broken for me anyway lol).
