### ISSUE TITLE
Touchpad right-click SB2 not working. 

### ISSUE THREAD

**Issue by jeffinman** [jakeday/linux-surface#444]
Hi,
I've been using the previous few kernels and recently updated to 5.0.1 and signed the kernel.

My issue is that right-click on touchpad has never worked on all the versions I've used; it works fine on attached USB/Blue-tooth mouse.

Has anyone else ran into this issue or has some suggestions? 

Cheers,

**Comment by qzed** [comment]
This is a config issue. right-click should work via two-finger-tap out of the box, but you can also enable it via the physical click using gnome-tweak-tools (on Gnome) by setting "Mouse Click Emulation" to "Area" under "Keyboard & Mouse".

**Comment by jeffinman** [comment]
Amazing, thanks @qzed ! Installed and now I can use right click on the touchpad. It also helped me disable suspend and hibernate which mostly resolved my issue of not being able to shut the lid. So double props to you!
