### ISSUE TITLE
Touchscreen not working in Surface Pro 4 (Ubuntu 18.04.2 LTS)

### ISSUE THREAD

**Issue by mwei2019** [jakeday/linux-surface#445]
I recently installed **Ubuntu 18.04.2 LTS** onto my **Surface Pro 4** and followed all of the instructions in the **readme** file for running **setup.sh** and the touchscreen feature still isn't working, please advise.

**_uname -r_** is showing that the **Surface Pro 4** is running on the **5.0.1-surface-linux-surface** kernel.

**Comment by mwei2019** [comment]
Just found the following Errors/Warnings just now:

ERROR (dkms apport): kernel package linux-headers-5.0.1-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 5.0.1-surface-linux-surface (x86_64)
Consult /var/lib/dkms/virtualbox/5.2.18/build/make.log for more information.
update-initramfs: Generating /boot/initrd.img-5.0.1-surface-linux-surface
W: Possible missing firmware /lib/firmware/i915/icl_dmc_ver1_07.bin for module i915

What should I do to resolve these issues?

**Comment by mwei2019** [comment]
Ok, update! I decided to do a fresh OS install with **Ubuntu 18.04.1 LTS** this time and ran **setup.sh** after I updated everything and the touchscreen is now working! Not sure why it did not work when I was using **_18.04.2 LTS_** but all is well on **18.04.1 LTS** for now, except for the features that were mentioned to be not working as of yet.

**Comment by mwei2019** [comment]
Just another update and require assistance again! 
Finally got a new battery into my surface pen and tried to connect the surface pen but was unable to do so. Is there something I have to do to pair the surface pen to my surface pro 4? 
I have successfully connected the surface pen via bluetooth but the surface pen is not detected in the wacom stylus section in the settings.

**Comment by thebeardbe** [comment]
I have the same problem on the surface pro 6 with ubuntu 18.04.2. The kernel does not install properly, because none of the functions work. 

After installing a couple of times I now get that linux is not loaded. I will try to do a fresh install again.

**Comment by mwei2019** [comment]
Ya, I just gave up with 18.04.2, if anything....just fall back to 18.04.1! 

I received some debugging advice for the surface pen issue from the gitter community and I'm going to safely assume that its my surface pen that is broken, not the system/kernel/surface pro itself as I just received my 3rd party surface pen replacement today and it is working flawlessly now.

**Comment by jakeday** [comment]
Seems like this is no longer an issue as it apparently has been resolved. If I'm mistaken, feel free to re-open.
