### ISSUE TITLE
SB2 Replaced suspend with hibernate - cannot close lid now without crash

### ISSUE THREAD

**Issue by jeffinman** [jakeday/linux-surface#446]
Hi,

Realising there is a few issues relating to hibernate and suspend however they seem to be different to mine.

I recently pulled 5.0.1 and reran set-up before signing my kernel, etc.

For the first time I replaced suspend with hibernate however now when I close my laptop lid (regardless of whether locked first, wifi/blue-tooth status), my laptop will make a loud speaker hissing sound before the power is killed and I need to start up again. 

I'd like to revert the changes and test, the script won't place the option back and I'm a little rookie with linux to be trying random commands found on the internet (in this area). 

Any suggestions?

**Comment by versipellis** [comment]
#431 has some instructions.

**Comment by jakeday** [comment]
Answer to how to revert is in #431  as @versipellis mentioned. Closing this one.
