### ISSUE TITLE
5.0.1 Surface Book 2 GPU not working after detach/attach

### ISSUE THREAD

**Issue by CorcovadoMing** [jakeday/linux-surface#457]
I'm using Ubuntu 18.04 with kernel 5.0.1 installed, everything goes well except the GPU won't work after detach then attach the screen, nvidia-smi shows 

`Unable to determine the device handle for GPU 0000:02:00.0: Unknown Error`

However, I can saw GPU in `lspci | grep NVIDIA`

`02:00.0 3D controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)`

Is it possible to be fixed? Thanks

**Comment by qzed** [comment]
Yeah, you need to unload the dGPU driver. Might be a bit tricky to do, as gnome will "claim" the device making this impossible. I haven't figured out a way yet to prevent this without disabling the dGPU, but I'm currently working on something that can be used to disable the dGPU at start to avoid this.
