### ISSUE TITLE
script UX issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [jakeday/linux-surface#459]
Hi Jake,

thanks a lot for this project, I just got a Surface Go 8GB/128GB going with it (kernel 4.19).

The script caused slight usability issues:

It asks some stuff, but often it is not clear why or what the precise consequence is.

## device detection

It worked, no problem here ! :-)

## suspend vs. hibernate

OK, this one is clear for me (to ram vs. to disk), but maybe one line with an explanation would be useful here, too.

Maybe about hibernate space/other requirements also.

## deleting the example configs

In what case would one rather delete or keep them?
- For xorg it doesn't seem to matter at all as everything in the config is just a comment.
- OTOH, for pulseaudio, there are non-comment lines.

## Downloading and installing kernel stuff:

I didn't try it (i just downloaded kernel stuff and a current copy of your github workdir and put all on a usb stick - because the wifi on the surface go with ubuntu 18.04 is initially broken), but I guess it might not work.

On a fresh ubuntu 18.04, there is no curl (IIRC), but wget is there.

# patched libwacom

Consequence unclear. I guess it is needed for the surface pen? What is the patch for?

Would it work with the daily ubuntu updates or could there be conflicts?

## clock utc vs. localtime

Good explanation here, nothing to do.

**Comment by jakeday** [comment]
I updated the setup.sh script and the readme. Thanks!
