### ISSUE TITLE
Surface Book: Position of Pen doesn't match in tablet mode or multiscreen

### ISSUE THREAD

**Issue by Sevimuelli** [jakeday/linux-surface#46]
Thanks for all the great work you have done here. 
Everything works pretty good now. I only experienced on issue. When I use my Surface Book as a Tablet and rotate it, for example i rotate 90°, then when I use the pen, the pointer isn't there where the pen is. If I move the pen left, then the pointer moves down and if I move the pen down, the pointer moves right. Same problem exists however i turn the tablet. It looks like there is just one standard coordinate system in use.

The other problem occurs, when i connect my docking-station with two monitors connected to it. On the left i have my Surface Book and in the middle and right, two screens. All screen words but when I try to use the pen, then the pointer moves all over the three screens. For example if i place the pen in the center of my Surface Book, then the pointer is in the center of my middle monitor. So the input of the pen is placed all over the three screens. If i put the pen on the right of my Surface Book, the pointer is on the right edge of my right screen. 

Is there a possibility to fix that? I would really appreciate that, cause i'd like to work with the pen while connected to my docking-station. Do you need some more informations?

Thanks

**Comment by jakeday** [comment]
The first issue should be fixed in my latest kernel push, due out tonight.

The second sounds like a configuration issue with your setup. I'm not sure the best way to adjust it for your setup, though, without doing the research myself.

**Comment by geoffholden** [comment]
@Sevimuelli I'm not sure if the surface book is using the same code as my 2017 surface pro, but I had the same issue on Ubuntu 17.10. I ended up patching libwacom so that the pen was detected as a wacom (or wacom-like) tablet. You can see my changes here https://github.com/geoffholden/libwacom

**Comment by jakeday** [comment]
@geoffholden That is definitely the issue, but we'll need to add the ids of the other devices for full support.

**Comment by jakeday** [comment]
@Sevimuelli Let us know if that works for you so we can close this ticket.

**Comment by geoffholden** [comment]
@jakeday Are all the IDs in your udev rules devices that'll show up on the MEI bus? If so, I'll add those to my libwacom modifications. I could even build a deb package for us surface users.

**Comment by jakeday** [comment]
@geoffholden Yep, that's correct.

**Comment by jakeday** [comment]
Marking this resolved.
