### ISSUE TITLE
can't install virtualbox software on surface because the kernel is not compatible?

### ISSUE THREAD

**Issue by juaolobo** [jakeday/linux-surface#461]
is it just not compatible yet or there is something to be done?

**Comment by qzed** [comment]
Try installing the dkms-version of the package. Virtualbox requires a kernel-module, and for that to work it has to be compiled for the respective kernel. The pre-compiled packages are all compiled for the distro's current kernel, so they won't work here.

**Comment by qzed** [comment]
I've added an FAQ section, as this has come up before: https://github.com/jakeday/linux-surface/wiki/Frequently-Asked-Questions#i-cant-install-package-x-because-the-kernel-is-incompatible. It has a bit more details if you're interested.

**Comment by qzed** [comment]
What distribution are you using? If you're using Ubuntu, it should be as simple as running `sudo apt install virtualbox-dkms`.

**Comment by juaolobo** [comment]
yeah im using ubuntu, and when i run this command it gives me this message: "virtualbox-dkms is already the newest version (5.2.18-dfsg-2~ubuntu18.04.3)."

**Comment by juaolobo** [comment]
also when I tried to reinstall it I got this : "Building initial module for 5.0.7-surface-linux-surface
ERROR (dkms apport): kernel package linux-headers-5.0.7-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 5.0.7-surface-linux-surface (x86_64)
Consult /var/lib/dkms/virtualbox/5.2.18/build/make.log for more information."

**Comment by qzed** [comment]
Ah sorry, then it's a different problem than I thought. It looks like virtualbox version 5.2 is incompatible with the 5.x kernel (this holds for all 5.x kernels, not just for this one). You have two options here: Either install the 4.19 kernel (that's a long-term-support version, so it's going to be around for a while) or use an updated version of virtualbox (e.g. 6.0.4 should support newer kernels), which might be a bit tricky to do on Ubuntu.

**Comment by juaolobo** [comment]
Hey, I just installed virtualbox-6.0 and it worked, thanks so much for your help.

**Comment by qzed** [comment]
Awesome, I've update the FAQ again, so it's also there now.
