### ISSUE TITLE
Surface Pro 4: Solution for no wifi after hibernation

### ISSUE THREAD

**Issue by casainho** [jakeday/linux-surface#47]
Not every time hibernation works, sometimes it hangs - I am on Linux Ubuntu 17.10, SP4 I3. And after rebooting, hibernation works but wifi does not!! But I got it working, just like I had it before using kernel 4.4.39, with this script:
- call the script: hibernate.sh and put it as exec, in the folder: /lib/systemd/system-sleep/:
~~~~~~
#!/bin/sh
case $1/$2 in
  pre/*)
    systemctl stop NetworkManager.service
    rmmod intel_ipts
    rmmod mei_me
    rmmod mei
    rmmod mwifiex_pcie
    rmmod mwifiex
    echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/reset
    ;;
  post/*)
    modprobe mei
    modprobe mei_me
    echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/reset
    modprobe mwifiex
    modprobe mwifiex_pcie
    systemctl start NetworkManager.service
    ;;
esac

~~~~

Great kernel!! Thank you.

**Comment by thekswenson** [comment]
@casainho : does this script have to be put in a particular location?
I'm assuming that the pre will be run pre-hibernate and the post will be run post-hibernate if I name this file properly and put it in the right spot.

**Comment by casainho** [comment]
call the script: hibernate.sh and put it as exec, in the folder: /lib/systemd/system-sleep/

**Comment by jakeday** [comment]
@casainho Can you submit a pull request to get this added to the repo?

**Comment by casainho** [comment]
I will submit a pull request.
