### ISSUE TITLE
Surface Laptop 1: Caps Lock indicate light is not working.

### ISSUE THREAD

**Issue by Lanvww** [jakeday/linux-surface#474]
Hello, I am now using the 5.0.7 kernel for Ubuntu 19.04. I was upgraded from 18.10 with the 4.19.28 kernel. In both of two systems, the indicator is not working. I have checked the [https://github.com/jakeday/linux-surface/issues/245](url) but there is no solution. I check with the windows system, and the light isn't broke. Please let me if there anything I can do to fix this problem.

**Comment by qzed** [comment]
Yeah, that's a different issue. The SL1 and SL2 caps lock light is currently not supported/implemented in the surface-acpi module (see [this](https://github.com/qzed/linux-surfacegen5-acpi/issues/8) issue). You can help change that, however: We need windows logs from a few caps-lock key presses. You can get the logs as described [here](https://github.com/qzed/linux-surfacegen5-acpi#getting-windows-logs-for-reverse-engineering).

**Comment by Lanvww** [comment]
> 
> 
> Yeah, that's a different issue. The SL1 and SL2 caps lock light is currently not supported/implemented in the surface-acpi module (see [this](https://github.com/qzed/linux-surfacegen5-acpi/issues/8) issue). You can help change that, however: We need windows logs from a few caps-lock key presses. You can get the logs as described [here](https://github.com/qzed/linux-surfacegen5-acpi#getting-windows-logs-for-reverse-engineering).

Cool, I will get those logs for you ASAP!

**Comment by qzed** [comment]
@Lanvww Awesome. let me know if you need more info.

**Comment by Lanvww** [comment]
> 
> 
> @Lanvww Awesome. let me know if you need more info.

Hello qzed, I follow the guide and got the logs from IRPMon, but the dbgview did not show anything to me. 
[CAPSLIGHT.log](https://github.com/jakeday/linux-surface/files/3125529/CAPSLIGHT.log)

I wish this is helpful to you.

**Comment by qzed** [comment]
@Lanvww To implement this I need the buffer contents which are unfortunately not captured by IRPMon but via dbgview, sorry. Have you set the component filter mask (e.g via the registry)? Also you need to run dbgview as admin and enable the "catpure kernel" setting or it won't work. There are unfortunately a couple of things that can go wrong here.

**Comment by Lanvww** [comment]
> 
> 
> @Lanvww To implement this I need the buffer contents which are unfortunately not captured by IRPMon but via dbgview, sorry. Have you set the component filter mask (e.g via the registry)? Also you need to run dbgview as admin and enable the "catpure kernel" setting or it won't work. There are unfortunately a couple of things that can go wrong here.

I will try again. I think the problem is the component filter mask part, I do not know which is key should change from DEFAULT to 0xffffffff . I am sorry that I don't know how this thing work...
I created the key "Debug Print Filter" it has a (default) key, then I have no idea for the value. 
Not really have free time in these days, probably will take a while for me to figure those out. Thanks for your works anyway.

**Comment by qzed** [comment]
@Lanvww nothing to be sorry for. If you're going via registry, you need to create `DEFAULT` in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter` as `DWORD` value and then set it to `0xffffffff` (hexadecimal).

**Comment by SmartBoy84** [comment]
Why did you close this, I still get the issue on SL1 even on Qzed's kernel
