### ISSUE TITLE
Surface Pro 4: advice on re-enabling touch after loss of input

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#48]
Once in a while I lose touch and pen input.  When this happens I can no longer switch to single touch mode (the command "echo 1 > /sys/kernel/debug/ipts/mode" hangs), and rotating the screen doesn't always work.  Hibernating doesn't work.

Does someone have any advice?  Can I reload a kernel module?

**Comment by jakeday** [comment]
@thekswenson Is this the same as #31 ? If so, can we just re-open that issue?

**Comment by thekswenson** [comment]
Issue #31 persists.
I wrote this issue as a way to get advice on how to recover when issue #31 crops up.

**Comment by jakeday** [comment]
Closing this since I re-opened #31
