### ISSUE TITLE
[Install Issue] Keyboard not responsive

### ISSUE THREAD

**Issue by Fenny** [jakeday/linux-surface#486]
Hello,

I'm trying to install Ubuntu 18.04.2 LTS from a bootable .iso on my surface laptop but the keyboard doesn't work and cannot finish the installation.

How can I build this kernel into a .iso so I can install Ubuntu with a working keyboard during the installation process?

Kind regards

Fenny

**Comment by AlexeyPogorelov** [comment]
@Fenny 
Hi. You can install it using touchpad and screen keyboard. Just get to Ubuntu without installing and activate it form settings menu 
![Screenshot from 2019-05-17 12-40-10](https://user-images.githubusercontent.com/6617585/57919717-0d055880-78a2-11e9-9196-3245ee6df8aa.png)
