### ISSUE TITLE
Touch not working Ubuntu 19.04 Surface Pro 4

### ISSUE THREAD

**Issue by MstrRichard** [jakeday/linux-surface#490]
First, the patch is awesome. It worked really well from 18.04 to 18.10. 
Days ago I updated to 19.04, then I found the touchscreen is not working. Reinstalling the patch doesn't help. Is this a issue of myself or is touchscreen not supported for 19.04 Surface Pro 4 yet?

**Comment by tmarkov** [comment]
There shouldn't be anything wrong about 19.04. Are you sure you boot into the custom kernel? Can you run uname -r to make sure?

**Comment by MstrRichard** [comment]
It says 5.0.0-13-generic.

**Comment by tmarkov** [comment]
It seems you don't boot into the custom kernel by default. Most likely it's properly installed, but you need to select it from GRUB when booting, because it's not the default option. Look into "additional options for Ubuntu" in the boot menu.

**Comment by MstrRichard** [comment]
The problem is solved. But it seems that the last installation of the kernel is not successful. When I go into additional options, the only options available are the generic one and the previous surface kernel. Then I booted into the previous surface kernel and installed the latest surface kernel, everything works fine. Thank you so much for help.
