### ISSUE TITLE
surface_acpi not functioning on surface pro 2017

### ISSUE THREAD

**Issue by rowanG077** [jakeday/linux-surface#496]
First of thank you very much for making this. It's very cool to be able to run linux on the surface!

I'm currently trying to make a configuration where everything included in this repo works with NixOS. The one thing I cannot get to work is the `surface_acpi` module. The module is loaded on startup but it seems it's not actually doing anything. I am using the `4.19.37-1` release of this repository and compile the kernel with the provided patches and config.

dmesg only shows that it is loading the module but nothing else.

```
$ dmesg | grep surface_acpi
[    2.207221] stage-1-init: loading module surface_acpi...
```

lsmod likewise shows it's loaded.

```
$ lsmod | grep surface_acpi
surface_acpi           16384  0
```

How can I debug this further? This is the last missing piece for me.

**Comment by qzed** [comment]
I assume you have the config options for the module:
```
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_ACPI_SSH=y
CONFIG_SURFACE_ACPI_SAN=y
CONFIG_SURFACE_ACPI_VHF=y
CONFIG_SURFACE_ACPI_DTX=y
CONFIG_SURFACE_ACPI_SID=y
```
set?

If so, I assume the driver doesn't get loaded. You can check that with
```
ls -l /sys/bus/serial/devices/serial0-0/driver
```

If the driver isn't loaded, it's most likely a missing config option related to the EC, i.e. an option that is not directly required for the module, but indirectly for the lower-level subsystems that power the specific type of serial-device the EC is. I still haven't figured all of them out, but [here](https://github.com/qzed/linux-surfacegen5-acpi/issues/1) is a list that you could have a look at.

**Comment by rowanG077** [comment]
Thank you for looking into this!

> I assume you have the config options for the module:
> 
> ```
> CONFIG_SURFACE_ACPI=m
> CONFIG_SURFACE_ACPI_SSH=y
> CONFIG_SURFACE_ACPI_SAN=y
> CONFIG_SURFACE_ACPI_VHF=y
> CONFIG_SURFACE_ACPI_DTX=y
> CONFIG_SURFACE_ACPI_SID=y
> ```
> 
> set?

It's odd that `CONFIG_SURFACE_ACPI=m` is in the config of  my running system but the other ones are not:

```
$ zcat /proc/config.gz | grep CONFIG_SURFACE_ACPI 
CONFIG_SURFACE_ACPI=m
```

To check this a little more I pulled the config I used while compiling from this repo and diffed it with my own. Which shows a lot of differences. I'm not sure how they get introduced but I assume this is the problem, I'll have to dig into how NixOS compiles kernels then!

> If so, I assume the driver doesn't get loaded. You can check that with
> 
> ```
> ls -l /sys/bus/serial/devices/serial0-0/driver
> ```
> 
> If the driver isn't loaded, it's most likely a missing config option related to the EC, i.e. an option that is not directly required for the module, but indirectly for the lower-level subsystems that power the specific type of serial-device the EC is. I still haven't figured all of them out, but [here](https://github.com/qzed/linux-surfacegen5-acpi/issues/1) is a list that you could have a look at.

I don't have the directory `/sys/bus/serial` at all.

**Comment by qzed** [comment]
> It's odd that CONFIG_SURFACE_ACPI=m is in the config of my running system but the other ones are not

The others should default to `y` if other required config options are set. Given that you don't have the `/sys/bus/serial` directory, I think the `serdev` subsystem specific options are missing. Those should be
```
CONFIG_SERIAL_DEV_BUS=y
CONFIG_SERIAL_DEV_CTRL_TTYPORT=y
```
You can also check if all of the [options](https://github.com/jakeday/linux-surface/blob/2b206b56e125c9fda4661dbcc91095e9bf993d28/patches/5.0/0001-surface-acpi.patch#L78-L81) required in kconfig for the `SURFACE_ACPI_SSH` driver are present. They themselves may require other options to be set, i.e. (`CONFIG_SERIAL_DEV_CTRL_TTYPORT` depends on `CONFIG_SERIAL_DEV_BUS`).

**Comment by rowanG077** [comment]
Sorry for this late reply. I was busy the last two weeks.

Regarding the `serdev` options. I followed the chain of dependencies. I represented it below as a tree where the associated values in my config are seen.
```
SURFACE_ACPI_SSH
  |-- CONFIG_SURFACE_ACPI=m
      |-- CONFIG_ACPI=y
  |-- CONFIG_X86_INTEL_LPSS=y
  |-- CONFIG_SERIAL_8250_DW=m
      |-- CONFIG_SERIAL_8250=y
  |-- CONFIG_SERIAL_8250_DMA=y
  |-- CONFIG_SERIAL_DEV_CTRL_TTYPORT(not set in running config)
      |-- CONFIG_TTY=y
      |-- CONFIG_SERIAL_DEV_BUS=m
```

So it seems there are some issues. `CONFIG_SERIAL_DEV_BUS` is set to `m` which it explicitly shouldn't be set to for `CONFIG_SERIAL_DEV_CTRL_TTYPORT` to work. However in the config I used to built the kernel the value is set to `y` https://github.com/jakeday/linux-surface/blob/4.19.37-1/configs/4.19/config#L4068.

**Comment by qzed** [comment]
If you have `CONFIG_SERIAL_DEV_BUS=m` set in the config, it might override the setting for `CONFIG_SERIAL_DEV_CTRL_TTYPORT` due to the dependency. Setting both to `y` should work though.

**Comment by rowanG077** [comment]
Thank you. It works now by setting `CONFIG_SERIAL_DEV_CTRL_TTYPORT` and `SERIAL_DEV_BUS` to `y`.

This issue can be closed. However what I would like to see in the future is the additional kernel config parameters that need to be set instead of giving an entire config. Is this a possibility? I could look into it.

**Comment by qzed** [comment]
Nice. It'd be awesome and much appreciated if you want to look into this. You could add a new wiki page (I think everyone should be able to edit and create new pages).

**Comment by razvan-flavius-panda** [comment]
@rowanG077 Did you manage to get this working on NixOS? If yes, could you share with us how to install it?
