### ISSUE TITLE
Touchscreen stops working when suspending

### ISSUE THREAD

**Issue by dasmikko** [jakeday/linux-surface#498]
I'm using the `5.0.10-surface-linux-surface` kernel, on a Surface Pro 4 running Pop!_os 19.04

When I suspend the device, the touch screen stops working.

**Comment by korakios** [comment]
It’s mentioned before,  look at #448

**Comment by dasmikko** [comment]
Sorry, thought I had searched for everything,  my bad.

**Comment by WesleyVanNeck** [comment]
@dasmikko i tested 4 versions of ubuntu it works fine on 16.04
