### ISSUE TITLE
ProximityOut triggers even if stylus pressed against the screen

### ISSUE THREAD

**Issue by giampierosalvi** [jakeday/linux-surface#500]
Hi,
I am running the jakeday kernel with Ubuntu 18.04 on a Surface Go with the Microsoft Pen. The pressure data from the pen is very unstable. When I use pressure sensitivity on xournal I can see the width of the line goes from zero to maximum thickness even though I try to keep the pressure constant. When I do not use pressure sensitivity, continuous lines get broken often, even though I am applying relatively high pressure. You can see two examples in the figure below.

Has anyone experienced a similar behavior? Any idea how to fix this? Changing the battery does not solve this. I can add more information if you tell me which info is relevant.

Thank you!
Giampiero
![github_bug_report](https://user-images.githubusercontent.com/1721573/57857738-04ece080-77f0-11e9-8d70-fc4be7a2fae2.png)

**Comment by giampierosalvi** [comment]
I did some more testing: running
xinput test -proximity "ELAN9038:00 04F3:261A stylus"
I get most of the time a "motion" entry with values for a[0] to a[5] that look reasonable. However, now and then I get "button release 1" or "proximity out" events even though I am not pressing buttons and I am still pressing the pen against the screen. Usually it takes some time before I start getting the "motion" entries again. Here is an example:

motion a[0]=9117 a[1]=4341 a[2]=7057 a[3]=19 a[4]=7 a[5]=-900 
motion a[0]=9135 a[1]=4316 a[2]=7004 a[3]=19 a[4]=7 a[5]=-900 
motion a[0]=9154 a[1]=4291 a[2]=6951 a[3]=19 a[4]=8 a[5]=-900 
motion a[0]=9175 a[1]=4266 a[2]=6898 a[3]=19 a[4]=8 a[5]=-900 
button release 1 a[0]=9175 a[1]=4266 a[2]=0 a[3]=0 a[4]=0 a[5]=-900 
proximity out a[0]=9175 a[1]=4266 a[2]=0 a[3]=0 a[4]=0 a[5]=-900

**Comment by giampierosalvi** [comment]
I solved this by changing from the wacom to the evdev driver in my /etc/X11/xorg.conf.d/70-wacom.conf file that I list below for completeness. Now the pen works a charm :)

Section "InputClass"
	Identifier "Surface Go tablet class"
	MatchProduct "ELAN9038|Elan9038"
	MatchDevicePath "/dev/input/event*"
	MatchIsTablet "true"
	Driver "evdev"
EndSection

Section "InputClass"
	Identifier "Surface Go touchscreen class"
	MatchProduct "ELAN9038|Elan9038"
	MatchDevicePath "/dev/input/event*"
	MatchIsTouchscreen "true"
	Driver "evdev"
EndSection

Section "InputClass"
	Identifier "Surface Go touchpad class"
	MatchProduct "ELAN9038|Elan9038"
	MatchDevicePath "/dev/input/event*"
	MatchIsTouchpad "true"
	Driver "evdev"
EndSection

**Comment by ShapeShifter499** [comment]
The wacom driver has a patch that should work, does for me. Could you please test it and report back over there?    The patch is listed at https://github.com/linuxwacom/xf86-input-wacom/issues/52#issuecomment-497164924
