### ISSUE TITLE
[Void Linux] Has anyone been able to build the kernel on Void?

### ISSUE THREAD

**Issue by minikN** [jakeday/linux-surface#507]
Hello. So I've tried to patch and build the kernel manually on Void. I didn't succeed (I think), here is what I did:

[void-packages Repo with source packages](https://github.com/void-linux/void-packages)
[linux5.0 package](https://github.com/void-linux/void-packages/tree/master/srcpkgs/linux5.0)
[XBPS-src wiki](https://wiki.voidlinux.org/Xbps-src)

I cloned the `void-packages` repo and set up `xbps-src` according to [the wiki](https://wiki.voidlinux.org/Xbps-src). I also did [this](https://github.com/void-linux/void-packages#building-packages-natively-for-the-musl-c-library).

I chose to build the 5.0 kernel. So I copied the [patches](https://github.com/jakeday/linux-surface/tree/master/patches/5.0) I need to `~/void-packages/srcpkgs/linux5.0/patches` and the [config file](https://github.com/jakeday/linux-surface/tree/master/configs/5.0) to `~/void-packages/srcpkgs/linux5.0/files/x86_64-dotconfig` (overwriting the old one).

Then I issued `./xbps-src pkg linux5.0` to build the kernel. I took over an hour, and through the output I could see that it was indeed applying the patches. I had a couple of warnings, but in the end it succeeded without an error.

Then I issued `xi linux5.0` followed by ` xbps-install --repository=hostdir/binpkgs linux5.0`. It installed the kernel successfully.

After that I unpacked the necessary firmware files from [here](https://github.com/jakeday/linux-surface/tree/master/firmware) to `/lib/firmware`. Specifially 
- ` firmware/ipts_firmware_v102.zip` to `/lib/firmware/intel/ipts/ `
- ` firmware/i915_firmware_kbl.zip` to `/lib/firmware/i915/ `
- ` firmware/mrvl_firmware.zip` to `/lib/firmware/mrvl/`
-  ` firmware/mwlwifi_firmware.zip ` to `/lib/firmware/mwlwifi/`

I chose the correct firmware files based oh the setup script (Surface Pro 2017).

After that I rebooted the machine and chose the correct kernel in the grub menu. It seemed to have booted successfully.

`uname -r` outputs `5.0.17_1`

Then I installed `xorg-minimal`, `xterm`,  `xf86-video-intel` and `openbox` just to test things. I've setup a minimal `.xinitrc` with just `exec openbox-session`.

I was able to start it. I would expect to be able to move a terminal window via touch. But it doesn't work. I actually see no difference what so ever. Also pressing the power button doesn't do anyting.

The only thing I haven't done is [this](https://github.com/jakeday/linux-surface/tree/master/packages/libwacom). Because there doesn't seem to be a void-equivalent for it. However I believe (not sure) this is only to make the pen work properly. I think touch input should work without it.

Would anyone have a guess where I went wrong?

**Comment by minikN** [comment]
Ok I'm a little further now. I'm getting the follow error when building:

```
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/aes-x86_64.ko] Error 3
    make[1]: *** Waiting for unfinished jobs....
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/camellia-aesni-avx-x86_64.ko] Error 3  
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/blowfish-x86_64.ko] Error 3
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/aesni-intel.ko] Error 3
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    sign-file: LibreSSL 2.8.3 only supports SHA1 signing
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/camellia-aesni-avx2.ko] Error 3
    make[1]: *** [scripts/Makefile.modinst:36: arch/x86/crypto/camellia-x86_64.ko] Error 3
    make: *** [Makefile:1312: _modinst_] Error 2
    => ERROR: linux5.0-5.0.18_1: do_install: 'make ${makejobs} ARCH=${subarch:-$arch} 
    INSTALL_MOD_PATH=${DESTDIR} modules_install' exited with 2
    => ERROR:   in do_install() at srcpkgs/linux5.0/template:117
```

I'm using your config file:
```
CONFIG_MODULE_SIG=y
# CONFIG_MODULE_SIG_FORCE is not set
CONFIG_MODULE_SIG_ALL=y
# CONFIG_MODULE_SIG_SHA1 is not set
# CONFIG_MODULE_SIG_SHA224 is not set
# CONFIG_MODULE_SIG_SHA256 is not set
# CONFIG_MODULE_SIG_SHA384 is not set
CONFIG_MODULE_SIG_SHA512=y
CONFIG_MODULE_SIG_HASH="sha512"
```

Anyone know whats up?

**Comment by StollD** [comment]
Your log contains an error message that only SHA1 signing is supported
`sign-file: LibreSSL 2.8.3 only supports SHA1 signing`

However, in the config file, the algorithm that should be used to sign kernel modules is set to SHA512:
```
CONFIG_MODULE_SIG_SHA512=y
CONFIG_MODULE_SIG_HASH="sha512"
```
You would want to change the following:
* `CONFIG_MODULE_SIG_SHA512=y` to `# CONFIG_MODULE_SIG_SHA512 is not set`
* `# CONFIG_MODULE_SIG_SHA1 is not set` to `CONFIG_MODULE_SIG_SHA1=y` 
* `CONFIG_MODULE_SIG_HASH="sha512"` to `CONFIG_MODULE_SIG_HASH="sha1"`

However, what might be better to retain compatibility with the ecosystem of your distribution is using it's default config instead of the reference config from jakeday, and setting the options for linux-surface yourself (add them to the bottom of the defconfig file):

```
# Surface related kernel configs
CONFIG_INTEL_IPTS=m
CONFIG_MEDIA_CEC_RC=y
# CONFIG_MWLWIFI is not set
CONFIG_NET_DSA_MV88E6060=m
CONFIG_NET_DSA_TAG_TRAILER=y
CONFIG_OVERLAY_FS_NFS_EXPORT=n
CONFIG_SURFACE_3_POWER_OPREGION=m
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_ACPI_SAN=y
CONFIG_SURFACE_ACPI_SSH=y
CONFIG_SURFACE_ACPI_SSH_DEBUG_DEVICE=n
CONFIG_SURFACE_ACPI_VHF=y
CONFIG_SURFACE_ACPI_DTX=y
CONFIG_SURFACE_ACPI_SID=y
```
I use Fedora with those options, and otherwise the default ones for Fedora, and it works just fine.

**Comment by minikN** [comment]
Thank you, I will try this today.

**Comment by minikN** [comment]
I successfully build the kernel. However after installing and booting from it. There doesn't seem to be any difference to the stock kernel. No touch ect.

**Comment by StollD** [comment]
You could try running `lsmod | grep ipts` and `lsmod | grep surface` to see if the added modules were loaded.

Also, if you have a file `/proc/config.gz`, try running `zgrep SURFACE /proc/config.gz` to see if your kernel actually compiled with the added options. I have had problems with `make oldconfig` or other `make *config` commands removing the surface options in the past, causing the modules not actually getting compiled.

**Comment by minikN** [comment]
```
lsmod | grep ipts
intel_ipts             28672  0
mei                    94208  3 intel_ipts,mei_me
hid                   131072  7 usbhid,hid_multitouch,hid_sensor_hub,intel_ipts,intel_ishtp_hid,hid_generic,uhid
i915                 2097152  10 intel_ipts
```
```
lsmod | grep surface
surfacepro3_button     16384  0
```
```
zgrep /proc/config.gz
CONFIG_TOUCHSCREEN_SURFACE3_SPI=m
CONFIG_SURFACE3_WMI=m
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_PRO3_BUTTON=m
CONFIG_SURFACE_3_POWER_OPREGION=m
```

**Comment by minikN** [comment]
Again maybe it's me doing something wrong. I would expect to be able to start an openbox-session and move windows arount via touch.

Also if I do `cat /dev/input/event*` I'd expect some output if I touch the screen the volume / power button.

But nothing.

**Comment by StollD** [comment]
Well, basically, as far as I know, what happens is that `make oldconfig` (like it is called in the void template) removes some of the surface specific config options from the defconfig and then builds the kernel without those options.

Seeing the IPTS module load but touch still failing suprises me since I thought it was the one responsible for the whole touch stuff, but I don't know if other critical options are hidden behind `#ifdefs` for surface devices.

The only idea (and maybe a stupid one) I have would be to remove all calls to `make oldconfig` or any `make *config` from the kernel build script, and then try again. In my experience, when you can find all the surface options you added to the defconfig in `/proc/config.gz`, touch and everything works.

But I just played around with it a bit and ultimatively gave up and used `make rpm-pkg` which works fine for Fedora, so I am not really an expert.

**Comment by minikN** [comment]
Okay, little update. I just build the kernel with [this](https://github.com/the-wrench99/void-packages/blob/surface-kernel/srcpkgs/linux5.0/files/x86_64-dotconfig) config file. And now, touch is working!

**Comment by minikN** [comment]
First step done. However, the power / volume buttons are not working. Pressing the power button does nothing except from hard shutting down the device when pressed for 10 seconds or so. If I close the lid (keyboard) the device will also not wake up from hibernate/suspend. I have to hard reset it with the power button (this also didn't work for me on ubuntu). I will look into it, but appreciate any advice.

Thank you @StollD so far.

**Comment by jjrugui** [comment]
@minikN I'm buying a Surface Go today and I'll give it a try to install void linux during the weekend. I would really appreciate if you share your results. I'll do the same during the weekend :)

**Comment by minikN** [comment]
@jjrugui Ok course. I fixed the button issue. As of now, everything (as far as I can tell) is working. But be aware that I have a Surface Pro (2017). Dont know if there are any major differences.

**Comment by minikN** [comment]
I could provide you a gist with everything I did to get it working

**Comment by minikN** [comment]
There are a couple of issues regarding suspend:

#479 
#454 
#450 
#431 

I did not switch from suspend to hibernate. But suspend itself isn't working at all. There are two possible scenarios (as fas as I can tell) which should trigger suspend.
- 1. Closing the lid
- 2. Manually via a terminal (for Void, it's simpy `zzz`)

Both have the same affect for me, the device won't wake up from suspend. No button presses have any affect. Pressing the power button will (sometimes, seems random) regularly shut the device down. Most often however, it doesn't do anything.

I have to hold the power button for 10-15 seconds to hard reset it.

**Comment by minikN** [comment]
Update regarding the suspend/resume issue.

I took [this](https://github.com/jakeday/linux-surface/blob/master/root/lib/systemd/system-sleep/sleep) script and copied the `pre` part to `/etc/zzz.d/suspend/sleep` and the `post` part to `/etc/zzz.d/resume/resume`.

Going into suspend is working properly now, also waking up is working, however, after it woke up, it suspends immediately afterwards.

Seems like there is one piece missing.

**Comment by minikN** [comment]
Actually sorry for spamming this issue.

But I guess the more information the better.

Going to suspend works pressing the power button and closing the lid.
Waking from suspend currently only works by pressing the power button again, however as I said it will go to suspend immediately again.

Opening the lid or pressing any keyboard button does not wake the device up.

At this point I'd be happy if I could wake it up properly by opening the lid or pressing any button.

Unfortunately I haven't dealt with ACPI events before therefore I'm just not good enough to debug this any further, any help appreciated. If any output is needed let me know.

**Comment by minikN** [comment]
Here is the output of `find /sys -name wakeup -printf '%p ' -exec cat {} \;`: [link](https://github.com/minikN/void-packages/blob/master/logs/wakeup_events)

Also, doing

```
modprobe -r intel_ipts
modprobe -r mei_me
modprobe -r mei
rtcwake -m freeze -s 10
```

works as expected. The surface suspends for 10 secs and comes back without a problem.

**Comment by minikN** [comment]
@jjrugui do you still need my help?
