### ISSUE TITLE
Pen not Detected

### ISSUE THREAD

**Issue by IsaulGarcia** [jakeday/linux-surface#509]
Pen not Detected
I have a surface book 2 with the new pen. When trying to connect the pen in the Bluetooth settings the pen is not detected therefore I cant connected it or use it. I am running Ubuntu 18.04. Does anyone know if i need to install any addition software besides the kernel or should it just work?

**Comment by Sartharon** [comment]
Did you install the patched libwacom packages? Could you please provide the output of 
`$ uname -r`
and
`$ xinput list`

**Comment by IsaulGarcia** [comment]
Sorry i'm not sure what those packages are and whether or not I've installed them. I install the kernel 3 days ago if that is any help. The outputs were:
```bash
(base) isaul@surface-book-2:~$ uname -r
5.0.10-surface-linux-surface
(base) isaul@surface-book-2:~$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Mouse        	id=8	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Consumer Control	id=9	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Touchpad     	id=10	[slave  pointer  (2)]
⎜   ↳ ipts 045E:0020 Mouse                    	id=14	[slave  pointer  (2)]
⎜   ↳ ADAPTER_D479 Mouse                      	id=18	[slave  pointer  (2)]
⎜   ↳ ADAPTER_D479 Consumer Control           	id=19	[slave  pointer  (2)]
⎜   ↳ BTLE Precision Mouse                    	id=21	[slave  pointer  (2)]
⎜   ↳ BTLE Precision Mouse Consumer Control   	id=23	[slave  pointer  (2)]
⎜   ↳ ipts 045E:0020 Touchscreen              	id=13	[slave  pointer  (2)]
⎜   ↳ ipts 045E:0020 UNKNOWN                  	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard              	id=7	[slave  keyboard (3)]
    ↳ ipts 045E:0020                          	id=12	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=15	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=16	[slave  keyboard (3)]
    ↳ ADAPTER_D479 Keyboard                   	id=17	[slave  keyboard (3)]
    ↳ ADAPTER_D479 System Control             	id=20	[slave  keyboard (3)]
    ↳ BTLE Precision Mouse Keyboard           	id=22	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard Consumer Control	id=24	[slave  keyboard (3)]
    ↳ ADAPTER_D479 Consumer Control           	id=25	[slave  keyboard (3)]
    ↳ BTLE Precision Mouse Consumer Control   	id=26	[slave  keyboard (3)]
(base) isaul@surface-book-2:~$ 

```

**Comment by Sartharon** [comment]
Your stylus is at least shown as an input

Cause you are not sure please install the patched libwacom package:
https://github.com/jakeday/linux-surface/blob/master/packages/libwacom/libwacom_0.32-surface-1_amd64.deb

Please report back if that helped

**Comment by IsaulGarcia** [comment]
I reinstalled the kernel with the patched libwacom packages and realized that I already installed them the first time around .After reinstalling the pen is still not detected when trying to pair it.

**Comment by Sartharon** [comment]
Oh you mean your bluetooth connection to the pen for the buttons?
Is you pen working then? If not is your touch working?
The side button should work anyway not sure about the Top button though.
I dont think connecting to the pen via bluetooth is a thing on linux I might be wrong though.

**Comment by IsaulGarcia** [comment]
Yes i'm trying to connect it via Bluetooth. Touch works fine , however the pen works only when I use in it windows, but will not connect in Linux.  The pen doesn't even display as a option to connect on the laptop. I didn't know there was an other options available for pens other than bluetooth? Is there other ways to connect a pen?

**Comment by Sartharon** [comment]
The pen doesnt need bluetooth to write on the screen or send the side button click. You should be able to use the pen as a mouse. (Same for windows).

**Comment by IsaulGarcia** [comment]
Oh, Well when I click the buttons or bring the pen to the screen nothing happens, thats why I thought I needed to connect it.

**Comment by Sartharon** [comment]
Weird, is the pen working in windows?

**Comment by IsaulGarcia** [comment]
Well I'm an idiot ,when the pen wasn't working at first I took apart the battery and put it in backwards. I put it in the right way and works perfect now. The battery has been in backwards the past couple days....
