### ISSUE TITLE
Collecting IPTS device IDs

### ISSUE THREAD

**Issue by qzed** [jakeday/linux-surface#513]
Hi all, I'm currently working on getting the libwacom changes in this repo upstream (see also [this discussion](https://github.com/linuxwacom/libwacom/issues/89)). For that we need to figure out which device IDs belong to which model, your help here would be much appreciated.

To help out, you simply have to run `sudo evtest` (or alternatively `sudo evemu-record`), look at the list of input devices and report back with the touchscreen device id. For example on the Surface Book 2 (13.5") that list contains
```
ipts 045E:0021
ipts 045E:0021 UNKNOWN
ipts 045E:0021 Touchscreen
ipts 045E:0021 Mouse
```

In this case, the relevant part would be `ipts 045E:0021`. All we need is this ID and your model number (e.g. _Surface Book 2 (13.5"): `ipts 045E:0021`_).

Thanks!

**Comment by krimple** [comment]
Surface Book 2 15" - 512GB disk, 16GB Ram, i7, DGPU 


```
/dev/input/event22:	ipts 045E:0020 Touchscreen
```

**Comment by kitakar5525** [comment]
Surface Book with Performance Base: `ipts 1B96:005E`
(This is the exact model number, maybe the same ID as most-original SB1, but just in case)

Thank you for your work as always!

**Comment by Predatux** [comment]
/dev/input/event21:     ipts 1B96:006A UNKNOWN
/dev/input/event22:     ipts 1B96:006A
/dev/input/event23:     ipts 1B96:006A Touchscreen
/dev/input/event24:     ipts 1B96:006A Mouse
/dev/input/event25:     ipts 1B96:006A UNKNOWN

Surface Pro 4

**Comment by yjzzjy4** [comment]
Surface pro 6 i5-8250U 8G RAM 256G ROM

```bash
Available devices:
/dev/input/event0:	        Lid Switch
/dev/input/event1:	        Video Bus
/dev/input/event2:	        Microsoft Surface Type Cover Keyboard
/dev/input/event3:	        Microsoft Surface Type Cover Mouse
/dev/input/event4:	        Microsoft Surface Type Cover Consumer Control
/dev/input/event5:	        Microsoft Surface Type Cover Touchpad
/dev/input/event6:	        ipts 045E:001F UNKNOWN
/dev/input/event7:	        ipts 045E:001F
/dev/input/event8:	    	ipts 045E:001F Touchscreen
/dev/input/event9:	        ipts 045E:001F Mouse
/dev/input/event10:	ipts 045E:001F UNKNOWN
/dev/input/event11:	HDA Intel PCH Mic
/dev/input/event12:	HDA Intel PCH Headphone
/dev/input/event13:	gpio-keys
/dev/input/event14:	gpio-keys
```

That's all output I got, not sure which is the wanted one, but I'm guessing is the `ipts 045E:001F`, and BTW,  can I get a tutor of enabling suspend/hibernate? really frustrated when I can't get it down, or simply because surface pro 6 is uncompatible with some modules for it's 2 in 1 device? And I really appreciate you work, really fabulous!

**Comment by qzed** [comment]
Thank you all, looks like we've got a complete list!

**Comment by qzed** [comment]
@yjzzjy4 You might want to ask around on the [gitter](https://gitter.im/linux-surface/support) chat about your suspend issues, I'm sure someone there can point you in the right direction.

**Comment by yjzzjy4** [comment]
@qzed Thanks a lot. Again, appreciate your good job.
