### ISSUE TITLE
No power indicator

### ISSUE THREAD

**Issue by Tarallik** [jakeday/linux-surface#517]
The Surface 3 has no battery status, can't see it.
![IMG_5399](https://user-images.githubusercontent.com/51668270/59207579-96f5c800-8ba7-11e9-939e-a280de87ac76.JPG)

**Comment by BlauerHunger** [comment]
Which kernel version are you using? (You can find out by running `uname -r`)

**Comment by Tarallik** [comment]
> Which kernel version are you using? (You can find out by running `uname -r`)

4.15.0-51-generic

**Comment by BlauerHunger** [comment]
Ok, that looks like you aren't running jakedays kernel, which btw. works fine on my surface 3. 
How did you install it? Did you reboot afterwards?

**Comment by Tarallik** [comment]
> Ok, that looks like you aren't running jakedays kernel, which btw. works fine on my surface 3.
> How did you install it? Did you reboot afterwards?


I installed it, normally I think... do you think I need to reinstall the OS again?
(yes, however, I reboot it, nothing has changed)

**Comment by BlauerHunger** [comment]
Can you select the jakeday kernel in grub? If it is installed but doesn't show up there, you have to recreate the grub config (`sudo update-grub` on Ubuntu). If it shows up but doesn't work, you have to sign it for secureboot or disable it in bios.

**Comment by Tarallik** [comment]
Ookay people: unfortunately Surface has unsupported hardware, the battery does not have a linux driver and there is no hope for Microsoft to publish one in the future. But there is a way of salvation...
THIS: **https://github.com/jakeday/linux-surface**
I solved it with this.
Anyway thanks a lot for the support BlauerHunger :)
