### ISSUE TITLE
Please Explain what to do for this step little in-detail

### ISSUE THREAD

**Issue by SirSharanChakradhar** [jakeday/linux-surface#518]
Hi Guys,

Newbie here.

sudo dpkg -i linux-headers-[VERSION].deb linux-image-[VERSION].deb linux-libc-dev-[VERSION].deb

This is the final step for pre-built kernel 

I'm not sure what version number I have to change. The new releases files shows amd at the end. I'm pretty confused. 

Please give me the command if you thin that works. 

Thanks In advance for explaining.

**Comment by condemnedmeat** [comment]
Step 4 is the final step in the [readme](https://github.com/jakeday/linux-surface/blob/master/README.md).
>    Reboot on installed kernel.
The setup script will handle installing the latest kernel for you.

[VERSION] is the [release version](https://github.com/jakeday/linux-surface/releases). If you download from there you can use terminal or double-click on the individual files.

**Comment by qzed** [comment]
Also: Don't get confused with the `amd64` part, that's just the architecture, as in 64-bit x86 (sometimes also referred to as x86_64). The only thing this has to do with AMD as company is that AMD "invented" the 64-bit extension to x86, it _does not_ mean that its exclusive to AMD processors or something like that.
