### ISSUE TITLE
Surface Pro 4: Unable to install Virtual Box

### ISSUE THREAD

**Issue by abutre** [jakeday/linux-surface#52]
Hello. The issue with Virtual Box seems to be solved (#33), but reconfigure still fails while running check_module_dependencies.sh ([check_module_dependencies.log](https://github.com/jakeday/linux-surface/files/1518152/check_module_dependencies.log)).
It seems caused by some links setup on kernel installation on /lib/modules/4.14.2-jakeday-surface :

build -> /home/jake/ipts/build/kernel
source -> /home/jake/ipts/build/kernel

**Comment by jakeday** [comment]
I'll take a look at it.

**Comment by npjohnson** [comment]
@jakeday The issue this refers to is actually bigger than just VBox, a lot of DKMS drivers fail to compile b/c of bad symlinks to your local machine's home directory. I am not entirely sure why these are present, however.

How are you packaging the debs? There are a few ways to do so, and not all of them are meant for distribution.

**Comment by jakeday** [comment]
@abutre Can you try the latest 4.14.7 build? This should hopefully be fixed.

**Comment by abutre** [comment]
@jakeday thank you very much ! It is working perfectly.
