### ISSUE TITLE
[Surface Pro 2017] Linux 5.1: No battery stats

### ISSUE THREAD

**Issue by minikN** [jakeday/linux-surface#529]
Hello. I've compiled the 5.1 kernel today using the provided config. I changed a couple of lines in the config. [Here](https://www.diffchecker.com/ijwBet0k) is a `diff`. So far, everything seems to be working.

Here is the output of `lsmod | grep acpi`
```
~   lsmod | grep acpi
surface_acpi           49152  0
acpi_thermal_rel       16384  1 int3400_thermal
acpi_pad              184320  0
hid                   131072  8 usbhid,hid_multitouch,hid_sensor_hub,intel_ipts,intel_ishtp_hid,hid_generic,uhid,surface_acpi
```

However: `ls -la /sys/class/power_supply/`
```
~   ls -la /sys/class/power_supply/
insgesamt 0
drwxr-xr-x  2 0 22. Jun 23:54 .
drwxr-xr-x 72 0 22. Jun 23:54 ..
lrwxrwxrwx  1 0 22. Jun 23:54 ADP1 -> ../../devices/LNXSYSTM:00/ACPI0003:00/power_supply/ADP1
````

I expected there to be a `BAT0` entry.

`acpi -V`:
```
~   acpi -V
Adapter 0: off-line
Cooling 0: Processor 0 of 10
Cooling 1: GEN7 no state information available
Cooling 2: Processor 0 of 10
Cooling 3: B0D4 no state information available
Cooling 4: Processor 0 of 10
Cooling 5: intel_powerclamp no state information available
Cooling 6: Processor 0 of 10
Cooling 7: GEN1 no state information available
Cooling 8: Processor 0 of 10
Cooling 9: GEN5 no state information available
Cooling 10: Processor 0 of 10
Cooling 11: pch_skylake no state information available
Cooling 12: Processor 0 of 10
Cooling 13: x86_pkg_temp no state information available
Cooling 14: CHRG 4 of 4
Cooling 15: INT3400 Thermal no state information available
Cooling 16: Processor 0 of 10
Cooling 17: GEN2 no state information available
```

[dmesg](https://0x0.st/z2PB.log)
[dmesg --level=err,warn](https://0x0.st/z2PS.log)

Thanks in advance.

**Comment by StollD** [comment]
Try compiling with the changes from #519 

It seems that there were some changes in 5.1.8 that need changes in the surface_acpi module as well.

**Comment by qzed** [comment]
@StollD is correct, there are some changes on the later 5.1 (if I'm not mistaken specifically 5.1.10, 4.19.51 and  later, I think it should still work with 5.1.9 though) versions to DMA that prevent the driver from loading. The changes in the PR fix that. Can you try with the patches and the latest 5.1 version?

**Comment by minikN** [comment]
@StollD @qzed Thanks for the input, that actually did the trick.

I was secretly hoping for the sleep issue I was description in the other issue to go away, but no luck there.

**Comment by kbrowder** [comment]
Wow the timing of this is great, just installed Fedora 30 on my surface pro 2017 and needed this, thanks!

Stupid question, and this is probably the wrong place for it, but can these kernel patches be pushed to Linus?

**Comment by qzed** [comment]
@kbrowder I'm working on that, but I don't have much time at the moment, so it's going slowly and part by part. Currently waiting on responses for a fix required for the surface-acpi module and the button patches.

**Comment by qzed** [comment]
@minikN Nice, let's track that problem in the other issue.
