### ISSUE TITLE
Surface Pro 4:  hibernate broken on 4.14.2 (Nov. 27) kernel

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#53]
Thanks again jakeday for your work, making my surface finally usable on linux.  Hibernate is very important to me with my mobile computing lifestyle, and this is one of the big reasons why the kernel is so important for me.

I updated to the 4.14.2 kernel (uploaded on Nov. 27) a couple of days ago and since then have had issues shutting down the computer with `sudo systemctl hibernate`.  What happens is that the machine hangs while shutting down so I have to hold the button for 15 seconds.  Often, upon boot it turns out that the previous state is recovered.  So hibernate "works" sometimes but the shutdown process always hangs.  I was not experiencing this with the 4.14.0 kernel.

The reason I use `sudo systemctl hibernate` is because, upon update of the kernel the button for suspend in Gnome shell disappeared.  It seems as though Gnome shell knows something is wrong.

I confirmed that all my links are in place:
```
=> ll /lib/systemd/system-sleep/hibernate.sh 
-rwxr-xr-x 1 root root 435 Nov 30 20:39 /lib/systemd/system-sleep/hibernate.sh*
=> ll /etc/systemd/system/suspend.target
lrwxrwxrwx 1 root root 36 Nov  6 16:18 /etc/systemd/system/suspend.target -> /lib/systemd/system/hibernate.target
=> ll /etc/systemd/system/systemd-suspend.service
lrwxrwxrwx 1 root root 45 Nov  6 16:20 /etc/systemd/system/systemd-suspend.service -> /lib/systemd/system/systemd-hibernate.service
```

Unfortunately, I deleted the packages for the 4.14.0 kernel.  Someone wouldn't happen to have them laying around would they?

**Comment by tcinbis** [comment]
@thekswenson I think I have the same problem, while running Arch linux on my  
Surface Pro 4. 
When I close my typecover it will turn of the display and run all commands specified in `hibernate.sh`.
But I can tell from my type cover, that the machine is still on. I am not quite sure, whether this is a supposed behavior (still quite new to this)?

**Comment by thekswenson** [comment]
I would love to go back to the 4.14.0 kernel if possible...
   does anybody have the .deb packages?

**Comment by tcinbis** [comment]
@thekswenson I guess you can just checkout the commit before the update to a new mainline kernel version and compile the kernel.

**Comment by thekswenson** [comment]
:)  @tcinbis  I suppose I was looking for the easy way out.

**Comment by jakeday** [comment]
@thekswenson Use my 4.14.4 build. Should give you the behavior you're looking for.

**Comment by thekswenson** [comment]
Yes @jakeday !  Very nice sir.
