### ISSUE TITLE
Timeline for camera integration?

### ISSUE THREAD

**Issue by han-so1omon** [jakeday/linux-surface#530]
Would love to use the surface book 2 with arch linux. Any idea on a timeline for camera integration? That's all that is missing for me to pull the trigger.

**Comment by SirSharanChakradhar** [comment]
I tried with Archlabs distro & I dont think it will work with Arch. I tried the setup from @dmhacker (https://github.com/dmhacker/arch-linux-surface), didnt work for me. Please let me know the steps that you try and commands(for a newbie like me).

**Comment by qzed** [comment]
@SirSharanChakradhar won't work on any distribution at the moment, the support in the kernel is missing.

Unfortunately I can't work on this right now due to some University stuff I have to do, so I can't give any concrete timeline. Also see #145 for details.
