### ISSUE TITLE
[Surface Book2]: No WiFi with Kernel 5.1

### ISSUE THREAD

**Issue by thmichel** [jakeday/linux-surface#532]
Hi,

I am running Fedora and compiled the kernel with the latest patches from this github. With 5.0, everything runs fine, with 5.1, the Wifi doesn't work. It tries to associate but always fails with the message
association to bssid xx:xx:xx:xx:xx:xx failed

Anyone else experiencing this? I did run the setup  script to install the latest firmware so that should not be the issue - and booting into the 5.0 kernel immediately resolves the problem.

**Comment by StollD** [comment]
Being unable to connect to certain wifi networks is the result of a patch from the 5.2 in-dev tree, that was added to the fedora sources between 5.1.6 and 5.1.7. I had the same problems with F30 and SB2 - I was unable to connect to the wifi at my university. It doesn't seem to be related to the surface hardware directly, but to the vendor hardware that the access point uses and how it identifies itself.

This is the patch in question: https://src.fedoraproject.org/rpms/kernel/blob/f30/f/Buffer-overflow-read-checks-in-mwifiex.patch

This looks like it could fix the issue (and it is on it's way to upstream as it seems), but I haven't had the chance to test it yet: https://patchwork.kernel.org/patch/10996895/

What I can confirm as working though, is just reverting the two commits that Fedora patched in, like this: https://github.com/StollD/fedora-linux-surface/blob/master/patches/0002-wifi.patch

Again, it doesn't seem to be a surface specific issue, but we happen to use the WiFi chipset that had it's driver changed. Any other device with a marvell cipset would probably show the same issues.

**Comment by thmichel** [comment]
Thanks, using the patch that reverts the commits fixed the issue,

**Comment by StollD** [comment]
Just for reference, I tried the two commits from the patchwork link I posted, and applying them instead of the revert fixes the issue as well.
