### ISSUE TITLE
Kernel patches for the Microsoft Surface Precision Mouse

### ISSUE THREAD

**Issue by scotty-c** [jakeday/linux-surface#541]
This is more of a question than an issue. I wondered if you would accept the patches suggest here  https://bugzilla.kernel.org/show_bug.cgi?id=199461 into your project to get the mouse working on Linux

**Comment by scotty-c** [comment]
closing due to patches being merged in the upstream kernel

**Comment by Hedronmx** [comment]
@scotty-c 
Hello, this might be off topic but im so frustrated... Do you know how can I use the fixes on my system? Its a desktop running elementary os juno with kernel 5.3.8-050308-generic.

Thank you for your time.

**Comment by scotty-c** [comment]
@Hedronmx The kernel patches to allow the mouse to work properly have been merged so that version of kernel should work. I am running ubuntu 19.04 with 5.3.6 from @qzed fork and the mouse works with no issues. What are the errors you are seeing in the logs?

**Comment by Hedronmx** [comment]
Right now I am using the mouse with my work around, but the problem right now is the scroll wheel. After some time the scroll wheel gets super slow, like super super slow. On the forum you posted, there was discussion on the same wheel problem.
