### ISSUE TITLE
Surface Pro 4: Touch Screen Problem

### ISSUE THREAD

**Issue by laomms** [jakeday/linux-surface#55]
the touch screen will lost after use about 10 minutes

**Comment by tcinbis** [comment]
@laomms Which ipts firmware do you use?

**Comment by laomms** [comment]
v78   on surface pro4

**Comment by thekswenson** [comment]
My SP4 touchscreen works pretty well.  Touch input may stop working if I do many touches at once...
  often rotating the screen (by just rotating it in my hands) will restore touch, but not always.

See related issues:
https://github.com/jakeday/linux-surface/issues/31
https://github.com/jakeday/linux-surface/issues/48

**Comment by jakeday** [comment]
I re-opened #31 to continue debugging this issue. This is a duplicate.

**Comment by laomms** [comment]
I use ipts78 in phoenix android_x86 os on sp4 , it's work perfect。 touchpad, wake up, touchscreen and so on, touch screen can use about 10 minute, then lost, when input  command rmmod intel_ipts and modprobe intel_ipts, touchscrren  will restore normal. I use it in android_x86 kernel version 4.9.24-android-x86_64.

**Comment by cabban** [comment]
have problem with all android os :( its a shame could have been awesome now its like android 14 on android os . cant seem to find anything to get it working
