### ISSUE TITLE
Surface Go Bluetooth problems

### ISSUE THREAD

**Issue by codev** [jakeday/linux-surface#552]
My Logitech keyboard and Lenovo keyboard both experience lots of dropouts using the latest version of jakeday. The keyboard's disconnect randomly and often there is delay or repeated keypresses when typing. This didn't happen previously but rolling back the kernel to 4.x didn't seem to solve anything.

**Comment by korakios** [comment]
Same issue like #533 ? In my case I have to pair the device in every reboot

**Comment by skogsmaskin** [comment]
Are you on a 2.4Ghz wifi network? Using 2.4Ghz wifi and bluetooth at the same time will give you a bad time, because they interfere with each other (known issue with the chip/ath10k driver). 5Ghz networks doesn't have this problem.

**Comment by codev** [comment]
That seems to have fixed it! I changed to our 5GHz network and haven't had a bluetooth disconnect since. Might still be a pain while traveling but at least it works at home now.
