### ISSUE TITLE
Keyboard not working after installation

### ISSUE THREAD

**Issue by lukezak99** [jakeday/linux-surface#563]
I am using the surface laptop 2. After i rebooted my system the keyboard still did not work.

**Comment by Xcsss** [comment]
I got the same issue.

**Comment by alturismo** [comment]
same here on surface laptop (1)

running 19.04, applied the setup.sh, reboot ...

mouse from start ok, wifi from start ok, touchscreen ok, but no keyboard ...

**Comment by alturismo** [comment]
made another try now

setup.sh
downloaded kernel
self compiled (5.1.21)

all with the same result on 19.04, keyboard not working, just as update

**Comment by alturismo** [comment]
ok, another update, when i apply this driver from this conversation it works.

would like to know if its possible to switch to this version for 19.04 disco or an easy way to replace the drivers ?

https://github.com/jakeday/linux-surface/issues/470#issuecomment-485086579

following this link from @qzed repo

https://github.com/qzed/linux-surfacegen5-acpi

so after modprobe -r ... and insmod surfacegen5_acpi.ko keyboard etc works, but not persistent.

**Comment by qzed** [comment]
Let's move this to #502, same issue.

Also please try the 5.2.5 and 5.2.14 kernels and see if it works there, those should contain a fix that is already in the module, so if the module works, these kernels should too (and report back in the other issue). Non-persistence across reboots for the module is to be expected. You'd have to blacklist the surface_acpi module built into the kernel to achieve persistence across reboots.
