### ISSUE TITLE
Error: You need to load the Kernel first

### ISSUE THREAD

**Issue by ImCruel** [jakeday/linux-surface#575]
I ran the script on Linux Mint 19.2, but if I try to start the new version I get the following error:

```
error: /boot/vmlinuz-5.1.15-surface-linux-surface has invalid signature.
Loading initial ramdisk ...
error: you need to load the kernel first.
```

I would greatly appreciate any help, I have already tried removing and reinstalling the kernel.
During the installation process I followed the recommended procedures.

Edit: booting in recovery mode produces the same issue.

**Comment by StollD** [comment]
You have to sign the kernel for secure boot: https://github.com/jakeday/linux-surface/blob/master/SIGNING.md

Alternatively, disable secure boot in the BIOS.

**Comment by ImCruel** [comment]
Thank you very much for your help, kind sir :)
