### ISSUE TITLE
Pen Rotation wrong

### ISSUE THREAD

**Issue by ImCruel** [jakeday/linux-surface#577]
Dear community, while my touchscreen works fine when rotating my device, the surface pen does not. When rotating clockwise by 90 degrees, the cursor of the pen is located 90 degrees counterclockwise from the actual position.

Trying to change the Coordinate Transformation Matrix of the Pen in xinput yielded the following error:
```
xinput set-prop 'Surface Pen Keyboard' 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1
Error of failed request: BadMatch (invalid parameter attributes)
Major opcode of failed request: 131 (XInputExtension)
Minor opcode of failed request: 57 ()
```

**Comment by thebitstick** [comment]
That solution is exclusive to X11. I'm experiencing the same problem on Wayland. Please re-open this isuse.
