### ISSUE TITLE
Surface Book 1 19.10 Kubuntu

### ISSUE THREAD

**Issue by daddacorn2019** [jakeday/linux-surface#587]
Hi ive just upgraded to kubuntu 19.10 from 19.04 and now nothing is working as far as touchscreen or the surface pen. The whole installation went fine except the touchscreen nor pen functionality. can any confirm this same issue or is it possibly im just doing something wrong but ive ran the installation twice already. I would appreciate some help if somebody knows how to, thankyou.

**Comment by kitakar5525** [comment]
I'm using SB1, too.

#### Known issues for touchscreen (IPTS driver)
Here are the known issues for touchscreen (IPTS driver):

1. GPU hang on resuming from suspend (#573)

following issues may be related to the issue:
  - IPTS breaks `no_console_suspend` (https://github.com/jakeday/linux-surface/issues/544#issuecomment-526656591)
  - occasionally IPTS will break resuming from suspend (`RIP: 0010:kmem_cache_alloc_trace`) (https://github.com/jakeday/linux-surface/issues/544#issuecomment-513531566)

2. `no_feedback` causes touch input unusable on some SB1 (#374)

3. Cannot resume touch after suspend/resume (or after unloading mei mei_me) (#448)

#### In your case
In your case, the cause might be No. 2.

Anyway, first of all, check what kernel you're using (copy-paste this script into your terminal):
```bash
# Get CPU model (script from neofetch)
awk -F '\\s*: | @' \
'/model name|Hardware|Processor|^cpu model|chip type|^cpu type/ {
cpu=$2; if ($1 == "Hardware") exit } END { print cpu }' "/proc/cpuinfo"; \
\
cat /etc/os-release | grep NAME; \
echo -n "uname -r: "; uname -r; \
sudo grep -H . /sys/devices/virtual/dmi/id/product_name; \
sudo grep -H . /sys/devices/virtual/dmi/id/product_sku;
```

**Comment by masenocturnal** [comment]
i am on a SB 1 Kubuntu 19.10 also and aside from the suspend and wifi issues which are known, I haven't had an issue with touch.

**Comment by tmarkov** [comment]
My guess: 19.10 comes with newer stock kernel, and so it gets loaded by default instead of the modified one. Make sure that GRUB loads the -surface kernel (The output of`uname -a` should contain `-surface`)

**Comment by daddacorn2019** [comment]
Ok your right I ran all the steps and I'm still getting back 5.3.0-19 generic kernel, can you explain to me how to get it to except the other, asside from what I read I have no idea other then super basic stuff of what I'm doing so if any of you can please guide me through it I'd super appreciate your time.

**Comment by daddacorn2019** [comment]
ok so i literally installed this three times everything done exactly 
how its supposed to but in kubuntu 19.10 its not switching out kernels 
only in 19.04 can i get everything to work correctly. can anybody help 
me out please?

**Comment by tmarkov** [comment]
@daddacorn2019 
So in linux, you can install multiple kernels alongside one another, and choose which one to load at boot.
By default, the bootloader chooses the newest kernel version, so in this case, you installed the kernel successfully. However, since it's not newer version than the one built in Ubuntu 19.04, the Ubuntu one gets loaded.

Did you use the newest custom kernel from https://github.com/qzed/linux-surface?

If so, and you're still booting into Ubuntu's kernel, look at this http://tipsonubuntu.com/2019/10/06/configure-startup-boot-menu-ubuntu-19-10/ on how to change GRUB boot defaults.

**Comment by daddacorn2019** [comment]
Ya I loaded the new kernel did the certificate signing end everything  but it still refers to the 5.3 kernel when I go to the kernel file location the surface kernel is sitting right beside  the original 5.3 kernel, what's wierd is I even had to update the surface kernel today but again it's just not the kernel that's officially being used by my computer but it's there, I'll check out the grub customizer but as far as switching them out will it show me how to do that? I know how to get to the grub defaults I've been reading alot but I just can't figure out how to replace the existing one for the surface kernel.

**Comment by daddacorn2019** [comment]
I'm gonna close this issue but I haven't fixed my problem
