### ISSUE TITLE
Unable to apply to kernel 5.3 ubuntu

### ISSUE THREAD

**Issue by calgrainger1990** [jakeday/linux-surface#588]
Upgraded to ubuntu 19.10 and attempted to upgrade the kernel.

When i applied everything to 5.3 headers etc the system would not boot it appeared to have halted them booted back to the grub menu.

5.1 works as expected but 5.3 does not appear to want to boot.

this is on a SL1 8gb, core i5, 256gb model running ubuntu 19.10. Only thing different is i've switched from Bash to ZSH

**Comment by calgrainger1990** [comment]
do you know if there will be precompiled version of the kernel I'd rather no have to compile it.

**Comment by StollD** [comment]
Check this out for prebuilt versions: https://github.com/qzed/linux-surface/releases

From what I have read on other issues, it seems that disabling the TPM in the BIOS might be required to get the surface to boot with 5.3

**Comment by calgrainger1990** [comment]
Ty Ty

this is exactly what I was looking for :P

**Comment by calgrainger1990** [comment]
this worked thank you guys
