### ISSUE TITLE
Current repo status

### ISSUE THREAD

**Issue by davejrt** [jakeday/linux-surface#590]
Hi

Thank you to all of the current and past contributors who have worked on this. I was just wondering if the repo is still in development, or if the maintainers have decided to move on to new projects?  

I am aware there is fork of this repo also, but figured this is the best place to ask Jake and others.

**Comment by CodingSpiderFox** [comment]
Also, I wonder why the issue tracker on the fork of @qzed is not enabled

**Comment by jakeday** [comment]
@davejrt @CodingSpiderFox I had to take a break from this project, but I do want you to know that there are big changes planned and it will be active again very soon!

**Comment by versipellis** [comment]
FYI to @jakeday and everyone else who aren't aware yet - I think the codebase got forked and is now being community-maintained here: https://github.com/linux-surface/linux-surface
