### ISSUE TITLE
installing on surface laptop 3 does not fix track pad and keyboard

### ISSUE THREAD

**Issue by xdumaine** [jakeday/linux-surface#591]
I installed this on a surface laptop 3 15 in which came out this week. Unfortunately I did not resolve issues with the trackpad and keyboard (specifically that they do not work at all). I did also try the 15.3 kernel from the fork of this repo and got the same results. If this is still active or if anyone is interested in helping I can get more detailed information about the machine. At this point I'm not going to attach them because it seems like the repo is dead.

**Comment by StollD** [comment]
The repo is not dead. Development currently happens on qzeds fork, because jake seems to be busy, but this is still used for issue tracking across both versions.

Since the SL3 is new, you should probably post an acpidump (`sudo acpidump > acpidump.out`) and the kernel log from when you tried with the latest 5.3.6 surface kernel (`dmesg > dmesg.txt`)

But those are just the basic steps to get any information about the problem, nowhere near a fix yet.

**Comment by xdumaine** [comment]
Awesome, thanks, I'll do that!

**Comment by qzed** [comment]
@xdumaine can upload the output of `ls /sys/bus/acpi/devices` and `ls /sys/bus/platform/devices`?

**Comment by qzed** [comment]
Also see https://github.com/qzed/linux-surfacegen5-acpi/issues/22 for the relevant issue on surface-acpi.

**Comment by heapwolf** [comment]
hey @xdumaine how did you fix the `ima: error communicating to tpm chip` error? I get that on boot.

**Comment by qzed** [comment]
@heapwolf I think the last error can be fixed by blacklisting `intel_lpss` via the kernel boot parameter `modprobe.blacklist=intel_lpss_pci` (as suggested in https://github.com/jakeday/linux-surface/issues/589#issuecomment-545522548).

**Comment by heapwolf** [comment]
Does this sequence of commands look correct?

![image](https://user-images.githubusercontent.com/136109/67642660-3f65b800-f90e-11e9-871f-17e003014543.png)

**Comment by qzed** [comment]
I think you need to add the `modprobe ...` to the `linux ...` line, for example after `splash`

**Comment by heapwolf** [comment]
success! I will capture `ls /sys/bus/acpi/devices` and `ls /sys/bus/platform/devices` next.

**Comment by xdumaine** [comment]
I can get that tonight after I get the baby to bed.

**Comment by qzed** [comment]
Thank you! I'll try to test a patch to fix the intel-lpss-pci/boot issue and include it in the repo if it works. See https://github.com/qzed/linux-surface-kernel/issues/12 for some additional links (this bug is already taken care of upstream).

**Comment by heapwolf** [comment]
Well I got past the ubuntu installer, but now after selecting ubuntu in grub, it just hangs. all I see is an underscore and a black screen.

**Comment by xdumaine** [comment]
@qzed Here's the output of those- 

<pre><font color="#4E9A06"><b>xdumaine@xsl3</b></font>:<font color="#3465A4"><b>~</b></font>$ ls /sys/bus/acpi/devices
<font color="#06989A"><b>ACPI0007:00</b></font>  <font color="#06989A"><b>ACPI000E:00</b></font>  <font color="#06989A"><b>AMDI0011:01</b></font>  <font color="#06989A"><b>device:00</b></font>  <font color="#06989A"><b>device:08</b></font>  <font color="#06989A"><b>device:10</b></font>  <font color="#06989A"><b>device:18</b></font>  <font color="#06989A"><b>device:20</b></font>    <font color="#06989A"><b>LNXPOWER:05</b></font>  <font color="#06989A"><b>LNXTHERM:04</b></font>  <font color="#06989A"><b>MSFT0101:00</b></font>  <font color="#06989A"><b>MSHW0184:00</b></font>  <font color="#06989A"><b>PNP0501:03</b></font>  <font color="#06989A"><b>PNP0C02:03</b></font>
<font color="#06989A"><b>ACPI0007:01</b></font>  <font color="#06989A"><b>ACPI0010:00</b></font>  <font color="#06989A"><b>AMDI0020:00</b></font>  <font color="#06989A"><b>device:01</b></font>  <font color="#06989A"><b>device:09</b></font>  <font color="#06989A"><b>device:11</b></font>  <font color="#06989A"><b>device:19</b></font>  <font color="#06989A"><b>device:21</b></font>    <font color="#06989A"><b>LNXSYBUS:00</b></font>  <font color="#06989A"><b>LNXTHERM:05</b></font>  <font color="#06989A"><b>MSHW0040:00</b></font>  <font color="#06989A"><b>PNP0000:00</b></font>   <font color="#06989A"><b>PNP0800:00</b></font>  <font color="#06989A"><b>PNP0C02:04</b></font>
<font color="#06989A"><b>ACPI0007:02</b></font>  <font color="#06989A"><b>AMD0004:00</b></font>   <font color="#06989A"><b>AMDI0020:01</b></font>  <font color="#06989A"><b>device:02</b></font>  <font color="#06989A"><b>device:0a</b></font>  <font color="#06989A"><b>device:12</b></font>  <font color="#06989A"><b>device:1a</b></font>  <font color="#06989A"><b>device:22</b></font>    <font color="#06989A"><b>LNXSYBUS:01</b></font>  <font color="#06989A"><b>LNXTHERM:06</b></font>  <font color="#06989A"><b>MSHW0084:00</b></font>  <font color="#06989A"><b>PNP0100:00</b></font>   <font color="#06989A"><b>PNP0A08:00</b></font>  <font color="#06989A"><b>PNP0C02:05</b></font>
<font color="#06989A"><b>ACPI0007:03</b></font>  <font color="#06989A"><b>AMDI0010:00</b></font>  <font color="#06989A"><b>AMDI0020:02</b></font>  <font color="#06989A"><b>device:03</b></font>  <font color="#06989A"><b>device:0b</b></font>  <font color="#06989A"><b>device:13</b></font>  <font color="#06989A"><b>device:1b</b></font>  <font color="#06989A"><b>LNXPOWER:00</b></font>  <font color="#06989A"><b>LNXSYSTM:00</b></font>  <font color="#06989A"><b>LNXTHERM:07</b></font>  <font color="#06989A"><b>MSHW0091:00</b></font>  <font color="#06989A"><b>PNP0103:00</b></font>   <font color="#06989A"><b>PNP0B00:00</b></font>  <font color="#06989A"><b>PNP0C02:06</b></font>
<font color="#06989A"><b>ACPI0007:04</b></font>  <font color="#06989A"><b>AMDI0010:01</b></font>  <font color="#06989A"><b>AMDI0020:03</b></font>  <font color="#06989A"><b>device:04</b></font>  <font color="#06989A"><b>device:0c</b></font>  <font color="#06989A"><b>device:14</b></font>  <font color="#06989A"><b>device:1c</b></font>  <font color="#06989A"><b>LNXPOWER:01</b></font>  <font color="#06989A"><b>LNXTHERM:00</b></font>  <font color="#06989A"><b>LNXVIDEO:00</b></font>  <font color="#06989A"><b>MSHW0110:00</b></font>  <font color="#06989A"><b>PNP0200:00</b></font>   <font color="#06989A"><b>PNP0C01:00</b></font>  <font color="#06989A"><b>PNP0C02:07</b></font>
<font color="#06989A"><b>ACPI0007:05</b></font>  <font color="#06989A"><b>AMDI0010:02</b></font>  <font color="#06989A"><b>AMDI0030:00</b></font>  <font color="#06989A"><b>device:05</b></font>  <font color="#06989A"><b>device:0d</b></font>  <font color="#06989A"><b>device:15</b></font>  <font color="#06989A"><b>device:1d</b></font>  <font color="#06989A"><b>LNXPOWER:02</b></font>  <font color="#06989A"><b>LNXTHERM:01</b></font>  <font color="#06989A"><b>MAX34417:00</b></font>  <font color="#06989A"><b>MSHW0124:00</b></font>  <font color="#06989A"><b>PNP0501:00</b></font>   <font color="#06989A"><b>PNP0C02:00</b></font>  <font color="#06989A"><b>PNP0C02:08</b></font>
<font color="#06989A"><b>ACPI0007:06</b></font>  <font color="#06989A"><b>AMDI0010:03</b></font>  <font color="#06989A"><b>AMDI0040:00</b></font>  <font color="#06989A"><b>device:06</b></font>  <font color="#06989A"><b>device:0e</b></font>  <font color="#06989A"><b>device:16</b></font>  <font color="#06989A"><b>device:1e</b></font>  <font color="#06989A"><b>LNXPOWER:03</b></font>  <font color="#06989A"><b>LNXTHERM:02</b></font>  <font color="#06989A"><b>MAX34417:01</b></font>  <font color="#06989A"><b>MSHW0153:00</b></font>  <font color="#06989A"><b>PNP0501:01</b></font>   <font color="#06989A"><b>PNP0C02:01</b></font>  <font color="#06989A"><b>PNP0C04:00</b></font>
<font color="#06989A"><b>ACPI0007:07</b></font>  <font color="#06989A"><b>AMDI0011:00</b></font>  <font color="#06989A"><b>AMDI0060:00</b></font>  <font color="#06989A"><b>device:07</b></font>  <font color="#06989A"><b>device:0f</b></font>  <font color="#06989A"><b>device:17</b></font>  <font color="#06989A"><b>device:1f</b></font>  <font color="#06989A"><b>LNXPOWER:04</b></font>  <font color="#06989A"><b>LNXTHERM:03</b></font>  <font color="#06989A"><b>MAX34417:02</b></font>  <font color="#06989A"><b>MSHW0162:00</b></font>  <font color="#06989A"><b>PNP0501:02</b></font>   <font color="#06989A"><b>PNP0C02:02</b></font>  <font color="#06989A"><b>PNP0C0D:00</b></font>
<font color="#4E9A06"><b>xdumaine@xsl3</b></font>:<font color="#3465A4"><b>~</b></font>$ ls /sys/bus/platform/devices
<font color="#06989A"><b>ACPI000E:00</b></font>  <font color="#06989A"><b>AMD0004:00</b></font>   <font color="#06989A"><b>AMDI0010:01</b></font>  <font color="#06989A"><b>AMDI0020:00</b></font>  <font color="#06989A"><b>AMDI0060:00</b></font>        <font color="#06989A"><b>efivars.0</b></font>         <font color="#06989A"><b>gpio-keys.1.auto</b></font>  <font color="#06989A"><b>MSHW0040:00</b></font>  <font color="#06989A"><b>MSHW0110:00</b></font>  <font color="#06989A"><b>pcspkr</b></font>      <font color="#06989A"><b>PNP0800:00</b></font>  <font color="#06989A"><b>PNP0C0D:00</b></font>  <font color="#06989A"><b>regulatory.0</b></font>
<font color="#06989A"><b>alarmtimer</b></font>   <font color="#06989A"><b>AMDI0010:00</b></font>  <font color="#06989A"><b>AMDI0011:01</b></font>  <font color="#06989A"><b>AMDI0030:00</b></font>  <font color="#06989A"><b>efi-framebuffer.0</b></font>  <font color="#06989A"><b>gpio-keys.0.auto</b></font>  <font color="#06989A"><b>microcode</b></font>         <font color="#06989A"><b>MSHW0091:00</b></font>  <font color="#06989A"><b>MSHW0153:00</b></font>  <font color="#06989A"><b>PNP0103:00</b></font>  <font color="#06989A"><b>PNP0C04:00</b></font>  <font color="#06989A"><b>reg-dummy</b></font>   <font color="#06989A"><b>serial8250</b></font>
</pre>

**Comment by qzed** [comment]
@xdumaine Thanks!

**Comment by heapwolf** [comment]
And for mine...

```
user@linux:~$ ls /sys/bus/acpi/devices/
ACPI000C:00  device:16  device:2e  device:46  device:5e  device:76  device:8e   INT3407:00   LNXPOWER:03  MSHW0125:00
ACPI000E:00  device:17  device:2f  device:47  device:5f  device:77  device:8f   INT3455:00   LNXPOWER:04  MSHW0153:00
device:00    device:18  device:30  device:48  device:60  device:78  device:90   INT3519:00   LNXPOWER:05  MSHW0184:00
device:01    device:19  device:31  device:49  device:61  device:79  device:91   INT3532:00   LNXPOWER:06  PNP0000:00
device:02    device:1a  device:32  device:4a  device:62  device:7a  device:92   INT3F0D:00   LNXPOWER:07  PNP0100:00
device:03    device:1b  device:33  device:4b  device:63  device:7b  device:93   LNXCPU:00    LNXPOWER:08  PNP0103:00
device:04    device:1c  device:34  device:4c  device:64  device:7c  device:94   LNXCPU:01    LNXSYBUS:00  PNP0A08:00
device:05    device:1d  device:35  device:4d  device:65  device:7d  device:95   LNXCPU:02    LNXSYBUS:01  PNP0B00:00
device:06    device:1e  device:36  device:4e  device:66  device:7e  device:96   LNXCPU:03    LNXSYSTM:00  PNP0C02:00
device:07    device:1f  device:37  device:4f  device:67  device:7f  device:97   LNXCPU:04    LNXTHERM:00  PNP0C02:01
device:08    device:20  device:38  device:50  device:68  device:80  INT0E0C:00  LNXCPU:05    LNXTHERM:01  PNP0C02:02
device:09    device:21  device:39  device:51  device:69  device:81  INT33A1:00  LNXCPU:06    LNXTHERM:02  PNP0C02:03
device:0a    device:22  device:3a  device:52  device:6a  device:82  INT3400:00  LNXCPU:07    LNXTHERM:03  PNP0C02:04
device:0b    device:23  device:3b  device:53  device:6b  device:83  INT3403:00  LNXCPU:08    LNXTHERM:04  PNP0C04:00
device:0c    device:24  device:3c  device:54  device:6c  device:84  INT3403:01  LNXCPU:09    LNXTHERM:05  PNP0C0D:00
device:0d    device:25  device:3d  device:55  device:6d  device:85  INT3403:02  LNXCPU:0a    LNXTHERM:06  PNP0C14:00
device:0e    device:26  device:3e  device:56  device:6e  device:86  INT3403:03  LNXCPU:0b    LNXVIDEO:00  PRP00001:00
device:0f    device:27  device:3f  device:57  device:6f  device:87  INT3403:04  LNXCPU:0c    MAX34417:00  USBC000:00
device:10    device:28  device:40  device:58  device:70  device:88  INT3403:05  LNXCPU:0d    MAX34417:01
device:11    device:29  device:41  device:59  device:71  device:89  INT3403:06  LNXCPU:0e    MAX34417:02
device:12    device:2a  device:42  device:5a  device:72  device:8a  INT3403:07  LNXCPU:0f    MSHW0040:00
device:13    device:2b  device:43  device:5b  device:73  device:8b  INT3403:08  LNXPOWER:00  MSHW0084:00
device:14    device:2c  device:44  device:5c  device:74  device:8c  INT3403:09  LNXPOWER:01  MSHW0091:00
device:15    device:2d  device:45  device:5d  device:75  device:8d  INT3403:0a  LNXPOWER:02  MSHW0114:00
user@linux:~$ ls /sys/bus/platform/devices/
 ACPI000C:00         eisa.0              INT3403:01   INT3532:00         MSHW0114:00   PNP0C14:00
 ACPI000E:00        'Fixed MDIO bus.0'   INT3403:04   intel_rapl_msr.0   MSHW0153:00   reg-dummy
 alarmtimer          INT33A1:00          INT3403:08   microcode          pcspkr        regulatory.0
 coretemp.0          INT3400:00          INT3407:00   MSHW0040:00        PNP0103:00    serial8250
 efi-framebuffer.0   INT3403:00          INT3455:00   MSHW0091:00        PNP0C0D:00    snd-soc-dummy
```

**Comment by qzed** [comment]
@heapwolf Thanks!

**Comment by qzed** [comment]
@heapwolf I assume you've got the 13"/intel model? If so, can you upload an acpidump (`sudo acpidump > acpidump.out`)?

**Comment by heapwolf** [comment]
@qzed 

https://gist.githubusercontent.com/heapwolf/15f6ddb5ee996ce5d47d74f666880624/raw/dd8de1d0b5e550c313f8221f32d77435d78ba6cd/gistfile1.txt

**Comment by qzed** [comment]
Thanks!

**Comment by xdumaine** [comment]
One weird thing I'm noticing is that my speakers play a low static sound on boot as well (after bootloader selects ubuntu)

**Comment by archseer** [comment]
@xdumaine see https://github.com/jakeday/linux-surface/issues/354

**Comment by mistay** [comment]
same for me. how can i support you in getting the keyboard of a surface laptop 3 working?

**Comment by archseer** [comment]
@mistay We're already tracking the changes here: https://github.com/qzed/linux-surfacegen5-acpi/issues/22

I have a set of patches that fixes both the keyboard and the trackpad and I hope to merge into qzed's repo in the next few days.

**Comment by qzed** [comment]
Could someone with the 15" model post the output of `cat /sys/bus/acpi/devices/MSHW0110/path` and `/sys/bus/acpi/devices/MSHW0124/path`?

**Comment by xdumaine** [comment]
@qzed those don't exist, but they do with a `:00` suffix -

<pre><font color="#4E9A06"><b>xdumaine@xsl3</b></font>:<font color="#3465A4"><b>~</b></font>$ cat /sys/bus/acpi/devices/MSHW0110:00/path
\_SB_.WSID
<font color="#4E9A06"><b>xdumaine@xsl3</b></font>:<font color="#3465A4"><b>~</b></font>$ cat /sys/bus/acpi/devices/MSHW0124\:00/path 
\_SB_.I2CC.FINK</pre>

**Comment by mistay** [comment]
> @mistay We're already tracking the changes here: [qzed/linux-surfacegen5-acpi#22](https://github.com/qzed/linux-surfacegen5-acpi/issues/22)
> 
> I have a set of patches that fixes both the keyboard and the trackpad and I hope to merge into qzed's repo in the next few days.

thanks @archseer. i found your feature branch "sl3" in your forked repro (https://github.com/archseer/linux-surfacegen5-acpi/tree/feature/sl3) and tried installing by running jake's 5.1.5-surface kernel (https://github.com/jakeday/linux-surface/releases) cloning your repro, checking-out that feature branch, changing to module/ directory, build ("make") & insmod surface_sam.ko

but ... unfortunatly the keyboard of my surface lapto3 13" still does not work. does it work for you @archseer ?

**Comment by qzed** [comment]
@xdumaine Ah yeah sorry forgot the ':00' suffix. Thanks!

**Comment by qzed** [comment]
@mistay AFAIK in the current state only the touchpad will work. Without going into too much detail: Both touchpad and keyboard work over HID reports, so they're the same as far as the required driver is concerned. Both however require some setup, that again is the same, but at the moment only done manually for the touchpad (mainly for testing). The plan is to auto-detect those HID devices (in case of SL3 keyboard and touchpad) and automatically configure them.

**Comment by archseer** [comment]
@mistay Jake's kernel is outdated. You need to use qzed's fork which is up to date (5.3), but right now the driver still won't work without swapping the HID patch and recompiling the kernel: https://github.com/qzed/linux-surface/pull/17

**Comment by mistay** [comment]
> @mistay Jake's kernel is outdated. You need to use qzed's fork which is up to date (5.3), but right now the driver still won't work without swapping the HID patch and recompiling the kernel: [qzed#17](https://github.com/qzed/linux-surface/pull/17)

aah ok. is it mentioned that one has to use qzed‘s firk instead of jake‘s kernel? in qzed‘s repro it‘s statet that you have to use one of jake‘s (binary/release) kernels.

ok so i‘ll try to build 5.3 ... fingers crossed...

**Comment by mistay** [comment]
> @mistay Jake's kernel is outdated. You need to use qzed's fork which is up to date (5.3), but right now the driver still won't work without swapping the HID patch and recompiling the kernel: [qzed#17](https://github.com/qzed/linux-surface/pull/17)

don‘t think so. as far as i understood @archseer provided support for that keyboard...

**Comment by archseer** [comment]
I added support for both keyboard and the touchpad, but if you build the current commit the keyboard won't work. I'm still developing a few things in the driver.

You can probably just wait a few days for my PR to be complete. At that point qzed will merge it and build a pre-built kernel so you don't have to deal with re-compiling.

**Comment by mistay** [comment]
sorry, i don't get it: so what if i cloned qzed's repro (https://github.com/qzed/linux-surfacegen5-acpi, branch feature sl/3), should the trackpad work?

btw: any news? ;) i'm very looking forward to get that feature, thanks @archseer & @qzed!

**Comment by mistay** [comment]
just cloned https://github.com/qzed/linux-surface-kernel, built kernel with config from https://github.com/qzed/linux-surface-kernel-configs/blob/v5.3/debian-5.3-x86_64.config and tried to boot on surface laptop 3 but hangs immediatly after selecting kernel in grub

{code}
Loading Linux 5.3.0+ ...
Loading initial ramdisk ...

<hangs>
{code}

expected that kernel to boot, what do you think?

**Comment by mistay** [comment]
![IMG_8564](https://user-images.githubusercontent.com/4216953/68552548-6cd75900-0418-11ea-9e2f-8b59c9217c63.jpg)

**Comment by mistay** [comment]
fixed this by unplugging USB keyboard, it now boots, yay!

**Comment by xdumaine** [comment]
@archseer is there anything else I could do to help with this one?

**Comment by archseer** [comment]
@xdumaine My changes has been merged into qzed's kernel mid-Novembe and I've been running Surface Laptop 3 on a daily basis now. It's now hosted at https://github.com/linux-surface/linux-surface

Follow [the install guide](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup) then look at [device specific quirks](https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3)

@mistay I'm pretty sure you were still booting from the normal kernel instead of qzed's, you need to modify your bootloader to start the new kernel. The normal one is missing [this patch](https://github.com/linux-surface/linux-surface/blob/master/patches/5.4/0001-ioremap_uc.patch) so you need to press `e` and then `modeprobe.blacklist=intel_lpss_pci` to get it to boot.
