### ISSUE TITLE
Compilation fails :(

### ISSUE THREAD

**Issue by iddover** [jakeday/linux-surface#6]
Also I've tried to compile the kernel in FC26 but I get this error

make[1]: *** No rule to make target 'firmware/intel/ipts/ipts_fw_config.bin', needed by '__fw_modbuild'.  Stop.
--

MAybe I'm doing somethig wrong because I've never compile kernel before

**Comment by jakeday** [comment]
You need to grab the file from the git repo and copy it to that location and try compiling again.
