### ISSUE TITLE
Surface Pro 4. Kubuntu 17.10 boot error (live)

### ISSUE THREAD

**Issue by Predatux** [jakeday/linux-surface#60]
I wanted to ask something that I consider relevant to install Linux in the Surface.
Which version of Ubuntu do you use to make an installation from scratch? I'm trying to install Kubuntu 17.10 but it doesn't start the live. I've been looking and it seems that there is some kind of problem with the latest versions of Kernel and Surface Pro 4.
I remember that I had no problem installing version 16 LTS and updating it later, but I would like to install the most current version directly.

Translated with www.DeepL.com/Translator

**Comment by sergiusens** [comment]
I installed vanilla Ubuntu 17.10 from scratch on my Surface Pro 4 from the live session just fine.

**Comment by jakeday** [comment]
You just need the intel microcode installed on 17.10 for newer kernels.

**Comment by Predatux** [comment]
Ok, thanks
