### ISSUE TITLE
ERROR: module not found: `surface_acpi' during mkinitcpio

### ISSUE THREAD

**Issue by hbh7** [jakeday/linux-surface#601]
Hi all, 

I've noticed this module not found error. As far as I know, the module is working fine as I have battery percentages and all, among other things. Nothing seems to be out of the ordinary/expected, other than that error. Anything I can do to fix it, or should I just ignore it? I'm running the linux-surface-5.3.8-1-x86_64 qzed kernal build on Arch linux on a Surface Book 2 13". 

Happy to provide any more info. Thanks

```
( 9/15) Updating linux-surface initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'default'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface.img
==> Starting build: 5.3.8-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
  -> Running build hook: [resume]
==> ERROR: module not found: `surface_acpi'
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface.img
==> WARNING: errors were encountered during the build. The image may not be complete.
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface-fallback.img -S autodetect
==> Starting build: 5.3.8-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: wd719x
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
  -> Running build hook: [resume]
==> ERROR: module not found: `surface_acpi'
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface-fallback.img
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly
(10/15) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'default'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface.img
==> Starting build: 5.3.8-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
  -> Running build hook: [resume]
==> ERROR: module not found: `surface_acpi'
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface.img
==> WARNING: errors were encountered during the build. The image may not be complete.
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface-fallback.img -S autodetect
==> Starting build: 5.3.8-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: wd719x
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
  -> Running build hook: [resume]
==> ERROR: module not found: `surface_acpi'
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface-fallback.img
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly
```

**Comment by qzed** [comment]
Sorry, was is probably my fault. I've split the `surface_acpi` module up into multiple modules (for easier development) and at the same time renamed it. This change has made its way into the latest releases. This means that `surface_acpi` now consists of the following modules:

- `surface-sam_ssh` (the core driver, communication with the EC)
- `surface_sam_san` (ACPI integration)
- `surface_sam_dtx` (detachment system)
- `surface_sam_sid` (performance states)
- `surface_sam_vhf` (SL1/SL2 keyboard)

If you've got any reference to `surface_acpi` in `mkinitcpio.conf` (or something similar) you'll need to replace that by the appropriate modules.

**Comment by hbh7** [comment]
Yep, looks like that might be it. I see it here: 

`MODULES=(hid hid_sensor_hub i2c_hid hid_generic usbhid hid_multitouch intel_ipts surface_acpi)`

So for the surface book 2, presumably I'd want the surface-sam_ssh, surface_sam_san, surface_sam_dtx, and surface_sam_sid modules listed in place of surface_acpi? Or is that just part of the kernel builds (I think I saw them listed/mentioned somewhere)? Apologies for the confusion

**Comment by qzed** [comment]
No apologies necessary. If you don't run any special setup, you should not need to add them there at all (I also run a 13" SB2 with Arch and I didn't add them, I don't have disk encryption or anything special though). On the top of my head I don't see a reason to put them there, but I might miss something. If you need it in any case, your list seems correct, although you probably don't really need `dtx` and `sid` in there, those both require access from user-space to be actually useful.

**Comment by hbh7** [comment]
Ok, just removed the surface_acpi module and left the others out and then ran `sudo mkinitcpio -p linux-surface` and the error seems to be gone. Rebooted and seems good so far. Thanks!
