### ISSUE TITLE
Surface Laptop 3 WiFi support

### ISSUE THREAD

**Issue by mistay** [jakeday/linux-surface#603]
using jake's 5.1.15-surface-linux-surface on Ubuntu 19.10

after booting, ethernet (surface dock) works, but no wifi device shows up.

[dmesg.txt](https://github.com/jakeday/linux-surface/files/3829196/dmesg.txt)

$ uname -a
Linux ysurfacelinux 5.1.15-surface-linux-surface #8 SMP Thu Jun 27 12:03:55 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by archseer** [comment]
I'm able to run wifi on my surface laptop 3 just fine, it should get picked up by intel's driver: https://wiki.debian.org/iwlwifi

**Comment by mistay** [comment]
@archseer which kernel do you run this driver on? for me it still doest not work on neither jake's kernel (iwlwifi-Qu-b0-hr-b0-46-ucode failed with error -2, no suitable firmware found! minimum required version: iwlwifi-Qu-b0-hr-b0-39, maximum version supported ... iwlwifi-Qu-b0-hr-b0-46) nor ubuntu's default kernel vmlinuz-5.3.0-19-generic.

still trying to run @qzed's kernel https://github.com/qzed/linux-surface-kernel w/ configs from https://github.com/qzed/linux-surface-kernel-configs/ but still stalls at loading ramdisk (https://github.com/jakeday/linux-surface/issues/591#issuecomment-552245636)

**Comment by mistay** [comment]
built 5.3.11 w/ @qzed's patches, details here: https://github.com/qzed/linux-surface-kernel/issues/17#issuecomment-553652790

running this kernel resolved this issue, so wifi is working, thanks @archseer and @qzed!

**Comment by PaulSchulz** [comment]
I have the following issue/bug in Ubuntu since 2019-05-08. It would be great if this has now been fixed. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1828168
