### ISSUE TITLE
Anyone running ubuntu 19.10 and working

### ISSUE THREAD

**Issue by daddacorn2019** [jakeday/linux-surface#607]
i have installed ubuntu 19.10 and all flavors and cant get anything to boot into the new kernel , ive tried grub customizer but nothing seems to work that im able to figure out. can anyone help me out or is there anyone currently running it on theirs?

**Comment by lukashufnagelhadar** [comment]
I switched to qzed's kernel after after installing Ubuntu 19.10 and it is booting fine for me.

**Comment by drcox23** [comment]
I switched to qzed's kernel as well. Installed the latest kernel and patches, signed it, and was working fine. However, after the initial boot before signing, I had to boot into the generic kernel in order to sign the qzed kernel.

**Comment by daddacorn2019** [comment]
I'm new Linux but I've been attacking this thing for awhile now to know alot more then just simple basics but I haven't for the life of me figure it how to use qzeds kernel either I don't know how to use the patches or anything, does anyone think they can help me out explaining how please I'd seriously appreciate it alot

**Comment by brunodrugowick** [comment]
Hi, my friend @daddacorn2019. I think they're only talking about switching to another kernel when booting. That's what I did and things are working fine for me.

On your GRUB screen, instead of letting it boot on the first option, select "Advanced Options for Ubuntu" (or something like that). On this screen you'll find the linux-surface kernel. 

What happens is that by default you'll boot on the most recent kernel, so if you don't want to do tht every time you boot you should remove the newest kernel (sudo apt-get remove).

Did you manage to make everything work?

**Comment by daddacorn2019** [comment]
No I haven't I just pretty much have up on the Ubuntu and have been trying to get it to work on pop os but just found out that pop doesn't use grub 2 and uses system-md instead and I've managed to get the kernel screen up upon boot and it shows all the pop is kernels but not the Linux surface one but still haven't managed to figure out how to even boot to it or pull it up even changing the etc/default/grub and the system-md file. Will this surface kernel just not work on pop os because is uses system-md I don't understand?

**Comment by daddacorn2019** [comment]
ok ive finally got it to work and im super new to this but for anyone who has found a better way please let me know but for now this works on Pop Os , pop os uses kernelstub instead of grub so i copied the new kernel to a folder in /boot/efi/EFI/newfolder both the vmlinuz and intrim surface files into that folder then i went to /boot/efi/loader/entries and modified the default pop os config so that it pointed to the new kernel in my newfolder i made. so now it makes it my default kernel. now im no expert by far at all and it took me alot of doing stuff i had no idea what i was doing but it works fine for me so i guess if it aint broke dont fix it, i hope this helps someone else. thank you everyone for your help
