### ISSUE TITLE
Surface Book 2: Keyboard & Trackpad Not Working After Dock/Undock

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#61]
Running kernel v101 on my 15" SB2, after disconnecting the tablet from the base touch screen functionality takes about 30 seconds to work. When reconnecting the tablet back to the base touch functionality continues to work but the trackpad and keyboard do not.

**Comment by jakeday** [comment]
@versipellis I'm able to duplicate this. I'll look into getting it fixed, but I may not have it addressed for my 4.14.9 update here shortly.

**Comment by versipellis** [comment]
Not a problem - thank you very much for all your work!

**Comment by matthias-vogt** [comment]
Using the nvidia drivers but changing to the intel driver through the nvidia x server settings app did the job for me. Now I can dock and undock with the keyboard and trackpad working just fine - it just takes a few seconds longer than on windows.

**Comment by jakeday** [comment]
@matthias-vogt Can confirm this fixes the issue.

**Comment by jakeday** [comment]
@versipellis Can you please confirm for you as well?

**Comment by versipellis** [comment]
Well, x server doesn't work on my SB2 on 4.14.15, heh... Been trying to debug that and can't figure it out :/

Does switching to the intel driver disable the discrete GPU?

**Comment by jakeday** [comment]
@versipellis No, you'd have disable the discrete GPU.

**Comment by thmichel** [comment]
Hi, I am running Wayland and the nourveau driver for the dGPU. I can confirm the issue, if I do a "rmmod nouveau" as root before undocking, everything works fine.

Seems that pressing the undock button does not cause the neavou driver to unload / the dGPU to be disabled.

**Comment by jakeday** [comment]
Added udev rule to handle this.

**Comment by versipellis** [comment]
@jakeday This issue still seems to be happening even with the udev rule.
