### ISSUE TITLE
Surface Book: dGPU Support

### ISSUE THREAD

**Issue by Shadoukun** [jakeday/linux-surface#62]
I know the dedicated GPU for the Surface Book (performance base) isn't working. I was wondering if you had any idea how difficult it would be to get working, or if you had any plans to get it working in the future?

Thanks!

**Comment by chrisaliascoco** [comment]
Hi Guys,

First of all, thank you the contributors for your great work!

I was wondering the same thing as Shadoukun. Could you provide an answer?

Thanks,
Christopher.

**Comment by dioptre** [comment]
I'm a +1 on helping

**Comment by jakeday** [comment]
While I do intend on working on it, it's really not that high on my todo list.

**Comment by jakeday** [comment]
@Shadoukun This is on my roadmap for right after the acpi notify module.

**Comment by jakeday** [comment]
Please post questions on the SurfaceLinux subreddit.

https://www.reddit.com/r/SurfaceLinux
