### ISSUE TITLE
Update SB2 firmware

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#628]
Hello,

I have a surface book 2 bought in first quarter of 2018, for which I would like to update
the firmware, especially the bios (or its equivalent). I guess I can only do that through windows 10.

However, I fear it messes the linux installation. I kept all windows partition except that I shrinked them to the maximum to make room for linux.

Currently, I run with secureboot disabled and I replaced the boot loader with ReFind which can launche either windows or linux.

I wonder if anyone has some experience in updating the SB2 firmware, how may I proceed ? Will I be still able to boot into linux after the upgrade ?

Thanks for your attention.

Regards

**Comment by tmarkov** [comment]
BIOS/UEFI updates shouldn't mess linux.

**Comment by chasecovello** [comment]
I updated my SB2 without Windows at all. fwupd can download and install for you. See the following for instructions:

https://github.com/StollD/linux-surface-firmware

Also, check the UEFI settings to make sure 'Boot configuration lock' is off, or it won't be able to boot the firmware update image.

**Comment by deb75** [comment]
Hi,

@chasecovello : thanks for pointing out this possibility. I had a look, interesting but I have too few time to perform carefully all steps, I fear I could mess or brick something. So at the moment, I will probably go through windows, hoping it will not mess anything, as  tmarkov said.

Regards
