### ISSUE TITLE
linux-surface not working on Zorin 15.1

### ISSUE THREAD

**Issue by KenMizz** [jakeday/linux-surface#630]
I have Zorin os 15.1 on my surface pro 2017, it's base on ubuntu bionic
I run the setup script to install the kernel, but after ``sudo reboot``, nothing really happen, I downloaded and installed the latest kernel through the script
Button, touch screen is not working at all, and there are no battery status too.
(Sorry for my bad english)

**Comment by atude** [comment]
I have it working with Zorin 15.1 on SB2. Might be something on your end, Zorin is essentially a skin over Ubuntu 18.04 anyway.
