### ISSUE TITLE
Surface Pro 3 + Dock no sound over DisplayPort to HDMI

### ISSUE THREAD

**Issue by Squall1980** [jakeday/linux-surface#633]
Hello everyone,
I am struggling a while now finding a solution. Tried all I could find.

Anyways, in the sound-settings I only have analog output. The built-in speakers work but no sound on the external screen.

Ubuntu version is 19.10

**Comment by losbaeros** [comment]
No sure if this solution would work for the Surface Pro 3, too. But this worked for me on a Surface Go.

#579

**Comment by Squall1980** [comment]
Hi. Didn’t have the chance to test it until today and yes, it solved my problem. 
Thank you very much for sharing.
