### ISSUE TITLE
New Ubuntu Realease

### ISSUE THREAD

**Issue by amir002001** [jakeday/linux-surface#635]
Doesn't work after I updated to new ubuntu.

Tried removing ~/linux-surface and recloning git and doing it all over and still no cigar.

Any clue what I can do??
Thanks

**Comment by tdvantine** [comment]
what version of Ubuntu are you running? I too am having some problems with the touch screen working after updating. (18.4.4)

**Comment by sphh** [comment]
Please see #677.
