### ISSUE TITLE
Question:Does this project support Surface 3(not Pro)?

### ISSUE THREAD

**Issue by izwb003** [jakeday/linux-surface#636]
I'd like to try Linux on my Surface 3 device(Not Surface Pro 3),but as I see Surface 3 is not in the list.  However,I found some issues said that someone else who uses Surface 3 are using this project,and everything goes well. So now I wonder whether this project supports Surface 3 or not? If it does, which firmware should I use and what should I do? Thanks.
(PS:I'm a newcomer in English and please don't mind it... thanks.)

**Comment by pikalover6** [comment]
Yes it does

**Comment by tannerlyons** [comment]
Further, check out https://github.com/linux-surface/linux-surface. That fork is now maintained by a larger community, and this repository is not being actively developed :)
