### ISSUE TITLE
Surface Laptop 2 keyboard not working *After Update*

### ISSUE THREAD

**Issue by Bri997** [jakeday/linux-surface#637]
Everything was working just fine I did an apt update last night and the keyboard is not working again.

**Comment by amir002001** [comment]
sameee

**Comment by ezyang** [comment]
@Bri997 Are you running a newer version of the Linux kernel after your update? If so, try booting into an older version of the kernel.

**Comment by Bri997** [comment]
@ezyang Yep. Went back to 5.1.15 everything is fine. (except I messed up my laptop and had to reinstall 18.04 ugh lol)
