### ISSUE TITLE
Not working on Surface Laptop 2

### ISSUE THREAD

**Issue by bharat8** [jakeday/linux-surface#641]
After following all the steps, no changes took place. In the installation script, i have given every answer a yes except where it asks about the pen installation drivers; but after rebooting nothing changes.
The issue of keyboard drivers still persists.

My laptop is Microsoft Surface Laptop 2 and the Ubuntu OS Version is 18.04. 

Please Help!!

**Comment by socaldavis** [comment]
I am having the same exact issue as @bharat8 .

Surface Laptop 2, both 18.04 LTS and 19.10.

Run through the install instructions, reboot, and onboard keyboard doesn't work, only a USB keybaord.

**Comment by socaldavis** [comment]
Here is what you need to do @bharat8 

After following the instructions, reboot, then at the GRUB menu (If you are getting to a GRUB menu, if not, I think holding SHIFT down during boot might get you to this point), don't select "Ubuntu". Scroll down to "Advanced options for Ubuntu".

In that menu, you should see the additional "Surface" kernel options.

For example, I arrow-down and select "Ubuntu, with Linux <ver>-surface-linux-surface".

**Comment by bharat8** [comment]
Yes! It did work. Thank you so much for resolving this issue. 

Thereby, I am closing this issue.
