### ISSUE TITLE
Touchscreen not functional on SP4 / Ubuntu 19.10

### ISSUE THREAD

**Issue by DaVince** [jakeday/linux-surface#653]
The touchscreen doesn't seem to work for me; at all. It seems the kernel modules that handle this aren't installed or loaded.

I'm running kernel 5.6.5-surface. When I try to follow [the instructions on the Known Issues page](https://github.com/linux-surface/linux-surface/wiki/Known-Issues#v419-ipts-touchscreen-driver-stops-working-sp4-and-sb1), it gives me the following output on the first two commands:

```bash
vincent@vincent-Surface-Pro-4:~$ sudo modprobe -r ipts_surface
modprobe: FATAL: Module ipts_surface not found.
vincent@vincent-Surface-Pro-4:~$ sudo modprobe -r intel_ipts
modprobe: FATAL: Module intel_ipts not found.
```

I use Secure Boot in Microsoft + 3rd Party mode and have installed the `linux-surface-secureboot-mok` package. I also made sure to sign it during boot. I have also (re)installed the linux-kernel package.

**Comment by sphh** [comment]
Please see #677.

**Comment by DaVince** [comment]
This hasn't been an issue in a while so I'll close this. Not sure why I reported this here rather than the community-maintained one in the first place...
