### ISSUE TITLE
Question on GPU throttling while on battery (SB2)

### ISSUE THREAD

**Issue by DevonCasey** [jakeday/linux-surface#662]
I've seen the previous issues on people with their GPUs being throttled to 139 MHz while on battery power. Most of the solutions I've found require installing a whole new kernel or just disabling the Nvidia drivers all together and have the CPU take over. Since it says that there is GPU support for the Surface Book 2, I'm just wondering if I am missing something. I've been having a bad case of quarantine brain so I apologize if this is a silly question. Thanks! 

New Issue: Disconnecting the tablet from the base causes my system to crash pretty hard. Only occurs when I have the Nvidia drivers installed as well.

**Comment by qzed** [comment]
The throttling issue is still present when the AC is not connected.

> New Issue: Disconnecting the tablet from the base causes my system to crash pretty hard. Only occurs when I have the Nvidia drivers installed as well.

Yes, this is expected. If you have the drivers loaded and something is using them when you disconnect the hardware, things will go wrong. You should always unload the drivers before detaching.

**Comment by DevonCasey** [comment]
Ah thanks! I wasn't too sure if everything was working correctly, thought I just of messed something up. Again, thanks for the help.
