### ISSUE TITLE
Battery percentage is not visible on top bar of Ubuntu 20.04 LTS for Surface Pro (Surface_Pro_1796)

### ISSUE THREAD

**Issue by prchanda** [jakeday/linux-surface#666]
I have done a fresh installation of Ubuntu 20.04 LTS on Surface Pro (Surface_Pro_1796) and it seems like there is some issue with battery percentage which supposed to be displayed on top bar of GNOME desktop. Did some research on this and tried the following without any success:

1. I have no entry for battery under these directories /proc/acpi/battery or /sys/class/power_supply
2. Ran **acpi -b** command - no output.
3. Installed **GNOME Tweaks** and tried to enable batter percentage but it didn't help.
4. Installed Linux Surface, but it didn't help as expected since I don't see Surface Pro in the list of supported devices, but gave a try.
5. Installed Genome extension **Vitals** but it doesn't show any data of battery.

Any help on supportability of this Kernel for battery would be appreciated on Surface Pro.

**Comment by StollD** [comment]
The Surface_Pro_1796 SKU is also called Surface Pro 2017 or Surface Pro 5. Microsoft for some reason chose to market it without any number, which can lead to confusion with the original Surface Pro (which has upstream support and doesn't need a patched kernel). So technically it is supported by this repo, but there are other issues that can prevent it from working.

The releases on this repository are vastly out of date. Their version number is lower than the default Ubuntu kernel, which means that Ubuntu will still boot the stock kernel by default. If you want to boot into this kernel, you need to select it from the advanced submenu.

However, you really should use the releases from https://github.com/linux-surface/linux-surface instead, which are up to date, actively maintained and include additional bugfixes / features.

**Comment by prchanda** [comment]
> The Surface_Pro_1796 SKU is also called Surface Pro 2017 or Surface Pro 5. Microsoft for some reason chose to market it without any number, which can lead to confusion with the original Surface Pro (which has upstream support and doesn't need a patched kernel). So technically it is supported by this repo, but there are other issues that can prevent it from working.
> 
> The releases on this repository are vastly out of date. Their version number is lower than the default Ubuntu kernel, which means that Ubuntu will still boot the stock kernel by default. If you want to boot into this kernel, you need to select it from the advanced submenu.
> 
> However, you really should use the releases from https://github.com/linux-surface/linux-surface instead, which are up to date, actively maintained and include additional bugfixes / features.

Thanks @StollD for your pointers, will try to install the kernel from https://github.com/linux-surface/linux-surface and will let you know.

**Comment by prchanda** [comment]
@StollD - I have followed the setup instructions over [here](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup), but I am getting this error while booting.

![Screenshot from 2020-07-10 20-00-17](https://user-images.githubusercontent.com/35064849/87551485-1076b880-c6ce-11ea-8784-52154af2859f.png)

Here are the commands I ran in sequence:

`1. wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc | sudo apt-key add -`

`2. echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" | sudo tee /etc/apt/sources.list.d/linux-surface.list`

`3. sudo apt-get update`

`4. sudo apt-get install linux-headers-surface linux-image-surface linux-libc-dev-surface surface-ipts-firmware libwacom-surface`

`5. sudo apt-get install linux-surface-secureboot-mok`

<code>6. export GRUB_CONFIG=\`sudo find /boot -name "grub.cfg"\`</code>

`7. sudo update-grub`

`8. sudo grep 'menuentry ' $GRUB_CONFIG | cut -f 2 -d "'" | nl -v 0`

`9. sudo grub-reboot 1`

`10. sudo reboot`


Am I missing something else ?

**Comment by prchanda** [comment]
@StollD - I was able to solve the above boot error by adding <code>GRUB_GFXPAYLOAD_LINUX=keep</code> in <code>/etc/default/grub</code>. But still after booting the kernel <code>Kernel: Linux 5.7.7-surface</code>, the issue remains the same. No battery info being displayed.

![Screenshot from 2020-07-16 10-50-54](https://user-images.githubusercontent.com/35064849/87630238-4d848e80-c752-11ea-93f8-9f40e5ebdef0.png)

Any thoughts around this ?

**Comment by prchanda** [comment]
@StollD - You know I jumped the gun, I am able to see now after doing manipulations from Tweaks :-)

![Screenshot from 2020-07-16 10-57-07](https://user-images.githubusercontent.com/35064849/87630609-1fec1500-c753-11ea-8745-98bde74616ee.png)

Thanks a lot for your help !

**Comment by MrWhite1010** [comment]
@prchanda I am really new to linux and I'm trying to regain most of my functionality to aide in turning linux into my daily driver on my surface.  I am at where you were in the photo with hwmatch error upon boot, how can I run GRUB_GFXPAYLOAD_LINUX=keep in `/etc/default/grub ```

**Comment by prchanda** [comment]
> @prchanda I am really new to linux and I'm trying to regain most of my functionality to aide in turning linux into my daily driver on my surface. I am at where you were in the photo with hwmatch error upon boot, how can I run GRUB_GFXPAYLOAD_LINUX=keep in `/etc/default/grub ```

@MrWhite1010 - You don't need to run anything. You just need to add the above text in grub file.
