### ISSUE TITLE
Has anyone tried this on a Surface Book 3? 

### ISSUE THREAD

**Issue by sam1am** [jakeday/linux-surface#668]
If not, what is the likelihood that it would work? Can't find any other topics mentioning it so sorry if this is answered somewhere else already.

**Comment by qzed** [comment]
You may want to have a look at https://github.com/linux-surface/linux-surface where we provide a more up-to-date kernel, as well as a [feature-matrix](https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#feature-matrix) of what is supported with that.
