### ISSUE TITLE
Surface Book 2 gets very hot

### ISSUE THREAD

**Issue by thmichel** [jakeday/linux-surface#67]
Hi,

I am running Fedora with this kernel compiled from source. The Surface Book 2 13" is getting very hot after running for less than 5 minutes. Not sure if this is related due to the battery not being found by the kernel, but this does not happpen with the standard Fedora kernel which does not see the battery either.

**Comment by thmichel** [comment]
I have compiled the latest version and the issue is gone. What I changed was instead using the provided config file as .config I used "make oldconfig" while running standard fedora kernel.
The other thing was I was runing Gnome under X11 instead of Wayland for whatever reason. Not sure which of these two changes solved the issue, but temperature is ok now.

**Comment by xlelephant** [comment]
I have installed Fedora27 on SP4, it is really great.
Actually, I don't know how to compile the kernel with Jakeday's patches.
Could you provide some instructions here?
