### ISSUE TITLE
Surface Pro 4 touch screen experiencing phantom touches

### ISSUE THREAD

**Issue by tduck973564** [jakeday/linux-surface#675]
When I use my SP4 on Ubuntu 21.04 with the latest kernel, after about 10-30 minutes I get an issue where I get progressively worse phantom touch issues, to the point where the laptop is unusable. As a temporary fix I simply stopped IPTS. I have had this same issue on Fedora and older Ubuntu, but both were running Gnome so it could be something to do with that.

Thanks in advance,

tduck973564

**Comment by fesdonomist** [comment]
Oops, I thought I was on that repo :sweat_smile:.
