### ISSUE TITLE
What is the difference between this repository and linux-surface/linux-surface?

### ISSUE THREAD

**Issue by 1900011604** [jakeday/linux-surface#676]
Is [linux-surface/linux-surface](https://github.com/linux-surface/linux-surface/) a fork? I found out that the [Gitter Community](https://gitter.im/linux-surface) lead to the same and [linux-surface/linux-surface](https://github.com/linux-surface/linux-surface/) has newer kernels.

**Comment by stucki** [comment]
From what I can see, all new development happens in the https://github.com/linux-surface/linux-surface/ project. This issue tracker is only used by people who are not aware of it. Someone should finally close it.

**Comment by sphh** [comment]
See #677. (I hope I have not become a _persona non grata_ on this repository now …)

**Comment by 1900011604** [comment]
> See #677. (I hope I have not become a _persona non grata_ on this repository now …)

Thanks, and I see that @jakeday is also in the contributers of https://github.com/linux-surface/linux-surface/
