### ISSUE TITLE
Surface Pro 2017: Breaks wifi

### ISSUE THREAD

**Issue by andrew-w-sherman** [jakeday/linux-surface#68]
Running Arch on SP2017, using Network Manager (problem also occurs with wpa_supplicant).  Using 4.14.8 mainline, wifi works great with the marvell firmware and all the other settings recommended here.

Once I install the new kernel, wifi works at startup but cuts out shortly after any significant load is put on it. I have ensured that power management is turned off, `modprobe -r mwifiex_pcie` hangs indefinitely when I run it, as does `lspci`. After the issue has occurred, the entry disappears from `ip link show`.

Grepping dmesg for `mwifiex_pcie` during the crash gives me:
```
mwifiex_pcie 0000:01:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xa4, act = 0x0
```
plus a bit of extra info which I can get if necessary, and then repeatedly:
```
mwifiex_pcie 0000:01:00.0: failed to get signal information
mwifiex_pcie 0000:01:00.0: PREP_CMD: FW is in bad state
```

I've gone back to mainline and the wifi works fine, but obviously IPTS doesn't. Working on patching mainline manually sans wifi patch, but it would be helpful for the future to have this issue addressed. Happy to offer any other information about my setup, although I'm not sure I could manage trying this with Ubuntu on my machine unless it was completely unavoidable (would have to do a lot of shifting partitions around). Thanks!

**Comment by a-soliman** [comment]
same issue with me, installed the kernel yesterday on SP2017, the touch screen works fine, but the wifi is working significantly slow..

**Comment by andrew-w-sherman** [comment]
Not to nitpick but that could be a separate issue if I'm understanding it right. This is a kernel module crash, not a slowdown.

**Comment by andrew-w-sherman** [comment]
Hmm... this issue seems to have at least substantially decreased in severity on my machine. Only change I made, as far as I can tell, was to get ntpd working (my system time was previously off by a few hours or so). Will update if I can repro consistently again.

**Comment by andrew-w-sherman** [comment]
Here's the full relevant dmesg output. [crash.txt](https://github.com/jakeday/linux-surface/files/1613892/crash.txt) Time to crash is pretty variable, using this kernel seems to accelerate it though. Is this something I should upstream?

**Comment by jakeday** [comment]
@andrew-w-sherman This looks like an upstream bug, but I'll work on it.

**Comment by andrew-w-sherman** [comment]
Thanks! I would be happy to file the upstream bug, but I wasn't sure if it would go to the kernel, to Marvell somewhere, or somewhere else.

**Comment by jakeday** [comment]
@andrew-w-sherman Can you test out my latest 4.14.16 build?

**Comment by andrew-w-sherman** [comment]
Working on it at the moment, the AUR is still on 4.14.15 so I'm compiling from source. Thanks for the new instructions, by the way! Have you tried to pare down the kernel config at all? It always takes up >15G when I'm compiling it, and so I have to run it on external media, but in the past I've spent some time fiddling with the config and gotten the time and space impact down substantially.

**Comment by jakeday** [comment]
@andrew-w-sherman I'm still using the stock config from Ubuntu with just a couple minor tweaks to enable a few new modules.

**Comment by andrew-w-sherman** [comment]
Looks like a no, unfortunately. Still getting about the same sort of behavior, fine under moderate load for a while but crashes on things like package installs or after a long enough time.

**Comment by jakeday** [comment]
@andrew-w-sherman  Can you give this another try with the latest builds I pushed? I re-compiled 4.15.1 and 4.14.17 with my updated wifi patches, so download the latest ones and give it a shot.

**Comment by jakeday** [comment]
@andrew-w-sherman I made some addtional changes for 4.14.18 and 4.15.2 for wifi. Can you test them out, please?

**Comment by andrew-w-sherman** [comment]
Yup, sorry, just takes me a while to build and I haven't had a ton of time. Will try to get it done tonight with 4.14.18. Thanks for the work on this!

**Comment by andrew-w-sherman** [comment]
Ok, so right now I'm running with the patches from 3 days ago and 4.14.16, and as near as I can tell it's working, or at least the most stable I've ever seen it. Compiling 4.17.1 with the very latest patches at the moment, and I'll try to keep load testing it, but it's looking good so far.

**Comment by tkimmm** [comment]
Hi jakeday and andrew-ws,

Firstly, thank you for the work that you have been doing on this project.

I'm exhibiting very similar issues as andew-ws described

SP2017 running i3 manjaro on 4.18 and tried 4.19 too

I've done several fresh installs trying to troubleshoot and narrowed down the issue to the IPTS drivers/patch is causing the WLAN to crash and no longer be detected as an available connection, what makes the bug particular nasty is, any attempt to reboot or shutdown results in a hang and requires a subsequent hard reset.

heres a grep output - its fairly long so I've tried to truncate, (also have simliar output to what andrew described)

[  173.005000] audit: type=1131 audit(1548910224.975:60): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  174.153557] mwifiex_pcie 0000:01:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xfa, act = 0x0
[  174.153582] mwifiex_pcie 0000:01:00.0: num_data_h2c_failure = 0
[  174.153584] mwifiex_pcie 0000:01:00.0: num_cmd_h2c_failure = 0
[  174.153585] mwifiex_pcie 0000:01:00.0: is_cmd_timedout = 1
[  174.153587] mwifiex_pcie 0000:01:00.0: num_tx_timeout = 0
[  174.153588] mwifiex_pcie 0000:01:00.0: last_cmd_index = 0
[  174.153590] mwifiex_pcie 0000:01:00.0: last_cmd_id: fa 00 a4 00 7f 00 16 00 3f 02
[  174.153592] mwifiex_pcie 0000:01:00.0: last_cmd_act: 00 00 00 00 00 00 00 00 00 00
[  174.153593] mwifiex_pcie 0000:01:00.0: last_cmd_resp_index = 3
[  174.153595] mwifiex_pcie 0000:01:00.0: last_cmd_resp_id: 16 80 a4 80 7f 80 16 80 7f 80
[  174.153596] mwifiex_pcie 0000:01:00.0: last_event_index = 4
[  174.153598] mwifiex_pcie 0000:01:00.0: last_event: 17 00 2b 00 1c 00 33 00 33 00
[  174.153599] mwifiex_pcie 0000:01:00.0: data_sent=0 cmd_sent=1
[  174.153601] mwifiex_pcie 0000:01:00.0: ps_mode=0 ps_state=0
[  174.153660] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device
