### ISSUE TITLE
Surface Pro 4: Type cover and plymouth

### ISSUE THREAD

**Issue by combivanCoder** [jakeday/linux-surface#69]
Although this isn't the fault of your custom kernel, I was really hoping it would fix the problem.

**Summary**
When using encrypted disks requiring a password to unlock at boot the kernels up to 4.10.x picked up type covers on SP3 and SP4 allowing password entry.

**Problem**
Kernels installed at upgrade from 17.04 to 17.10 (4.10.0.32 -> 4.13.0.21) plus the custom 4.14 in this repo no longer detect type cover early enough to use in plymouth

**Also Tried**
- changing to text only plymouth (trick used with desktops where nvidia drivers prevent graphical plymouth working)
- older SP3 type cover instead of SP4 type cover
- disabling secure boot

**Only Workaround Discovered**
Plug in a separate USB keyboard to get disks unlocked, then type cover is operational by the time the login screen loads. This is a real pain so keeping to the 4.10 remaining on the device from 17.04.

Is this SP4 specific? Let me know if you need any logs or if I can do anything to test etc.

**Comment by oleid** [comment]
I use full disk encryption for my SP4, too. You might consider using a keyfile to unlock your disks. It needs to be embedded to the initramfs to allow an automatic unlock. **Bonus**: you don't need LVM to encrypt swap with the same key.

In order to prevent random people from extracting the keyfile from your initramfs, you need to store it to an encrypted boot partition. Nowadays, grub is able to decrypt partitions itself, so that isn't a problem. 

So in the end, you enter your password in grub (where the keyboard is working fine) and you don't need any keyboard input during linux's bootup.

**Note**: for some reason, grub tried installing the signed efi file. That, however, didn't support decryption at least on Ubuntu 17.10. (at least I couldn't get it working).

**Comment by combivanCoder** [comment]
It's a good idea, although I'm still not convinced the changes in 17.10 are fully operational. Whilst keyfiles might be a valid workaround, business policy does not allow them due to the need for USB reads at / just after boot (preferring password schemes instead). Btw I don't write the policy :)  

I'd recommend using randomly generated keys for encrypted swap though instead of persisted keys of any kind.

This keyboard problem more seems to be that the modules needed to support the type cover are no longer loaded early enough. Not sure what happened between 4.10 and 4.13 to that end.

If anyone knows what modules for type cover are involved I might be able to test by forcing them to be loaded sooner - I seem to remember doing this on a desktop to try and get a bluetooth keyboard to work in the same scenario.

**Comment by combivanCoder** [comment]
Sorted :)

I'd like to take credit but I'm just not smart enough to figure it out on my own - I found a reference to the hid_multitouch module here in almost identical circumstances:
[noreeps SP3 Git](https://github.com/neoreeps/surface-pro-3/issues/14)

Add the `hid_multitouch` module to your `/etc/initramfs/modules` config, `sudo update-initramfs -u` and reboot. I think it only updates the latest kernel in your initramfs list as it only seems to work on Jake's awesome kernel, not 4.13 (previous in my list of installed). Keyboard detected for luks password entry.

I now have touch, gestures and all the magic I've been missing since my SP3 and 16.04 on my SP4 and this kernel on 17.10. So good to get touchscreen back in Linux :1st_place_medal:

**Comment by combivanCoder** [comment]
@jakeday the resolution seems to solve the problem from 4.13 onwards with crypt disk & pwd entry on boot. Is it worth adding to the install?

**Comment by jakeday** [comment]
@combivanCoder I have already added the modules config for loading the input modules a boot to address this issue. Check the latest in my repo.

**Comment by combivanCoder** [comment]
Good work - many thanks
