### ISSUE TITLE
Touchscreen not work after the 4.13 commit

### ISSUE THREAD

**Issue by yodahuang** [jakeday/linux-surface#7]
Hi there,

I was using 4.12.10 kernel and the touch functionality was fine. After I install the new kernel and `sudo cp -R root/* /`, I lost the touch support.

Thanks for your work!

**Comment by jakeday** [comment]
For 4.13, it works as long as it's docked and powered. I'm working on fixing the issue with the driver for 4.13 series at the moment. For now, you can stick with the 4.12 series (and I updated it to 4.12.11).

**Comment by jakeday** [comment]
This is fixed in my 4.14.x series kernel.
