### ISSUE TITLE
All Models: Ethernet Interfaces Refuse to Connect

### ISSUE THREAD

**Issue by npjohnson** [jakeday/linux-surface#70]
Hey JakeDay,

In your previous 4.14.5 kernel iteration, Ethernet over both USB and Surface Connect worked great.

On a vanilla Ubuntu 17.10 install on the Surface Book (Performance Base), I  was able to connect to Ethernet over both the Surface USB3 to Ethernet adapter, and the Surface Dock's Integrated Ethernet.

Now, on your most recent kernel iteration, at 4.14.13, upon plugging either of them in, the Wired interface appears in Settings and ifconfig, but the device never gets an address assigned to it.

I booted to Windows to confirm that the adapters work, and that the network wasn't at fault. If I take the DHCP address I was assigned in Windows, and configure a static IP on the Ethernet interface on Ubuntu, the interface reports "Connected", but then no traffic can flow outward/inward.

Looking at the dmesg output, I get spamed with this message repeatedly:

 `[ $SYSTEMUPTIME ] cdc_ether 2-1.2:2.0 enx$MYMACADDRESS: kevent 12 may have been dropped`

Looking a bit harder revealed these two additional messages:

`[ $SYSTEMUPTIME ] xhci_hcd 0000:00:14.0: WARN Cannot submit Set TR Deq Ptr`
`[ $SYSTEMUPTIME ] xhci_hcd 0000:00:14.0: A Set TR Deq Ptr command is pending.`
 `[...]`
`[ $SYSTEMUPTIME ] IPv6: ADDRCONF(NETDEV_UP): enx$MYMACADDRESS: link is not ready`

I also recieve these two ACPI errors almost immeadiately after decompressing the kenrel (nto sure if these are to be expected:

`[ $SYSTEMUPTIME ] ACPI Error: [_SB_.PCI0] Namespace lookup failure, AE_NOT_FOUND (20170728/dswload2-191)`
`[ $SYSTEMUPTIME ] ACPI Exception: AE_NOT_FOUND, During name lookup/catalog (20170728/psobject-252)`
`[ $SYSTEMUPTIME ] ACPI Error: Method parse/execution failed \_SB.PCI0.UA02, AE_NOT_FOUND (20170728/psparse-550)`
`[ $SYSTEMUPTIME ] ACPI Exception: Could not find/resolve named package element: SKC1 (20170728/dspkginit-381)`
`[ $SYSTEMUPTIME ] ACPI Exception: Could not find/resolve named package element: SKC2 (20170728/dspkginit-381)`

Any help/insight you could offer would be great.

Thanks ahead of time.

V/R

Nolen Johnson

**Comment by npjohnson** [comment]
@jakeday Entirely feasible... Do you have a link to your 4.14.5 kernel I could try once more to verify it works? Now that I am thinking, it could have also been an Ubuntu side update.

**Comment by jakeday** [comment]
@npjohnson Unfortunately no, but you could compile off the commit for 4.14.5.

**Comment by jakeday** [comment]
@npjohnson Can you give this a try with my latest 4.14.16 build?

**Comment by scheissegal1** [comment]
It seem like i have the same problem. Please help me to send you the information needed to get more insight into the problem.
Hans Michel

**Comment by jakeday** [comment]
@scheissegal1 What distro are you on? I tested with the latest of my kernels on elementary os and ethernet over usb works fine here.

**Comment by npjohnson** [comment]
@jakeday Sure can. Just booted to Ubuntu and updater to 4.15, will try again tonight.

**Comment by jakeday** [comment]
@npjohnson Great, thanks!

**Comment by Gentoli** [comment]
I have the same problem for both the USB ethernet adapter and the dock's ethernet adapter. Base on what I found online, the upstream kernel was using USB 2.0 to communicate with the adapter (I am not really sure how when its on a 3.0 port), that is why it was working before. But they have switched to using USB 3.0 and it is broken. Using a 2.0 hub for the ethernet adapter it works fine but it won't work when plugging directly in to a 3.0 port.

It also appears that when ethernet and the adapter is plugged in before booting, it will work until it is unplugged.

Hope you will find this helpful.
Thanks,
Gentoli

**Comment by npjohnson** [comment]
@Gentoli I'll try the 2.0 dock as well and see.

Worth nothing though that when plugged in on boot, Ethernet does not work as of the 4.13 kernel.

**Comment by npjohnson** [comment]
@jakeday unfotunately, 4.15.1 suffers from the same problem... as @Gentoli mentioned, this seems to be an upstream xhci_usb bug with USB 3.0 Ethernet Adapters (as comically, my 2.0 Ethernet adapter works fine).

Additional logs (with only relevant info) for connection of a USB 3 Ethernet adapter:

- [  353.997913] IPv6: ADDRCONF(NETDEV_UP): enx5882a88b6ff0: link is not ready
- [  389.292225] usb 2-1.1: USB disconnect, device number 21
- [  389.292462] cdc_ether 2-1.1:2.0 enx5882a88b6ff0: unregister 'cdc_ether' usb-0000:00:14.0-1.1, CDC Ethernet Device
- [  389.299986] xhci_hcd 0000:00:14.0: WARN Cannot submit Set TR Deq Ptr
- [  389.299988] xhci_hcd 0000:00:14.0: A Set TR Deq Ptr command is pending.

**Comment by jakeday** [comment]
@npjohnson Ok, so this is most definitely an upstream issue. Can you please file a big there?

**Comment by johnutz-self** [comment]
OK. Who is tasked with filing upstream bug? Me?

**Comment by jakeday** [comment]
@johnutz-self Would you mind doing so?

**Comment by johnutz-self** [comment]
NP!

**Comment by qzed** [comment]
@sedulam As per #105, [this](https://bugzilla.kernel.org/show_bug.cgi?id=199153) should be the report, doesn't seem like there is much activity though.
