### ISSUE TITLE
Surface Book 2: Errors in Logs for Power Domains

### ISSUE THREAD

**Issue by kryton** [jakeday/linux-surface#72]
First of all.
1. Thank you for building this.
2. I don't think this is your specific patches.
3. SurfaceBook2 /15" about  2 weeks old.

I have attached a sample.
It seems to generate these multiple times a second sadly.

[kernel.output.txt](https://github.com/jakeday/linux-surface/files/1628526/kernel.output.txt)

**Comment by jakeday** [comment]
@kryton Those are not specific to my kernel. The power domains are not updated in the mainline 4.14 kernel for the SB2. From the looks of it, this will be fixed upstream in 4.15. However, it shouldn't really be causing an issue for you.

**Comment by kryton** [comment]
Thx Jake.
