### ISSUE TITLE
Documentation: "Suspend To Disk"

### ISSUE THREAD

**Issue by andrew-w-sherman** [jakeday/linux-surface#73]
Hi, it seems like there's an issue either in your documentation or your command for the "Suspend To Disk" fix. Suspend to disk = hibernate, and yet the command copies over the _suspend_ entry with the hibernate one, which seems to suggest fixing suspend by replacing it with hibernate.

**Comment by jakeday** [comment]
@andrew-w-sherman That's exactly what it's doing. The newer Surface devices support hibernate but not suspend as it was replaced with connected stand-by.
