### ISSUE TITLE
Surfacebook 2: Headphone jack doesn't work

### ISSUE THREAD

**Issue by versipellis** [jakeday/linux-surface#75]
Main speakers output audio fine, but the headphone jack is nonfunctional. It detects the headphone jack and that something is plugged in to it, but no audio gets sent.

**Comment by jakeday** [comment]
@versipellis Headphones are working fine on my SB2. Are you sure you have them plugged in all the way and the volume turned up and not muted?

**Comment by versipellis** [comment]
Yup. Works fine with my Windows OS. Will test again tomorrow.

**Comment by jakeday** [comment]
@versipellis What distro are you running?

**Comment by versipellis** [comment]
Ubuntu 17.10

**Comment by scotty86bne** [comment]
I have the same issue running Mint 18.3 on a Surface Pro 4 with jakedays 4.14.13-surface kernel compiled from source.

**Comment by jakeday** [comment]
@versipellis @scotty86bne To be fair, I was running my 4.14.14 build when I verified (which is uploaded now). I don't think any changes in there would fix it, but maybe give it a shot as it's definitely working here.

**Comment by versipellis** [comment]
Tested with 4.14.15 and works - looks like something in 4.14.14 fixed it! Closing this issue.
