### ISSUE TITLE
Misleading information for Surface Book 2

### ISSUE THREAD

**Issue by Fabyao** [jakeday/linux-surface#77]
@jakeday Thank you for the fantastic kernel. On the main GitHub page, the What’s Working section is misleading. It states the power button, volume buttons, battery readings and docking/unlocking are all fully working. This isn’t the case for the Surface Book 2 and I believe it misleads people expectations.
I understand that some feature might work on other devices, however the Surface Book 2 should be excluded so new comers are well informed before jumping into the process of installing Linux.

**Comment by jakeday** [comment]
@Fabyao Updated.
