### ISSUE TITLE
SB2: syndaemon can't start (accidental clicking with touchpad)

### ISSUE THREAD

**Issue by matthias-vogt** [jakeday/linux-surface#78]
I'm not sure if this is the right place to post because I don't know if this is a Surface related bug or just me.
`syndaemon` closes with error code 2 when I'm trying to launch it. (Kernel: 4.14.8, Running: SB2 13in, Ubuntu 17.10)
In theory, it should disable the touchpad while typing to prevent accidental clicks.
Can you reproduce this?
Also I can only agree with the other issue posters and not thank you enough for all the hard work you've done on this kernel.

**Comment by jakeday** [comment]
@matthias-vogt This is an issue with configuration in the distro and not in the kernel. You probably have syndaemon looking at the wrong driver.
