### ISSUE TITLE
Surface Dock / Surface Pro 2017: external monitors "disconnected"

### ISSUE THREAD

**Issue by zeroskyx** [jakeday/linux-surface#79]
First off, thank you so much for your great work here -- everything is working flawlessly except for one thing.
I'm running a Surface Pro 2017 with a Surface Dock (the brick) and have attached two Dell U2518D LCD/LED (2560x1440) screens to the dock.
Running the latest Linux Mint does not recognize the screens -- xrandr shows both ports as "Disconnected" -- when I attach one of the screens (doesn't matter which one) directly to the mDP on the SP, the screens gets recognized directly.

Both screens are working on Win 10, so there is no wiring/ power issue.

Is anybody experiencing the same issue?
Thanks in advance for your help.

Keep up the amazing work! Your work bridging Surface hardware and Linux OS really is a huge deal.
-Simon

**Comment by jakeday** [comment]
@zeroskyx The issue is that the monitors need to be attached to the dock and the dock connected to the Surface Pro when booting. That's the only way it currently sees the screens, otherwise they won't be detected.

**Comment by zeroskyx** [comment]
Hi Jake,

thanks for the fast response -- I have read about this minor limitation but unfortunately for me the screens stay dark even when the dock is attached (with connected screens) and the SP is booted afterwards; unfortunately there appears to be another issue.

Can I supply you with any additional data to help you trace the possible issue?
dmesg/ xrandr outputs or anything else?

Thanks and best reagards
-Simon

**Comment by jakeday** [comment]
@zeroskyx Can you try my latest 4.14.16 build?

**Comment by zeroskyx** [comment]
Hi Jake, unfortunately the problem still exists in:
Linux zeroskyx-mint 4.14.16-surface-linux-surface #1 SMP Thu Feb 1 21:20:48 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

The following is my xrandr output:
Screen 0: minimum 320 x 200, current 2736 x 1824, maximum 8192 x 8192
eDP-1 connected primary 2736x1824+0+0 (normal left inverted right x axis y axis) 260mm x 173mm
   2736x1824     59.96*+
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 disconnected (normal left inverted right x axis y axis)
DP-2-2 disconnected (normal left inverted right x axis y axis)

When I connect the screen to the mDP on the SP itself, the display works.

**Comment by npjohnson** [comment]
Surface Dock works fine here on my Surface Book PB. I run 3 monitors off it (2x Mini-DP to HDMI, one USB to HDMI).

**Comment by jakeday** [comment]
@npjohnson I agree, it's working fine for me here too.

@zeroskyx Can you get me a full dmesg output?

**Comment by zeroskyx** [comment]
Thanks for your analysis; here's the full dmesg after a fresh start:

[dmesg.txt](https://github.com/jakeday/linux-surface/files/1725373/dmesg.txt)

**Comment by jakeday** [comment]
@zeroskyx I don't see any issue unfortunately.

**Comment by jakeday** [comment]
Please feel free to re-open this issue if you continue to experience issues in the latest releases on a fresh install.

**Comment by arupbg** [comment]
Hello jakeday,

I face similar external monitor *no signal* issue on DP-2-2. Even though  `xrandr` shows connected ... but no signal. Note it works fine with windows.

Screen 0: minimum 320 x 200, current 2736 x 1824, maximum 8192 x 8192
`eDP-1 connected primary 2736x1824+0+0 (normal left inverted right x axis y axis) 260mm x 173mm
   2736x1824     60.01*+`
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 disconnected (normal left inverted right x axis y axis)
`DP-2-2 connected (normal left inverted right x axis y axis)`
   3840x2160     60.00 +  30.00    29.97  
   1920x2160     60.00  
   2560x1440     59.95  
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    50.00    59.94    24.00    23.98  
   1600x1200     60.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08

**Comment by chigandhi** [comment]
I have the exact same issue - external monitor directly connected to the SP3 mDP port works fine, no signal is detected when trying to connect via the docking station. I have a Dell Ultrasharp 2518D.
