### ISSUE TITLE
Surface Book: Wrong i915 binaries in firmware/i915_firmware.zip?

### ISSUE THREAD

**Issue by deweyx** [jakeday/linux-surface#80]
On my SurfaceBook, I extracted `i915_firmware.zip` to `/lib/firmware/i915` per instructions, but later the `dpkg` step gave (Edit: turns out I didn't keep the original error list, but amongst others it included the skl_ files from the later dmesg errors): 

    W: Possible missing firmware /lib/firmware/i915/skl_dmc_ver1_26.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/skl_guc_ver6_1.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/skl_huc_ver01_07_1398.bin for module i915

After boot, touch not working and `dmesg` was giving errors:

	[    2.246330] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
	[    2.246372] i915 0000:00:02.0: Direct firmware load for i915/skl_dmc_ver1_26.bin failed with error -2
	[    2.246375] i915 0000:00:02.0: Failed to load DMC firmware [https://01.org/linuxgraphics/downloads/firmware], disabling runtime power management.
	[    2.252688] i915 0000:00:02.0: Direct firmware load for i915/skl_huc_ver01_07_1398.bin failed with error -2
	[    2.252692] [drm] Failed to fetch valid uC firmware from i915/skl_huc_ver01_07_1398.bin (error -2)
	[    2.252699] i915 0000:00:02.0: Direct firmware load for i915/skl_guc_ver6_1.bin failed with error -2
	[    2.252700] [drm] Failed to fetch valid uC firmware from i915/skl_guc_ver6_1.bin (error -2)
	[    2.255926] [drm:intel_uc_init_hw [i915]] *ERROR* GuC init failed
	[    2.255929] [drm] Falling back from GuC submission to execlist mode
	[    2.255931] [drm] GuC firmware loading disabled

A bit of research led to [01.org firmware here](https://01.org/linuxgraphics/downloads/firmware). I downloaded the Skylake versions, extracted and re-ran `update-initramfs -u`. I doubt I need the bxt files (?).

    ➜  ~ sudo update-initramfs -u
    update-initramfs: Generating /boot/initrd.img-4.14.14-surface-jakeday
    W: Possible missing firmware /lib/firmware/i915/bxt_dmc_ver1_07.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/bxt_huc_ver01_07_1398.bin for module i915

Touch now works.

Not sure if it's related to above, but `pm-hibernate` returns to the screen to where I left off, but system is completely unresponsive.

Great job with this kernel, my WiFi problems are gone! Thanks!

**Comment by jakeday** [comment]
@deweyx The ones I have uploaded are generic enough for most devices to work. However, each surface device might use different modules and loading the correct ones are always the best bet. Maybe I should package them up like I did the ipts firmware? Just didn't see the need with them being readily available. Which Surface Book are you using by the way?

**Comment by jakeday** [comment]
@deweyx I broke out the i915 firmware files into separate zips for targeted devices. Please use the correct version going forward.
