### ISSUE TITLE
No touch screen or pen support on Debian Buster

### ISSUE THREAD

**Issue by ardynn** [jakeday/linux-surface#82]
Followed the steps exactly as stated, but the touch screen is unresponsive and the pen doesn't seem to be recognized. Have checked the start up - definitely booted Jake Day's kernel

Have successfully used this on Ubuntu 17.10 but went with Debian for stability issues.

Thanks very much for any help.

**Comment by jakeday** [comment]
@ardynn Can you get me a full dmesg output so I can take a look?

**Comment by jakeday** [comment]
@ardynn Also which device is this?
