### ISSUE TITLE
Surface Book: Keyboard not working in initramfs (4.15.3-surface-linux-surface)

### ISSUE THREAD

**Issue by LTDeto** [jakeday/linux-surface#85]
Thanks for the amazing work.
I am running Ubuntu 17.10 on a luks encrypted disk. During boot when it comes to the password prompt to unlock the disk I have noticed that Surface Book's keyboard doesn't seem to work at all.
After entering the passphrase with an external keyboard connected via USB I quickly checked lsmod. 
Adding "hid" and its dependencies to /etc/initramfs-tools/modules fixed that for me and now the keyboard works fine. Don't forget #update-initramfs -u

The missing modules are
hid
hid_sensor_hub
i2c_hid
hid_generic
usbhid
hid_multitouch
intel_ipts

You might want to add this to your root/ folder and installation steps.
Cheers LTDeto

**Comment by jakeday** [comment]
Will do.
