### ISSUE TITLE
problem emerges with Instructions to install

### ISSUE THREAD

**Issue by phihh** [jakeday/linux-surface#86]
1. May I directly enter the command in the terminal to get it installed?
I'm new to this ubuntu system
----------------------------------------------------
:~$ sudo cp -R root/* /
[sudo] password for z: 
cp: cannot stat 'root/*': No such file or directory
-----------------------------------------------------

**Comment by ajensenwaud** [comment]
You need to first clone the git repo into a folder and then cd into it for the command to work.

**Comment by jakeday** [comment]
@phihh As @ajensenwaud mentioned, you need to clone the repo and cd into it first.
