### ISSUE TITLE
Ubuntu 17.10.1 - touch screen doesn’t work after login

### ISSUE THREAD

**Issue by ajensenwaud** [jakeday/linux-surface#87]
Hello. I have installed patches on Ubuntu 17.10.1 on a Surface Book (not Book 2), using the 4.15 deb package.
When I reach login screen the touch seems to work and for about two minutes after login. Then touch stops working, with and without pen.syslog:Feb 17 17:40:25 kennedy kernel: [  540.682529] mwifiex_pcie 0000:03:00.0: info: shutdown mwifiex...
In addition, suspend doesn’t work. When I close the lid, it keeps running with the screen on.
Finally, wifi doesn't seem to come back up after suspend.

**Comment by ajensenwaud** [comment]
To be clear re suspend - it does try to suspend (ie black screen) when I press suspend icon in Gnome, but when I try and close the lid the screen turns back on. I dont experience any system hang as such. It’s like t tries to suspend but then is woken back up.

**Comment by ajensenwaud** [comment]
I just found the following in syslog: 

```
syslog:Feb 17 17:40:25 kennedy kernel: [  540.682529] mwifiex_pcie 0000:03:00.0: info: shutdown mwifiex...
syslog:Feb 17 17:40:25 kennedy kernel: [  540.682946] mwifiex_pcie 0000:03:00.0: PREP_CMD: card is removed
syslog:Feb 17 17:40:49 kennedy systemd-sleep[5552]: rmmod: ERROR: Module mwifiex_pcie is not currently loaded
syslog:Feb 17 17:40:49 kennedy systemd-sleep[5552]: rmmod: ERROR: Module mwifiex is not currently loaded
syslog:Feb 17 18:10:37 kennedy NetworkManager[7223]: <info>  [1518851437.8895] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-dns-resolved.conf, 20-connectivity-ubuntu.conf) (run: 10-globally-managed-devices.conf) (etc: default-wifi-powersave-on.conf)
syslog:Feb 17 18:10:38 kennedy NetworkManager[7223]: <info>  [1518851438.1911] manager: rfkill: WiFi enabled by radio killswitch; enabled by state file
```
Kicking the wifi with modprobe -i mwifiex_pcie and modprobe -i mwifiex seemed get the adapter back up and running.

**Comment by jakeday** [comment]
@ajensenwaud The two issues reported here are duplicates of #31 and #56
