### ISSUE TITLE
Marvell Git repo unavailable

### ISSUE THREAD

**Issue by combivanCoder** [jakeday/linux-surface#89]
Every time I've tried to access the http://git.marvell.com/mwifiex-firmware repo it's always been unavailable.

Looks like I'm [not the only one](https://www.reddit.com/r/SurfaceLinux/comments/6pmvpi/gitmarvellcom_alternative/). Is there an alternative source to update the README.md with?

Not sure if [this](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/mrvl) is a suitable replacement or not?

**Comment by jakeday** [comment]
@combivanCoder I just tested their repo again and it's available. I know it goes down from time to time, but it always comes back up. I just pulled the latest this morning and I can push up a clone but it's always best to get the latest from them.

**Comment by combivanCoder** [comment]
Agreed - looks like it's up now and again. My bad - thanks
