### ISSUE TITLE
Surface Pro 2017: Xorg often crashes

### ISSUE THREAD

**Issue by ingermy** [jakeday/linux-surface#90]
On my surface pro 2017 on xorg it often crashes (ubuntu 17.10  kernel 4.15.4). Why?
Thank's for your job!

**Comment by jakeday** [comment]
@ingermy Can you give me the xorg log and the output of dmesg?

**Comment by ingermy** [comment]
certainly. I hope I have sent what you need. I just got into the linux world. thanks for the support.
[dmesg.txt](https://github.com/jakeday/linux-surface/files/1736569/dmesg.txt)
[log.txt](https://github.com/jakeday/linux-surface/files/1736570/log.txt)

**Comment by fpoussin** [comment]
@ingermy it should be /var/log/Xorg.0.log and /var/log/kern.log for ubuntu

**Comment by ingermy** [comment]
I only found this
[kern.log](https://github.com/jakeday/linux-surface/files/1741055/kern.log)

**Comment by jakeday** [comment]
@ingermy Did you make any other changes to your system? I don't see any kernel issues, so I'm assuming it's some other distro config change that's been made.

**Comment by ingermy** [comment]
It stops when you open the virtual keyboard and only on xorg. As soon as I have time, I reinstall everything from the beginning. Thank you

**Comment by ingermy** [comment]
It stops when you open the virtual keyboard and only on xorg. As soon as I have time, I reinstall everything from the beginning. Thank you

**Comment by jakeday** [comment]
@ingermy Please re-open this after your re-install if you are still having issues.
