### ISSUE TITLE
Surface book 2 (13'') Freeze when undocking

### ISSUE THREAD

**Issue by tdurand** [jakeday/linux-surface#93]
Hi !

First thanks for your hard work.

I just installed ubuntu 17.10 with the 4.15.4-surface-linux-surface kernel, and every supported feature seems to work alright (touchscreen, bluetooth ...) but when I detach the screen, ubuntu freeze, the tablet get super hot and I can't do anything. If I try to replug the screen it stays like that and I need to reboot the computer.

One thing I'm not sure is if I needed to install the 4.15.x kernel or the 4.14.x kernel ?

Thanks, 

Thibault

**Comment by jakeday** [comment]
@tdurand Did you also install the root files? Namely the udev rule for the keyboard.

**Comment by tdurand** [comment]
I just re-copied them and restarted to make sure, and yes it does now, sorry, not sure what went wrong during first install...

I'm also wondering, do I need to install nvidia driver and how to see which GPU is used (maybe off-topic) ?
