### ISSUE TITLE
surface book 2 : battery readings

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#95]
The current state of the surface book 2 says they are no battery readings.

Does it mean you cannot know the battery level ?

I ask this question because, without knowing the battery level, you may drain the battery totally, which can damage it.

**Comment by niklaskorz** [comment]
Yup, that's what it means.

**Comment by deb75** [comment]
Is it going to be addressed soon ?

Regards

**Comment by dangerm0us** [comment]
All we know is that as per a few other issues, an ACPI Notify Module is required to fix this issue.  In the meantime you're flying blind on battery like the rest of us.

**Comment by samsungrocks10** [comment]
#28 is talking about the same thing

**Comment by jakeday** [comment]
@deb75 Yes, this is currently being worked under #28 and I hope to have it complete very very soon!

**Comment by deb75** [comment]
Hi,

There were several commit during last days, did they were related to this issue ?

Regards

**Comment by jakeday** [comment]
@deb75 They were a stepping stone to support the core acpi driver. Battery stats are coming soon.

**Comment by deb75** [comment]
Hi,

Is the issue with the dGPU also related with acpi ?
