### ISSUE TITLE
dGPU driver installation problem on release 4.15.6-1

### ISSUE THREAD

**Issue by didibaba** [jakeday/linux-surface#96]
My device is Surface book2 15 inch with Ubuntu 16.04. After I install the linux-surface kernel release 4.15.6-1, the NVIdia drive 390.25 failed. 

I tried to reinstall it, but showed the error message as follows.

sudo apt-get install nvidia-390-dev 
[sudo] password for xx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcuda1-390 nvidia-390 nvidia-opencl-icd-390 nvidia-prime nvidia-settings
The following NEW packages will be installed:
  libcuda1-390 nvidia-390 nvidia-390-dev nvidia-opencl-icd-390 nvidia-prime
  nvidia-settings
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/81.9 MB of archives.
After this operation, 360 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package nvidia-390.
(Reading database ... 259450 files and directories currently installed.)
Preparing to unpack .../nvidia-390_390.25-0ubuntu0~gpu16.04.1_amd64.deb ...

WARNING: Your driver installation has been altered since it was initially
         installed; this may happen, for example, if you have since installed
         the NVIDIA driver through a mechanism other than nvidia-installer
         (such as your distribution's native package management system). 
         nvidia-installer will attempt to uninstall as best it can.  Please see
         the file '/var/log/nvidia-uninstall.log' for details.

ERROR: Unable to create '/usr/lib/i386-linux-gnu/libcuda.so.390.25' for copying
       (No such file or directory)

ERROR: Unable to create '/usr/lib/i386-linux-gnu/libnvidia-opencl.so.390.25'
       for copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-encode.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvcuvid.so.390.25' for copying
       (No such file or directory)

ERROR: Unable to create
       '/usr/lib/nvidia-390/libnvidia-fatbinaryloader.so.390.25' for copying
       (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-cfg.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/xorg/nvidia_drv.so' for copying
       (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-fbc.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/vdpau/libvdpau_nvidia.so.390.25'
       for copying (No such file or directory)

ERROR: Unable to create
       '/usr/lib/nvidia-390/libnvidia-ptxjitcompiler.so.390.25' for copying (No
       such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-ifr.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-ml.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-wfb.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib/nvidia-390/libnvidia-compiler.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-encode.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvcuvid.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create
       '/usr/lib32/nvidia-390/libnvidia-fatbinaryloader.so.390.25' for copying
       (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-cfg.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-fbc.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/vdpau/libvdpau_nvidia.so.390.25'
       for copying (No such file or directory)

ERROR: Unable to create
       '/usr/lib32/nvidia-390/libnvidia-ptxjitcompiler.so.390.25' for copying
       (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-ifr.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-ml.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-wfb.so.390.25' for
       copying (No such file or directory)

ERROR: Unable to create '/usr/lib32/nvidia-390/libnvidia-compiler.so.390.25'
       for copying (No such file or directory)

ERROR: Unable to create '/etc/OpenCL/vendors/nvidia.icd' for copying (No such
       file or directory)

WARNING: Failed to restore some backed up files/symlinks, and/or their
         attributes. See /var/log/nvidia-uninstall.log for details

Unpacking nvidia-390 (390.25-0ubuntu0~gpu16.04.1) ...
Selecting previously unselected package libcuda1-390.
Preparing to unpack .../libcuda1-390_390.25-0ubuntu0~gpu16.04.1_amd64.deb ...
Unpacking libcuda1-390 (390.25-0ubuntu0~gpu16.04.1) ...
Selecting previously unselected package nvidia-390-dev.
Preparing to unpack .../nvidia-390-dev_390.25-0ubuntu0~gpu16.04.1_amd64.deb ...
Unpacking nvidia-390-dev (390.25-0ubuntu0~gpu16.04.1) ...
Selecting previously unselected package nvidia-opencl-icd-390.
Preparing to unpack .../nvidia-opencl-icd-390_390.25-0ubuntu0~gpu16.04.1_amd64.deb ...
Unpacking nvidia-opencl-icd-390 (390.25-0ubuntu0~gpu16.04.1) ...
Selecting previously unselected package nvidia-prime.
Preparing to unpack .../nvidia-prime_0.8.2_amd64.deb ...
Unpacking nvidia-prime (0.8.2) ...
Selecting previously unselected package nvidia-settings.
Preparing to unpack .../nvidia-settings_390.25-0ubuntu0~gpu16.04.1_amd64.deb ...
Unpacking nvidia-settings (390.25-0ubuntu0~gpu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up nvidia-390 (390.25-0ubuntu0~gpu16.04.1) ...
update-alternatives: using /usr/lib/nvidia-390/alt_ld.so.conf to provide /etc/ld.so.conf.d/i386-linux-gnu_GL.conf (i386-linux-gnu_gl_conf) in auto mode
update-alternatives: using /usr/lib/nvidia-390/alt_ld.so.conf to provide /etc/ld.so.conf.d/i386-linux-gnu_EGL.conf (i386-linux-gnu_egl_conf) in auto mode
update-alternatives: using /usr/share/nvidia-390/glamor.conf to provide /usr/share/X11/xorg.conf.d/glamoregl.conf (glamor_conf) in auto mode
INFO:Enable nvidia-390
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/lenovo_thinkpad
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/put_your_quirks_here
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/dell_latitude
Adding system user `nvidia-persistenced' (UID 123) ...
Adding new group `nvidia-persistenced' (GID 129) ...
Adding new user `nvidia-persistenced' (UID 123) with group `nvidia-persistenced' ...
Not creating home directory `/'.
Loading new nvidia-390-390.25 DKMS files...
First Installation: checking all kernels...
Building only for 4.15.6-surface-linux-surface
Building for architecture x86_64
Building initial module for 4.15.6-surface-linux-surface
ERROR (dkms apport): kernel package linux-headers-4.15.6-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 4.15.6-surface-linux-surface (x86_64)
Consult /var/lib/dkms/nvidia-390/390.25/build/make.log for more information.
Setting up libcuda1-390 (390.25-0ubuntu0~gpu16.04.1) ...
Setting up nvidia-390-dev (390.25-0ubuntu0~gpu16.04.1) ...
Setting up nvidia-opencl-icd-390 (390.25-0ubuntu0~gpu16.04.1) ...
Setting up nvidia-prime (0.8.2) ...
Setting up nvidia-settings (390.25-0ubuntu0~gpu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for ureadahead (0.100.0-19) ...

The driver just failed to load. What is the problem?

**Comment by jakeday** [comment]
@didibaba Can you try purging (not just removing) the nvidia drivers and try again? It looks like something in the driver's installer got messed up. On a side note, I don't see any relation to a kernel issue with this.

**Comment by didibaba** [comment]
This is the error about the kernel.  I used "sudo apt-get install nvidia-390-dev" to install the driver.

> ERROR (dkms apport): kernel package linux-headers-4.15.6-surface-linux-surface is not supported
> Error! Bad return status for module build on kernel: 4.15.6-surface-linux-surface (x86_64)

I am sure that the deep learning algorithms using dGPU doesn't work. My tensorflow just shows,

> In [3]: tf.Session()
> 2018-03-02 10:56:47.852951: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2018-03-02 10:56:47.866778: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
> 2018-03-02 10:56:47.866825: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (didibaba-Surface-Book-2): /proc/driver/nvidia/version does not exist
> Out[3]: <tensorflow.python.client.session.Session at 0x7f5cc52127d0>

However, before installing the surface kernel, this did work.

**Comment by jakeday** [comment]
@didibaba What version kernel were you using prior? This looks like a dkms issue going to 4.15 and you need to update the 4.15 dkms files.

**Comment by didibaba** [comment]
It was 4.15.4-041504. I have also tried 4.13 and got the same problem.

**Comment by didibaba** [comment]
Unfortunately, I've tried your newest release, and the problem still exists.

>  sudo dkms autoinstall 
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> make KERNELRELEASE=4.15.7-surface-linux-surface KVERSION=4.15.7-surface-linux-surface....(bad exit status: 2)
> ERROR (dkms apport): kernel package linux-headers-4.15.7-surface-linux-surface is not supported
> Error! Bad return status for module build on kernel: 4.15.7-surface-linux-surface (x86_64)
> Consult /var/lib/dkms/bbswitch/0.8/build/make.log for more information.
> 
> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area....
> 'make' -j8 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=4.15.7-surface-linux-surface IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/4.15.7-surface-linux-surface/build LD=/usr/bin/ld.bfd modules....(bad exit status: 2)
> ERROR (dkms apport): kernel package linux-headers-4.15.7-surface-linux-surface is not supported
> Error! Bad return status for module build on kernel: 4.15.7-surface-linux-surface (x86_64)
> Consult /var/lib/dkms/nvidia-390/390.25/build/make.log for more information.

Do I need to do something to the dkms??

**Comment by jakeday** [comment]
@didibaba Yes, you need to update the patch files for dkms. Also, the errors you posted previously are not from the kernel. This looks like a user space issue and would be better asked on the SurfaceLinux subreddit as well.

https://www.reddit.com/r/SurfaceLinux/

**Comment by nathanielhobbs** [comment]
I am running into a similar issue after trying to upgrade to the latest kernel.

Can you offer any resources for how to update the patch files for dkms?  I've done some googling, but feel a little out of my depth and am not sure how to go about doing this.

**Comment by didibaba** [comment]
Hi @nathanielhobbs,

Please first try update linux kernel to 4.15 and install the latest linux-surface kernel. Using 'apt-get' to install the nvidia driver with version 396. I have also tried version 410 and 415, but my SB2 would suddenly crash and shut down. No idea about this so far.

Hope this will  help. ;-)

**Comment by nathanielhobbs** [comment]
@didibaba Thanks for the info!  I am currently running jakeday kernel 4.18.16 with nvidia driver version 390.  That works for the machine learning tasks I'm working on (cuda, cudnn, everything works without any gpu under-clocking issues).

Am I to understand you are recommending booting into the standard linux kernel, updating it to version 4.15, rebooting into that version, and then installing the latest linux-surface kernel from there?  Would you recommend removing my current nvidia driver before upgrading any kernel?

I could start from a fresh linux install, but I've got so many things to work on, I don't necessarily want to take a day and start fresh, get all my application settings set up again, etc.  The main reason I wanted the latest kernel is just so that I can see my battery levels! 

 So far when trying to upgrade to the latest jakeday kernel and running into this dkms issue, I got stuck with the nouveau driver, couldn't purge the nvidia drivers to reinstall them, and just felt lost. I ended up loading up a backup image to take me back to my original setup (as described in the first paragraph)

Do you know anything about "patch files for dkms"?

**Comment by didibaba** [comment]
Hi @nathanielhobbs,

You can uninstall the old NV driver. Reboot to the standard Linux kernel and update it. Install the jakeday kernel. Using APT get to install the new nv driver.
