### ISSUE TITLE
How to use the command "nvidia-smi" to monitor the usage of dGPU on SB2 15?

### ISSUE THREAD

**Issue by didibaba** [jakeday/linux-surface#97]
After installing the surface kernel 4.15, the command "nvidia-smi" doesn't work, and shows the message "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

So, I am not quite sure if the nvidia driver functioned normally, since this command is what I used to verify this when running deep learning algorithms.

Thanks!

**Comment by jakeday** [comment]
Please post questions on the SurfaceLinux subreddit.

https://www.reddit.com/r/SurfaceLinux
