### ISSUE TITLE
Surface Book 2 : best distribution to use with jakeday kernel ?

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#98]
Hello,

Which distribution do you use and recommend for the surface book 2 ? Especially to make use of the touchscreen and stylus.

Also, which distribution (version of ubuntu I guess) for the linux-surface kernel ?

Regards

**Comment by jakeday** [comment]
I was using Elementary OS, but I switched to KDE Neon. Any distro should work fine, though.
