### ISSUE TITLE
Issues installing 4.15.7 kernel (SB2 15')

### ISSUE THREAD

**Issue by atharos1** [jakeday/linux-surface#99]
Hi!
I was just trying to install the new kernel by following your instructions, by the last step I ran into the following issues.

```
Desempaquetando linux-headers-4.15.7-surface-linux-surface (4.15.7-surface-linux-surface-7) ...
Seleccionando el paquete linux-image-4.15.7-surface-linux-surface previamente no seleccionado.
Preparando para desempaquetar kernel-image.deb ...
Desempaquetando linux-image-4.15.7-surface-linux-surface (4.15.7-surface-linux-surface-7) ...
Configurando linux-headers-4.15.7-surface-linux-surface (4.15.7-surface-linux-surface-7) ...
Configurando linux-image-4.15.7-surface-linux-surface (4.15.7-surface-linux-surface-7) ...
ERROR (dkms apport): kernel package linux-headers-4.15.7-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 4.15.7-surface-linux-surface (x86_64)
Consult /var/lib/dkms/anbox-modules-ashmem/9/build/make.log for more information.
ERROR (dkms apport): kernel package linux-headers-4.15.7-surface-linux-surface is not supported
Error! Bad return status for module build on kernel: 4.15.7-surface-linux-surface (x86_64)
Consult /var/lib/dkms/anbox-modules-binder/9/build/make.log for more information.
update-initramfs: Generating /boot/initrd.img-4.15.7-surface-linux-surface
W: Possible missing firmware /lib/firmware/i915/bxt_dmc_ver1_07.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_dmc_ver1_26.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_guc_ver8_7.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver6_1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_huc_ver01_07_1398.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_huc_ver01_07_1398.bin for module i915
```

A total noob here, will try booting into the new kernel anyway, as it seems to be complaining about i915 files for previous Surface generations.

Thanks!

**Comment by atharos1** [comment]
OK, so even if the OS boots and seems to be working nicely, I get a lot of complaints during boot that I can't read, but that don't show up when booting your old .14 kernel.
Running _systemctl status systemd-modules-load.service_ returned:
`systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-03-03 23:04:51 -03; 4min 57s ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 606 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 606 (code=exited, status=1/FAILURE)

mar 03 23:04:50 nico-Surface-Book-2 systemd[1]: Starting Load Kernel Modules...
mar 03 23:04:50 nico-Surface-Book-2 systemd-modules-load[606]: Failed to find module 'ashmem_linux'
mar 03 23:04:50 nico-Surface-Book-2 systemd-modules-load[606]: Failed to find module 'binder_linux'
mar 03 23:04:51 nico-Surface-Book-2 systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
mar 03 23:04:51 nico-Surface-Book-2 systemd[1]: Failed to start Load Kernel Modules.
mar 03 23:04:51 nico-Surface-Book-2 systemd[1]: systemd-modules-load.service: Unit entered failed state.
mar 03 23:04:51 nico-Surface-Book-2 systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.`

**Comment by jakeday** [comment]
Your issue isn't with the kernel but with having anbox installed. They always have issues with their modules getting loaded on newer kernels. You'll need to send a bug to them.
